### ISSUE TITLE
Using source directory doesn't populate globals.css & tailwind.config.css

### ISSUE THREAD

**Issue by YugandharrPatil** [shadcn-ui/ui#1001]
Not sure what if I'm missing something here, but probably creating a Next app using src directory and then initializing shadcn there doesn't add the required colors and theming presets in the globals.css & tailwind.config.css.

Issue here:
Tailwind config with src: [tailwind.config.txt](https://github.com/shadcn-ui/ui/files/12135674/tailwind.config.txt)
globals.css with src: [globals.txt](https://github.com/shadcn-ui/ui/files/12135675/globals.txt)

No issue here:
Tailwind config without src: [tailwind.config.txt](https://github.com/shadcn-ui/ui/files/12135681/tailwind.config.txt)
globals.css without src: [globals.txt](https://github.com/shadcn-ui/ui/files/12135684/globals.txt)

Again I might be missing something here, perhaps a prompt here n there. But probably there's an issue since I've been scratching my head all night.

**Comment by nsquaredotone** [comment]
When initializing the ui with Next, make sure to return the right path in your CLI. You can add the custom classes manually as well, that should work fine.

**Comment by YugandharrPatil** [comment]
> When initializing the ui with Next, make sure to return the right path in your CLI. You can add the custom classes manually as well, that should work fine.

Yeah true, that's how I've been doing hence. But it is a bug right?
