### ISSUE TITLE
Scroll-area how to add onScroll event

### ISSUE THREAD

**Issue by joeylin** [shadcn-ui/ui#1005]
I use like this, it can not work,  How do I implement this feature？
```
<ScrollArea onScroll={scrollhandder}>
      <div
        className="min-h-screen"
        style={{
          backgroundColor: chatData.style.backgroundColor || "#fff",
          height: "100vh",
        }}
      >
        <OtherComponent chatData={chatData} />
      </div>
    </ScrollArea>
```
thanks very much!

**Comment by nsquaredotone** [comment]
What does your scrollhandler function look like?

**Comment by joaom00** [comment]
The event need to be passed on Viewport component part

**Comment by joeylin** [comment]
> What does your scrollhandler function look like?

this is simple, just a anonymous function with console.log("xxx") in the function. 
the question is I can not bind scroll event on Viewport component part, that is what scroll event was triggered.

any other solution ?

**Comment by joaom00** [comment]
> the question is I can not bind scroll event on Viewport component part, that is where scroll event was triggered

Why not?

**Comment by joeylin** [comment]
> <ScrollArea onScroll={scrollhandder}>
>       <div
>         className="min-h-screen"
>         style={{
>           backgroundColor: chatData.style.backgroundColor || "#fff",
>           height: "100vh",
>         }}
>       >
>         <OtherComponent chatData={chatData} />
>       </div>
>     </ScrollArea>

```
<ScrollArea onScroll={scrollhandder}>
      <div
        className="min-h-screen"
        style={{
          backgroundColor: chatData.style.backgroundColor || "#fff",
          height: "100vh",
        }}
      >
        <OtherComponent chatData={chatData} />
      </div>
    </ScrollArea>
```
I understand that I can only manipulate the ScrollArea element, not the Viewport component part ？ is it right ? or there is another way to get Viewport component ?

**Comment by joaom00** [comment]
You can spread the props on `Viewport` component instead of `Root`, in  `scroll-area` file
