### ISSUE TITLE
DropdownMenu doesn't load default classes CSS

### ISSUE THREAD

**Issue by edwini** [shadcn-ui/ui#101]
Hi! in the `<DropdownMenu />` component, CSS classes aren't load in the final `<div>` element. 
![Captura de Pantalla 2023-02-19 a la(s) 22 45 10](https://user-images.githubusercontent.com/4822615/220011524-2af3c649-5624-48be-b9fb-92ceda5bde41.png)

As you can see I am using `<DropdownMenuSeparator />` withour classes and the final div is empty, but if I add classes by my own, its loads only my custom classes.
![Captura de Pantalla 2023-02-19 a la(s) 22 49 11](https://user-images.githubusercontent.com/4822615/220011940-8d7e1aad-3b05-4b9e-9756-d9e596eaf5d4.png)
![Captura de Pantalla 2023-02-19 a la(s) 22 49 31](https://user-images.githubusercontent.com/4822615/220011993-89d08695-a9bd-4c7e-ba6c-93eac25fca6d.png)

I added in lib folder the utils.ts file, but I dont undertand the why it is not working. This is happeding with all childs of `<DropdownMenu />` 

Thank you.

**Comment by leabs** [comment]
Hi! Are you importing the component and then adding the classes on the element? It worked for me so I'm not sure I'm understanding. If you had some code public I'd be willing to look at it.

What I did:
![Screenshot 2023-02-20 at 11 24 35 AM](https://user-images.githubusercontent.com/7071812/220158455-795ff9ab-82c9-4d09-b923-d9bdd80fa118.png)

Result:
![Screenshot 2023-02-20 at 11 21 11 AM](https://user-images.githubusercontent.com/7071812/220158496-f7ceb503-897d-44eb-be6d-65728b7f3012.png)

**Comment by PatrickJoannisse** [comment]
@edwini If you're still having this issue, I had the same and found the reason.

**Check your imports and make sure you're actually importing from the DropdownMenu.tsx you created and not the Radix UI.**

Turns out VS Code was importing from the wrong place when I used the "fix this".

**Comment by sojinsamuel** [comment]
> @edwini If you're still having this issue, I had the same and found the reason.
> 
> **Check your imports and make sure you're actually importing from the DropdownMenu.tsx you created and not the Radix UI.**
> 
> Turns out VS Code was importing from the wrong place when I used the "fix this".

Worked for me to. thanks @PatrickJoannisse

**Comment by LucasJantschChitolina** [comment]
> @edwini If you're still having this issue, I had the same and found the reason.
> 
> **Check your imports and make sure you're actually importing from the DropdownMenu.tsx you created and not the Radix UI.**
> 
> Turns out VS Code was importing from the wrong place when I used the "fix this".

That's it. Thanks @PatrickJoannisse

**Comment by edwini** [comment]
that was the problem, thanks

**Comment by shicham** [comment]
for me it was a parent div with a fixed position style, so i change it, and it works for me
