### ISSUE TITLE
using combobox inside sheet component

### ISSUE THREAD

**Issue by omarakahdery** [shadcn-ui/ui#1019]
the issue related to using a Combobox within a Sheet component. Specifically, when utilizing the Combobox, I am unable to focus inside the Command Input to search for items from the Combobox. It's worth mentioning that I am using a Combobox Popover as a modal.

The code

`
 function Form() {
  return (
    <Sheet modal={true} onOpenChange={toggleModalVisibility} open={isModalOpen}>
      <SheetContent position={position} size={size}>
        <ScrollArea className="h-full w-full">
          <FormWrapper>
            <Form {...form}>
              <form
                onSubmit={form.handleSubmit(onSubmit)}
                className="space-y-8"
              >
                <FormField
                  control={form.control}
                  name="year"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Yıl</FormLabel>
                      <FormControl>
                        <Combobox
                          placeholder="Yıl"
                          options={years}
                          value={field?.value?.toString()}
                          onSelect={(value) => {
                            form.setValue("year", Number(value));
                          }}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </form>
            </Form>
          </FormWrapper>
        </ScrollArea>
      </SheetContent>
    </Sheet>
  );
 }
`

Screenshot

![ss](https://github.com/shadcn-ui/ui/assets/85066587/5cc70482-3e04-4afc-8c0d-a04430ba66e8)

**Comment by joaom00** [comment]
Can you try wrap the `SheetPrimitive.Content` with `SheetOverlay`?

**Comment by omarakahdery** [comment]
> > it's already wrapped inside SheetContent component
> 
> I mean, do it like this:
> 
> ```tsx
> <SheetPortal>
>   <SheetOverlay>
>     <SheetPrimitive.Content />
>   </SheetOverlay>
> </SheetPortal>
> ```

yes, it's like this

**Comment by shadcn** [comment]
@omarakahdery I try to reproduce this but it seems to be working. Can you take a look at https://codesandbox.io/p/sandbox/sheet-with-combobox-qhmtt4?file=%2Fcomponents%2Fsheet-with-combobox.tsx%3A62%2C42?

**Comment by omarakahdery** [comment]
> @omarakahdery I try to reproduce this but it seems to be working. Can you take a look at https://codesandbox.io/p/sandbox/sheet-with-combobox-qhmtt4?file=%2Fcomponents%2Fsheet-with-combobox.tsx%3A62%2C42?

yes, it works in your code but not in mine :). My code and yours are exactly the same, only one difference that when i close the Sheet component the body pointer-events change to be none, do you think this is the problem and what could be the solution for body pointer-events.

**Comment by shadcn** [comment]
@omarakahdery Any chance you can share the code or add it to a Codesandbox?

**Comment by omarakahdery** [comment]
> @omarakahdery Any chance you can share the code or add it to a Codesandbox?
this is the code
https://github.com/omarakahdery/cbox-sss
you can check the issues at 
http://localhost:3000/any 
page

**Comment by joaom00** [comment]
it looks like the problem is https://github.com/radix-ui/primitives/issues/1088. To make it work, delete `node_modules` and `package-lock.json` and install everything again.

**Comment by omarakahdery** [comment]
> it looks like the problem is [radix-ui/primitives#1088](https://github.com/radix-ui/primitives/issues/1088). To make it work, delete `node_modules` and `package-lock.json` and install everything again.

yes, when I install everything again it work thank you.

**Comment by salfel** [comment]
for anyone who experienced the same issue as me, when the PopoverContent is not scrollable, [here](https://github.com/radix-ui/primitives/issues/1159#issuecomment-1741282769)'s the solution for this problem

**Comment by Azoonex** [comment]
Friends who want to put comboboxin Shadcn sheet component because it has Radix portal, you should delete it.

**Comment by VishalLudhrani** [comment]
> for anyone who experienced the same issue as me, when the PopoverContent is not scrollable, [here](https://github.com/radix-ui/primitives/issues/1159#issuecomment-1741282769)'s the solution for this problem

This worked for me.
Thank you!

I have a follow up situation.
The transition direction is not what I expected.
Is there a means to change the transition direction to "down" or "bottom"?
Currently, the popover transitions from the right, towards the left on mount.

https://github.com/user-attachments/assets/af98151a-5f23-426e-90b5-d50be13c4e63
