### ISSUE TITLE
QUESTION: Additional variants

### ISSUE THREAD

**Issue by brandonmcconnell** [shadcn-ui/ui#1044]
I only see a destructive variant listed in the docs.

Are there others available like success/warning/info variants, or is that the only one?

Are these variants easily configurable?

**Comment by shadcn** [comment]
I intentionally kept the number of variants minimum since you have access to the code if you need more. I think we can cover this in docs. Tagging docs.

Thank you.

**Comment by elliot** [comment]
Yes, there are more variants and they are easily configurable. 
Simply add the variant to `buttonVariants` in your component and apply the appropriate styling

https://github.com/shadcn-ui/ui/blob/91727ec4602a741127318d859ccf40ebf944d2e8/apps/www/registry/default/ui/button.tsx#L11-L21

**Comment by brandonmcconnell** [comment]
related to #1046

**Comment by cstayyab** [comment]
I am extended existing components but want to keep the original ones for easy upgrade/pull if anything changes. Is there a way to `extend` the variants while keeping the existing as is. Here's an example:

```tsx
import React from 'react';
import { Button as ShadcnButton, ButtonProps as ShadcnButtonProps } from '@/components/shadcn/ui/button';
import { LucideIcon } from 'lucide-react';

// Extend the original ButtonProps with your new properties
interface ButtonProps extends ShadcnButtonProps {
  preIcon?: LucideIcon;
  postIcon?: LucideIcon;
}

// wrapper component
const Button: React.FC<ButtonProps> = ({ preIcon: PreIcon, postIcon: PostIcon, children, ...props }) => {
  return (
    <ShadcnButton {...props}>
      {PreIcon && <PreIcon style={{ marginRight: '8px' }} />}
      {children}
      {PostIcon && <PostIcon style={{ marginLeft: '8px' }} />}
    </ShadcnButton>
  );
};

export default Button;

```

**Comment by shadcn** [comment]
@cstayyab See my comment here: https://github.com/shadcn-ui/ui/issues/1046#issuecomment-1925615814
