### ISSUE TITLE
QUESTION: Component extensibility

### ISSUE THREAD

**Issue by brandonmcconnell** [shadcn-ui/ui#1046]
I started exploring the components, and I was curious if, for some components (e.g., Toast), you have any instructions for extending it to support more variants, actions, etc.?

Would those sorts of extensibility instructions be somewhere else in the docs?

**Comment by brandonmcconnell** [comment]
related to #1046

**Comment by shadcn** [comment]
@brandonmcconnell Modify the code directly and add your custom variants. That's the goal of having the code in your code base. Adding another abstraction layer on top will increase complexity.

Re. updates I'll document the updates on the component page, so you can pick and manually apply the updates you want.
