### ISSUE TITLE
form - trigger submit from checkbox

### ISSUE THREAD

**Issue by bukine** [shadcn-ui/ui#1057]
it's possible to trigger the submit event - when checkbox is changed?

         <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} >
                   .......................................
            checked={field.value==="0"?false:true}
                  onCheckedChange={ 
                    (checked)=>{
                     if (!checked){ form.setValue("fiel1","0");
                                   form.setValue("fiel2","");
                             **form.handleSubmit(onsubmit)**   ---> not working
                    
                    }
                     return checked?field.onChange("1"):field.onChange("0")}
                   }

**Comment by limitless-dev** [comment]
You may use `form.trigger()` then check for the response if it is true, then call the onSubmit function.
Something like this:
```tsx
form.trigger().then((res) => {
    if (res) {
        onSubmit(form.getValues());
    }
});
```
