### ISSUE TITLE
 unable to add the button component

### ISSUE THREAD

**Issue by munan56** [shadcn-ui/ui#1060]
Following the steps on the official website ([https://ui.shadcn.com/docs/installation/next), ↗](https://ui.shadcn.com/docs/installation/next),) I am unable to add the button component.

`./app/page.js:2:0
Module not found: Can't resolve '@/components/ui'
  1 | import Image from 'next/image'
> 2 | import {Button} from '@/components/ui'
  3 | 
  4 | export default function Home() {
  5 |   return (

https://nextjs.org/docs/messages/module-not-found`

**Comment by munan56** [comment]
components.json
`{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": false,
  "tsx": false,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "app/globals.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}`

jsconfig.json

`{
  "compilerOptions": {
    "paths": {
      "@/*": ["./*"]
    }
  }
}
`

**Comment by nedois** [comment]
you must import it from  import {Button} from `@/components/ui/button`

**Comment by munan56** [comment]
> you must import it from import {Button} from `@/components/ui/button`

thanks bro
