### ISSUE TITLE
Combobox search does not work?

### ISSUE THREAD

**Issue by t-rosa** [shadcn-ui/ui#1072]
Hello everyone, the combobox search doesn't seem to be working.

Here's an example via the docs => https://ui.shadcn.com/docs/components/combobox#form

![cbx-search-issue](https://github.com/shadcn-ui/ui/assets/56064543/303ba908-764b-4cdf-b0b0-ab434e4c3ba5)

**Comment by datnmqti** [comment]
maybe the documentation wasn't clear, but that doesn't seem to be a bug. 
You are searching by what you see, but by default it is searching by ``value`` not ``label``
so if you wanna search for ``Chinese`` you would type ``zh``

```ts
const languages = [
   { label: "English", value: "en" },
   { label: "French", value: "fr" },
   { label: "German", value: "de" },
   { label: "Spanish", value: "es" },
   { label: "Portuguese", value: "pt" },
   { label: "Russian", value: "ru" },
   { label: "Japanese", value: "ja" },
   { label: "Korean", value: "ko" },
   { label: "Chinese", value: "zh" },
] as const

```

**Comment by ZeldOcarina** [comment]
Are we sure this is supposed to be closed? It's such a bad UX to search by value instead of label, usually values are uuids and other system-friendly stuff while labels are human friendly, this is what a human should look for..

**Comment by t-rosa** [comment]
> Are we sure this is supposed to be closed? It's such a bad UX to search by value instead of label, usually values are uuids and other system-friendly stuff while labels are human friendly, this is what a human should look for..

It has been updated to search by label.

**Comment by ZeldOcarina** [comment]
I tried it two days ago and I had to go through a bunch of hoops to make it work by label, I made it to work but the default is still search by value!

**Comment by t-rosa** [comment]
> I tried it two days ago and I had to go through a bunch of hoops to make it work by label, I made it to work but the default is still search by value!

Well now the examples uses label instead of value.
