### ISSUE TITLE
'Popover' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by yannxaver** [shadcn-ui/ui#1091]
```ts
'Popover' cannot be used as a JSX component.
  Its type 'FC<PopoverProps>' is not a valid JSX element type.
    Type 'FunctionComponent<PopoverProps>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
```

Code taken from https://ui.shadcn.com/docs/components/combobox

**Comment by yannxaver** [comment]
The error disappeared after updating dependencies.

**Comment by ricsands2801** [comment]
+1.  @shadcn After upgrading to typescript 5.2.2 it broke all components

**Comment by shadcn** [comment]
@ricsands2801 Can you help me reproduce please?

**Comment by ricsands2801** [comment]
> @ricsands2801 Can you help me reproduce please?

Yes definitely. Would the package and lock file help?

**Comment by ziyafenn** [comment]
Here is more info on where error stems from @shadcn:

```
const PopoverContent = React.forwardRef<
  React.ElementRef<typeof PopoverPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof PopoverPrimitive.Content>
>
```

`React.ElementRef<typeof PopoverPrimitive.Content>`:

```
Type 'ForwardRefExoticComponent<PopoverContentProps & RefAttributes<HTMLDivElement>>' does not satisfy the constraint 'keyof IntrinsicElements | ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) | ((props: any, context?: any) => ReactNode)'.
  Type 'ForwardRefExoticComponent<PopoverContentProps & RefAttributes<HTMLDivElement>>' is not assignable to type 'ForwardRefExoticComponent<any>'.
        Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2344)
index.d.ts(176, 9): 'children' is declared here.
```

`React.ComponentPropsWithoutRef<typeof PopoverPrimitive.Content>`:
```
Type 'ForwardRefExoticComponent<PopoverContentProps & RefAttributes<HTMLDivElement>>' does not satisfy the constraint 'ElementType<any, keyof IntrinsicElements>'.
  Type 'ForwardRefExoticComponent<PopoverContentProps & RefAttributes<HTMLDivElement>>' is not assignable to type 'FunctionComponent<any>'.
  ```
<details><summary>Screenshot</summary>
<img width="801" alt="Screenshot 2024-02-02 at 18 12 24" src="https://github.com/shadcn-ui/ui/assets/314302/f1c296ad-a950-4718-85d4-e682eeb22d31">
</details> 


<details><summary>Package Versioning</summary>

-     "react": "^18.2.0",
-     "react-dom": "^18.2.0",
-     "@radix-ui/react-popover": "^1.0.7",
-     "typescript": "^5.3.3",
-     "@types/react": "^18.2.51",
-     "@types/react-dom": "^18.2.18",

</details>

**Comment by CaioAugustoo** [comment]
i'm facing the same issue. React 19 and typescript 5.6.3 here.
