### ISSUE TITLE
Cannot find module '../../@/components/ui/button' and Cannot find module '@/lib/utils' or its corresponding type declarations.

### ISSUE THREAD

**Issue by MuhammadSalmanAlfarisi** [shadcn-ui/ui#1101]
So i just started ts + vite + tailwind. tried installing shadcn and the button component to test it out, but it gave this error message. tried looking for the same issue here but didnt find any solution. i have run `npx shadcn-ui init` and it still didnt work, i dont use react server component.

**Comment by nsquaredotone** [comment]
Can you please share your import, your components.json and the folder structure of your project?

**Comment by shivxmr** [comment]
> So i just started ts + vite + tailwind. tried installing shadcn and the button component to test it out, but it gave this error message. tried looking for the same issue here but didnt find any solution. i have run `npx shadcn-ui init` and it still didnt work, i dont use react server component.

You can try this 
`npx shadcn-ui@latest init`

**Comment by MuhammadSalmanAlfarisi** [comment]
I solved this problem by just moving the downloaded components into a ui folder in my src/components/ui and also the lib/utils. i think i messed up when I first init the library.

**Comment by stephanebruckert** [comment]
> I solved this problem by just moving the downloaded components into a ui folder in my src/components/ui and also the lib/utils. i think i messed up when I first init the library.

works, however the shadcn cli moves it to `/` (above src) by default, which causes this issue:

> Module not found: Error: You attempted to import ../../@/components/ui/button which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
> You can either move it inside src/, or add a symlink to it from project's node_modules/.

@shadcn do you recommend to put @ into `src` by default (React app here btw), if so should the cli take care of it?

**Comment by vim-diesel** [comment]
Why is this closed? I'm having this issue and moving the folders doesn't work.

**Comment by stephanebruckert** [comment]
@vim-diesel also update your `components.json` with:

    "aliases": {
      "components": "src/@/components",
      "utils": "src/@/lib/utils"
    }

**Comment by vim-diesel** [comment]
@stephanebruckert 
sorry I deleted my comment. I messed up putting the compiler options in before initializing. I deleted the project and tried again and seems to be working okay now.

**Comment by geekaara** [comment]
I encountered the same issue, my mistake was in pasting 
`    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }`
outside the compilerOptions, please do check

**Comment by StreetDevs** [comment]
I have the same issue but i tried all the above but is still does not work

**Comment by grainme** [comment]
same goes for me here, I still have the same issue!

**Comment by shadcn** [comment]
@lethib What's in your `tsconfig.json`?

**Comment by lethib** [comment]
@shadcn My `tsconfig.json` looks like this:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"]
}
```

**Comment by theG0ulart** [comment]
@shadcn , that problem occurs only during the compilation when using Create React App + Shadcn-UI

Today I lost a lot of time trying to solve that, but I fail. 

@shadcn , any plans to solve that error??

**Comment by IronHeartDan** [comment]
My mistake was configuring ts config file after 
`npx shadcn-ui@latest init`

I resolved by again going through the setup, and this time I setup ts config file first
`
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
}
`

Then ran
`npx shadcn-ui@latest init`

Incase if it helps someone

**Comment by pierresisson** [comment]
@IronHeartDan many thanks, it works!

**Comment by efgomes** [comment]
aqqui acontece a mesma coisa, vite com typescript, quando instalo o shadcn ele fica na raiz do projeto, 6 horas tentando resovler isso, vou deixar aqqui e vou continuar usando o antd ate conseguir resolver esses imports

**Comment by yeongbin-jo** [comment]
```
yarn run v1.22.21
$ tsc -b && vite build
src/components/ui/button.tsx:5:20 - error TS2307: Cannot find module '@/lib/utils' or its corresponding type declarations.
```

Still same issue occured :sob:

**Comment by yeongbin-jo** [comment]
I solved this problem by adding `baseUrl`, `paths` config to `tsconfig.app.json`.

Like below:
```javascript
{
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,

    "baseUrl": ".",
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
  },
  "include": ["src"]
}
```

**Comment by dandheedge** [comment]
> I solved this problem by adding `baseUrl`, `paths` config to `tsconfig.app.json`.
> 
> Like below:
> 
> ```js
> {
>   "compilerOptions": {
>     "composite": true,
>     "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
>     "target": "ES2020",
>     "useDefineForClassFields": true,
>     "lib": ["ES2020", "DOM", "DOM.Iterable"],
>     "module": "ESNext",
>     "skipLibCheck": true,
> 
>     /* Bundler mode */
>     "moduleResolution": "bundler",
>     "allowImportingTsExtensions": true,
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "moduleDetection": "force",
>     "noEmit": true,
>     "jsx": "react-jsx",
> 
>     /* Linting */
>     "strict": true,
>     "noUnusedLocals": true,
>     "noUnusedParameters": true,
>     "noFallthroughCasesInSwitch": true,
> 
>     "baseUrl": ".",
>     "paths": {
>       "@/*": [
>         "src/*"
>       ]
>     }
>   },
>   "include": ["src"]
> }
> ```

This works for me. Thank you 👍

**Comment by KaziMdMehediHasan** [comment]
> I solved this problem by adding `baseUrl`, `paths` config to `tsconfig.app.json`.
> 
> Like below:
> 
> ```js
> {
>   "compilerOptions": {
>     "composite": true,
>     "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
>     "target": "ES2020",
>     "useDefineForClassFields": true,
>     "lib": ["ES2020", "DOM", "DOM.Iterable"],
>     "module": "ESNext",
>     "skipLibCheck": true,
> 
>     /* Bundler mode */
>     "moduleResolution": "bundler",
>     "allowImportingTsExtensions": true,
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "moduleDetection": "force",
>     "noEmit": true,
>     "jsx": "react-jsx",
> 
>     /* Linting */
>     "strict": true,
>     "noUnusedLocals": true,
>     "noUnusedParameters": true,
>     "noFallthroughCasesInSwitch": true,
> 
>     "baseUrl": ".",
>     "paths": {
>       "@/*": [
>         "src/*"
>       ]
>     }
>   },
>   "include": ["src"]
> }
> ```

It's finally working for me!

**Comment by efgomes** [comment]
> I solved this problem by adding `baseUrl`, `paths` config to `tsconfig.app.json`.
> 
> Like below:
> 
> ```js
> {
>   "compilerOptions": {
>     "composite": true,
>     "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
>     "target": "ES2020",
>     "useDefineForClassFields": true,
>     "lib": ["ES2020", "DOM", "DOM.Iterable"],
>     "module": "ESNext",
>     "skipLibCheck": true,
> 
>     /* Bundler mode */
>     "moduleResolution": "bundler",
>     "allowImportingTsExtensions": true,
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "moduleDetection": "force",
>     "noEmit": true,
>     "jsx": "react-jsx",
> 
>     /* Linting */
>     "strict": true,
>     "noUnusedLocals": true,
>     "noUnusedParameters": true,
>     "noFallthroughCasesInSwitch": true,
> 
>     "baseUrl": ".",
>     "paths": {
>       "@/*": [
>         "src/*"
>       ]
>     }
>   },
>   "include": ["src"]
> }
> ```


fiz seguindo o codigo do colega, mas como podem ver na iamgem abaixo ele continua sendo criado o @na raiz
![image](https://github.com/shadcn-ui/ui/assets/53862865/f6d7db2b-68e5-4ecf-9009-fd8a4e5d304f)

**Comment by deno-source** [comment]
> ```js
> "baseUrl": ".",
>     "paths": {
>       "@/*": [
>         "src/*"
>       ]
>     }
> ```

终于找到了一个靠谱的答案

**Comment by sovetski** [comment]
Thanks @yeongbin-jo, I was editing all tsconfig files except tsconfig.app.json, I don't understand why we have a lot of tsconfig files but anyway you saved my day

**Comment by Govinda088** [comment]
> I solved this problem by adding `baseUrl`, `paths` config to `tsconfig.app.json`.
> 
> Like below:
> 
> ```js
> {
>   "compilerOptions": {
>     "composite": true,
>     "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
>     "target": "ES2020",
>     "useDefineForClassFields": true,
>     "lib": ["ES2020", "DOM", "DOM.Iterable"],
>     "module": "ESNext",
>     "skipLibCheck": true,
> 
>     /* Bundler mode */
>     "moduleResolution": "bundler",
>     "allowImportingTsExtensions": true,
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "moduleDetection": "force",
>     "noEmit": true,
>     "jsx": "react-jsx",
> 
>     /* Linting */
>     "strict": true,
>     "noUnusedLocals": true,
>     "noUnusedParameters": true,
>     "noFallthroughCasesInSwitch": true,
> 
>     "baseUrl": ".",
>     "paths": {
>       "@/*": [
>         "src/*"
>       ]
>     }
>   },
>   "include": ["src"]
> }
> ```

You are GodSend.

**Comment by Quinlivanner** [comment]
> 我通过将`baseUrl` 、 `paths` config 添加到`tsconfig.app.json`解决了这个问题。
> 
>  就像下面这样：
> 
> ```js
> {
>   "compilerOptions": {
>     "composite": true,
>     "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
>     "target": "ES2020",
>     "useDefineForClassFields": true,
>     "lib": ["ES2020", "DOM", "DOM.Iterable"],
>     "module": "ESNext",
>     "skipLibCheck": true,
> 
>     /* Bundler mode */
>     "moduleResolution": "bundler",
>     "allowImportingTsExtensions": true,
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "moduleDetection": "force",
>     "noEmit": true,
>     "jsx": "react-jsx",
> 
>     /* Linting */
>     "strict": true,
>     "noUnusedLocals": true,
>     "noUnusedParameters": true,
>     "noFallthroughCasesInSwitch": true,
> 
>     "baseUrl": ".",
>     "paths": {
>       "@/*": [
>         "src/*"
>       ]
>     }
>   },
>   "include": ["src"]
> }
> ```

Worked for me!!amazing!

**Comment by Noudea** [comment]
If u have this structure

```

.
└── src/
    ├── components/
    │   └── ui/
    │       └── button.tsx
    └── lib/
        └── utils.ts


```

You have to make sure sur the `@libs` as correct 

```json

    "paths": {
      "@/*": ["./src/*"],
      "@auth/*": ["./src/features/auth/*"],
      "@components/*": ["./src/components/*"],
      "@libs/*": ["./src/lib/*"]
    }

```

**Comment by Noudea** [comment]
When using shadcn/ui, you might encounter import issues due to path aliasing configuration.


For example if you have this kind of structure

## Project Structure

```
.
└── src/
    ├── components/
    │   └── ui/
    │       └── button.tsx
    └── lib/
        └── utils.ts

```


## Required Configuration

You need to configure both `vite.config.ts` and `tsconfig.json`:

```ts
// vite.config.ts
resolve: {
  alias: [
    { find: '@', replacement: path.resolve(__dirname, 'src') },
    { find: '@libs', replacement: path.resolve(__dirname, 'src/lib') }
  ]
}
```
```json
// tsconfig.json
{
  "compilerOptions": {
    "paths": {
      "@/*": ["./src/*"],
      "@libs/*": ["./src/lib/*"]
    }
  }
}
````

##  Key Points

Make sure paths match exactly in both files
Use @libs/utils instead of @lib/utils
Restart your dev server after config changes

This will allow imports like:
```ts
import { cn } from "@libs/utils"
```

**Comment by Govinda088** [comment]
> When using shadcn/ui, you might encounter import issues due to path aliasing configuration.
> 
> For example if you have this kind of structure
> 
> ## Project Structure
> ```
> .
> └── src/
>     ├── components/
>     │   └── ui/
>     │       └── button.tsx
>     └── lib/
>         └── utils.ts
> ```
> 
> ## Required Configuration
> You need to configure both `vite.config.ts` and `tsconfig.json`:
> 
> ```ts
> // vite.config.ts
> resolve: {
>   alias: [
>     { find: '@', replacement: path.resolve(__dirname, 'src') },
>     { find: '@libs', replacement: path.resolve(__dirname, 'src/lib') }
>   ]
> }
> ```
> 
> ```json
> // tsconfig.json
> {
>   "compilerOptions": {
>     "paths": {
>       "@/*": ["./src/*"],
>       "@libs/*": ["./src/lib/*"]
>     }
>   }
> }
> ```
> 
> This will allow imports like:
> 
> ```ts
> import { cn } from "@libs/utils"
> ```
> 
> ## Key Points
> Make sure paths match exactly in both files You could have to restart TS Server after config changes
> 
> # How to Restart TypeScript Server
> ## Using Command Palette
> 1. `Cmd/Ctrl + Shift + P`
> 2. Type "TypeScript: Restart TS Server"
> 3. Press Enter

Thank you very much for the information it will a great help for someone in future.

**Comment by 1saifj** [comment]
after changing the ts.config sometimes you need to exit VsCode or the editor, and if you running VsCode its worth trying restarting the TS server.

**Comment by lequocmanhno1** [comment]
Reference: https://stackoverflow.com/a/75121301/8345133
In the `tsconfig.app.json` file, add `"extends": "./tsconfig.json"` as shown below:
```js
{
  "extends": "./tsconfig.json",
   "compilerOptions": {
    // ...
   }
}
```
This worked for me.

**Comment by meepstertron** [comment]
> I solved this problem by adding `baseUrl`, `paths` config to `tsconfig.app.json`.
> 
> Like below:
> 
> ```js
> {
>   "compilerOptions": {
>     "composite": true,
>     "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
>     "target": "ES2020",
>     "useDefineForClassFields": true,
>     "lib": ["ES2020", "DOM", "DOM.Iterable"],
>     "module": "ESNext",
>     "skipLibCheck": true,
> 
>     /* Bundler mode */
>     "moduleResolution": "bundler",
>     "allowImportingTsExtensions": true,
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "moduleDetection": "force",
>     "noEmit": true,
>     "jsx": "react-jsx",
> 
>     /* Linting */
>     "strict": true,
>     "noUnusedLocals": true,
>     "noUnusedParameters": true,
>     "noFallthroughCasesInSwitch": true,
> 
>     "baseUrl": ".",
>     "paths": {
>       "@/*": [
>         "src/*"
>       ]
>     }
>   },
>   "include": ["src"]
> }
> ```

Thanks, this worked for me :)

**Comment by josephbima** [comment]
> My mistake was configuring ts config file after `npx shadcn-ui@latest init`
> 
> I resolved by again going through the setup, and this time I setup ts config file first `"compilerOptions": { "baseUrl": ".", "paths": { "@/*": [ "./src/*" ] }, }`
> 
> Then ran `npx shadcn-ui@latest init`
> 
> Incase if it helps someone

This worked for me in my Nextjs project. Thanks!

**Comment by MarkmeDEV** [comment]
lmao, i am also having a hard time on this but when i review my code i put the baseUrl and path outside of the compilerOptions in tsconfig.app.json

**Comment by amansubudhi** [comment]
In tsconfig.app.json, just adding a * in ./src as shown below worked for me

"paths": {
      "@/*": [
        "./src/*"
      ]
    },

**Comment by zznicole** [comment]
`  "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }`
Put the above in "compilerOptions" in tsconfig.json. It worked for me.

**Comment by igprasad09** [comment]
update user tsconfig.app.json with this. this is the main problem


{
  "extends": "./tsconfig.json", // <-- inherit baseUrl + paths from root
  "compilerOptions": {
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
    "target": "ES2022",
    "useDefineForClassFields": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "verbatimModuleSyntax": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "erasableSyntaxOnly": true,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedSideEffectImports": true
  },
  "include": ["src"]
}
