### ISSUE TITLE
Programmatically controll tabs?

### ISSUE THREAD

**Issue by holy-dev** [shadcn-ui/ui#1105]
Can I programmatically switch tabs?

**Comment by cerimorse** [comment]
This set of components is using [Radix-UI primitives](https://www.radix-ui.com/docs/primitives/components/tabs) under the hood, so generally anything you can do with Radix-UI, you can do here. 

Rather than using the tabs as an uncontrolled component, you can change it to be controlled something like the below. I haven't tested but this would allow you to programmatically switch tabs.

```
export function TabsDemo() {
  const [tab, setTab] = useState("tab1");

  const onTabChange = (value) => {
    setTab(value);
  }

  return (
    <Tabs value={tab} onValueChange={onTabChange} className="w-[400px]">
      <TabsList className="grid w-full grid-cols-2">
        <TabsTrigger value="tab1">Tab 1</TabsTrigger>
        <TabsTrigger value="tab2">Tab 2</TabsTrigger>
        <TabsTrigger value="tab3">Tab 3</TabsTrigger>
      </TabsList>
      <TabsContent value="tab1">
        
      </TabsContent>
      <TabsContent value="tab2">
        
      </TabsContent>
      <TabsContent value="tab3">
        
      </TabsContent>
    </Tabs>
  )
}
```

Let me know if this isn't working for you and I'll spin up a sandbox example.

**Comment by shadcn** [comment]
@holy-dev What @cerimorse suggested above should work. Let me know if it doesn't.

**Comment by holy-dev** [comment]
Thank you. Sorry for responding late.

**Comment by itpaulin** [comment]
Works to me, but the defaultValue when the component is initialized stopped works. I don't know why.

**Comment by yuri-rage** [comment]
Apologies if it's poor form to respond to a closed issue, but I thought it might be useful to have an example where a Preact signal is used to manage state (very minor change to the working example above):

```
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useSignal } from '@preact/signals-react';

export default function TabsDemo() {
    const tab = useSignal('tab1');

    const onTabChange = (value: string) => {
        tab.value = value;
    };

    return (
        <Tabs value={tab.value} onValueChange={onTabChange} className="w-[400px]">
            <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="tab1">Tab 1</TabsTrigger>
                <TabsTrigger value="tab2">Tab 2</TabsTrigger>
                <TabsTrigger value="tab3">Tab 3</TabsTrigger>
            </TabsList>
            <TabsContent value="tab1"></TabsContent>
            <TabsContent value="tab2"></TabsContent>
            <TabsContent value="tab3"></TabsContent>
        </Tabs>
    );
}
```

**Comment by AstralBaby** [comment]
Can we use dynamic tabs?

**Comment by itpaulin** [comment]
> Can we use dynamic tabs?

yes, you need to do a map using an array with tabs you want, and make this control with a state, probably using a initial value to default tab

**Comment by MauDavalos10** [comment]
@shadcn Can we redirect to different url next.js pages? instead of having it everything embed in one single switching component?

**Comment by ImEins** [comment]
> what if want to apply different css a/c to which tab is active inside the tabsTrigger how can i achieve that without maintaining external state? is there any way @shadcn

use `data-[state=active]` using the className prop form the tab trigger 
`data-[state=active]:bg-green-200`

**Comment by maxih4** [comment]
> @shadcn Can we redirect to different url next.js pages? instead of having it everything embed in one single switching component?

Is this somehow possible with paralell routes? Cant find any answers
