### ISSUE TITLE
Wrong code gets copied on clicking "copy" from "yarn"

### ISSUE THREAD

**Issue by shivxmr** [shadcn-ui/ui#1109]
There is a code snippet provided for running the CLI using "yarn." However, when I select "yarn" and click the copy button, **_the copied code is actually the "npm" code instead of the expected "yarn" code_**.

[Next.js - shadcn/ui](https://ui.shadcn.com/docs/installation/next)

Steps to reproduce:

Go to the "Install and Configure Next.js" section of the shadcn ui website or click above link.
Select "yarn" from the code block.
Click the copy button.
Check the clipboard contents.

Actual Result:
The copied code is the "**npm**" code.

Expected Result:
The copied code should be the "yarn" code.

This inconsistency might confuse new users who prefer using "yarn" for their projects.

![Screenshot 2023-08-04 014300](https://github.com/shadcn-ui/ui/assets/94984885/35f5ae19-2af1-4989-ac0d-bfec8d8ea6d2)

**Comment by dan5py** [comment]
Yarn 1.x doesn't provide an equivalent of `npx`. Only the latest version implements the `dlx` command like `pnpm` does.

**Comment by evanlong0926** [comment]
`pnpx` is short for `pnpm dlx`.

**Comment by dan5py** [comment]
> `pnpx` is short for `pnpm dlx`.

`pnpx` is deprecated.

**Comment by evanlong0926** [comment]
@dan5py Do I know you from somewhere. But I can't remember, Your profile picture looks familiar.🤣

**Comment by dan5py** [comment]
@evanlong0926 I may have answered in some of your past issues. Can you please close this issue 😃 ?

**Comment by evanlong0926** [comment]
> @evanlong0926 I may have answered in some of your past issues. Can you please close this issue 😃 ?

Nice to meet you. No, because I'm not an administrator 🤣
