### ISSUE TITLE
bug: title/description of `toast` hardly visible in darkmode

### ISSUE THREAD

**Issue by DerTimonius** [shadcn-ui/ui#1121]
## Description
When using the default values after running `npx shadcn-ui@latest init` and `npx shadcn-ui@latest add toast`, the title and description of a toast are barely visible in darkmode:
<img width="418" alt="image" src="https://github.com/shadcn-ui/ui/assets/103483059/695bd651-a596-4b34-8da1-03daa4313f4d">
Only after manually adding `dark:text-slate-100` (in my case at least with the default values) to both `ToastTitle` and `ToastDescription` is it possible to read the toast:
<img width="417" alt="image" src="https://github.com/shadcn-ui/ui/assets/103483059/1d977b64-e9be-4fd0-b179-de1da727236e">

## Expected behavior
The text should be visible in darkmode without any additional changes

I'd be happy to help with a PR!

**Comment by SimeonAnunciado** [comment]
Good @DerTimonius day how is it going ? just want seek help the toast in mine are not working how did you install that properly?
i follow this unfortunately not work in my machine https://ui.shadcn.com/docs/components/toast
thanks

**Comment by DerTimonius** [comment]
@1danii did you use CSS variables? in the project where I encountered the issue I don't. I only followed the installation (for Astro in the case above) without making additional changes to the tw config

**Comment by SimeonAnunciado** [comment]
@1danii  do you have any reference for that installation ? unfortunately not work on me 
i use also version 13.4.12
here's the issue i landed when i put this components in my layout 
Error: `Toast` must be used within `ToastProvider` next js

i follow both cli and manual way of installation but no luck
https://ui.shadcn.com/docs/components/toast

**Comment by SimeonAnunciado** [comment]
what i did was i create a components i follow the docs and import it in my layout
![image](https://github.com/shadcn-ui/ui/assets/39466324/5aa6c7c6-400b-44c6-9960-d7519c126fa5)
then in my toast sample component i try to trigger that onclick 
![image](https://github.com/shadcn-ui/ui/assets/39466324/3a330b34-0231-44c0-bd03-78cd6505f5da)

and did not appear any toast message

**Comment by Roronoa-Zoroo** [comment]
Still not working
