### ISSUE TITLE
DropdownMenu inside DataTable causes viewport scroll on mobile

### ISSUE THREAD

**Issue by chillichelli** [shadcn-ui/ui#1134]
On the sample page ((https://ui.shadcn.com/examples/tasks), when viewed on smaller screens, the dropdown menu, positioned as the final column, leads to a scrolling effect on the x-axis as is visible on the nav-bar

![Schermafbeelding 2023-08-07 om 18 51 37](https://github.com/shadcn-ui/ui/assets/80068137/32ee8b9d-7e52-4e07-8199-02189761f143)

**Comment by X-Vneer** [comment]
it's because of the **sr-only** class on the **<span className="sr-only">Open menu</span>**

delete it and it should work just fine
