### ISSUE TITLE
The new asset "themes", broke the components page.

### ISSUE THREAD

**Issue by anteqkois** [shadcn-ui/ui#1142]
I don't know if it's planned. But some css styles seem to have started to mix with styles from 'themes' page. E.g. almost all of the border radious are set to 0. (but not when I e.g. open menubar)

![image](https://github.com/shadcn-ui/ui/assets/73034007/2125f37e-61c0-4004-b510-551c0bd59b75)

**Comment by shadcn** [comment]
Fixed in https://github.com/shadcn-ui/ui/pull/1265. Thank you.
