### ISSUE TITLE
[Major-Bug] Module not found: lucide-react

### ISSUE THREAD

**Issue by KaramveerSinghSidhu** [shadcn-ui/ui#1148]
I have created a few next js 13 apps using the https://ui.shadcn.com/docs/installation. When ever i try to use a any component that uses lucide-react i get this error 

./node_modules/lucide-react/dist/cjs/lucide-react.js:2:0
Module not found: Can't resolve 'C:\Users\PC\Desktop\gla3\node_modules\lucide-react\dist\cjs\icons\check'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./components/ui/select.tsx

**Comment by JairHuamanBellido** [comment]
I'm faced the same issue, I think it's related to next@13.4.13 , I downgraded the version to 13.4.12 and it worked.

**Comment by JairHuamanBellido** [comment]
There are more workarounds in this issue:

https://github.com/lucide-icons/lucide/issues/1482

**Comment by dan5py** [comment]
Hi @KaramveerSinghSidhu both the CLI and the Manual guide are missing the icon dependency installation. The Icon library changes from theme to theme:
- `Default` uses `lucide-react`
- `New York` uses `@radix-ui/react-icons`

You can manually install them based on your current theme.

**Comment by KaramveerSinghSidhu** [comment]
Yeah, i played around with it. It was as JairHuamanBellido said. its a next js versions issue.
