### ISSUE TITLE
How to open project on local?

### ISSUE THREAD

**Issue by ThamsanQue** [shadcn-ui/ui#1149]
### Discussed in https://github.com/shadcn-ui/ui/discussions/1126

<div type='discussions-op-text'>

<sup>Originally posted by **sellimenes** August  6, 2023</sup>
Hello, I want to enter the open-source world, and since I have a strong affinity for Shadcn, I'd like to contribute to this project. However, I'm facing difficulties when trying to open the project on my local machine. Is there any documentation available that could guide me through the process?</div> 

I just forked the project as well and was looking for a contributing file but i didnt find any...Im a junior developer and would like to start contributing to this project...If anyone could help me set up the project locally and take me through it ...id be more than welcome to write the contributing.md

**Comment by Filsommer** [comment]
Are on on MacOS/Unix or Windows?
A good first step would be to clone this repository -> go to the `apps/www/` directory, and run `npm install` to install the needed dependencies. If successful, run `npm run dev` to run the project locally and a url like localhost:3000 should pop up in the terminal for you to start developing locally

**Comment by dan5py** [comment]
@Filsommer this project uses `pnpm` as package manager and you should stick to that if you plan to contribute. 
@ThamsanQue As soon as I have some free time I'll create a detailed guide on how to contribute.

**Comment by ThamsanQue** [comment]
@Filsommer Im on windows ...thanks for breaking it down for me!
@dan5py  oh alright thanks will use pnpm
