### ISSUE TITLE
Change default ui directory

### ISSUE THREAD

**Issue by riccardolardi** [shadcn-ui/ui#1156]
Is it possible to change the default `ui` directory? I'd like the CLI to install new components into `@/components/ui-library` instead of `@/components/ui`. Thanks

**Comment by mohamedaleya** [comment]
According to CLI docs, there's a -p (or --path) option that should do the trick, however after testing it, that didn't work. It keeps installing the component in the /src/components/ui folder.

Should we create a new issue and mark it as a bug or is it enough to say it here? If I have entered the command wrong or misunderstood something, please let me know. 

Here's what I have tried:
```
npx shadcn-ui add --path /src/components/ui-library alert
npx shadcn-ui add --path /src/components/ui-library alert
npx shadcn-ui add -p /ui-library alert
```

https://ui.shadcn.com/docs/cli
![brave_QlhsvsdATn](https://github.com/shadcn-ui/ui/assets/43639707/78468054-4ab4-4439-85a4-8d66d53a0966)

**Comment by TeaRexcellence** [comment]
Can we do this now?

**Comment by Stefandasbach** [comment]
Any update on this @shadcn?

**Comment by shadcn** [comment]
@Stefandasbach I haven't had time to look into it yet. For now, as a workaround, you can provide --path when adding components.

```
-p, --path <path>  the path to add the component to.
```

**Comment by mindofjonas** [comment]
Looks like this still isn't working with `npx shadcn-ui add <component> --path <path>` either.

**Comment by nopitown** [comment]
The workaround doesn't work as well :( I hope this option is enabled soon so adoption for existing projects is easier.

**Comment by claudfuen** [comment]
Bumping this up, would love to be able to configure a default path on components.json for CLI to reference

**Comment by datproto** [comment]
Bump this again, really need this kind of feature

**Comment by artemshchirov** [comment]
Bump this again, really need this kind of feature

**Comment by josephdburdick** [comment]
Change the path setting in the components.json then run the cli again.

**Comment by victorharry** [comment]
Any update on this @shadcn?

**Comment by joemcbroom** [comment]
@shadcn I know you're busy but I tracked down the line which  seems to be blocking the workaround
I hesitate to open a PR for it though since it's there for a reason I guess?
https://github.com/shadcn-ui/ui/blob/1cf5fad881b1da8f96923b7ad81d22d0aa3574b9/packages/cli/src/utils/registry/index.ts#L121

**Comment by shadcn** [comment]
Update: Back from vacation. Working on this now.

**Comment by joemcbroom** [comment]
@shadcn if it's a simple fix but you don't have time to work on it, let me know I'd love to sync on it and be able to contribute. And I'm on PTO this week so have the time :)

**Comment by schulzf** [comment]
#2266 closes this

**Comment by shadcn** [comment]
Yes. I believe this is fixed #2266. Please reopen if not. Thank you.

**Comment by seanparkross** [comment]
I don't think this is working. 
`npx shadcn@latest add --path /src/components/ui progress` 
It always goes to `/components/ui` and then need to move it manually

Tried:
`npx shadcn@latest add --p /src/components/ui progress` 
`npx shadcn@latest add --path src/components/ui progress` 
etc.

**Comment by olajoao** [comment]
> I don't think this is working. `npx shadcn@latest add --path /src/components/ui progress` It always goes to `/components/ui` and then need to move it manually
> 
> Tried: `npx shadcn@latest add --p /src/components/ui progress` `npx shadcn@latest add --path src/components/ui progress` etc.

change your components.json to the custom path you want
![image](https://github.com/user-attachments/assets/58d48ee4-a1a6-41e3-a78c-d87582c714d2)

**Comment by L3on06** [comment]
To customize the installation path for ShadCN/UI components, follow these steps:

1. Navigate to the components.json file.

- If this file does not exist at the root level, run the command:

```
npx shadcn@latest init
```

2. In the components.json file, update the following properties:

- ui: Specify the path where the components should be installed.
- components: Define the path for the components' installation.

Example:

```
{
  "ui": "@/shared/components/ui",
  "components": "@/shared/components"
}
```

**Comment by alex-reusables** [comment]
I modified my `components.json` and that does work to set the install directory to a custom path.

The `-p` flag remains documented as an option for the `add` command but for me that path was ignored on component installation. Perhaps it should be removed from the documentation?

**Comment by imranaalam** [comment]
using Rails+ inertia+ react + shadcn

specify in tsconfig.json or tconfig.js file

{
    "compilerOptions": {
      "baseUrl": ".",
      "paths": {
        "@/*": ["app/frontend/*"],
        "@components/*": ["app/frontend/components/*"],
        "@ui/*": ["app/frontend/components/ui/*"],
        "@utils/*": ["app/frontend/utils/*"],
        "@hooks/*": ["app/frontend/hooks/*"]
      }
    },
    "include": ["app/frontend/**/*.ts", "app/frontend/**/*.tsx"]
  }
  

then run

npx shadcn@latest init       

it will create component.json


then finally add components

npx shadcn@latest add button

**Comment by thekenna** [comment]
`npx shadcnf@latest add button`
https://github.com/someError/shadcn-folder-component
https://www.npmjs.com/package/shadcnf

**Comment by corbinlazarone** [comment]
This worked for me!

```
npx shadcn@latest add sidebar --path src/shared/components/ui
```
