### ISSUE TITLE
Error Loading tsconfig.json: Using shadcn/ui with Vite"

### ISSUE THREAD

**Issue by MrMaina100** [shadcn-ui/ui#1158]
I'm starting to explore shadcn/ui for some side projects, but I ran into an issue: "Failed to load tsconfig.json. Couldn't find tsconfig.json."  I actually skipped a step during the Vite installation process since I'm not using TypeScript. Can anyone guide me on resolving this or  how to install it properly because am just using react without typescript

**Comment by dan5py** [comment]
Hi @MrMaina100, can add this to your `components.json` file in order to use JavaScript for the components:

```json
"tsx": false
```

**Comment by MrMaina100** [comment]
added a jsconfig.json with the configurations given to me in the docs and the  error disappeared and was able to install components, but then started to face another issue. When installing a component eg. a button I get an error in the console when using the component  ''GET http://localhost:5173/src/components/ui/button net::ERR_ABORTED 404 (Not Found)"..

**Comment by dan5py** [comment]
Can you share you `jsconfig.json`, please?

**Comment by MrMaina100** [comment]
`{
  "compilerOptions": {
    "paths": {
      "@/*": ["./*"]
    }
  }
}`

**Comment by dan5py** [comment]
Can you add this to the `compilerOptions` and try again:
```json
"baseUrl": "."
```

**Comment by MrMaina100** [comment]
still nothing ...actually deleted the project .lol it started to frustrate me ..thanks for your time my friend .

**Comment by dan5py** [comment]
Sorry I forgot about a thing, you also need to add the aliases in the `vite.config.js`:

```js
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': '/src',
    },
  },
});

```

**Comment by dan5py** [comment]
> thanks for your time my friend .

No problem.

**Comment by Beki78** [comment]
I was facing the same error I did everything by following the documentation and on the next day I tried to move the jsconfig.json file to the main folder, I think we dont have to add the json.json file to src folder but rather the outer folder
