### ISSUE TITLE
Navmenu not working

### ISSUE THREAD

**Issue by crisdegraciadev** [shadcn-ui/ui#1163]
I'm getting this error when trying to implement a navbar. I have installed lucide-react, but it seems to don't work.

I'm working with Next.js, pnpm as package manager. 

```
./node_modules/.pnpm/lucide-react@0.265.0_react@18.2.0/node_modules/lucide-react/dist/cjs/lucide-react.js:2:0
Module not found: Can't resolve '/home/cristian/Code/typescript/trainix/dashboard/node_modules/.pnpm/lucide-react@0.265.0_react@18.2.0/node_modules/lucide-react/dist/cjs/icons/chevron-down'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./components/ui/navigation-menu.tsx
./components/navbar.tsx
```

EDIT: It seems like an issue with Next 13.4.3, downgrading to 13.4.2 seems to solve the issue

**Comment by atleugim** [comment]
This is not related to shadcn-ui.

See lucide-dev issues: https://github.com/lucide-icons/lucide/issues/1482
