### ISSUE TITLE
Dialog not displaying correctly

### ISSUE THREAD

**Issue by crisdegraciadev** [shadcn-ui/ui#1166]
When using a dialog (from docs examples), the dialog content appears right next to the bottom, but no actual dialog is shown. I'm using next.js

**Comment by adamkangas** [comment]
Having this exact issue – did you find a solution? Thanks!

**Comment by crisdegraciadev** [comment]
> Having this exact issue – did you find a solution? Thanks!

It wasn't an issue with shacdn, I just was importing the dialog from Radix UI. Instead, you should import it from shacdn

**Comment by adamkangas** [comment]
*facepalm* Yes that's it, thanks
