### ISSUE TITLE
Select is unscrollable 

### ISSUE THREAD

**Issue by DaQMinh** [shadcn-ui/ui#1175]
I have a trouble with select components of shadcn is can't scroll when select item is more higer than the screen.
removed `overflow-hidden` in components/ui/select  file still can't solve the problem

**Comment by neilk17** [comment]
You can try to set the max-width or use overflow-x
https://tailwindcss.com/docs/overflow#scrolling-if-needed

**Comment by dan5py** [comment]
Hi @DaQMinh, you can make your `SelectContent` scrollable by passing `overflow-y-auto` and `max-h-[YOUR_CHOICE]` classes. 
Like this:

```tsx
<SelectContent className="overflow-y-auto max-h-[10rem]">
        <SelectGroup>
          <SelectLabel>Fruits</SelectLabel>
          <SelectItem value="apple">Apple</SelectItem>
          <SelectItem value="banana">Banana</SelectItem>
          <SelectItem value="blueberry">Blueberry</SelectItem>
          <SelectItem value="grapes">Grapes</SelectItem>
          <SelectItem value="pineapple">Pineapple</SelectItem>
        </SelectGroup>
</SelectContent>
```

**Comment by diptaMVN** [comment]
Hi @dan5py, your given example is not working. But if I add that class (overflow-y-auto max-h-[10rem]) on SelectGroup, then It is working but It can't scrolling by mouse scroll wheel.

**Comment by giacomoferretti** [comment]
> Hi @dan5py, your given example is not working from my side. But if I add that class (overflow-y-auto max-h-[10rem]) on SelectGroup, then It is working but It can't scrolling by mouse scroll wheel.

You need to put it on `SelectContent`.

**Comment by diptaMVN** [comment]
@giacomoferretti I put it on `SelectContent`. but it can't scrolling.

**Comment by jeffmerrick** [comment]
@diptaMVN This also occurred for me when the select was in a dialog. Changing the dialog component so `DialogPrimitive.Content` is wrapped in `DialogOverlay` instead of a sibling fixed the issue and allowed the overflow and max-h classes to work.

**Comment by Apestein** [comment]
> Hi @DaQMinh, as @neilk17 suggested, you can make your `SelectContent` scrollable by passing `overflow-y-auto` and `max-h-[YOUR_CHOICE]` classes. Like this:
> 
> ```tsx
> <SelectContent className="overflow-y-auto max-h-[10rem]">
>         <SelectGroup>
>           <SelectLabel>Fruits</SelectLabel>
>           <SelectItem value="apple">Apple</SelectItem>
>           <SelectItem value="banana">Banana</SelectItem>
>           <SelectItem value="blueberry">Blueberry</SelectItem>
>           <SelectItem value="grapes">Grapes</SelectItem>
>           <SelectItem value="pineapple">Pineapple</SelectItem>
>         </SelectGroup>
> </SelectContent>
> ```

This works but there is not scrollbar to indicate that it is scrollable.

**Comment by danimydev** [comment]
> > Hi @DaQMinh, as @neilk17 suggested, you can make your `SelectContent` scrollable by passing `overflow-y-auto` and `max-h-[YOUR_CHOICE]` classes. Like this:
> > ```tsx
> > <SelectContent className="overflow-y-auto max-h-[10rem]">
> >         <SelectGroup>
> >           <SelectLabel>Fruits</SelectLabel>
> >           <SelectItem value="apple">Apple</SelectItem>
> >           <SelectItem value="banana">Banana</SelectItem>
> >           <SelectItem value="blueberry">Blueberry</SelectItem>
> >           <SelectItem value="grapes">Grapes</SelectItem>
> >           <SelectItem value="pineapple">Pineapple</SelectItem>
> >         </SelectGroup>
> > </SelectContent>
> > ```
> 
> This works but there is not scrollbar to indicate that it is scrollable.

If you want to show the scrollable, put it into the SelectGroup component

```tsx
<SelectContent>
  <SelectGroup className="overflow-y-auto max-h-[10rem]">
     {...}
  </SelectGroup>
</SelectContent>
```

**Comment by svarup** [comment]
> @diptaMVN This also occurred for me when the select was in a dialog. Changing the dialog component so `DialogPrimitive.Content` is wrapped in `DialogOverlay` instead of a sibling fixed the issue and allowed the overflow and max-h classes to work.

@jeffmerrick i face the same issue can you share the example code how you fixed it

**Comment by jeffmerrick** [comment]
@svarup In your dialog component change this:
```
  <DialogPortal>
    <DialogOverlay />
    <DialogPrimitive.Content 
    ...
    </DialogPrimitive.Content>
  </DialogPortal>
```
to this:
```
  <DialogPortal>
    <DialogOverlay>
      <DialogPrimitive.Content 
      ...
      </DialogPrimitive.Content>
    </DialogOverlay>
  </DialogPortal>
))
```

More info on it here: https://www.radix-ui.com/primitives/docs/components/dialog#scrollable-overlay

**Comment by 0xtz** [comment]
The issue in the <Sheet /> too i cant scroll ....
it needs the same fix i need to open a new issue?

**Comment by Emmanuel-Xs** [comment]
how to make the scrollbar visible when the shadcnui select component is clicked on

**Comment by Scglia** [comment]
I had this issue with Select components within Sheet and solved it by doing [what jeffmerrick suggested above](https://github.com/shadcn-ui/ui/issues/1175#issuecomment-2228543893) + updating the [react-select dependency](https://www.npmjs.com/package/@radix-ui/react-select) to v2.1.1

**Comment by vanydiah** [comment]
> @svarup In your dialog component change this:
> 
> ```
>   <DialogPortal>
>     <DialogOverlay />
>     <DialogPrimitive.Content 
>     ...
>     </DialogPrimitive.Content>
>   </DialogPortal>
> ```
> 
> to this:
> 
> ```
>   <DialogPortal>
>     <DialogOverlay>
>       <DialogPrimitive.Content 
>       ...
>       </DialogPrimitive.Content>
>     </DialogOverlay>
>   </DialogPortal>
> ))
> ```
> 
> More info on it here: https://www.radix-ui.com/primitives/docs/components/dialog#scrollable-overlay

I've spent 1 day to figuring out. I also update radix-ui package version. 
Finally i found the answer here.
Thank you @jeffmerrick , you made my day ✨

**Comment by shedrack-prog** [comment]
> how to make the scrollbar visible when the shadcnui select component is clicked on

Add className="overfow-y-scroll max-h-[your-choice]" to the <SelectGroup></SelectGroup> component

**Comment by Evavic44** [comment]
Thanks a lot. @jeffmerrick. Your solution also works on the drawer component

**Comment by edjo241** [comment]
Try out Event Handler Solution, like
onWheel={(e) => e.stopPropagation()}

 It prevents the event from bubbling up to parent elements.  The current element still handles the event.
