### ISSUE TITLE
Website's `--radius` is broken

### ISSUE THREAD

**Issue by DaniGuardiola** [shadcn-ui/ui#1176]
The `--radius` var is broken and has `undefinedrem` as value, causing border radiuses to not work (e.g. Input or Card demos). See video:

[shadcn-bug.webm](https://github.com/shadcn-ui/ui/assets/8862967/d645dc9a-e415-431e-89c0-7a1151814de5)

**Comment by shadcn** [comment]
Hmm I think I know what's happening here. I'll fix. Thanks for the heads up.

**Comment by JohnKinyanjui** [comment]
This is also happening for almost all components not sure if its related but when i add Button and Input they had no radius

<img width="663" alt="Screenshot 2023-08-12 at 13 32 55" src="https://github.com/shadcn-ui/ui/assets/52638680/f05feda3-0169-4520-9d88-e097c0e4c951">

**Comment by zaleGZL** [comment]
I noticed that all the components on the website have become right-angled. I thought it was a "break change" feature, haha.

**Comment by limitless-dev** [comment]
A temporary solution is to define the `radius` property on the `body` within the same `useEffect` that manages the themes. 

```tsx
// apps/www/components/theme-switcher.tsx

  React.useEffect(() => {
     // ..
    if (theme) {
      document.body.style.setProperty('--radius', `${config.radius}rem`);
      return document.body.classList.add(`theme-${theme}`)
    }
  }, [segment, config.radius, config.theme])

```

**Comment by shadcn** [comment]
Fixed. Thank you.
