### ISSUE TITLE
Payment cards :has selector does not work on Firefox

### ISSUE THREAD

**Issue by alonsourena** [shadcn-ui/ui#1178]
I have discovered that in `example/cards/payment-method.tsx`, the `[&:has([data-state=checked]))]:border-primary` class does not work in Firefox, because it is not yet supported.

So I managed to fix it by tweaking the code a bit and using the `peer` variant.

So my code now looks like this for each RadioGroupItem

```
<div>
    <RadioGroupItem
        value="card"
        id="card"
        className="peer sr-only"
        aria-label="Card"
    />
    <Label
        htmlFor="card"
        className="flex flex-col items-center justify-between rounded-md border-2 border-muted bg-transparent p-4 hover:bg-accent peer-data-[state=checked]:border-primary hover:text-accent-foreground [&:has([data-state=checked])]:border-primary"
    >
        <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            className="mb-3 h-6 w-6"
        >
            <rect width="20" height="14" x="2" y="5" rx="2" />
            <path d="M2 10h20" />
        </svg>
        Card
    </Label>
</div>
```

**Comment by dan5py** [comment]
Great job @alonsourena! It's always Firefox 😄. We already had a problem with the `:has` pseudo-class on another component. 

Could please create a PR for this?

**Comment by alonsourena** [comment]
Sure thing! Never done one before but I'm going to figure out a way to do it 👍🏻.

**Comment by shadcn** [comment]
Fixed by https://github.com/shadcn-ui/ui/pull/1209
