### ISSUE TITLE
Question: Introducing new colors/variants to a component

### ISSUE THREAD

**Issue by willwillis** [shadcn-ui/ui#1208]
Am I doing this right?

To add a new style for a button I need to 

1. introduce new colors`--variables` in `globals.css`
2. extend the theme, referencing said variables in `tailwind.config.js` 
3. add a new variant to `badgeVariants`, referencing the color key from step2

I would need to follow this pattern for every new color I want to introduce, right? The workflow seems a bit cumbersome, is there no way to piggy back off the colors already defined in stock tailwind, or even Radix? I'm guessing there is, I just couldn't find any reference for how to accomplish this in the docs. TIA.

**Comment by dan5py** [comment]
Hi @willwillis, if you want you just use the base tailwind colors and add a new variant based off them, like this:

```tsx
success: 'border-transparent bg-green-500 text-success-foreground',
```

And then use the new variant:

```tsx
<Badge variant="success">Badge</Badge>
```

**Comment by LiuZhenyan-Wuzhong** [comment]
Hi, @willwillis , have you solved this? I want to switch theme like what shadcn-ui's website did but I have no idea.

**Comment by willwillis** [comment]
> Hi @willwillis, if you want you can just use the base tailwind colors and add a new variant based off them, like this:
> 
> ```tsx
> success: 'border-transparent bg-green-500 text-success-foreground',
> ```
> 
> And then use the new variant:
> 
> ```tsx
> <Badge variant="success">Badge</Badge>
> ```

This worked! Thank you.
