### ISSUE TITLE
docs: missing useForm Import in Form Component Example

### ISSUE THREAD

**Issue by kishanhitk** [shadcn-ui/ui#1223]
In the Form component page of the current documentation, the example code under the usage section is missing the code to import `useForm` from `react-hook-form`. This can be inconvenient for users who might copy-paste the example directly.

For clarity, here's a portion of the code from the section:

```
"use client"

import Link from "next/link"
import { zodResolver } from "@hookform/resolvers/zod"
import * as z from "zod"

const formSchema = z.object({
  username: z.string().min(2, {
    message: "Username must be at least 2 characters.",
  }),
})

export function ProfileForm() {
  // 1. Define your form.
  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      username: "",
    },
  })

  // 2. Define a submit handler.
  function onSubmit(values: z.infer<typeof formSchema>) {
    // Do something with the form values.
    // ✅ This will be type-safe and validated.
    console.log(values)
  }
}
```

Notice the absence of the useForm import.

I'm suggesting we add:
```
import { useForm } from "react-hook-form";
```
I'm happy to open a PR to address this.

**Comment by dan5py** [comment]
@kishanhitk thanks for the issue and the PR but this is a duplicate of #663

**Comment by kishanhitk** [comment]
Thanks @dan5py,
Closing this issue.
