### ISSUE TITLE
Extra semicolon in custom theme css output

### ISSUE THREAD

**Issue by SyedAhkam** [shadcn-ui/ui#1233]
It seems to generating an extra `;` at `--popover` variable declaration.

![image](https://github.com/shadcn-ui/ui/assets/52673095/8e7fe1ea-ed6f-4c1a-9979-6620e29f3143)

Seems to be only affecting the Zinc color theme

**Comment by dan5py** [comment]
Hi @SyedAhkam this has just been fixed with #1152 and 8be9e5d96623105c3fd8b46e53098c4591353245.

**Comment by SyedAhkam** [comment]
Oh I might've missed that. Thanks!
