### ISSUE TITLE
cli fails to build

### ISSUE THREAD

**Issue by kurtisdunn** [shadcn-ui/ui#1237]
npx shadcn-ui@latest init fails with Unexpected token {

Using Nextjs build process

```shell
~/project main ❯ npx shadcn-ui@latest init                    10s 13:42:51

npx: installed 198 in 12.828s
Unexpected token {
~/project main ❯                                              14s 13:43:26

```

**Comment by kurtisdunn** [comment]
Resolved.

**Comment by allanctan** [comment]
how did you fix this error? I encountered same problem,

**Comment by allanctan** [comment]
Fixed it already by running the command on external terminal instead of terminal inside VSCode.

**Comment by DarkcoderSe** [comment]
getting same issue
