### ISSUE TITLE
Toast import error inside a function

### ISSUE THREAD

**Issue by ShahriarDhruvo** [shadcn-ui/ui#1262]
I am using shadcn/ui toast like this:

In /lib/utils.ts file I have called toast like this:
```
import { toast } from "@/components/ui/use-toast";

function jsonAlert(title: string, description: object | string) {
  toast({
    title: title,
    description: formatJSON(description),
  });
}
```

Then calling JSON alert inside a functional component. And by doing this I am facing this warning while running next dev and next build:

```
Import trace for requested module:
./components/ui/use-toast.ts
./lib/utils.ts
./app/layout.tsx
- wait compiling...
- warn ./components/ui/use-toast.ts
Attempted import error: 'useState' is not exported from 'react' (imported as 'React').

Import trace for requested module:
./components/ui/use-toast.ts
./lib/utils.ts
./app/layout.tsx

./components/ui/use-toast.ts
Attempted import error: 'useEffect' is not exported from 'react' (imported as 'React').
```

The toast is rendering just file but I am wondering if I should do something about this warning and fix any potential bug?

**Comment by ShaikRehan123** [comment]
Are you using 'use client'.
I think to use toast component need to be client, Correct me If I'm wrong.

**Comment by ShahriarDhruvo** [comment]
I am using 'use client' at the parent level not at the file where I declare the definitions. I have defined jsonAlert function in a utils.ts file which is not specified any 'use client of use server' but I used this function in a page where I used 'use client'. As the parent uses use client the child shouldn't have the issue right?

**Comment by ShaikRehan123** [comment]
Yes, It's weird, I also faced this issue due to not using 'use client' at the top, but I used toast directly inside the component.

But I used `useToast`.

**Comment by ShaikRehan123** [comment]
If possible, can you share the code of the component you are trying to use toast.

**Comment by ShahriarDhruvo** [comment]
I have solved this warning by moving the function definition from utils.ts to another file, I called it csf.ts. And now it doesn't warns me while building or running the dev server. I didn't use any directive like "use client" at the top of csf.ts file. It increase the build size by a few bytes (Enough to make the 130kb build's color to change from green to yellow :3) But I am fine with it rather than having any warning which could lead to some unknown behaviour.

I can close this issue if you think it's a right move?

**Comment by ShaikRehan123** [comment]
Yes close the issue.

I tried your code,

It was confusing, I got the error you got first time, then I added ` 'use client'` at the top of utils.ts, the error was gone.

I again removed 'use client', but this time there was no error.
