### ISSUE TITLE
Add position prop to toaster

### ISSUE THREAD

**Issue by minjie0501** [shadcn-ui/ui#128]
Any plans on adding a 'position' prop that could be passed when using the useToast hook? 
Something similar to react-hot-toast ⬇️ 
`
toast('Hello World', {
  position: 'top-center',
});
`

**Comment by shadcn** [comment]
You mean on a per toast basis. You generally want all your toasts to always be from one position. 

If you want to switch to `top center`, you can do this by changing the classes here: https://github.com/shadcn/ui/blob/faf05aa086c27d1d7a021cb716768ac2e1261f65/apps/www/components/ui/toast.tsx#L17

```diff
- fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4 sm:top-auto sm:bottom-0 sm:right-0 sm:flex-col md:max-w-[420px]
+ fixed top-0 left-[50%] z-[100] flex max-h-screen w-full translate-x-[-50%] flex-col-reverse p-4 sm:right-0 sm:flex-col md:max-w-[420px]
```

This will position the toast to the top center. (Might need some animations adjustments)

**Comment by minjie0501** [comment]
Yes I do want to do it on a per toast basis. I agree that it should appear in the same position in most cases but I do have a use case where I would like it to appear in a different place for one of the toasts.

**Comment by hiql** [comment]
One time one toast not enough, showing multiple toasts is the common senario

**Comment by AdisonCavani** [comment]
`react-hot-toast` API has `id` prop.
It allows to create multiple toasts without duplication.

Are you planning to update Toast component to have that feature?

See: https://react-hot-toast.com/docs/toast
@: Prevent duplicate toasts

**Comment by Ryuk-hash** [comment]
Hi, any update on this?

**Comment by AuroraLantean** [comment]
The above `cn` function is defined here:
```
import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
```

**Comment by goktugerce** [comment]
> For Top-Right, just remove `sm:top-auto sm:bottom-0` from the Shadcn toast.tsx. So the result would be:
> 
> ```
> "fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4  sm:right-0  sm:flex-col md:max-w-[420px]",
> ```

I found that it is also a good idea to change `data-[state=open]:sm:slide-in-from-bottom-full` to `data-[state=open]:sm:slide-in-from-top-full` for a nicer animation.

**Comment by Azoonex** [comment]
You can change it in the toast component


```javascript
const toastVariants = cva(
  "group pointer-events-auto relative flex w-full items-center justify-between space-x-4 overflow-hidden rounded-md border p-6 pr-8 shadow-lg transition-all data-[swipe=cancel]:translate-x-0 data-[swipe=end]:translate-x-[var(--radix-toast-swipe-end-x)] data-[swipe=move]:translate-x-[var(--radix-toast-swipe-move-x)] data-[swipe=move]:transition-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[swipe=end]:animate-out data-[state=closed]:fade-out-80 data-[state=closed]:slide-out-to-right-full data-[state=open]:slide-in-from-top-full data-[state=open]:sm:slide-in-from-bottom-full",
  {
    variants: {
      variant: {
        default: "border bg-background text-foreground",
        destructive:
          "destructive group border-destructive bg-destructive text-destructive-foreground",
        success: "bg-teal-400 border-white text-white ",
        error: "bg-red-400 text-white"
      },
      position: {
        default: 'top-0 right-0 flex fixed md:max-w-[420px] md:top-4 md:right-4',
      }
    },
    defaultVariants: {
      variant: "default",
      position: "default"
    },
  }
)

And then change

```javascript
const Toast = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Root> &
  VariantProps<typeof toastVariants>
>(({ className, variant, position, ...props }, ref) => {
  return (
    <ToastPrimitives.Root
      ref={ref}
      className={cn(toastVariants({ variant, position }), className)}
      {...props}
    />
  )
})
Toast.displayName = ToastPrimitives.Root.displayName

**Comment by polarisiota** [comment]
> > For Top-Right, just remove `sm:top-auto sm:bottom-0` from the Shadcn toast.tsx. So the result would be:
> > ```
> > "fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4  sm:right-0  sm:flex-col md:max-w-[420px]",
> > ```
> 
> I found that it is also a good idea to change `data-[state=open]:sm:slide-in-from-bottom-full` to `data-[state=open]:sm:slide-in-from-top-full` for a nicer animation.

This works for me. Thanks.

**Comment by Bin-Mohammad** [comment]
are toast top-right animation fixes available?

**Comment by HugoRamonPereira** [comment]
@Bin-Mohammad you can adapt the code above from @polarisiota. You can paste the code in the toast.tsx file in the components/ui folder and in the styles for the <ToastPrimitives.Viewport> you can paste the following: "fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4  sm:right-0  sm:flex-col md:max-w-[420px]" and in the same file but in the toastVariants variable at the end of the styles you can paste the following changes, instead of "data-[state=open]:slide-in-from-top-full data-[state=open]:sm:slide-in-from-top-full" you should paste "data-[state=open]:slide-in-from-right-full data-[state=open]:sm:slide-in-from-right-full" and by doing so you will have animations appearing from top-right and animated coming from the right in such a smooth way.

**Comment by HugoRamonPereira** [comment]
@Bin-Mohammad you can adapt the code above from @polarisiota. You can paste the code in the toast.tsx file in the components/ui folder and in the styles for the <ToastPrimitives.Viewport> you can paste the following: 

```
"fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4 sm:right-0 sm:flex-col md:max-w-[420px]"
```

 and in the same file but in the toastVariants variable at the end of the styles you can paste the following changes, instead of 

```
"data-[state=open]:slide-in-from-top-full data-[state=open]:sm:slide-in-from-top-full"
```

 you should paste 

```
"data-[state=open]:slide-in-from-right-full data-[state=open]:sm:slide-in-from-right-full" 
```

and by doing so you will have animations appearing from top-right and animated coming from the right in such a smooth way.

**Comment by Andynopol** [comment]
```
const viewportVariant = cva(
  'absolute overflow-hidden top-0 z-[100] flex max-h-screen w-full p-4 md:max-w-[420px]',
  {
    variants: {
      variant: {
        'bottom-right': 'sm:right-0 sm:bottom-0 sm:top-auto flex-col sm:flex-col',
        'bottom-left': 'sm:left-0 sm:bottom-0 flex-col sm:top-auto sm:flex-col',
        'top-left': 'sm:left-0 flex-col sm:flex-col-reverse',
        'top-right': 'sm:right-0 flex-col sm:flex-col-revese',
      },
    },
    defaultVariants: {
      variant: 'bottom-right',
    },
  },
);

const toastVariants = cva(
  'group pointer-events-auto relative flex w-full items-center justify-between space-x-2 overflow-hidden rounded-md border p-4 pr-6 transition-all data-[swipe=cancel]:translate-x-0 data-[swipe=end]:translate-x-[var(--radix-toast-swipe-end-x)] data-[swipe=move]:translate-x-[var(--radix-toast-swipe-move-x)] data-[swipe=move]:transition-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[swipe=end]:animate-out data-[state=closed]:fade-out-80',
  {
    variants: {
      variant: {
        default: 'border bg-background text-foreground',
        destructive: 'destructive group border-destructive bg-destructive text-destructive-foreground',
      },
      placement: {
        'bottom-right':
          'sm:right-0 sm:bottom-0 sm:top-auto flex-col sm:flex-col data-[state=open]:slide-in-from-bottom-full data-[state=open]:sm:slide-in-from-bottom-full data-[state=closed]:slide-out-to-right-full',
        'bottom-left':
          'sm:left-0 sm:bottom-0 flex-col sm:top-auto sm:flex-col data-[state=open]:slide-in-from-bottom-full data-[state=open]:sm:slide-in-from-bottom-full data-[state=closed]:slide-out-to-left-full',
        'top-left':
          'sm:left-0 flex-col-reverse sm:flex-col-reverse data-[state=open]:slide-in-from-top-full data-[state=open]:sm:slide-in-from-top-full data-[state=closed]:slide-out-to-left-full',
        'top-right':
          'sm:right-0 flex-col-reverse sm:flex-col-reverse data-[state=open]:slide-in-from-top-full data-[state=open]:sm:slide-in-from-top-full data-[state=closed]:slide-out-to-right-full',
      },
    },
    defaultVariants: {
      variant: 'default',
      placement: 'bottom-right',
    },
  },
);
```

There you go. All 4 corners of the screen. In my case I had to use `position-absolute` to bound it to a specific container, but if you don't have that constraint, use `position-fixed`.

The only thing that I could not solve is the `shadow-lg`. It looks fine on `flex-col`, but weird on `flex-col-reverse`. The shadow comes over the below toast.

Also, very important, I recommend based on the placement of the `ToastViewport` to specify the `swipeDirection` on the `ToastProvider` component:

```
<ToastProvider duration={duration} swipeDirection={placement.split('-')[1] as ToastAnimationsOut}>
  /* code */
</ToastProvider>
```

The placements are: `top-left`, `top-right`, `bottom-left`, `bottom-right`

**Comment by composedshapes-origami** [comment]
trigger:
`toast(error.message);`

display:
`<Toaster position="top-right" />`

available position: top-left, top-center, top-right, bottom-left, bottom-center, bottom-right
