### ISSUE TITLE
Installation instructions for Next.js result in broken app

### ISSUE THREAD

**Issue by hendriklammers** [shadcn-ui/ui#1290]
After following the installation instructions (found [here](https://ui.shadcn.com/docs/installation/next)) for creating a new Next.js project with shadcn, running `npm run dev` will result in **404 This page could not be found** for the root page which can normally be found on localhost:3000.

I first ran: `npx create-next-app@latest my-app --typescript --tailwind --eslint` pressing enter for all default selected values.
Going to localhost:3000 shows the default Next.js template.

Then I ran the second command from the instructions which is: `npx shadcn-ui@latest init`
Going to localhost:3000 now shows **404 This page could not be found**

Expected behaviour: Next.js template to show after running all commands with default options selected.

Versions used:
Node: v18.17.1
NPM: 9.6.7
Next.js: 13.4.19

**Comment by munezerobagira** [comment]
what was the version that you were using before updating and structure (if it is new nextjs app router)that you were using?

**Comment by ShaikRehan123** [comment]
@hendriklammers Are you sure you didn't use src folder.

It asks you this question while creating the next-app:
![Screenshot 2023-08-20 at 3 28 49 PM](https://github.com/shadcn-ui/ui/assets/83860384/9439c4d4-5934-48dd-883c-9491a84d6419)

**Comment by dan5py** [comment]
Duplicate of #755

**Comment by hendriklammers** [comment]
> @hendriklammers Are you sure you didn't use src folder.
> 
> It asks you this question while creating the next-app: ![Screenshot 2023-08-20 at 3 28 49 PM](https://user-images.githubusercontent.com/83860384/261844653-9439c4d4-5934-48dd-883c-9491a84d6419.jpg)

Aah my bad, it was indeed using the src folder.. I thought the preselected answers in the cli were the defaults, but apparently they are stored somewhere from previous usage. Learned something new today 😄 

I tried running the commands again, this time making sure not to use the src folder and everything is working as expected.
