### ISSUE TITLE
bug(docs): unnecessary imports in example of textarea form example 

### ISSUE THREAD

**Issue by NiazMorshed2007** [shadcn-ui/ui#1309]
On Textarea example with Form,, shows some not used imports in code docs which can be removed.

#### How to reproduce?
1. Go to: https://ui.shadcn.com/docs/components/textarea#form
2. Switch to code tab

![image](https://github.com/shadcn-ui/ui/assets/77217706/1731f57b-05f2-4939-9fd7-75dd9af0c4b7)

**Comment by Deveesh-Shetty** [comment]
I would like to work on this!
