### ISSUE TITLE
Tailwind not working in react

### ISSUE THREAD

**Issue by AlivioDev** [shadcn-ui/ui#1340]
@ShaikRehan123 in https://github.com/shadcn-ui/ui/issues/1303#issuecomment-1693737340_
 
 So here a new issue, thank you for that advice.
 
 I have a repository you can have a look at if you want:
 
 https://github.com/AlivioDev/data_table_shadcn-ui.git

**Comment by NikharPandya** [comment]
@AlivioDev we have a cra installation guide [here](https://ui.shadcn.com/docs/installation/manual). looks like the import alias is also not being able resolve the path to import components.

**Comment by AlivioDev** [comment]
@NikharPandya yes I followed this and tried numerous settings, uninstalled everything, reinstalling everything, I have been trying things for 2 days now, and I'm lost.
The only thing that I do know is that at first I was trying to work with tanstack table, following along with a YouTube video, and no matter what I did, my rows were not rendering. Headers, no problem, rows, blanc.
So finally I gave that up, threw everything away (after already starting over from scratch once) and went looking for another approach. Came across this awesome website with super cool components and went for it. Only to end up with another rendering problem. 
something is going on between react and tables...

**Comment by ShaikRehan123** [comment]
The TailwindCSS has not been installed properly, and CRA is not recommended for new React apps and Tailwind.

You can switch to Vite if you think it's possible, Vite has better DX and you can install Tailwind and Shadcn much smoothly.

If you are sure you want to use CRA, then follow the Shadcn Manual Setup, step by step from scratch, then copy and paste your existing code into your new project

**Comment by AlivioDev** [comment]
Thank you @ShaikRehan123 this is very helpful 😊
I don't know Vite yet, but it's worth starting to learn now if CRA is really not keeping up anymore.

Have a nice (rest of the) weekend!
