### ISSUE TITLE
Dialog component X close button with useState

### ISSUE THREAD

**Issue by aleksandrmakarov-dev** [shadcn-ui/ui#1352]
I have useState hook to control open state of dialog. How can change I state from default dialog X close button?
```typescript
const [open, setOpen] = useState<boolean>(false);
<Dialog open={open}>
        <DialogTrigger asChild>
          {trigger}
        </DialogTrigger>
        <DialogContent className="sm:max-w-xl">
           ...
        </DialogContent>
</Dialog>
```

![image](https://github.com/shadcn-ui/ui/assets/128474912/12dc64e2-6859-4574-b837-b01be9b03c16)

**Comment by NikharPandya** [comment]
@aleksandrmakarov-dev 
### You will also need to pass setOpen inside onOpenChange event. And now you can change the state using setOpen, Here is the api refrence from radix ui:-  [Dialog docs](https://www.radix-ui.com/primitives/docs/components/dialog#api-reference) and also a code snippet. 
### Let me know if you need more help.
```
const [open, setOpen] = useState<boolean>(false);
<Dialog open={open} onOpenChange={setOpen}>
        <DialogTrigger asChild>
          {trigger}
        </DialogTrigger>
        <DialogContent className="sm:max-w-xl">
           ...
        </DialogContent>
</Dialog>
```

**Comment by aleksandrmakarov-dev** [comment]
Yes, everything works fine, thank you!
