### ISSUE TITLE
onChange of Input or Textarea in FormControl can not be changed ?

### ISSUE THREAD

**Issue by NguyenHoangHieu22GIT2** [shadcn-ui/ui#1360]
So I am building a markdown system in my website, you can write markdown and then you will see the preview in other panel

![image](https://github.com/shadcn-ui/ui/assets/133379564/5b37e329-f8fd-4ea7-a4de-5e1f5580324b)
Like this.

But for some reason: the value doesn't get updated.
___The Input___
```ts
          <FormField
            control={form.control}
            name="articleBody"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Article Body</FormLabel>
                <FormControl>
                  <Textarea
                    {...field}
                    onChange={(e) => {
                      onChangeValue(e);
                      field.onChange();
                    }}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
```

__The onChangeValue__

```ts
  function onChangeValue(e: React.ChangeEvent<HTMLTextAreaElement>) {
    props.onChangeMarkdown(e.target.value);
  }
```
the props.onChangeMarkdown is just a "lifting state up" function only

So I look into field properties and it's all "On" handler functions, so I figured it out is to use field.onChange() inside of onChange() function to see if the value is being updated but it doesn't  work either.

Maybe I am bad at explaining to this is a video for you to understand.

https://github.com/shadcn-ui/ui/assets/133379564/9c71eb6d-4261-45c8-99ef-ff31d69bbfb2

Thank you!

**Comment by limitless-dev** [comment]
This will keep resetting field value `articleBody`:
``` tsx
field.onChange();
```
Try below instead:
```tsx
field.onChange(e.target.value)
```

**Comment by NguyenHoangHieu22GIT2** [comment]
> This will keep resetting field value `articleBody`:
> 
> ```tsx
> field.onChange();
> ```
> 
> Try below instead:
> 
> ```tsx
> field.onChange(e.target.value)
> ```

Oh wow, I am dumb... Didn't think of that. Now this is something that typescript can help us do better with an error :D thank you for your answer <3 !
