### ISSUE TITLE
Outdated "Getting started" docs?

### ISSUE THREAD

**Issue by mahmoudkhader** [shadcn-ui/ui#1362]
The first part of the Getting Started docs states:

```md
---
title: Introduction
description: Re-usable components built using Radix UI and Tailwind CSS.
---

This is **NOT** a component library. It's a collection of re-usable components that you can copy and paste into your apps.

**What do you mean by not a component library?**

I mean you do not install it as a dependency. It is not available or distributed via npm.
```

I had actually found out about the site due to it's connection to Radix, so I was confused by this statement. Took me a while to figure out how to proceed with it, because as far as the component documentation is concerned, there are no imports from "@radix-ui". 

There's also the npm page that threw me off: https://www.npmjs.com/package/shadcn-ui.

I could be wrong and this could just be outdated docs, but just wanted to raise the issue in case other newcomers get confused as I did.

**Comment by Xenfo** [comment]
You copy and paste the component code or install it with the CLI. This might have imports from Radix UI. Then you import the component that you've installed which doesn't have Radix imports and you use it.

So the library is made using Radix UI but you don't have to actually touch anything from Radix for it to work.

**Comment by miquelvir** [comment]
@mahmoudkhader it means there are no imports of shadcn, the point is you directly import the dependencies (i.e. radix). I believe the text is clear enough. Could we close this?

**Comment by mahmoudkhader** [comment]
Yes, I understand how it works now. It wasn't very clear at first, but I got the hang of it after a while. I'll close the issue, though I'd recommend rephrasing "It is not available or distributed via npm" given that the default docs for each component feature an npx command for the component installation.
