### ISSUE TITLE
responsive issue on mobile with data table

### ISSUE THREAD

**Issue by asavor** [shadcn-ui/ui#1378]
![image](https://github.com/shadcn-ui/ui/assets/74147411/e0251141-830c-48f1-9212-4f90650989e0)
```ts
<DropdownMenuTrigger asChild>
            <Button variant="ghost" className="h-8 w-8 p-0">
              <span className="sr-only">Open menu</span>
              <MoreHorizontal className="h-4 w-4" />
            </Button>
</DropdownMenuTrigger>
```

The button component seem to cause responsive issue on mobile.

**Comment by omgismartinez** [comment]
hi @asavor I have made a PR where I explain and solve this problem #1345
