### ISSUE TITLE
Themes are not consistent in Nextjs 13

### ISSUE THREAD

**Issue by ryzzer0** [shadcn-ui/ui#1392]
This is how my directory looks like and my theme provider wraps the root layout. However when I switch from the home page to the signup page the theme changes from system default to light and if I refresh the page it changes back to system default. However, if I switch from the home page to demo/pricing/contact it stays consistent. Is this because I am using Nextjs Route Groups?

<img width="239" alt="Screenshot 2023-08-30 at 12 51 01 PM" src="https://github.com/shadcn-ui/ui/assets/51649853/cd845a34-e1b4-453a-9886-e0f803077ffc">

**Comment by emigdio821** [comment]
Hi, are you using `next-themes`? if so, it should look similar to this:
![code](https://github.com/shadcn-ui/ui/assets/6751108/d21427ba-41d0-4e03-b1e9-de8f9b70be89)

[Here](https://ui.shadcn.com/docs/dark-mode/next) are the steps to setup `Next.js` with `next-themes`.

**Comment by ryzzer0** [comment]
Hi @emigdio821 I am using next-themes and have followed the exact steps. I have the theme-provider.tsx in my component folder and it wraps around the root layout. Here is the code : 
`import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'
import { ThemeProvider } from '@/components/theme-provider'
import { ModeToggle } from '@/components/mode-toggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}

` and for theme-provider.tsx 
`"use client"

import * as React from "react"
import { ThemeProvider as NextThemesProvider } from "next-themes"
import { type ThemeProviderProps } from "next-themes/dist/types"

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>
}
`

**Comment by deven298** [comment]
Hi @ryzzer0 

How did you solve your problem? I am running into the same issue.

**Comment by ryzzer0** [comment]
Hey @deven298,

I was just using the Next.js layout feature incorrectly. I used the `<html>` and `<body>` tags twice, once in one layout and once in another, but I should have only used them in the root layout.

**Comment by ryzzer0** [comment]
Not really. Other than the issue I mentioned above, if you've followed all the setup steps correctly, I'm not sure what else could be causing the problem.

**Comment by juanpeyrot** [comment]
> Oh, okay.
> 
> I have default=system theme working in the app/page.tsx file. However when I transition through the link tag to another page somehow the theme changes to light. Any idea what could be the issue?

Hi, could you solve this one? i'm running into the same problem.
