### ISSUE TITLE
Checkbox isnt overlapped by element background

### ISSUE THREAD

**Issue by DaQMinh** [shadcn-ui/ui#1419]
![image](https://github.com/shadcn-ui/ui/assets/114815151/f097cd3d-271e-448e-a7d0-3e9f361ae2c2)
Im doing sticky header for a Data Table here it's the code
```tsx
<nav
className={cn("sticky top-0 bg-background", className)}
>
      Home
</nav>
```

**Comment by limitless-dev** [comment]
Try to add `z-index` in the navbar so that it gets a priority over the checkbox.
```
className={cn("... z-[100]", className)}
```

**Comment by arjay-dala** [comment]
Hi, I am also doing sticky header on my data table but its not working. I have already tried putting classnames sticky and top-0 on table header but still not working, here's the code:

<div className="rounded-md border overflow-auto max-h-[50vh]">
        <Table id="table-main" className="min-w-full">
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => {
                  return (
                    <TableHead key={header.id} className="sticky top-0 z-[100]">
                      {header.isPlaceholder
                        ? null
                        : flexRender(
                            header.column.columnDef.header,
                            header.getContext()
                          )}
                    </TableHead>
                  )
                })}
              </TableRow>
            ))}
          </TableHeader>
