### ISSUE TITLE
Truncate don't work in Command/Scroll area

### ISSUE THREAD

**Issue by Natchii59** [shadcn-ui/ui#1421]
Hello, I would like to have a combobox component, with a scrollable area. I set a fixed width to 200px. The problem is when the number of characters exceeds the width, my `truncate` attribute (from tailwindcss) doesn't work because of the ScrollArea. I tried without it and it works. Do you have a solution for using truncate with ScrollArea?

My code:
```ts
<CommandGroup heading={'Wallets'}>
  <ScrollArea className='h-[96px]'>
    {wallets.map(wallet => (
      <CommandItem
        key={wallet.id}
        onSelect={() => {
          setWallet(wallet)
          setPopoverOpen(false)
        }}
        className='text-sm'
      >
        <Avatar className='mr-2 h-5 w-5'>
          <AvatarImage
            src={`https://avatar.vercel.sh/${wallet.id}.png`}
            alt={wallet.name}
          />
          <AvatarFallback />
        </Avatar>

        <span className='flex-auto truncate'>{wallet.name}</span>  <----- HERE

        {selectWallet?.id === wallet.id && (
          <Icons.check className='h-4 w-4' />
        )}
      </CommandItem>
    ))}
  </ScrollArea>
</CommandGroup>
```

Screenshot:
<img width="209" alt="image" src="https://github.com/shadcn-ui/ui/assets/96394660/77c32620-a8bc-4851-a43f-59bdb91381f2">

**Comment by WangLarry** [comment]
@Natchii59 https://github.com/radix-ui/primitives/issues/926#issuecomment-1266790070

**Comment by holdenmatt** [comment]
I was running into a similar issue (child elements of a ScrollArea not respecting w-full).

After finding this issue, here's a simple workaround for shadcn adapted from the radix-ui issue thread:

<ScrollArea className="[&>div>div]:!block">{children}</ScrollArea>
