### ISSUE TITLE
Error: `Toast` must be used within `ToastProvider`

### ISSUE THREAD

**Issue by dinogomez** [shadcn-ui/ui#1424]
![image](https://github.com/shadcn-ui/ui/assets/41871666/a8040529-0a49-4d53-b55d-a754d28c7a54)
![image](https://github.com/shadcn-ui/ui/assets/41871666/1eb1a124-bf87-42c3-a6d4-c1a745225a99)

I got this issue when using the Toast downloaded using the cli

**Comment by vedantpatil2021** [comment]
Try to add <Toaster/> inside the main tag

**Comment by JosephVoid** [comment]
@dinogomez Did you solve the issue?

**Comment by JosephVoid** [comment]
@dinogomez Did you solve the issue?
I just had the same issue.

**Comment by dinogomez** [comment]
> @dinogomez Did you solve the issue? I just had the same issue.

Hi, yup I got it to work with following the documentation

1. Add the `<Toaster />` inside the body tag and double check it comes from `/ui/toaster` since theres another toaster coming from `/ui/sonner` which is a opinionated variant of it.

2. Then you can use the toaster inside your components with the `useToast()` hook.

Example from the docs.

```ts
"use client"
 
import { Button } from "@/components/ui/button"
import { useToast } from "@/components/ui/use-toast"
 
export function ToastSimple() {
  const { toast } = useToast()
 
  return (
    <Button
      variant="outline"
      onClick={() => {
        toast({
          description: "Your message has been sent.",
        })
      }}
    >
      Show Toast
    </Button>
  )
}
```

**Comment by JosephVoid** [comment]
Hi @dinogomez 

I solved it. On the RootLayout, I imported `ui/toast` instead of `ui/toaster`.
with `<Toaster/>` it works.

Thanks man.

**Comment by LKL2017** [comment]
I made the same mistake you did 🤣 , and thanks for your information
