### ISSUE TITLE
error 404 

### ISSUE THREAD

**Issue by burhan-maliksher** [shadcn-ui/ui#1439]
on integrating shadcn in next js 13.once the app reloads it says 404.

**Comment by muradbu** [comment]
Same issue

**Comment by ShaikRehan123** [comment]
Can you share your directory, maybe duplicate of https://github.com/shadcn-ui/ui/issues/755

**Comment by burhan-maliksher** [comment]
> Can you share your directory, maybe duplicate of #755

thanks for sharing reference issue resolved . as it was creating a new app directory outside src directory

**Comment by burhan-maliksher** [comment]
> Same issue
check these links this worked for me :
1.https://github.com/shadcn-ui/ui/issues/755#issuecomment-1633710780
2.https://github.com/shadcn-ui/ui/issues/755#issuecomment-1615939390
