### ISSUE TITLE
The Select style are wrong inside Dialog

### ISSUE THREAD

**Issue by lucasjinreal** [shadcn-ui/ui#1440]
![image](https://github.com/shadcn-ui/ui/assets/21303438/232f4d40-6e90-4364-8e76-c8f864837b17)

Don't know why, my website other where using Select have hover effecet

But place it inside Dailog, it was gone. No hover effect

**Comment by rafael-ferreira-11** [comment]
Having the same issue @lucasjinreal , any luck on figuring it out?

**Comment by Marcosfitzsimons** [comment]
✋🏽 Same problem here when using the select in a dialog

**Comment by zaleGZL** [comment]
+1
