### ISSUE TITLE
Type imports break Astro

### ISSUE THREAD

**Issue by ahkhanjani** [shadcn-ui/ui#1442]
In my Astro project I'm using some shadcn components and for some reasonm out of my 3 components with `client:load`, one of them didn't run the JS on the client and React dev tools didn't recognize that one component either. I was also getting this error on my client console: `Uncaught (in promise) SyntaxError: The requested module '/node_modules/.vite/deps/@radix-ui_react-dialog.js?v=6c257eda' does not provide an export named 'DialogProps' (at command.tsx:2:10)`.

In the latest version of the Command component you're doing:
```ts
import { DialogProps } from "@radix-ui/react-dialog"
```
which makes TS yell `DialogProps is a type and must be imported using a type-only import when verbatimModuleSyntax is enabled.`. Changing that to a `type` import fixed the problem.

This seems to be the case for some other components as well. Please make them a `type` import like this:
```ts
import { type DialogProps } from "@radix-ui/react-dialog"
```

It's really not ideal to make changes ourselves to the installed components as it makes the CLI `diff` command obsolete. A proper ESLint rule would catch these before they break things in our websites.

We all really appreciate the work you put in this library. But as #1436 suggests, the issue count is way too high right now. My other issue #889 which appears to be many others' problem as well has got no response yet. I hope to at least see an announcement to get more help from the community.

**Comment by jlarmstrongiv** [comment]
The `Form` component is also affected by the same type imports issue

**Comment by chribjel** [comment]
I always enable `verbatimModuleSyntax` in my projects, and i always have to modify the imports in the shadcn `Form`.

Would love for all type imports to be imported with the type keyword by default, as they shouldn't break anything if you haven't enabled `verbatimModuleSyntax`.

**Comment by alicercedigital** [comment]
This is something that everyone of us have to do when install shadcn on ts projects. It is just put the type on the imports.
