### ISSUE TITLE
[bug] Inconsistent Suggestions in Command Input Box

### ISSUE THREAD

**Issue by rajgop1** [shadcn-ui/ui#1450]
### Issue Description:
The command input box is not providing consistent suggestions based on user input. When typing a partial query, such as "se," the input box should display relevant suggestions. However, when additional characters are added or removed, the suggestions do not consistently reflect the available options, causing confusion for users.

### Steps to Reproduce:
1. Open the link https://ui.shadcn.com/docs/components/command and navigate to the command input box.
2. Start typing a partial query, such as "se," to trigger suggestions.

#### Expected Behavior:
- The input box should show relevant suggestions based on the partial query.

3. Continue typing or modifying the query and the press backspace.

#### Expected Behavior:
- The input box should update and display relevant suggestions based on the current query.

#### Actual Behavior:
- The suggestions in the input box are not consistently updated to reflect the available options as the query is modified.

### Additional Information:
- This issue impacts the user experience and may lead to confusion as users expect the input box to provide accurate and up-to-date suggestions.
- It's important to ensure that the command input box dynamically adjusts its suggestions as the user types or modifies their query to provide a smooth and intuitive user experience.
- This issue should be addressed to improve the overall usability of the command input box.

I would like to work on this issue and contribute to its resolution. Please assign it to me.

**Comment by ahmadghoniem** [comment]
i had the same issue and what i can contribute to solve this issue right now is that under the hood cmdk uses the commandItem dom element's textContent to search the commands

**Comment by NicoToff** [comment]
Bumping this.

Is there a configuration to change this behaviour in the <Command> component? It's a bit frustrating that it only updates the result when the input becomes longer, but nothing happens when characters are deleted from it (except when removing everything).

Also, pressing "enter" doesn't trigger the first element in the list.

**Comment by NicoToff** [comment]
The result update when removing characters has been fixed as part of cmdk 0.2.1 🎉
