### ISSUE TITLE
Extra spacing on mobile view when Select component is in open state

### ISSUE THREAD

**Issue by iamshubhamjangle** [shadcn-ui/ui#1451]
When viewing on mobile view from chrome browser using dev tools. `<Select />` brings up spacing at right throughout the page when it's in open state. Not sure why it's happening.

let me know if we require more information.

Screenshot:
<img src="https://i.imgur.com/lydO6j9l.png" />

```
<FormField
  control={form.control}
  name="gender"
  render={({ field }) => (
    <FormItem>
      <FormLabel>Gender</FormLabel>
      <Select
        onValueChange={field.onChange}
        defaultValue={field.value}
      >
        <FormControl>
          <SelectTrigger>
            <SelectValue placeholder="Select your gender" />
          </SelectTrigger>
        </FormControl>
        <SelectContent>
          <SelectItem value="Male">Male</SelectItem>
          <SelectItem value="Female">Female</SelectItem>
          <SelectItem value="Other">Other</SelectItem>
        </SelectContent>
      </Select>
      <FormMessage />
    </FormItem>
  )}
/>
```

**Comment by Joshuajrodrigues** [comment]
Seems like a css issue no ? Have you tried making select width w-full  for small screen ?

**Comment by iamshubhamjangle** [comment]
> Seems like a css issue no ? Have you tried making select width w-full for small screen ?

Yeah It's css issue. Thanks.
