### ISSUE TITLE
shadcn-ui@latest init doesnt work on node v20.6.0

### ISSUE THREAD

**Issue by arnvgh** [shadcn-ui/ui#1458]
![image](https://github.com/shadcn-ui/ui/assets/102473837/29df8385-6ebd-4911-9407-0683ae011af0)

```bash
> node -v       
v20.6.0
> uname -a
Linux fedora 6.2.9-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux
```

Tried the same project with shadcn-ui@latest init with node -v lts (v18.17.1) and it worked correctly.

### To reproduce
```bash
nvm use node # get the latet sone using nvm install node (in this case v20.6.0)
pnpm create next-app@latest my-app --typescript --tailwind --eslint
pnpm dlx shadcn-ui@latest init
```

**Comment by Bonchouuuur** [comment]
I'm facing the same issue with Node 20.6.0 but it works properly with Node 20.5.1

**Comment by Bonchouuuur** [comment]
It's possibly outside the repo for now since babel (and even node) itself is issuing in the same way

https://github.com/babel/babel/issues/15927

**Comment by Thanaen** [comment]
Hello @Bonchouuuur! Since the problem is solved, and it was on the Node.js side, maybe the issue could be closed?

**Comment by Bonchouuuur** [comment]
Yes ! @arnvgh can you close it if update Node with 20.6.1 solved your issue ?

**Comment by arnvgh** [comment]
Yep sure, closing it as we got the issue solved.

**Comment by Thanaen** [comment]
Oops, my bad, I thought you were the author of the issue 😅

**Comment by sumituppal03** [comment]
Can any one help for installing shadcn.ui on vs code while i installed Node.js v24 LTS which shadcn.ui cant run

**Comment by Thanaen** [comment]
> Can any one help for installing shadcn.ui on vs code while i installed Node.js v24 LTS which shadcn.ui cant run

@sumituppal03 I think you should open a new issue for this problem!
