### ISSUE TITLE
Component (Popover/ Dialog / Command) TS issues in Turborepo with NextJS?

### ISSUE THREAD

**Issue by rnnyrk** [shadcn-ui/ui#1459]
I'll keep  running into TS issues with components in my Turborepo. I don't know how to fix them. 

<img width="1735" alt="Screenshot 2023-09-06 at 10 34 58" src="https://github.com/shadcn-ui/ui/assets/4519142/872bf139-a3c9-4e4c-b161-a382bfdf2c82">
<img width="1760" alt="Screenshot 2023-09-06 at 10 34 49" src="https://github.com/shadcn-ui/ui/assets/4519142/5a2a909b-455b-4d3e-a9a8-89e03ee7edbd">
<img width="1303" alt="Screenshot 2023-09-06 at 10 29 19" src="https://github.com/shadcn-ui/ui/assets/4519142/aa80da8d-07a5-4769-a2fb-8a6019dc45d9">

Using the latest versions of all Radix component. Latest NextJS and Typescript.

```
    "@radix-ui/react-dialog": "1.0.4",
    "@radix-ui/react-popover": "1.0.6",
    "cmdk": "0.2.0",
    "next": "13.4.19",
    "typescript": "5.2.2"
```

Anyone ran into similar issues? Besides changing the used icons in the Shadcn components, there where no additions.

**Edit: For the popover component the errors disappear when downgrading to 1.0.4**

**Comment by essejmclean** [comment]
Have had this same issue pop up essentially overnight and can't explain why.

**Comment by richfly** [comment]
Dialog issue in Astro as well 
![image](https://github.com/shadcn-ui/ui/assets/32109737/c50f9ec3-b1fd-42bb-9db7-aaa0218026f8)

**Comment by jedimonkey** [comment]
I was having this issue with a new monorepo and looks one of the apps had an old version of @types/react and react-dom. Since upgrading them to the same it seems to be okay now 🤞

**Comment by cpotey** [comment]
> I was having this issue with a new monorepo and looks one of the apps had an old version of @types/react and react-dom. Since upgrading them to the same it seems to be okay now 🤞

Can confirm, this worked for me when I updated `@types/react` & `@types/react-dom` in my `packages/ui`
For reference, my package.json

```
{
  "name": "shared-ui",
  "version": "1.0.0",
  "main": "./index.tsx",
  "types": "./index.tsx",
  "scripts": {
    "lint": "eslint *.ts*"
  },
  "sideEffects": false,
  "devDependencies": {
    "@types/node": "^18.16.19",
    "@types/react": "^18.2.21",
    "@types/react-dom": "^18.2.7",
    "eslint": "^8.44.0",
    "react": "^18.2.0",
    "tsconfig": "workspace:*",
    "typescript": "^5.1.6"
  },
  "dependencies": {
    "@radix-ui/react-accordion": "^1.1.2",
    "@radix-ui/react-alert-dialog": "^1.0.4",
    "@radix-ui/react-checkbox": "^1.0.4",
    "@radix-ui/react-collapsible": "^1.0.3",
    "@radix-ui/react-dialog": "^1.0.4",
    "@radix-ui/react-dropdown-menu": "^2.0.5",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-navigation-menu": "^1.1.3",
    "@radix-ui/react-popover": "1.0.5",
    "@radix-ui/react-radio-group": "^1.1.3",
    "@radix-ui/react-select": "^1.2.2",
    "@radix-ui/react-slot": "^1.0.2",
    "@radix-ui/react-switch": "^1.0.3",
    "@radix-ui/react-tabs": "^1.0.4",
    "@radix-ui/react-toggle": "^1.0.3",
    "@radix-ui/react-tooltip": "^1.0.6",
    "class-variance-authority": "^0.6.1",
    "clsx": "^1.2.1",
    "cmdk": "^0.2.0",
    "react-hook-form": "^7.44.3",
    "react-select": "^5.7.3"
  }
}
```

I had tried updating all other packages, including Typescript, but ended up getting a whole heap of other new errors

**Comment by rnnyrk** [comment]
Work for me as well. Thanks for pointing it out. Closed.
