### ISSUE TITLE
Using Select with react-hook-form not setting SelectValue 

### ISSUE THREAD

**Issue by yousihy** [shadcn-ui/ui#1463]
I am having an issue with `Shadcn` react library's `Select` component when using it with `react-hook-form`. It seems that "dynamically" generated `SelectItem` is causing an issue where they are not displayed in the `SelectValue` box when selected.

I am using Zod validation library with the hoosk form as suggested by the documentation. I am supposed to select from available types of properties. The selection works and Zod is getting the value. But the selected item is not being displayed in the `SelectValue` box. It is just showing empty.

Here is a sample replication in codesandbox:

[sample code](https://codesandbox.io/p/sandbox/elastic-andras-35r33x)

```
    <FormField
    control={form.control}
    name="type"
    render={({ field }) => (
    <FormItem className="grid grid-cols-4 items-center gap-4">
       <FormLabel className="sm:block sm:text-right">
          Type
       </FormLabel>
       <Select
          disabled={isSubmitting}
          onValueChange={field.onChange}
          defaultValue={field.value}
          >
          <FormControl>
             <SelectTrigger className="col-span-4 sm:col-span-3">
                <SelectValue placeholder="Select a property type"/>
             </SelectTrigger>
          </FormControl>
          <SelectContent className="SelectContent">
             {propTypes.map((type) => (
             <SelectItem key={type.id} value={type.id}>
                {type.name}
             </SelectItem>
             ))}
          </SelectContent>
       </Select>
    </FormItem>
    )}
    />
```

![image](https://github.com/shadcn-ui/ui/assets/70659920/a44edd7f-50d7-418d-a0b4-ffaa9ad2728e)

I am not seeing the value selected:

![image](https://github.com/shadcn-ui/ui/assets/70659920/45e8aaf1-5126-4122-883f-1897790ba259)

However, Zod is getting the value successfully:

![image](https://github.com/shadcn-ui/ui/assets/70659920/afe447e8-e288-4bf9-882b-2c0592d648a4)

Now, if I replace the dynamically generated values with static values as below, it will work, and I will be able to see what I selected:

```
    <SelectContent>
       <SelectItem value="m@example.com">m@example.com</SelectItem>
       <SelectItem value="m@google.com">m@google.com</SelectItem>
       <SelectItem value="m@support.com">m@support.com</SelectItem>
    </SelectContent>
```

Something is wrong when we generate the `SelectItem` dynamically. It seems that I need to manually type the `SelectItem` myself which doesn't make sense. 

Any idea what is wrong here or how to fix it?

Thank you all.

**Comment by joaom00** [comment]
Try use value={field.value} instead of defaultValue={field.value}

**Comment by yousihy** [comment]
> Try use `value={field.value}` instead of `defaultValue={field.value}`

I did. It's not working. Can you check my code sample? [sample](https://codesandbox.io/p/sandbox/elastic-andras-35r33x?file=%2Fapp%2Fpage.tsx%3A65%2C59)

**Comment by joaom00** [comment]
The value prop in `SelectItem` should be a string [Codesandbox](https://codesandbox.io/p/sandbox/elastic-andras-35r33x?file=/app/page.tsx:41,11)

**Comment by yousihy** [comment]
> The value prop in `SelectItem` should be a string [Codesandbox](https://codesandbox.io/p/sandbox/elastic-andras-35r33x?file=/app/page.tsx:41,11)

You're kidding?? Omg! how the h*** did I miss that?? That worked! Thanks a lot. I have been struggling for days!

**Comment by yousihy** [comment]
@joaom00 figured out the issue that I had. Many thanks

**Comment by LowScarlet** [comment]
> [@joaom00](https://github.com/joaom00) figured out the issue that I had. Many thanks

how u mark this as completed, im still have this issue
