### ISSUE TITLE
CLI command to add tabs fails

### ISSUE THREAD

**Issue by Olaleye-Blessing** [shadcn-ui/ui#1476]
[https://ui.shadcn.com/docs/components/tabs](https://ui.shadcn.com/docs/components/tabs)
```
npx shadcn-ui@latest add tabs
```
<img width="1413" alt="Screenshot 2023-09-08 at 11 32 40" src="https://github.com/shadcn-ui/ui/assets/70102539/c1b95cab-a8b1-4362-bccc-1197ce12b361">

**Comment by dan5py** [comment]
Duplicate of #1458

**Comment by Olaleye-Blessing** [comment]
No, not anymore.
