### ISSUE TITLE
`import { useForm } from "react-hook-form"` not present in Form Guide

### ISSUE THREAD

**Issue by inclinedadarsh** [shadcn-ui/ui#1482]
For someone who's absolutely copying and pasting form the guide, this would give an error, as `useForm` is not imported in the guide. 

Can simple fix it by adding that in the documentation.

**Comment by inclinedadarsh** [comment]
If you want, I can fix this

**Comment by inclinedadarsh** [comment]
I can fix this, but maybe `good first issue` label would do the justice here.

**Comment by onurhan1337** [comment]
Hi, if installed via CLI, zod & react-hook-form are automatically included in the project along with the form component. For manual installation, follow the instructions in the installation section.

**Comment by onurhan1337** [comment]
Thanks for offering this. I noticed this problem the other day too. I just opened the PR that fixed this issue.

https://github.com/shadcn-ui/ui/pull/1486
