### ISSUE TITLE
Calendar shadcn-ui language

### ISSUE THREAD

**Issue by Steveb599** [shadcn-ui/ui#1498]
Hi, how do I change the calendar language?
also, when it displays the date such as "September 7th 2023" 
I want it to display in another language.

**Comment by kaiiiiiiiii** [comment]
This is not a shadcn-ui related issue.

Please have a look into the react-daypicker documentation, as stated on the shadcn example page.

https://react-day-picker.js.org/basics/localization

**Comment by Steveb599** [comment]
> This is not a shadcn-ui related issue.
> 
> Please have a look into the react-daypicker documentation, as stated on the shadcn example page.
> 
> https://react-day-picker.js.org/basics/localization

Thank you.
I have fixed the issue with their documentation, but the documentation in the date-fns seems to be not updated.

I try locale the format function in the field but getting typescript error.

>                                                 <BiCalendar className="ml-auto h-4 w-4 opacity-50" />
                                                {field.value ? (
                                                    format(field.value as any, "PPP", {locale: heLocale})
                                                ) : (
                                                    <span>some text</span>
                                                )}


the locale: heLocale giving typescript error, tried enLocale as well. its from date-fns documentatiion. do you have any clue?

**Comment by kaiiiiiiiii** [comment]
No worries, feel free to close the issue :)

**Comment by joaofranciscoguarda** [comment]
> ```ts
> import { ptBR } from "date-fns/locale"
> ```

And how about using DayPicker with i18n? Using TimePicker I had no problem chaging the Hours. Minutes, Seconds hardcoded in the component for a i18n function, but in this situation, what is the best approach?

How to make it more dynamic but still simple?

Zod has a amazing approch where u just need to import a json, and pass it in the locale file in the project and done, everything working

**Comment by Kokleng-Dev** [comment]
shadcn-vue 

<Calendar
          v-model="model"
          :year="selectedYear"
          :month="selectedMonth + 1"
          initial-focus
          class="p-0"
          locale="km-KH"
 />

didn't work. please help.

**Comment by jsanchezpc** [comment]
> shadcn-vue
> 
> ```
> <Calendar
>           v-model="model"
>           :year="selectedYear"
>           :month="selectedMonth + 1"
>           initial-focus
>           class="p-0"
>           locale="km-KH"
>  />
> ```
> 
> didn't work. please help.

components/ui/calendar > `import { es } from "date-fns/locale"; ` then use it on <DayPicker>
