### ISSUE TITLE
Next.js 13 appDir support for next-themes

### ISSUE THREAD

**Issue by markozxuu** [shadcn-ui/ui#15]
Hi, awesome Job ! I see you used 'next-themes' for the support for the dark-mode. I have the following question, do you came across this problem in development. I use tailwindCSS
With related to "Hydration failed because of the initial UI"

<img width="1200" alt="Screenshot 2023-01-25 at 10 40 45" src="https://user-images.githubusercontent.com/16585386/214626888-3a5f3956-fd53-4e08-8c77-c283eb98e339.png">

**app/layout.tsx**
```jsx
// Styles
import '@styles/global.css';
// Lib
import Providers from '@lib/Providers';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <Providers>
          <body>{children}</body>
        </Providers>
      </html>
    </>
  );
}

```

**lib/Providers**

```jsx
'use client';

import { ReactNode } from 'react';
import { ThemeProvider } from 'next-themes';

// Context
import { SettingsProvider } from './SettingsContext';

export default function Providers({ children }: { children: ReactNode }) {
  return (
    <SettingsProvider>
      <ThemeProvider
        disableTransitionOnChange
        attribute="class"
        defaultTheme="system"
      >
        {children}
      </ThemeProvider>
    </SettingsProvider>
  );
}

```

**NOTE**: In production these message not show

**Comment by guilhermefront** [comment]
> NOTE: In production these message not show

just a minor explanation, hydration errors don't show in production (so real users don't get frustrated by it), only when you run it locally.

**Comment by markozxuu** [comment]
@guilhermefront  Is there a way to not show it in development?

**Comment by Zebeqo** [comment]
Deleting your local storage key "theme" followed by a hard refresh might help.

If not, restart your dev server.

If it still doesn't work, try my pr https://github.com/shadcn/ui/pull/4 and do it again.

I've had this problem before and usually doing the first two steps solves the problem.

**Comment by SDBurt** [comment]
Check the console. Often at the top, there is a more useful error such as a missing tag or something Nextjs related. Happy coding!

**Comment by hajimism** [comment]
@markozxuu 
Hi! I also faced the same problem. 
This discussion was helpful for me.
https://github.com/pacocoursey/next-themes/issues/152

This worked for my environment. Providers should be child of <body>.
```tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.variable}>
        <Providers>
           {children}
        </Providers>
      </body>
    </html>
  );
}
```

**Comment by luisdsolano** [comment]
https://blog.idrisolubisi.com/how-to-fix-react-hydration-error-in-nextjs-practical-guide#

**Comment by edwinvelez** [comment]
I came across a solution that seems to work. Please see [Step-4 Fixing Hydration Mismatch Problem](https://nextjsdev.com/dark-mode-in-next-js-13-app-using-tailwind-css/#step-4-fixing-hydration-mismatch-problem) for more info.
