### ISSUE TITLE
FetchError: request to https://ui.shadcn.com/registry/styles/default/button.json failed

### ISSUE THREAD

**Issue by MarvelousMarcin** [shadcn-ui/ui#1503]
Recently when I want to import new component:
`pnpm dlx shadcn-ui@latest add button`
I get this error:
`FetchError: request to https://ui.shadcn.com/registry/styles/default/button.json failed`

![obraz](https://github.com/shadcn-ui/ui/assets/73672172/d59b99da-412d-405a-a052-c82d64d0fa5a)

It's not blocking, because when I try multiple times it solves the problem and of course we can just copy paste this component

Problem occurs both **npm** and **pnpm**. 
Something is definitely wrong with TLSSocket

**Comment by brunocroh** [comment]
I try this here, and working as expected

![Screenshot 2023-09-11 at 21 18 13](https://github.com/shadcn-ui/ui/assets/13812512/10e81b3a-e2d3-493b-b190-57123766b163)

Can you access the [file directly](https://ui.shadcn.com/registry/styles/default/button.json) in your browser? If yes and problem persist, can you please create a repo with the problem, and so I can try investigated this one
https://ui.shadcn.com/registry/styles/default/button.json
