### ISSUE TITLE
how to navigation menu put the right side?

### ISSUE THREAD

**Issue by lawplatform** [shadcn-ui/ui#1506]
I tried to align the navigation menu to the right using 
`<NavigationMenu className="mx-auto flex flex-row justify-end" > `
but it didn't work. 

When I added 'mx-auto,' 
it centered the menu but not to the right. 

I want to place the logo on the left side and the menu on the right side, 
but I'm not sure how to do it.

**Comment by onurhan1337** [comment]
I had no problems while testing. It's probably related to the `<NavigationMenu>` parent element. Please share the relevant code block for further help.

**Comment by lawplatform** [comment]
I noticed that max-width was applied by the developer tools, 
but I never added max-width: max-content myself. 

I couldn't figure out why it was added to the navigation component. 
I checked all the CSS code, but I couldn't find it anywhere. 

Nevertheless, I was able to solve the issue by overriding the max-w attribute like this
`<NavigationMenu className="bg-blue-200 mx-auto flex flex-row justify-end max-w-5xl">`

**Comment by onurhan1337** [comment]
> I noticed that `max-width` was applied by the developer tools, but I never added max-width: max-content myself.
> 
> I couldn't figure out why it was added to the navigation component. I checked all the CSS code, but I couldn't find it anywhere.
> 
> Nevertheless, I was able to solve the issue by overriding the max-w attribute like this `<NavigationMenu className="bg-blue-200 mx-auto flex flex-row justify-end max-w-5xl">`

No, the "relative z-10 flex max-w-max flex-1 items-center justify-center" styling is already in the component as default, not added by developer tools. but you can override it if needed. For details, you can check this file: https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/navigation-menu.tsx
