### ISSUE TITLE
How to display some bullet points inside a Dialog?

### ISSUE THREAD

**Issue by jiapei100** [shadcn-ui/ui#1517]
Hi, all:

Please give me a hand on this simple issue.
I am actually using the simple [Dialog example here](https://ui.shadcn.com/docs/components/dialog) .

I'd love to put everything inside ```<DialogDescription>
        This action cannot be undone. This will permanently delete your account
        and remove your data from our servers.
      </DialogDescription>```

However, I prefer to have some bullet points inside there. I've already tried simple HTML
```HTML
<ul>
        <li>
         ...
</ul>
```

Those expected bullet points didn't show up.

Can anybody help? Thank you ...

**Comment by kaiiiiiiiii** [comment]
You need to style your list according to your needs. A list without any className is completely unstyled.

Documentation -> https://tailwindcss.com/docs/list-style-type

For Example:

```
[...]
<DialogDescription>
  Make changes to your profile here. Click save when you&apos;re done.
  <ul className="list-disc pl-4 pt-2">
    <li>aaa</li>
    <li>aaa</li>
    <li>aaa</li>
    <li>aaa</li>
    <li>aaa</li>
  </ul>
</DialogDescription>
[...]
```


<img width="339" alt="list" src="https://github.com/shadcn-ui/ui/assets/4711233/90ac5f1f-2634-44d9-9d67-cf6e0eb6f788">
