### ISSUE TITLE
Default install of next with default shadcn-ui install breaks application

### ISSUE THREAD

**Issue by mulrooneydesign** [shadcn-ui/ui#1535]
Hey thanks for the great work first of all. Awesome project!

**What happened:**
Default shadcn-ui CLI settings break a default install of nextjs throwing a 404 error.

**How did it happen?**
This happened with a fresh nextjs install with the default settings (I just input yes to everything)

```npx create-next-app@latest```

So I can run the app fine of course. 

Then I run

```npx shadcn-ui@latest init``` 

I just input yes to everything. 

And get the 404 error when run ```npm run dev``` 

**What I expected to happen:** 
Default settings should not break default nextjs app setup.

**Comment by mahmudz** [comment]
@mulrooneydesign You will see 2 `app` folders. One inside the src folder & another at root level.
Just move the `/app/globals.css` to `/src/app/globals.css`. Then delete `/app` folder.

Restart the app `npm run dev`

**Comment by mulrooneydesign** [comment]
Thanks for the help @mahmudz I think this could be the default setting though! 

For anyone else that is having the issue you can also change the globals.css location on install:

```
✔ Would you like to use TypeScript (recommended)? … no / yes
✔ Which style would you like to use? › Default
✔ Which color would you like to use as base color? › Slate
✔ Where is your global CSS file? … src/app/globals.css <-------------------here
✔ Would you like to use CSS variables for colors? … no / yes
✔ Where is your tailwind.config.js located? … tailwind.config.ts
✔ Configure the import alias for components: … @/components
✔ Configure the import alias for utils: … @/lib/utils
✔ Are you using React Server Components? … no / yes
✔ Write configuration to components.json. Proceed? … yes
```
