### ISSUE TITLE
How to remove the border highlight of shadcn-ui input component when focusing on it?

### ISSUE THREAD

**Issue by PankidT** [shadcn-ui/ui#1550]
``` jsx
<Input
   type="text"
   placeholder="Search"
   className="focus:border-none"
/> 
```
I try to change properties of `focus:` to border-none, border-0, outline-none, outline-0, ring-none, and ring-0. However, nothing work for me.

**Comment by onurhan1337** [comment]
Hi, You can update `@/components/ui/input` file with:

```ts
import * as React from "react"

import { cn } from "@/lib/utils"

export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50",
          className
        )}
        ref={ref}
        {...props}
      />
    )
  }
)
Input.displayName = "Input"

export { Input }
```

After changing, you can use your Input with no focus ring.

**Comment by PankidT** [comment]
> Hi, You can update `@/components/ui/input` file with:
> 
> ```ts
> import * as React from "react"
> 
> import { cn } from "@/lib/utils"
> 
> export interface InputProps
>   extends React.InputHTMLAttributes<HTMLInputElement> {}
> 
> const Input = React.forwardRef<HTMLInputElement, InputProps>(
>   ({ className, type, ...props }, ref) => {
>     return (
>       <input
>         type={type}
>         className={cn(
>           "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50",
>           className
>         )}
>         ref={ref}
>         {...props}
>       />
>     )
>   }
> )
> Input.displayName = "Input"
> 
> export { Input }
> ```
> 
> After changing, you can use your Input with no border highlight and focus ring.

Thank you! It finally work.
