### ISSUE TITLE
ENOENT error when installing component with npx shadcn-ui@latest

### ISSUE THREAD

**Issue by renanleonel** [shadcn-ui/ui#1559]
i tried to install the 'Toast' component using the command in the documentation 'npx shadcn-ui@latest add toast', and received the following error:

`npx shadcn-ui@latest add toast`
`npm ERR! code ENOENT`
`npm ERR! syscall lstat`
`npm ERR! path C:\Users\renan\AppData\Roaming\npm`
`npm ERR! errno -4058`
`npm ERR! enoent ENOENT: no such file or directory, lstat 'C:\Users\...\AppData\Roaming\npm'`
`npm ERR! enoent This is related to npm not being able to find a file.`
`npm ERR! enoent`

after deleting the 'node_modules' folder, '.next', and the 'package-lock.json' file and reinstalling everything, I found that the error was due to the '@latest' flag. running the command 'npx shadcn-ui add toast' instead of 'npx shadcn-ui@latest add toast' as stated in the documentation solved my problem.
 
https://ui.shadcn.com/docs/components/toast

**Comment by jaosn60810** [comment]
I met same the problem, thanks for solution.

**Comment by mstf1985** [comment]
**add the component manually**

**Comment by samima55** [comment]
ENOENT error when installing component with npx shadcn-ui@latest
```
npx shadcn-ui@latest add button
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path C:\Users\renan\AppData\Roaming\npm
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat 'C:\Users\...\AppData\Roaming\npm'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoen
```
i was getting the same error and removing the `@lastest` , i was using  `zsh` in terminal , I solved the problem by switching to the` bash` terminal

**Comment by Sambod50** [comment]
I had been getting the same error. I solve it  as follow
create npm directory on %Appdata% 
works on me

**Comment by hsellik** [comment]
I faced the same error on a new Windows dev machine when running command `npx shadcn-ui init@latest`
and receiving `no such file or directory, lstat 'C:\Users\...\AppData\Roaming\npm'`

Since the error says the directory is missing, I simply created the directory with command `mkdir 'C:\Users\...\AppData\Roaming\npm'` and it started working

**Comment by LironCareto** [comment]
All solutions, including the one proposed by @hsellik didn't work for me. Only managed to start the installation, but after pressing y I got the error 

Error: package.json: ENOENT: no such file or directory, open 'C:\Users\...\AppData\Roaming\package.json'

**Comment by LucasMagaldi** [comment]
@hsellik  thanks! The solution works fine for me.
In my case, after created a directory npm in `C:\Users\....AppData\Roaming `  I was able to keep using `@latest `

**Comment by jlioanag** [comment]
Also had this issue but `npx shadcn-ui@latest init` fixed it

**Comment by c-ent** [comment]
it works without using the latest

**Comment by claudsondouglas** [comment]
If you are using Linux, it may help you:

```npm install -g npm```

**Comment by magnobiet** [comment]
The shadcn-ui CLI is going to be deprecated soon. Use https://www.npmjs.com/package/shadcn instead.

**Comment by devKangMinHyeok** [comment]
in my case, Use https://www.npmjs.com/package/shadcn instead. -> solved
