### ISSUE TITLE
Sticky header not working

### ISSUE THREAD

**Issue by arjay-dala** [shadcn-ui/ui#1564]
Hi, I am working on a data table to become sticky but it is not working, have tried putting classnames "sticky top-0 z-10" on table header, table head but still not working. Someone can help? Here's the code:

```
<div className="rounded-md border overflow-auto max-h-[50vh]">
        <Table id="table-main" className="min-w-full">
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => {
                  return (
                    <TableHead key={header.id} className="sticky top-0 z-[100]">
                      {header.isPlaceholder
                        ? null
                        : flexRender(
                            header.column.columnDef.header,
                            header.getContext()
                          )}
                    </TableHead>
                  )
                })}
              </TableRow>
            ))}
          </TableHeader>
```

**Comment by nicolasthy** [comment]
Have you tried adding `relative` to the wrapping div?

```
<div className="relative rounded-md border overflow-auto max-h-[50vh]">
  <table id="table-main" className="min-w-full">
    <TableHeader>
      {table.getHeaderGroups().map((headerGroup) => (
      <TableRow key="{headerGroup.id}">
        {headerGroup.headers.map((header) => { return (
        <TableHead key="{header.id}" className="sticky top-0 z-[100]">
          {header.isPlaceholder ? null : flexRender(
          header.column.columnDef.header, header.getContext() )}
        </TableHead>
        ) })}
      </TableRow>
      ))}
    </TableHeader>
  </table>
</div>
```

**Comment by arjay-dala** [comment]
> Have you tried adding `relative` to the wrapping div?
> 
> ```js
> <div className="relative rounded-md border overflow-auto max-h-[50vh]">
>   <table id="table-main" className="min-w-full">
>     <TableHeader>
>       {table.getHeaderGroups().map((headerGroup) => (
>       <TableRow key="{headerGroup.id}">
>         {headerGroup.headers.map((header) => { return (
>         <TableHead key="{header.id}" className="sticky top-0 z-[100]">
>           {header.isPlaceholder ? null : flexRender(
>           header.column.columnDef.header, header.getContext() )}
>         </TableHead>
>         ) })}
>       </TableRow>
>       ))}
>     </TableHeader>
>   </table>
> </div>
> ```

Yes already tried that still not working

**Comment by arjay-dala** [comment]
> Hmm, I managed to get it to work on my side, but don't remember the exact method 😬 Just found a comment in my repo, could you try updating the `Table` component and remove the div that is wrapping the table node? Here's what I have:
> 
> ```js
> const Table = React.forwardRef<HTMLTableElement, React.HTMLAttributes<HTMLTableElement>>(
>   ({ className, ...props }, ref) => (
>     <table ref={ref} className={cn("w-full caption-bottom text-sm", className)} {...props} />
>   )
> );
> Table.displayName = "Table";
> ```

This works! Big thanks. I've been working this for a week now and this only solves my problem. Kudos!

**Comment by GihanDuane** [comment]
wow thanks. this fixed columns work

**Comment by Vansh-Baghel** [comment]
> Hmm, I managed to get it to work on my side, but don't remember the exact method 😬 Just found a comment in my repo, could you try updating the `Table` component and remove the div that is wrapping the table node? Here's what I have:
> 
> ```js
> const Table = React.forwardRef<HTMLTableElement, React.HTMLAttributes<HTMLTableElement>>(
>   ({ className, ...props }, ref) => (
>     <table ref={ref} className={cn("w-full caption-bottom text-sm", className)} {...props} />
>   )
> );
> Table.displayName = "Table";
> ```

Thank you so much!! Have been trying since long

**Comment by vatro** [comment]
> Hmm, I managed to get it to work on my side, but don't remember the exact method 😬 Just found a comment in my repo, could you try updating the `Table` component and remove the div that is wrapping the table node? Here's what I have:
> 
> ```tsx
> const Table = React.forwardRef<HTMLTableElement, React.HTMLAttributes<HTMLTableElement>>(
>   ({ className, ...props }, ref) => (
>     <table ref={ref} className={cn("w-full caption-bottom text-sm", className)} {...props} />
>   )
> );
> Table.displayName = "Table";
>```

Thanks for the hint! :)
The main problem here is the `overflow-auto` class, when removed, the sticky stuff works:
```diff
const Table = React.forwardRef<HTMLTableElement, React.HTMLAttributes<HTMLTableElement>>(
  ({ className, ...props }, ref) => (
-   <div className="relative w-full overflow-auto">
+   <div className="relative w-full">
      <table ref={ref} className={cn('w-full caption-bottom text-sm', className)} {...props} />
    </div>
  ),
)
Table.displayName = 'Table'
```
as stated here: https://css-tricks.com/dealing-with-overflow-and-position-sticky/

> Any [overflow](https://css-tricks.com/almanac/properties/o/overflow/) value other than visible and no height is the enemy of child elements with position: sticky;

Related to that:

**My problem**: I wanted to hide table shadows leaking to the sides
```tsx
<section className="w-full overflow-x-hidden">
  <Table key={product_id} className="mb-8 shadow-lg">
    <TableHeader className="sticky top-[248px] z-60 shadow-md">...</TableHeader>
    ...
  </Table>
</section>
```
but using `overflow-x-hidden` on the parent container would break the sticky headers

**Solution**: I ended up using `overflow-x-clip` instead, which **doesn't break the sticky position** of children (see this article: [CSS 'position: sticky' not working? Try 'overflow: clip', not 'overflow: hidden'](https://www.terluinwebdesign.nl/en/blog/position-sticky-not-working-try-overflow-clip-not-overflow-hidden/))

```diff
- <section className="w-full overflow-x-hidden">
+ <section className="w-full overflow-x-clip">
  <Table key={product_id} className="mb-8 shadow-lg">
    <TableHeader className="sticky top-[248px] z-60 shadow-md">...</TableHeader>
    ...
  </Table>
</section>
```

**Comment by reyhan-ransnet** [comment]
> const Table = React.forwardRef<HTMLTableElement, React.HTMLAttributes<HTMLTableElement>>(
>   ({ className, ...props }, ref) => (
>     <table ref={ref} className={cn("w-full caption-bottom text-sm", className)} {...props} />
>   )
> );
> Table.displayName = "Table";

oh my god, you save my life from stuck dude, very cool mate

**Comment by ccorpuz** [comment]
> > Hmm, I managed to get it to work on my side, but don't remember the exact method 😬 Just found a comment in my repo, could you try updating the `Table` component and remove the div that is wrapping the table node? Here's what I have:
> > const Table = React.forwardRef<HTMLTableElement, React.HTMLAttributes<HTMLTableElement>>(
> >   ({ className, ...props }, ref) => (
> >     <table ref={ref} className={cn("w-full caption-bottom text-sm", className)} {...props} />
> >   )
> > );
> > Table.displayName = "Table";
> 
> This works! Big thanks. I've been working this for a week now and this only solves my problem. Kudos!

That fixed it dude. You just one upped Claude, even he couldn't figure it out 😅
