### ISSUE TITLE
Pagination in DataTable component freezes browser.

### ISSUE THREAD

**Issue by devrolle** [shadcn-ui/ui#1571]
## Description
I've run into an issue that has me pretty confused. Just for some context, i'm using the latest version of NextJS with the app directory. In my project, I have a DataTable client component that is re-used to display different groups of data. I'll post the component code below:

```javascript
"use client";
import {
  ColumnDef,
  flexRender,
  getCoreRowModel,
  getPaginationRowModel,
  useReactTable,
} from "@tanstack/react-table";

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useEffect } from "react";
import { Button } from "./ui/button";

interface DataTableProps<TData, TValue> {
// Props
}

export function DataTable<TData, TValue>({
  columns,
  data,
  pageSize = 5,
  togglePagination = true,
}: DataTableProps<TData, TValue>) {
  const table = useReactTable({
    data: data.filter((items) => {
      return items !== null;
    }),
    columns,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
  });

  useEffect(() => {
    if (togglePagination) {
      table.setPageSize(pageSize);
    }
  }, [table, pageSize, togglePagination]);

  return (
    <>
      <div className="rounded-md border h-full">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => {
                  return (
                    <TableHead key={header.id}>
                      {header.isPlaceholder
                        ? null
                        : flexRender(
                            header.column.columnDef.header,
                            header.getContext()
                          )}
                    </TableHead>
                  );
                })}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {table.getRowModel().rows?.length ? (
              table.getRowModel().rows.map((row) => (
                <TableRow
                  key={row.id}
                  data-state={row.getIsSelected() && "selected"}
                >
                  {row.getVisibleCells().map((cell) => (
                    <TableCell key={cell.id}>
                      {flexRender(
                        cell.column.columnDef.cell,
                        cell.getContext()
                      )}
                    </TableCell>
                  ))}
                </TableRow>
              ))
            ) : (
              <TableRow>
                <TableCell
                  colSpan={columns.length}
                  className="h-24 text-center"
                >
                  No results.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>
      {togglePagination && (
        <div className="flex items-center justify-end space-x-2 py-4">
          <Button
            variant="outline"
            size="sm"
            onClick={() => table.previousPage()}
            disabled={!table.getCanPreviousPage()}
          >
            Previous
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => table.nextPage()}
            disabled={!table.getCanNextPage()}
          >
            Next
          </Button>
        </div>
      )}
    </>
  );
}

```

### What's The Issue?
The issue I'm having is as follows. When I click the "Next" button, the table.nextPage() function freezes up my browser. It stops me from navigating the application. After a while firefox tells me that my application is slowing the browser down and prompts me to stop whatever the application is running. I tested the onClick to see if just clicking the button was the issue but its only when I try to run table.nextPage().

It feels to me like table.nextPage is getting stuck somewhere or running infinitely but I honestly have no real idea what could be the cause. I figured I would post an issue here to see if I could get some insight from people who know more than me lol. Thanks in advanced for any help!

**Comment by Joshuajrodrigues** [comment]
Seems like an issue with your useEffect, most likely that setPageSize is causing an infinite loop. (pageSize is a dep again)
Im not entirely sure as to the use case here can you explain what it does ?

There is a built in way to do pagination for dataTables https://ui.shadcn.com/docs/components/data-table#pagination you can check out

**Comment by devrolle** [comment]
I figured out what was causing the issue in my case. It was caused by the filter i'm using when initializing the table using the useReactTable hook.

```javascript
const table = useReactTable({
    data: data.filter((items) => {  // <---- This is the line i'm referring to
      return items !== null;
    }),
    columns,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
  });
```
I guess doing this filtering inline was confusing the program and causing it to get stuck. I simply removed this and passed the data straight from the component props and it works perfectly.

**Comment by kulterryan** [comment]
> Seems like an issue with your useEffect, most likely that setPageSize is causing an infinite loop. (pageSize is a dep again) Im not entirely sure as to the use case here can you explain what it does ?
> 
> There is a built in way to do pagination for dataTables https://ui.shadcn.com/docs/components/data-table#pagination you can check out

Hi There!

I'm trying to follow the same, but when I use the pagination state function, the whole table freeze on the first page ;/

[Ref. Tanstack](https://tanstack.com/table/v8/docs/api/features/pagination)
