### ISSUE TITLE
Adding a character count to the TextArea component in a Form

### ISSUE THREAD

**Issue by henrybabbage** [shadcn-ui/ui#1575]
I am not clear on how to add extra functionality to the shadcn-ui form, such as a character count for a textarea.

React-Hook-Form provide an example of a character count implemented on a form field using watch at this CodeSandBox [link](https://codesandbox.io/s/react-hook-form-v7-ts-usewatch-forked-ljgtky?file=/src/index.tsx:158-628), but I have not been able to get this logic working within shadcn-ui. I also tried simply using onChange on the textarea component and updating the charCount in useState, but the count went to 1 and did not increment further.

I would be hugely grateful for any guidance that anyone can offer. My form is much like the example from the shadcn-ui docs:

```ts
<Form {...form}>
		<form onSubmit={form.handleSubmit(onSubmit)} className='group flex h-full flex-col'>
			<div className='flex-grow border-b-2 border-border p-6'>
				<FormField
					disabled={submitting}
					control={form.control}
					name='body'
					render={({ field }) => (
						<FormItem className={cn({ 'opacity-50': submitting })}>
							<FormLabel className='sr-only'>Story</FormLabel>
							<FormControl>
								<Textarea
									placeholder='Tell us your story about someone who is an Apple Tree in your life.'
									className='h-52 resize-none'
									{...field}
									// onChange={handleCharCount}
								/>
							</FormControl>
							<FormMessage />
						</FormItem>
					)}
				/>
			</div>
			<div className='space-y-8 p-6'>
				<FormField
					disabled={submitting}
					control={form.control}
					name='name'
					render={({ field }) => (
						<FormItem className={cn({ 'opacity-50': submitting })}>
							<div className='flex items-baseline space-x-2'>
								<FormLabel>Name</FormLabel>
								<FormControl>
									<Input
										placeholder='Please provide your name.'
										{...field}
										className='border-b-2 border-border'
									/>
								</FormControl>
							</div>
							<FormMessage />
						</FormItem>
					)}
				/>
				<Button
					variant='secondary'
					size='full'
					type='submit'
					className={cn({ 'pointer-events-none opacity-50': submitting })}
				>
					<Spinner
						className={cn('absolute h-4', { 'opacity-0': !submitting, 'opacity-100': submitting })}
					/>
					<h3
						className={cn('font-neueMontreal text-lg group-disabled:!opacity-0', {
							'opacity-0': submitting,
							'opacity-100': !submitting,
						})}
					>
						Share
					</h3>
				</Button>
			</div>
		</form>
	</Form>
```

**Comment by Aboubakary833** [comment]
Did you try  `onInput` on your TextArea component? Something like this:
`
<FormField
					disabled={submitting}
					control={form.control}
					name='body'
					render={({ field }) => (
						<FormItem className={cn({ 'opacity-50': submitting })}>
							<FormLabel className='sr-only'>Story</FormLabel>
							<FormControl>
								<Textarea
									placeholder='Tell us your story about someone who is an Apple Tree in your life.'
									className='h-52 resize-none'
									{...field}
									onInput={(e) => console.log(e.currentTarget.value?.length)}
								/>
							</FormControl>
							<FormMessage />
						</FormItem>
					)}
				/>
`

**Comment by henrybabbage** [comment]
Hi @Aboubakary833 thanks so much for your suggestion — that got it working. In combination with the zod validation to trigger the error / warning message, this is what worked for me:

```ts
const [charCount, setCharCount] = useState(0)
const handleCharCount = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
		setCharCount(event.currentTarget.value.length)
}
```

```ts
<FormItem className={cn({ 'opacity-50': submitting })}>
	<FormLabel className='sr-only'>Story</FormLabel>
	<FormControl>
		<Textarea
			placeholder='Tell us your story about someone who is an Apple Tree in your life.'
			className='h-52 resize-none'
			onInput={handleCharCount}
			maxLength={250}
			{...field}
		/>
	</FormControl>
	<FormDescription>
		<span className={cn('py-4 font-neueMontreal text-sm text-primary-foreground')}>
			{charCount}/250
		</span>
	</FormDescription>
	<FormMessage />
</FormItem>
```

**Comment by octav20** [comment]
Thanks, it was a good solution
