### ISSUE TITLE
Question about forwardRef

### ISSUE THREAD

**Issue by t-rosa** [shadcn-ui/ui#1576]
Hi, I just wanted to know why some components are built with forwardRef? For example, in the button component, I'm having trouble understanding why it's used. Does it have anything to do with the "asChild" props? Or perhaps to do with the use of Slot radix?

I'm going to find out more about this, as I've rarely needed to use the forwardRef.

Thanks.

**Comment by AshrafElshaer** [comment]
As I know you can't pass a regular ref instance to custom components as you do to html tags that's why you need to pass forward ref through props as react recommending 
Docs https://react.dev/reference/react/forwardRef#forwarding-a-ref-through-multiple-components

**Comment by t-rosa** [comment]
Thanks !
