### ISSUE TITLE
how to set <NavigationMenuContent> position ? 

### ISSUE THREAD

**Issue by lawplatform** [shadcn-ui/ui#1588]
I applied 'jusitfy-end' to position the <NavigationMenu> to the right. 
Successfully, the <NavigationMenu> is on the right, 
but the position of the <NavigationMenuContent> 
does not follow the position of the Navigation Menu.
 
[https://i.ibb.co/L91NXS6/navbar.jpg](https://i.ibb.co/L91NXS6/navbar.jpg)

We tried applying relative left and so on to the NavigationMenuContent, 
but the same thing happened. 

I want the NavigationMenuContent to be directly below the NavigationMenuTrigger, 
is there any way to do this? 

Here is the source code 
```
<NavigationMenu className="bg-blue-200 flex justify-end max-w-5xl">
			<NavigationMenuList className=" ">
				<NavigationMenuItem className="">
					<NavigationMenuTrigger>Getting started</NavigationMenuTrigger>
					<NavigationMenuContent className="">
						<ul className="grid gap-3 p-6 md:w-[400px] lg:w-[500px] lg:grid-cols-[.75fr_1fr]">
							<ListItem href="/docs/primitives/typography" title="Typography">
								Styles for headings, paragraphs, lists...etc
							</ListItem>
							<ListItem href="/docs/primitives/typography" title="Typography">
								Styles for headings, paragraphs, lists...etc
							</ListItem>
						</ul>
					</NavigationMenuContent>
				</NavigationMenuItem>
			</NavigationMenu List>
</NavigationMenu>
```

**Comment by Joshuajrodrigues** [comment]
hey, try 

```
		<NavigationMenuContent className=" right-0 left-auto">
						<ul className="grid gap-3 p-6 md:w-[400px] lg:w-[500px] lg:grid-cols-[.75fr_1fr]">
							
								Styles for headings, paragraphs, lists...etc
						
					
								Styles for headings, paragraphs, lists...etc
					
						</ul>
					</NavigationMenuContent>
```

**Comment by Joshuajrodrigues** [comment]
It seems like the culprit is viewport, what you can do is provide right-0 and left-auto directly in the nativation-menu.jsx here

```
const NavigationMenuViewport = React.forwardRef<
  React.ElementRef<typeof NavigationMenuPrimitive.Viewport>,
  React.ComponentPropsWithoutRef<typeof NavigationMenuPrimitive.Viewport>
>(({ className, ...props }, ref) => (
  <div className={cn("absolute top-full flex justify-center right-0 left-auto")}> <----------here
    <NavigationMenuPrimitive.Viewport
      className={cn(
        "origin-top-center relative mt-1.5 h-[var(--radix-navigation-menu-viewport-height)] w-full overflow-hidden rounded-md border bg-popover text-popover-foreground shadow data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-90 md:w-[var(--radix-navigation-menu-viewport-width)]",
        className
      )}
      ref={ref}
      {...props}
    />
  </div>
))
```

Or as per docs use      <NavigationMenuViewport className="right-0 left-auto"/> tho this seemed to create duplicate menus for me, so im not sure how to use it this way

**Comment by lawplatform** [comment]
Thanks ! after apply "right-0 left-auto" it work out of box!

**Comment by mikechabotcandy** [comment]
This shouldn't be closed; it's a bug.

**Comment by Joshuajrodrigues** [comment]
https://github.com/shadcn-ui/ui/issues/1591

I had created a open issue for it

**Comment by aramrw** [comment]
> It seems like the culprit is viewport, what you can do is provide right-0 and left-auto directly in the nativation-menu.jsx here
> 
> ```
> const NavigationMenuViewport = React.forwardRef<
>   React.ElementRef<typeof NavigationMenuPrimitive.Viewport>,
>   React.ComponentPropsWithoutRef<typeof NavigationMenuPrimitive.Viewport>
> >(({ className, ...props }, ref) => (
>   <div className={cn("absolute top-full flex justify-center right-0 left-auto")}> <----------here
>     <NavigationMenuPrimitive.Viewport
>       className={cn(
>         "origin-top-center relative mt-1.5 h-[var(--radix-navigation-menu-viewport-height)] w-full overflow-hidden rounded-md border bg-popover text-popover-foreground shadow data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-90 md:w-[var(--radix-navigation-menu-viewport-width)]",
>         className
>       )}
>       ref={ref}
>       {...props}
>     />
>   </div>
> ))
> ```
> 
> As per docs use `<NavigationMenuViewport className="right-0 left-auto"/> ` tho this seemed to ignore any props passed down to it

Worked perfect thx

**Comment by alperkay** [comment]
Also if the navigation is used in a footer (bottom of the page), I expect the NavigationMenuContent to appear on top of the trigger. But it still appears below the page. So in a nutshell, the Menu should be smart and appear on available side instead of always trying to appear on the bottom of the trigger. A logic or library like [popperjs](https://floating-ui.com/) should be used to achieve this.

**Comment by Mohit1310** [comment]
> > It seems like the culprit is viewport, what you can do is provide right-0 and left-auto directly in the nativation-menu.jsx here
> > ```
> > const NavigationMenuViewport = React.forwardRef<
> >   React.ElementRef<typeof NavigationMenuPrimitive.Viewport>,
> >   React.ComponentPropsWithoutRef<typeof NavigationMenuPrimitive.Viewport>
> > >(({ className, ...props }, ref) => (
> >   <div className={cn("absolute top-full flex justify-center right-0 left-auto")}> <----------here
> >     <NavigationMenuPrimitive.Viewport
> >       className={cn(
> >         "origin-top-center relative mt-1.5 h-[var(--radix-navigation-menu-viewport-height)] w-full overflow-hidden rounded-md border bg-popover text-popover-foreground shadow data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-90 md:w-[var(--radix-navigation-menu-viewport-width)]",
> >         className
> >       )}
> >       ref={ref}
> >       {...props}
> >     />
> >   </div>
> > ))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As per docs use `<NavigationMenuViewport className="right-0 left-auto"/> ` tho this seemed to ignore any props passed down to it
> 
> Worked perfect thx

doesn't work as you can see below it is not exactly below About us
![image](https://github.com/user-attachments/assets/eef93076-4a00-49c4-a549-c0726ecd0d63)

**Comment by STP5940** [comment]
```
<NavigationMenu>
    <NavigationMenuList>
      <NavigationMenuItem>
        <NavigationMenuTrigger>Projects</NavigationMenuTrigger>
        <NavigationMenuContent> ... </NavigationMenuContent>
      </NavigationMenuItem>
    </NavigationMenuList>

    <!-- Add NavigationMenuViewport And set mt-15 -->
    <NavigationMenuViewport class="mt-15" />
</NavigationMenu>
```

**Comment by STP5940** [comment]
`<NavigationMenuViewport class="mt-15" />`

set position top in class to NavigationMenuViewport
