### ISSUE TITLE
Override browser keybinds

### ISSUE THREAD

**Issue by esau-morais** [shadcn-ui/ui#159]
When I try to hit the suggested key in the command component, it actually opens the downloads page in Firefox. To fix this, I'd suggest to prevent the default behavior by using `preventDefault`

**Comment by dBianchii** [comment]
Did you figure this out?

Using e.preventDefault() stopped me from being able to type

**Comment by esau-morais** [comment]
The issue is not only related to `preventDefault`, but also because it was conditionally rendering only based on `metaKey`, missing the `ctrlKey`
