### ISSUE TITLE
Toast not working

### ISSUE THREAD

**Issue by moha-abdi** [shadcn-ui/ui#1593]
I am using nextjs and the Toast is not wrking for me. when I click the button, he burron works and I can see that but no toast shows up at all here is the code i used

```
"use client"

import { Button } from "./ui/button"
import { useToast } from "./ui/use-toast"

export function ToastSimple() {
    const { toast } = useToast()

    return (
      <Button
        variant="outline"
        onClick={() => {
          toast({
            description: "Your message has been sent.",
          })
        }}
      >
        Show Toast
      </Button>
    )
  }
```

and my page.tsx

```import { ToastSimple } from "@/components/ToastSimple";


export default function Home() {
  return (
    <main>
      <ToastSimple></ToastSimple>
    </main>
  )
}
```

**Comment by moha-abdi** [comment]
when using `npx shadcn-ui@latest add toast ` it install the `use-toast.tsx` as `use-toast.ts` I dont now why the compiler didnt shw e errors but now it works fne after I manually installed it.

**Comment by augusto-it** [comment]
Could you solve it? I have the same problem, the useToast function is called, but the toast is not displayed

**Comment by moha-abdi** [comment]
> Could you solve it? I have the same problem, the useToast function is called, but the toast is not displayed

Are you sure you added toast to the layout, if you’re using nextjs

**Comment by sweatpotato13** [comment]
Are you add `<Toaster />` in layout?
