### ISSUE TITLE
Toast is not showing

### ISSUE THREAD

**Issue by Default-01** [shadcn-ui/ui#1597]
When i use the default code for showing a toast it does not show on the page. Did I miss something or do I need to add some extra logic for toasts to show.

I added the following code to my client component:

```tsx
<Button
	variant='outline'
	onClick={() => {
		toast({
			title: 'Uh oh! Something went wrong.',
			description: 'There was a problem with your request.',
		});
	}}>
	Show Toast
</Button>
```

Im working on a nextjs project with ts. not sure if you need more information.

**Comment by alapanbagchi** [comment]
@Default-01 Did you put the Toaster component in the layout.tsx?

Your layout.tsx should have a Toaster like this as mentioned in the docs. Hope that solves it
```
  import { Toaster } from "@/components/ui/toaster"
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <head />
        <body>
          <main>{children}</main>
          <Toaster />
        </body>
      </html>
    )
  }
```

**Comment by Default-01** [comment]
I would need to figure out how to do that, cause I cant place metadata in the layout if its client component.

my current lauyout.tsx
```tsx
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}

```

**Comment by yuirsilva** [comment]
@Default-01 Your `layout.tsx` just need the <Toaster />, nothing more, you do not need to set `use client` in the layout.

**Comment by yuirsilva** [comment]
@Default-01 Your `layout.tsx` just need the Toaster, you don't need to set `use client` in the layout.

**Comment by Default-01** [comment]
> @Default-01 Your `layout.tsx` just need the Toaster, you don't need to set `use client` in the layout.

Thank you, but i have tried this ad got the error that toast must be in a client component. Do you know how to solve that? Thank you in advance.

**Comment by yuirsilva** [comment]
Yes, the `useToast()` and `toast({})` must be in a client component, but the Toaster should be in the `layout.tsx`, like the example below:

```javascript
import "@/styles/globals.css";

import { Toaster } from "@/components/ui/Toaster";

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html>
      <body className="min-h-screen bg-background antialiased">
          <main className="relative flex min-h-screen flex-col">
            <div className="flex flex-1 flex-col">{children}</div>
          </main>
          <Toaster />
      </body>
    </html>
  );
}
```

**Comment by Default-01** [comment]
When i do that i get the following error.

error
```tsx
useMemo as $eyrYI$useMemo, Fragment as $eyrYI$Fragment} from "react";
   ·                                                                                                                                                                          ─────────
 3 │ import {createPortal as $eyrYI$createPortal} from "react-dom";
 4 │ import {composeEventHandlers as $eyrYI$composeEventHandlers} from "@radix-ui/primitive";
 5 │ import {useComposedRefs as $eyrYI$useComposedRefs} from "@radix-ui/react-compose-refs";
   ╰────

Maybe one of these should be marked as a client entry with "use client":
  ./node_modules\@radix-ui\react-toast\dist\index.mjs
  ./src\components\ui\toast.tsx
  ./src\components\ui\toaster.tsx
  ./src\app\layout.tsx
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
```

layout.tsx
```tsx
import '@/styles/globals.css';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';

interface RootLayoutProps {
	children: React.ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

export default async function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				{children}

				<Toaster />
			</body>
		</html>
	);
}

```

**Comment by anirudh-777** [comment]
@Default-01 You can add `'use client'` in the toaster.jsx|tsx file at '@/components/ui/toaster'. That way you don't need to add `'use client'` in your layout file. Should fix this issue.

**Comment by Default-01** [comment]
Thank you !

**Comment by soutot** [comment]
> > @Default-01 Your `layout.tsx` just need the Toaster, you don't need to set `use client` in the layout.
> 
> Thank you, but i have tried this ad got the error that toast must be in a client component. Do you know how to solve that? Thank you in advance.

In my case, I could not set the layout as `use client` due to metadata. And as I also need some logics and state handlers, I ended up creating a Root component with the `use client` directive and importing it to the layout. That could be an alternative for you so you don't have to touch the UI component

Root.tsx
```tsx
'use client'

import {Inter} from 'next/font/google'
import {ReactNode} from 'react'

import {Toaster} from '@/components/ui/toaster'

const inter = Inter({subsets: ['latin']})

type Props = {
  children: ReactNode
}

const Root = ({children}: Props) => {
  return (
    <html lang="en">
      <body  className={inter.className}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}

export default Root
```

layout.tsx
```tsx
import type {Metadata} from 'next'
import React from 'react'

import Root from '../components/Root'
import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'App',
  description: 'My app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return <Root>{children}</Root>
}
```

**Comment by hcmutemimi** [comment]
I want sow toast without click button, what should I do?

**Comment by MuhamadShoaib** [comment]
@hcmutemimi i am also trying to show this without button click to update the design. 
What you can do is create a new component and just copy the styling from the index.ts file. 
This way you will be able to modify the css without clicking again and again.

**Comment by dagweg** [comment]
> > @Default-01 Your `layout.tsx` just need the Toaster, you don't need to set `use client` in the layout.
> 
> Thank you, but i have tried this ad got the error that toast must be in a client component. Do you know how to solve that? Thank you in advance.

You can create a wrapper for `Toaster` and make that a client component and use it in the layout.tsx. Have you tried that.

**Comment by hkashyap-developer** [comment]
> Yes, the `useToast()` and `toast({})` must be in a client component, but the Toaster should be in the `layout.tsx`, like the example below:
> 
> ```js
> import "@/styles/globals.css";
> 
> import { Toaster } from "@/components/ui/Toaster";
> 
> interface RootLayoutProps {
>   children: React.ReactNode;
> }
> 
> export default async function RootLayout({
>   children,
> }: RootLayoutProps) {
>   return (
>     <html>
>       <body className="min-h-screen bg-background antialiased">
>           <main className="relative flex min-h-screen flex-col">
>             <div className="flex flex-1 flex-col">{children}</div>
>           </main>
>           <Toaster />
>       </body>
>     </html>
>   );
> }
> ```

You are an Angel!

**Comment by LukeberryPi** [comment]
> I want sow toast without click button, what should I do?

@hcmutemimi a sonner may suit your needs https://ui.shadcn.com/docs/components/sonner

**Comment by bappyasif** [comment]
> ```js
> 
> import { Toaster } from "@/components/ui/Toaster";
> ```

you can show it for any specific ations such as "successful request to api or otherwise", you dont not necessarily needs to have a "button click" event, it can take place for any event as you see fit for your requirement. happy coding :)

**Comment by BeastGamer81** [comment]
How do I do this in Astro?

**Comment by krishnagkmit** [comment]
My toast component is work fine for client component but the toast does not work in my async component, I have `<Toaster/> in my root `layout.tsx` and I even tried `use client` but still not working.
can someone explain me why this is happening please 🙏.

```typescript
import { fetchBlogs } from '@/apis/blogs';
import { dehydrate, HydrationBoundary, QueryClient } from '@tanstack/react-query';
import Home from '../ui/home';
import FallBackUi from '@/components/fallback-ui';
import { toast } from '@/components/ui/use-toast';

const queryClient = new QueryClient();

async function fetchBlogData() {
  try {
    return queryClient.fetchQuery({
      queryKey: ['blogs'],
      queryFn: fetchBlogs,
    });
  } catch (error) {
    throw error;
  }
}

export default async function HomePage() {
  try {
    await fetchBlogData();
    return (
      <HydrationBoundary state={dehydrate(queryClient)}>
        <Home />
      </HydrationBoundary>
    );
  } catch (error) {
     // not working
     toast({
      title: 'Failed to load blog data',
    })
    return (
      // this is rendered
      <FallBackUi
        heading='Blogs not found'
        message={'Unable to fetch blogs details. Please try again later.'}
      />
    );
  }
}

```

**Comment by yogaNO01** [comment]
can i use the toast in .js file? I want to use it in the request.js to provide the message.
