### ISSUE TITLE
Make Toast to display permanently

### ISSUE THREAD

**Issue by iamcarlo042** [shadcn-ui/ui#1611]
Hi, is it possible to display the Toast permanently? But still dismissible.

I have tried to add a longer duration as mentioned here https://github.com/shadcn-ui/ui/issues/1078 but I will be needing to display it permanently until the user closes it.

**Comment by sou-gabriel** [comment]
Hi, you can use `Infinity` in duration, so the toast is only closed when you close it manually.

```ts
toast({
  duration: Infinity,
  variant: "destructive",
  title: "...",
  description: "...",
});
```

**Comment by iamcarlo042** [comment]
Thanks @sou-gabriel !
Didn't know there's an `Infinity` number that we can use in javascript until now.
