### ISSUE TITLE
CSS variables undefined after adding shadcn-ui to existing Vite + Tailwind + React App

### ISSUE THREAD

**Issue by acharyasaagar** [shadcn-ui/ui#1623]
Hi,

I encountered an issue while attempting to integrate shadcn-ui into my existing Vite + Tailwind + React application. Despite following the steps outlined in the documentation, all of CSS variables are undefined so basically the components do not work. Has anyone encountered this before?
I have also included my projects configuration after going through all the steps.

**Comment by acharyasaagar** [comment]
```
# tailwind.config.cjs
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
	],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
```

**Comment by acharyasaagar** [comment]
```
# postcss.config.cjs
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}

```

**Comment by acharyasaagar** [comment]
```json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": false,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.cjs",
    "css": "src/app/assets/globals.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
```

**Comment by 0xaddm** [comment]
Hey, 
I think you're missing a `globals.css` file.  You should import it on the top of your application
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;
    --primary: 221.2 83.2% 53.3%;
    --primary-foreground: 210 40% 98%;
    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;
    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;
    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 221.2 83.2% 53.3%;
    --radius: 1rem;
  }

  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
    --card: 222.2 84% 4.9%;
    --card-foreground: 210 40% 98%;
    --popover: 222.2 84% 4.9%;
    --popover-foreground: 210 40% 98%;
    --primary: 217.2 91.2% 59.8%;
    --primary-foreground: 222.2 47.4% 11.2%;
    --secondary: 217.2 32.6% 17.5%;
    --secondary-foreground: 210 40% 98%;
    --muted: 217.2 32.6% 17.5%;
    --muted-foreground: 215 20.2% 65.1%;
    --accent: 217.2 32.6% 17.5%;
    --accent-foreground: 210 40% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 210 40% 98%;
    --border: 217.2 32.6% 17.5%;
    --input: 217.2 32.6% 17.5%;
    --ring: 224.3 76.3% 48%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}

```

**Comment by acharyasaagar** [comment]
Yeah turns out I was never importing the `globals.css` file in my app. Now it works. Thanks @0xaddm

**Comment by miraclemenikelechi** [comment]
> #### tailwind.config.cjs
> 
> ```js
> /** @type {import('tailwindcss').Config} */
> module.exports = {
>   darkMode: ["class"],
>   content: [
>     './pages/**/*.{ts,tsx}',
>     './components/**/*.{ts,tsx}',
>     './app/**/*.{ts,tsx}',
>     './src/**/*.{ts,tsx}',
> 	],
>   theme: {
>     container: {
>       center: true,
>       padding: "2rem",
>       screens: {
>         "2xl": "1400px",
>       },
>     },
>     extend: {
>       colors: {
>         border: "hsl(var(--border))",
>         input: "hsl(var(--input))",
>         ring: "hsl(var(--ring))",
>         background: "hsl(var(--background))",
>         foreground: "hsl(var(--foreground))",
>         primary: {
>           DEFAULT: "hsl(var(--primary))",
>           foreground: "hsl(var(--primary-foreground))",
>         },
>         secondary: {
>           DEFAULT: "hsl(var(--secondary))",
>           foreground: "hsl(var(--secondary-foreground))",
>         },
>         destructive: {
>           DEFAULT: "hsl(var(--destructive))",
>           foreground: "hsl(var(--destructive-foreground))",
>         },
>         muted: {
>           DEFAULT: "hsl(var(--muted))",
>           foreground: "hsl(var(--muted-foreground))",
>         },
>         accent: {
>           DEFAULT: "hsl(var(--accent))",
>           foreground: "hsl(var(--accent-foreground))",
>         },
>         popover: {
>           DEFAULT: "hsl(var(--popover))",
>           foreground: "hsl(var(--popover-foreground))",
>         },
>         card: {
>           DEFAULT: "hsl(var(--card))",
>           foreground: "hsl(var(--card-foreground))",
>         },
>       },
>       borderRadius: {
>         lg: "var(--radius)",
>         md: "calc(var(--radius) - 2px)",
>         sm: "calc(var(--radius) - 4px)",
>       },
>       keyframes: {
>         "accordion-down": {
>           from: { height: 0 },
>           to: { height: "var(--radix-accordion-content-height)" },
>         },
>         "accordion-up": {
>           from: { height: "var(--radix-accordion-content-height)" },
>           to: { height: 0 },
>         },
>       },
>       animation: {
>         "accordion-down": "accordion-down 0.2s ease-out",
>         "accordion-up": "accordion-up 0.2s ease-out",
>       },
>     },
>   },
>   plugins: [require("tailwindcss-animate")],
> }
> ```

for some weird reason, i ran into this issue you're facing and it's this config that works for me...
