### ISSUE TITLE
Component Dialog breaks the production build

### ISSUE THREAD

**Issue by Zaid-maker** [shadcn-ui/ui#1655]
i am getting this error when try to deploy my app it was working perfectly and when i add sheet component it breaks my app and giving this error, i tried delete and install the component as well but still didn't work

![image](https://github.com/shadcn-ui/ui/assets/53424436/bd97ff70-c05d-43a2-b755-fbff7eabc292)

![image](https://github.com/shadcn-ui/ui/assets/53424436/2870bbaf-de78-4f11-8c86-53b9dba009b3)

**Comment by Zaid-maker** [comment]
its working fine in dev mode but not in production

**Comment by aashahin** [comment]
The solution is to delete the code lines in the picture and put this instead
`const DialogPortal = DialogPrimitive.Portal;`

**Comment by KKUPGRADER** [comment]
This issue is exclusive with @radix-ui/react-alert-dialog version 1.0.5. What you can do is . delete your package-lock.json and change  ` "@radix-ui/react-dialog": "^1.0.5",` and `"@radix-ui/react-alert-dialog": "^1.0.5"` to 
```
    "@radix-ui/react-alert-dialog": "1.0.4",
    "@radix-ui/react-dialog": "1.0.4",
```
Then run `npm install`

**Comment by Magesh-sam** [comment]
> The solution is to delete the code lines in the picture and put this instead `const DialogPortal = DialogPrimitive.Portal;`

Hey I've the same Error. but there is no DigitalPortal in my Sheet component.

```jsx
const SheetPortal = ({
  className,
  ...props
}: SheetPrimitive.DialogPortalProps) => (
  <SheetPrimitive.Portal className={cn(className)} {...props} />
);
SheetPortal.displayName = SheetPrimitive.Portal.displayName;
```

snapshot below

![image](https://github.com/shadcn-ui/ui/assets/41033755/7c61c54f-c71c-4d08-8db5-6c55081a4104)

**Tried readding the Sheet Component. The issue is still there. unable to build for production.**

**Comment by Zaid-maker** [comment]
> This issue is exclusive with @radix-ui/react-alert-dialog version 1.0.5. What you can do is . delete your package-lock.json and change ` "@radix-ui/react-dialog": "^1.0.5",` and `"@radix-ui/react-alert-dialog": "^1.0.5"` to
> 
> ```
>     "@radix-ui/react-alert-dialog": "1.0.4",
>     "@radix-ui/react-dialog": "1.0.4",
> ```
> 
> Then run `npm install`

OK I will give it a try

**Comment by Zaid-maker** [comment]
> The solution is to delete the code lines in the picture and put this instead `const DialogPortal = DialogPrimitive.Portal;`

Yup, that's what exactly I do
