### ISSUE TITLE
What are the differences between Form and Card?

### ISSUE THREAD

**Issue by jiapei100** [shadcn-ui/ui#1657]
`Card` and `Form` look very similar anyway.

Is it possible to integrate `Card` content into a `Form`?

**Comment by 0xaddm** [comment]
Hey, 
Those are 2 different components. 
`<Card/>` is supposed to be used as a presentational component, and `<Form/>` on the other hand should be used to handle forms in your application.

Answering your question: It is possible to use Form together with Card.

**Comment by yuirsilva** [comment]
This is not supposed to be an issue.
