### ISSUE TITLE
Types not compatible with latest version of @types/react

### ISSUE THREAD

**Issue by mdugue** [shadcn-ui/ui#1672]
I assume that this is mostly related to **radix**, but makes **shadcn** fail as well. 
Apparently the latest version @types/react has changed regarding ReactNode / children definition.

Here an example, looks like most components are affected though,

Versions used:
- `@types/react: 18.2.24`
- `"@radix-ui/react-slot": "^1.0.2"`

TypeScript complains about the following eg. in `ui/button.tsx`:

`Type 'React.ReactNode' is not assignable to type 'import("xxx/node_modules/@radix-ui/react-avatar/node_modules/@types/react/index").ReactNode'.
      Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.` 

and

`Type 'import("xxx/node_modules/@radix-ui/react-avatar/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'`

**Comment by johnrackles** [comment]
For anybody looking for a quick solution, downgrading to `"@types/react": "18.2.23"` solved the problem for me

**Comment by mdugue** [comment]
oh, interesting, I even had to downgrade to **`18.2.22`**

**Comment by mdugue** [comment]
any news, thoughts or hints on this? @shadcn I assume https://v0.dev/ uses the same stack, so the topic might be relevant there, too

**Comment by bright-and-early** [comment]
I'm using Next.js 13 and extending @tsconfig/next/tsconfig.json, I simply removed @types/react from my project and it resolved the issues.

**Comment by mdugue** [comment]
@bright-and-early do you know which version of `@react/types` this uses under the hood?

**Comment by mdugue** [comment]
any news here? ping @shadcn

**Comment by shadcn** [comment]
@mdugue Can you help me reproduce this please? A Codesandbox link would help. Thank you.

**Comment by mdugue** [comment]
It turned out that the problem (at least with the current version of `@types/react` 18.2.31) was only related to `bun`. Removing `node_modules` & `bun.lockb` and then reinstalling all dependencies `bun install` fixed it. 

As I am not so familiar with bun yet, I didn't dive any deeper into the lockfile topic. 

@shadcn sorry for the confusion.

**Comment by beorn** [comment]
I think this is related to https://github.com/oven-sh/bun/issues/6103 - I saw this occasionally, and a clean install would fix it, but now the type mismatch (basically for me: is children required or not on ReactNode) has become permanent.

**Comment by ImBIOS** [comment]
Solved:
- https://github.com/shadcn-ui/ui/issues/1978#issuecomment-1873574838

**Comment by sethgw** [comment]
In my case I needed to turn off auto-install peers.

.npmrc `auto-install-peers=false`

**Comment by apiel51** [comment]
In my situation I needed to upgrade `@types/react` from `19.0.10` → `19.0.12` (if you're using turborepo/monorepo setup, ensure that all packages are on that version)

**Comment by sp88011** [comment]
> In my situation I needed to upgrade `@types/react` from `19.0.10` → `19.0.12` (if you're using turborepo/monorepo setup, ensure that all packages are on that version)

you saved my life mate

**Comment by djpsychofogbear** [comment]
> In my situation I needed to upgrade `@types/react` from `19.0.10` → `19.0.12` (if you're using turborepo/monorepo setup, ensure that all packages are on that version)

seconded - was banging my head on this for a minute 🙏

**Comment by julianrutten** [comment]
Still having this issue with `"react": "^19.1.0"` and `"@types/react": "^19.1.4",`

**Comment by 0xbuidler** [comment]
Still having this issue with:
```
        "react": "19.1.0"
        "react-dom": "19.1.0"
        "@types/react": "19.1.6"
        "@types/react-dom": "19.1.5"
        "@types/node": "22.15.29"
        "typescript": "5.8.3"
```

**Comment by Willis0826** [comment]
@sshmaxime  Same issue here. Sorry to bump this thread, but have you found a solution yet?

**Comment by marlonmarcello** [comment]
Just bumped into this as well, using the latest types/react and react.

**Comment by superbellum** [comment]
why tf is this closed without solution?

**Comment by andreyselin** [comment]
Im using a package with react components among multiple monorepos and just had this issue in one of them while not having in another. Dropping yarn.lock and running yarn solved the problem

**Comment by MarkLee425** [comment]
Still doesn't work
