### ISSUE TITLE
How to make Combobox width relative to container

### ISSUE THREAD

**Issue by victormongi** [shadcn-ui/ui#1690]
How to make Combobox width full relative to container and it responsive also, not hard code it. thank you
<img width="433" alt="Screenshot 2023-10-06 at 5 37 33 PM" src="https://github.com/shadcn-ui/ui/assets/5617746/2e3c7ecb-0be8-4b89-8d27-19ad1ebf8fd3">

**Comment by atleugim** [comment]
I added this to my custom TailwindCSS Utilities

Workaround for Popover to take the same width as the trigger
REF: https://www.radix-ui.com/primitives/docs/components/popover#constrain-the-content-size

```
".popover-content-width-same-as-its-trigger": {
  width: "var(--radix-popover-trigger-width)",
  "max-height": "var(--radix-popover-content-available-height)",
}
```

Then use the `popover-content-width-same-as-its-trigger` class, you can use it for the `PopoverContent` inside the `Combobox` component or any `PopoverContent` you have.

**Comment by victormongi** [comment]
Thank you @atleugim it works like a charm...

**Comment by JuGit-pk** [comment]
Thanks @atleugim, its working

**Comment by max-programming** [comment]
BTW if someone wants to use variables directly inside the `className`, here's the way
```tsx
<PopoverContent className="w-[--radix-popover-trigger-width] max-h-[--radix-popover-content-available-height]">
```

**Comment by DerizhyLouise** [comment]
you can edit the combobox component to this
`<Popover.Content sameWidth>`
The sameWidth is a props from popover to make it the same width as its parent

**Comment by lkpnchl** [comment]
> BTW if someone wants to use variables directly inside the `className`, here's the way
> 
> ```tsx
> <PopoverContent className="w-[--radix-popover-trigger-width] max-h-[--radix-popover-content-available-height]">
> ```

I tried this one but it resulted in this error for me: 

```
ERROR: ResizeObserver loop limit exceeded
```

How can I avoid this?

**Comment by dynamite-bud** [comment]
> I added this to my custom TailwindCSS Utilities
> 
> Workaround for Popover to take the same width as the trigger REF: https://www.radix-ui.com/primitives/docs/components/popover#constrain-the-content-size
> 
> ```
> ".popover-content-width-same-as-its-trigger": {
>   width: "var(--radix-popover-trigger-width)",
>   "max-height": "var(--radix-popover-content-available-height)",
> }
> ```
> 
> Then use the `popover-content-width-same-as-its-trigger` class, you can use it for the `PopoverContent` inside the `Combobox` component or any `PopoverContent` you have.

Which file should I add it to @atleugim ? `tailwind.config.js` or my extended `globals.css` ?

If adding it to `tailwind.config.js`, how should I place it in there ?

**Comment by stmchan93** [comment]
@dynamite-bud you can put it in your `globals.css` file like so:

```
@layer utilities {
  .popover-content-width-full {
    width: var(--radix-popover-trigger-width);
    max-height: var(--radix-popover-content-available-height);
  }
}
```

and in your `PopoverContent` should look like this: `<PopoverContent className="p-0 popover-content-width-full">`

**Comment by dharmayudistira** [comment]
After implementing this, I can't hover on my `PopoverContent` and it is **unclickable**. Does anyone have the same issue ?

**Comment by victormongi** [comment]
> After implementing this, I can't hover on my `PopoverContent` and it is **unclickable**. Does anyone have the same issue ?

try to remove `PopoverPrimitive.Portal` in popover.tsx

**Comment by Steve-conqueror1** [comment]
This should work:  
@layer utilities {
    .popover-content-width-full {
      @apply w-[var(--radix-popover-trigger-width)];
    }
}

      <PopoverContent className="popover-content-width-full">
      // content
  </PopoverContent>

**Comment by jurmadani** [comment]
> BTW if someone wants to use variables directly inside the `className`, here's the way
> 
> ```tsx
> <PopoverContent className="w-[--radix-popover-trigger-width] max-h-[--radix-popover-content-available-height]">
> ```

it worked like magic, thank you!

**Comment by dwolrdcojp** [comment]
> > BTW if someone wants to use variables directly inside the `className`, here's the way
> > <PopoverContent className="w-[--radix-popover-trigger-width] max-h-[--radix-popover-content-available-height]">
> 
> I tried this one but it resulted in this error for me:
> 
> ```
> ERROR: ResizeObserver loop limit exceeded
> ```
> 
> How can I avoid this?

I encountered the same issue and it seems to be coming from the parent being `flex`

**Comment by abishekbaiju** [comment]
> [@dynamite-bud](https://github.com/dynamite-bud) you can put it in your `globals.css` file like so:
> 
> ```
> @layer utilities {
>   .popover-content-width-full {
>     width: var(--radix-popover-trigger-width);
>     max-height: var(--radix-popover-content-available-height);
>   }
> }
> ```
> 
> and in your `PopoverContent` should look like this: `<PopoverContent className="p-0 popover-content-width-full">`

Thank you so much. worked perfectly

**Comment by abishekbaiju** [comment]
> BTW if someone wants to use variables directly inside the `className`, here's the way
> 
> <PopoverContent className="w-[--radix-popover-trigger-width] max-h-[--radix-popover-content-available-height]">

why adding like this is not working for me. but 
```
@layer utilities {
  .popover-content-width-full {
    width: var(--radix-popover-trigger-width);
    max-height: var(--radix-popover-content-available-height);
  }
}
``` - this works perfectly for me

**Comment by harithawRC** [comment]
For **Tailwind V4** users use following syntax.

`<PopoverContent className="p-0 w-[var(--radix-popover-trigger-width)]"> {...} </PopoverContent>`

solution credit : https://github.com/radix-ui/primitives/discussions/2894#discussioncomment-12288897

**Comment by pedro-santiago** [comment]
For those who have this problem after migration to Reka UI, this should work:

```<ComboboxList class="w-[--reka-combobox-trigger-width]">```

> BTW if someone wants to use variables directly inside the `className`, here's the way
> 
> <PopoverContent className="w-[--radix-popover-trigger-width] max-h-[--radix-popover-content-available-height]">

**Comment by Kokleng-Dev** [comment]
> class="w-[--reka-combobox-trigger-width]"

wow, it is works. how do you know that? amazing...

**Comment by jovanlopez32** [comment]
> For those who have this problem after migration to Reka UI, this should work:
> 
> `<ComboboxList class="w-[--reka-combobox-trigger-width]">`
> 
> > BTW if someone wants to use variables directly inside the `className`, here's the way

Thanks, it's works, how did you find out???

**Comment by Prasunneupane** [comment]
its not fixed after writing the class also 
i am using shadcn vue i have mad another component that contains the combobox 

<img width="508" height="388" alt="Image" src="https://github.com/user-attachments/assets/99c95912-fa22-472e-9e66-5820578df9b5" />

**Comment by pauldmps** [comment]
If someone is still trying to figure this out recently, the css variables have changed. Use w-(--radix-popper-anchor-width) max-w-(--radix-popper-available-width)

`<PopoverPrimitive.Content className={cn(....<existing classes>, 
className, 
'w-(--radix-popper-anchor-width) max-w-(--radix-popper-available-width)')}`>

**Comment by Prasunneupane** [comment]
> its not fixed after writing the class also i am using shadcn vue i have mad another component that contains the combobox
> 
> <img alt="Image" width="508" height="388" src="https://private-user-images.githubusercontent.com/59379684/479554090-99c95912-fa22-472e-9e66-5820578df9b5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU4NzcyMzIsIm5iZiI6MTc1NTg3NjkzMiwicGF0aCI6Ii81OTM3OTY4NC80Nzk1NTQwOTAtOTljOTU5MTItZmEyMi00NzJlLTllNjYtNTgyMDU3OGRmOWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODIyVDE1MzUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NTU5MTFlYTA0M2VhNTU5NzkyMDViMjA4ZTU3ZjQzNjhiYzlkOTViY2QzYzZhNTFiNTFkZTBjNzRlNDRhOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ooLQvKGlA4W7YonesmflQS0g4AQIWmyfwkZgYrJQywc">

Ok i have found the solution 
The Issue was -
The original code used class="w-[--reka-combobox-trigger-width]", but Tailwind's arbitrary value syntax with CSS custom properties doesn't always work reliably, especially with complex variable references.
so i did this 
in my style tag
<style>

[data-slot="combobox-list"] {
  width: var(--reka-popper-anchor-width) !important;
  min-width: var(--reka-popper-anchor-width) !important;
  max-width: var(--reka-popper-anchor-width) !important;
}
</style>

**Comment by body20002** [comment]
tailwindcss v4
```css
@layer utilities {
  .popover-content-width-full {
    width: var(--radix-popper-anchor-width);
    max-height: var(--radix-popper-available-width);
  }
}
```
