### ISSUE TITLE
Toast success variant - gist

### ISSUE THREAD

**Issue by webdiego** [shadcn-ui/ui#1704]
Could be nice have a success variant for the toast component other than the default and destructive. :) 

I leave the gist if someone needs a green toast 😄

https://gist.github.com/webdiego/b23471d78ee6e55e24c2e0d454b016eb
<img width="460" alt="Screenshot 2023-10-08 at 17 33 43" src="https://github.com/shadcn-ui/ui/assets/63283003/ef2a20eb-fbe7-48e1-804c-bf90587aeff6">

**Comment by ShaikRehan123** [comment]
@webdiego This is not right place to post this, please use discussions and close this.

**Comment by webdiego** [comment]
> @webdiego This is not right place to post this, please use discussions and close this.

You are right! Sorry for that😅

**Comment by mickdewald** [comment]
Is there a discussion for this?
@webdiego I like your solution and I think this option should exist.

**Comment by bakikucukcakiroglu** [comment]
I agree with the opinion that 'success', 'error', 'warning', etc. variants should be built-in.

**Comment by fGiordi** [comment]
@webdiego is this not built approved yet? I'm facing the same issue, and thought if it was not built I could assist in building it.
Please advise if its been approved or what next steps are.
