### ISSUE TITLE
broken style when installing shadcn on an already started nextjs project.

### ISSUE THREAD

**Issue by elblogbruno** [shadcn-ui/ui#1709]
Hello everyone!

I was working on a next js project with tailwind enabled and .tsx files. I decided to try shadcn, and when I installed it and used the sample code for the dark mode toggle button, I could see the style of the website was broken.

![image](https://github.com/shadcn-ui/ui/assets/10481058/85d16b8c-768f-4fe9-a183-0e61767249e7)

I can also see that with other shadcn elements: 

![image](https://github.com/shadcn-ui/ui/assets/10481058/051b0b29-504a-44bb-87fc-75012eb80459)

or even the light button state:

![image](https://github.com/shadcn-ui/ui/assets/10481058/41aa38ac-79a5-4c8f-ba98-d548aa8a28b6)
![image](https://github.com/shadcn-ui/ui/assets/10481058/aecd469b-2644-459d-b2b2-a7ff1346f391)

I do have custom css inside a index.css file 
![image](https://github.com/shadcn-ui/ui/assets/10481058/8199b349-b53c-461d-95b8-3d20485e523d)

but I believe this css should not affect shadcn. This is how the file starts (Added by shadcn) and below I added my custom css.
```

@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 47.4% 11.2%;

    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;

    --popover: 0 0% 100%;
    --popover-foreground: 222.2 47.4% 11.2%;

    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;

    --card: 0 0% 100%;
    --card-foreground: 222.2 47.4% 11.2%;

    --primary: 222.2 47.4% 11.2%;
    --primary-foreground: 210 40% 98%;

    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;

    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;

    --destructive: 0 100% 50%;
    --destructive-foreground: 210 40% 98%;

    --ring: 215 20.2% 65.1%;

    --radius: 0.5rem;
  }

  .dark {
    --background: 224 71% 4%;
    --foreground: 213 31% 91%;

    --muted: 223 47% 11%;
    --muted-foreground: 215.4 16.3% 56.9%;

    --accent: 216 34% 17%;
    --accent-foreground: 210 40% 98%;

    --popover: 224 71% 4%;
    --popover-foreground: 215 20.2% 65.1%;

    --border: 216 34% 17%;
    --input: 216 34% 17%;

    --card: 224 71% 4%;
    --card-foreground: 213 31% 91%;

    --primary: 210 40% 98%;
    --primary-foreground: 222.2 47.4% 1.2%;

    --secondary: 222.2 47.4% 11.2%;
    --secondary-foreground: 210 40% 98%;

    --destructive: 0 63% 31%;
    --destructive-foreground: 210 40% 98%;

    --ring: 216 34% 17%;

    --radius: 0.5rem;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
    font-feature-settings: "rlig" 1, "calt" 1;
  }
}


/* Your own custom utilities */
```

What could be wrong here?

My components.json file references the correct css file and tailwind config file.
`{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "styles/index.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
`
Thanks for your help
Cordially,
Bruno

**Comment by elblogbruno** [comment]
fixed it. I moved the contents inside @/components to my main components folder, and the same with lib.

Maybe there was another solution but this works.

**Comment by DoctorZulu** [comment]
Howdy, you can also change the alias in your components.json file.

```
  "aliases": {
    "components": "@/src/app/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  }
```
