### ISSUE TITLE
How to show currently selected date when opening Datepicker

### ISSUE THREAD

**Issue by minhson3012** [shadcn-ui/ui#1713]
Hi, I'm looking for a way to change the Datepicker to the month of the selected date for single mode when I open it. When I select a date (1/1/2023 for example), close the Datepicker and open it again, the Datepicker just shows the default month.

How can I change this behavior, and if possible, how can I do the same with `captionLayout="dropdown-buttons`.

**Comment by minhson3012** [comment]
According to react-day-picker docs, I can add `defaultMonth={selected}` to calendar to maintain the selected date

**Comment by harithawRC** [comment]
For anyone wondering the `defaultMonth={selected}` should be passed on to the `<Calendar>` component by Shadcn.
