### ISSUE TITLE
Next-themes not working

### ISSUE THREAD

**Issue by iyifr** [shadcn-ui/ui#1724]
Currently using next js 13 and the theme toggle feature with next-themes doesn't work. Any pointers?

**Comment by schardev** [comment]
Without any code or repro it's hard to tell. Create a repro with [codesandbox](https://codesandbox.io/) or [stackblitz](https://stackblitz.com/) and share the link.

**Comment by semkolol** [comment]
In case if you used the example from [shadcn's documentation](https://ui.shadcn.com/docs/dark-mode/next), and it won't change the Theme on toggle, then try moving the ThemeProvider ouside of the body, instead inside as it's shown in the docs. 

Here is my Layout:
`
<html lang="en" suppressHydrationWarning>
 // Move Provider outside of body element
      <NextThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange
      >
        <body className="loading">
            <main
              id="skip"
              className="min-h-[calc(100dvh-4rem)] md:min-h[calc(100dvh-5rem)]"
            >
              {children}
            </main>
        </body>
      </NextThemeProvider>
    </html>
`

Everything else is just as shown here:
https://ui.shadcn.com/docs/dark-mode/next

I just had the same issue, where the toggle would not update the theme on a new Next project. Next Version: 13.5.4 & Next-Themes Version: 0.2.1.

Hope this helped

**Comment by iyifr** [comment]
Yes it did , thanks! , i should've provided some code samples. Everything works fine

**Comment by mayanksinghal-dev** [comment]
Hi, I am facing an issue in next-themes. 
I am trying to create a toggle for mode change. But my local storage theme is not updating on hitting the refresh button. 

Due to which, if i set my theme as light and then hit the refresh button, my toggle switches to dark but my theme is still light on-screen and in local storage.

I have set my toggle on condition that if theme is light then get on sun icon else on moon icon. So if i am on light theme, on hit of refresh icon, probably my theme is set as undefined or whatever so my toggle switches to moon, but my local storage still shows theme as light.

**Comment by Owais-Ahmed7** [comment]
> In case if you used the example from [shadcn's documentation](https://ui.shadcn.com/docs/dark-mode/next), and it won't change the Theme on toggle, then try moving the ThemeProvider ouside of the body, instead inside as it's shown in the docs.
> 
> Here is my Layout: `
> 
> // Move Provider outside of body element {children} `
> Everything else is just as shown here: https://ui.shadcn.com/docs/dark-mode/next
> 
> I just had the same issue, where the toggle would not update the theme on a new Next project. Next Version: 13.5.4 & Next-Themes Version: 0.2.1.
> 
> Hope this helped

I did it like this but there comes another problem so ThemeProvider goes at the top which renders the script of next-theme outside body ta which gives hydration issue

<img width="512" alt="Screenshot 2024-09-07 at 4 17 45 AM" src="https://github.com/user-attachments/assets/752b5b00-0bf4-4bc1-b315-ddc32d3fc271">
