### ISSUE TITLE
Errors in sheet.tsx

### ISSUE THREAD

**Issue by azimari-toure-ikbal** [shadcn-ui/ui#1727]
Hello, I've been working on a project and had to use sheet but when I tried to deploy on vercel it pointed to me an error in the sheet.tsx code. I didn't touch it just installed using bunx.

<img width="653" alt="image" src="https://github.com/shadcn-ui/ui/assets/119160287/961840ee-5e13-4edb-bca8-20db54268b5c">

<img width="613" alt="image" src="https://github.com/shadcn-ui/ui/assets/119160287/d54f0b1d-38bd-4990-b6f9-8ed845f2132a">

<img width="980" alt="image" src="https://github.com/shadcn-ui/ui/assets/119160287/95861c0c-12c2-45c7-93fe-47d630dfb658">

**Comment by giannis198** [comment]
Same here

**Comment by D3OXY** [comment]
Downgrading `@radix-ui/react-dialog` from `1.0.5` to `1.04` can temporarily fix the issue.

``` bash
npm install @radix-ui/react-dialog@1.0.4
```

**Comment by azimari-toure-ikbal** [comment]
Thanks I'll try that

**Comment by azimari-toure-ikbal** [comment]
> Same thing happened in dialog.tsx and after reinstalling it fixed

It fixed the dialog but not the sheet I did what @D3OXY told me and it worked

**Comment by Ibrahim-Isah** [comment]
I just came to report the problem. @shadcn I think the issue is with radix. after installing both sheet and dialog thats when the problem occured

**Comment by Jarred-Sumner** [comment]
This might be a peer dependencies bug in Bun. 

Can you try adding this to `bunfig.toml`:
```
install.peer = false 
```

**Comment by mhdizmni** [comment]
I faced the issue with Node.js as well, [D3OXY](https://github.com/D3OXY) helped.

> Downgrading `@radix-ui/react-dialog` from `1.0.5` to `1.0.4` can temporarily fix the issue.
> 
> ```shell
> bun add @radix-ui/react-dialog@1.0.4
> ```

**Comment by azimari-toure-ikbal** [comment]
> This might be a peer dependencies bug in Bun.
> 
> Can you try adding this to `bunfig.toml`:
> 
> ```
> install.peer = false 
> ```

But wouldn't that be a problem when installing other packages?

**Comment by johnrackles** [comment]
As far as I know, className doesn't make any sense on the Portal element, that why it was removed from radix. So you can just delete the prop when using the latest version of the radix primitive.

**Comment by azimari-toure-ikbal** [comment]
Got it thanks everyone :D
