### ISSUE TITLE
Sheet Transition effect is not working

### ISSUE THREAD

**Issue by rajayteqmavens** [shadcn-ui/ui#1738]
### Discussed in https://github.com/shadcn-ui/ui/discussions/1737

<div type='discussions-op-text'>

<sup>Originally posted by **rajayteqmavens** October 13, 2023</sup>
I am using shadcn-ui in next.js along with tailwind CSS. I have installed the latest version using yarn. But I am getting a strange issue that transition effects are not working at our end as these are working on https://ui.shadcn.com/docs/components/sheet

I also tried with given approaches to solve this issue 

- Downgraded the shadcn-ui package
- We were supposing that tailwind css and shadcn-ui css are conflicting so we removed the default tailwind css. 
- Setup the raw sheet component on the new page without customization
- We tried copying all the shadcn-ui sheet page css(https://ui.shadcn.com/docs/components/sheet) from the console and keeping this in our layout CSS file. This is resolving the issue but this is not an optimized approach because there are many unnecessary codes and it is mashed up in our current layout designs.

Please suggest how I can fix it </div>

**Comment by NabeelAhmed23** [comment]
I am also facing this issue. Have you solved it or not ?

**Comment by shadcn** [comment]
Left a comment on the thread. https://github.com/shadcn-ui/ui/discussions/1737

**Comment by NabeelAhmed23** [comment]
Nvm i got it to work

**Comment by mfahadmachapal** [comment]
make sure you have this in tailwindcss config
![image](https://github.com/shadcn-ui/ui/assets/149381345/9cbaa61a-1ff1-4986-98ef-1f8db3ff3681)

**Comment by josematute** [comment]
Yup, @mfahadmachapal's answer is the solution. [Here](https://github.com/shadcn-ui/ui/blob/main/tailwind.config.cjs) is the reference of the `tailwind.config.cjs` file.
