### ISSUE TITLE
Recomendation to tailwind.config.ts

### ISSUE THREAD

**Issue by josuejs23** [shadcn-ui/ui#1740]
When im adding shadcn-ui to my nextjs project that is created with Typecript it ask me if my tailwind config file is TS or JS, it would be graat if by default is TypeSscipt if my project is created with TypeScript?

<img width="616" alt="Screenshot 2023-10-13 at 1 32 59 PM" src="https://github.com/shadcn-ui/ui/assets/86853211/c9e416ad-ea3e-4a70-90be-988303eb64cb">

**Comment by p7uverma** [comment]
I want to work in this issue. Could you assign me! @shadcn

**Comment by Gravy59** [comment]
#1247 might interest you.

**Comment by shadcn** [comment]
@josuejs23 https://github.com/shadcn-ui/ui/pull/1247 was merged. Hope this helped. If not, feel free to reopen this issue and we can take a look. Thanks.
