### ISSUE TITLE
Theme Provider with AOS Configuration Not working

### ISSUE THREAD

**Issue by jsvelte** [shadcn-ui/ui#1745]

**Comment by Gravy59** [comment]
I'm not a contributor, but I noticed this issue. It's quite vague. To benefit all parties, you should provide more details about the specific requirements and functionalities you have in mind.

Being more explicit about your needs will help potential contributors better understand the scope and purpose of the request, making it easier for them to provide a meaningful solution.

**Comment by jsvelte** [comment]
Sorry for not putting the code

This is the previous that I faced problem with (The AOS Animation not working)
![image](https://github.com/shadcn-ui/ui/assets/108642414/1e84cc94-52ed-4ea8-b237-6657d629bbc1)


I just simply removed the props of the ThemeProvider of `disableTransitionOnChange` and it working now haha
![image](https://github.com/shadcn-ui/ui/assets/108642414/e62d9ffb-3795-47b8-bf3a-b43aeae97a0e)
