### ISSUE TITLE
 Error: Type 'Element' is not assignable to type 'ReactNode'. in SelectContent Component Inside Select Component

### ISSUE THREAD

**Issue by MonaAghili** [shadcn-ui/ui#1746]
I recently installed the `npx shadcn-ui@latest` package and tried to add a `SelectContent` component inside the `Select` component. However, I encountered the following error:

```text
Type 'Element' is not assignable to type 'ReactNode'
```
and
```
The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & SelectPortalProps'
```

The error seems to be related to the `children` prop of the `SelectContent` component, and it mentions that the expected type is coming from the property 'children' on the type 'IntrinsicAttributes & SelectPortalProps'. 

I'm not sure how to resolve this issue. Could you provide guidance on how to fix this error and successfully use the `SelectContent` component within the `Select` component in Shadcn-UI?

Additional Information:
- Package: `npx shadcn-ui@latest`
- Component causing the error: `SelectContent` inside the `Select` component

**Comment by johnrackles** [comment]
I think this might be related to https://github.com/shadcn-ui/ui/issues/1672

**Comment by faris-work** [comment]
Upgrading `@types/react` to `18.2.28` fixes it for me

**Comment by farisamirmudin** [comment]
Upgrading `@types/react` to `18.2.28` fixes it for me

**Comment by leonardogrig** [comment]
Got this issue now and re-openning my vs-code solved it haha
