### ISSUE TITLE
Maximum call stack size exceeded with pnpm install

### ISSUE THREAD

**Issue by tsecret** [shadcn-ui/ui#1747]
Im installing shadcn with pnpm and nextjs. After initializing the project and running the development, i get the following error

`./app/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@13.5.4_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/.pnpm/next@13.5.4_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./app/globals.css
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)`

Tried node version 20, 18 and 16. The error occurs only when using pnpm

**Comment by alexander-rebai** [comment]
I have this same error.

**Comment by shadcn** [comment]
@tsecret @alexander-rebai What was the command for this?

**Comment by codeacme17** [comment]
> @tsecret @alexander-rebai What was the command for this?

hi, my command is 
pnpm dlx shadcn-ui@latest init

and I get the same issue

**Comment by lookevink** [comment]
as a quick fix, in your `layout.tsx` file delete `import './globals.css'`

```
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css' // <<< delete this line

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

```

**Comment by lookevink** [comment]
default tailwind config appears to be tailwind.config.js

specifying tailwind.config.ts during setup fixed it for me

```
Where is your tailwind.config.js located? › tailwind.config.js
```

**Comment by tsecret** [comment]
> default tailwind config appears to be tailwind.config.js
> 
> specifying tailwind.config.ts during setup fixed it for me
> 
> ```
> Where is your tailwind.config.js located? › tailwind.config.js
> ```

Tried it, now get the following error

`./app/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@13.5.6_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!./node_modules/.pnpm/next@13.5.6_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!./app/globals.css
TypeError: Cannot read properties of undefined (reading 'config')`

Here are my configuration settings

![image](https://github.com/shadcn-ui/ui/assets/36734601/f68cdfdb-a0c6-4824-bb22-4353d7e05134)
![image](https://github.com/shadcn-ui/ui/assets/36734601/42020dd2-9efc-41fd-96c0-4d1d4ff7cd89)

**Comment by jsfez** [comment]
Hello, I encountered a similar issue. However, I believe the root cause is not from shadcn but rather from the Next installation command. 
I suggest replacing:`pnpm create next-app@latest my-app --typescript --tailwind --eslint`
with: `npx create-next-app@latest my-app`
It has fixed the bug for me.

**Comment by tsecret** [comment]
Just wanted to inform that the issue has been fixed in the newer versions
