### ISSUE TITLE
 [Bug Report] DMARC RECORD MISSING

### ISSUE THREAD

**Issue by DR34M14** [shadcn-ui/ui#1749]
Spammers can forge the "From" address on email messages to make messages appear to come from someone in your domain.If spammers use your domain to send spam or junk email, your domain quality is negatively affected.
People who get the forged emails can mark them as spam or junk, which can impact authentic messages sent from your domain. eg: `taxonomy@shadcn.com`

url: `shadcn.com`

![Screenshot_2023-10-15_00-17-00](https://github.com/shadcn-ui/ui/assets/89645994/0ceee103-e49f-4856-846e-caae38dbf8e1)

**Comment by shadcn** [comment]
I'll check this out (shadcn.com is my personal site). Thanks for the heads up.
