### ISSUE TITLE
Trigger dialog close.

### ISSUE THREAD

**Issue by pawan-poudel-github** [shadcn-ui/ui#1750]
I want to close the dialog element when user click on specific button. How can I achieve this in shadcn dialog component.

**Comment by anthowm** [comment]
Just setOpen(false) when you want 
```
const [open, setOpen] = useState(false);
  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle className="mb-2">Add product</DialogTitle>

        </DialogHeader>
      </DialogContent>
    </Dialog>
  );
```

**Comment by quilariobenjo** [comment]
You can now custom a close button check the latest docs

[https://ui.shadcn.com/docs/components/dialog](https://ui.shadcn.com/docs/components/dialog)

**Comment by pawan-poudel-github** [comment]
> Just setOpen(false) when you want
> 
> ```
> const [open, setOpen] = useState(false);
>   return (
>     <Dialog open={open} onOpenChange={setOpen}>
>       <DialogContent>
>         <DialogHeader>
>           <DialogTitle className="mb-2">Add product</DialogTitle>
> 
>         </DialogHeader>
>       </DialogContent>
>     </Dialog>
>   );
> ```

How can I get value of switch component or add custom on/off value?
