### ISSUE TITLE
Changing Color of Link Globally

### ISSUE THREAD

**Issue by hirvesh** [shadcn-ui/ui#1759]
Hello 👋

I'm trying to figure out how I can change my link color globally to be different from my primary/secondary colors - i.e. a separate variable for link colors for light mode/dark mode.

Any idea on how to go about this?

**Comment by shadcn** [comment]
Are the `<a>` tags inside `.prose` i.e `tailwindcss/typography` or you want the color applied everywhere?

**Comment by hirvesh** [comment]
@shadcn - it’s everywhere- I would mind an example of both scenarios though 👀

**Comment by shadcn** [comment]
Closing this as done @hirvesh but feel free to reopen if you have any other question. Thanks.

**Comment by hirvesh** [comment]
Thanks @shadcn! Proposed implementation worked like a charm! ✅
