### ISSUE TITLE
Bug: Cannot access AccordionItem.prototype on the server.

### ISSUE THREAD

**Issue by recallwei** [shadcn-ui/ui#1761]
Every time I refresh the page or HMR, I get this error.
Seriously affected my development experience.
I had to refresh again to clear the error dialog.
![image](https://github.com/shadcn-ui/ui/assets/62941121/f4e1ea38-ff72-499f-ba79-94347ffd3537)

**Comment by shadcn** [comment]
Can you help me reproduce this?

**Comment by recallwei** [comment]
I rolled the code back to the time when the problem occurred and the error didn't reproduce again.
I can't find the cause of this problem.
