### ISSUE TITLE
Form reset in react-hook-form does not clear fields' values.

### ISSUE THREAD

**Issue by Lenghak** [shadcn-ui/ui#1763]
- I have been experiencing a problem while trying to reset form when the submit is successfully completed. 
- After the submission completed, the inner form value (react-hook-form inner value states) will be cleared (expected behavior), yet the visible input value are still visible to the user even though react-hook-form's states are already cleared. 

**Below is my custom hook for react-hook-form initialization & side effect handling.**

```typescript
// import ...
export const useProjectUpdateHandler = ({
  status,
}: {
  status?: ProjectStatusType;
}) => {
  const form = useForm<z.infer<typeof projectUpdateFormSchema>>({
    shouldUnregister: true,
    defaultValues: {
      status: status,
      subject: "",
      comment: "",
    },
    resolver: zodResolver(projectUpdateFormSchema),
  });

// ...

  /**
   *  Handle the result of updating the project status.
   * */
  useEffect(() => {
    if (updatingStatus === "success") {
      toast({
        title: "Project status updated successfully",
        variant: "successive", // custom variant
      });

      form.reset();
    }

    if (updatingStatus === "error") {
      toast({
        title: "Project status updated failed",
        variant: "destructive",
      });
    }
  }, [updatingStatus, toast, form, router]);
  // ...
};
```

**Comment by PlagueFPS** [comment]
The solution currently that I found is to pass your default values to the reset function. This shouldn't be the intended functionality since you're providing the default values at initialization, but, seems like this is what we have to do currently. It's a react-hook-form issue as it happens with or without using shadcn/ui.

`form.reset({
status: status,
subject: "",
comment: "",
})`

**Comment by Lenghak** [comment]
Hello @PlagueFPS . Thank you for your replay. Unfortunately, that solution does not work either. I have tried them already, and even forcing page to refresh as well. But it's still no use.

**Comment by Lenghak** [comment]
I think I have found a solution: `form.control._reset();` does the work; however IMO, this feels so illegal to access the forbidden `control`.

**Comment by friscolie-cc** [comment]
try to wrap it like this

```jsx
useEffect(() => {
form.reset({....})
},[])
```
don't forget to add which depedency you want to listen into the `useEffect` depedency listener. Hope it works

**Comment by Lenghak** [comment]
Yeah, I already use it with `useEffect` and included all necessary dependency array, but that's not working. I have also found a temporary solution above.

**Comment by friscolie-cc** [comment]
> Yeah, I already use it with `useEffect` and included all necessary dependencies array, but that's not working. I have also found a temporary solution above.

maybe try to use controller from RHF??

**Comment by aashirisrar** [comment]
Here's a workaround I found, try:
`form.setValue("fieldValue", "");`

**Comment by Lenghak** [comment]
Straight and simple. By the way, it still take a significant amount of codes if we have lots of fields.

**Comment by Bergie81** [comment]
Why not just `form.reset({})`?

**Comment by HarshArora-1205** [comment]
What you guys did to handle default case if say select menu's options are dynamic? On resetting using form.reset(), the states are reset but their values are still shown in the menu. I don't intend to use undefined which is ig not the best practice.
