### ISSUE TITLE
Type error: Property 'className' does not exist on type 'DialogPortalProps'.

### ISSUE THREAD

**Issue by pawan-poudel-github** [shadcn-ui/ui#1773]
I got this error while building next app: 
```ts
Linting and checking validity of types  ..Failed to compile.

./src/components/ui/dialog.tsx:14:3
Type error: Property 'className' does not exist on type 'DialogPortalProps'.

  12 | 
  13 | const DialogPortal = ({
> 14 |   className,
     |   ^
  15 |   ...props
  16 | }: DialogPrimitive.DialogPortalProps) => (
  17 |   <DialogPrimitive.Portal className={cn(className)} {...props} />```

**Comment by kthehatter** [comment]
hello it seems it was solved in [1603](https://github.com/shadcn-ui/ui/pull/1603) just updated it to latest version

**Comment by pawan-poudel-github** [comment]
> hello it seems it was solved in [1603](https://github.com/shadcn-ui/ui/pull/1603) just update it to latest version

Although I disable eslint for that error. But my all packages are upto date, I already tried that before. Also same error occuring for sheet component

**Comment by kthehatter** [comment]
> Although I disable eslint for that error. But my all packages are upto date, I already tried that before. Also same error occuring for sheet component

sorry what i meant is that i deleted  Dialog in the ui  folder  the added it again it fixed the issue for me as for sheet i heard the  issue still exists

**Comment by vtrikoupis** [comment]
className seems to still be missing in radix-ui/react-dialog 1.0.5

**Comment by r0ld3x** [comment]
Same error for me

**Comment by w4jo** [comment]
Same error for me

**Comment by Illyism** [comment]
Downgrading @types/react supposedly helps

**Comment by Illyism** [comment]
Possible cause https://github.com/DefinitelyTyped/DefinitelyTyped/issues/66841

**Comment by Illyism** [comment]
Removing the `className` for me did the trick

<img width="716" alt="image" src="https://github.com/shadcn-ui/ui/assets/304283/4c082a74-31dd-49f4-8a0f-516df1c13c44">

**Comment by shadcn** [comment]
Yes. This was fixed. You can safely remove the `className` from `<DialogPortal />`
