### ISSUE TITLE
Dark mode in React with Vite not working

### ISSUE THREAD

**Issue by eduardoslg** [shadcn-ui/ui#1775]
Hello, I'm having problems building an app on Vercel. Dark mode is not working. I've tried every way (I even took a look at the issues created) and it still doesn't work. Can anybody help me?

**Comment by headironc** [comment]
You need to provide a demo with the least amount of code to reproduce the problem

**Comment by eduardoslg** [comment]
basically in all <div></div> tags that I create I need to pass dark:bg-background? Is there no way to set it by default?

**Comment by yahia-berashish** [comment]
Hello @eduardoslg 
Can you provide some code or screenshots of the problem you are facing?
The config files & `App.tsx` will be useful.

**Comment by hdadr** [comment]
> Hello @eduardoslg Can you provide some code or screenshots of the problem you are facing? The config files & `App.tsx` will be useful.

I have the same issue.
New vite react typescript app, and only added the shadcnui. 
Followed the dark mode installation in the doc for the vite. What I see is the html tag receives the class=light property, but does not change when I give dark as an initial value to the theme provider. 

If I manually override it in the browser to <html class="dark">
It does change the button theme, but the background stays white.

**Comment by yahia-berashish** [comment]
Can you provide your `App.jsx` and `tailwind.config.js` files? @hdadr

**Comment by yahia-berashish** [comment]
Thanks for the additional context. 
I managed to recreate the issue by using the `shadcn-ui` CLI and choosing `no` for CSS Variables, which resulted in the tailwind.config.js file not having any color extension colors while leaving the `src/index.css` file empty from any color variables too. 
It seems that there is an issue with the CLI itself @shadcn. 
You can solve the issue by initiating shadcn-ui again and enabling the CSS Variables option @hdadr, hope this solves your problem too @eduardoslg

**Comment by hdadr** [comment]
> Thanks for the additional context. I managed to recreate the issue by using the `shadcn-ui` CLI and choosing `no` for `CSS Variables`, which resulted in the `tailwind.config.js` file not having any color extension colors while leaving the `src/index.css` file empty from any color variables too. It seems that there is an issue with the CLI itself @shadcn. You can solve the issue by initiating shadcn-ui again and enabling the CSS Variables option @hdadr, hope this solves your problem too @eduardoslg

I have another shadcn-ui problem, i am not sure its connected here, but might be.
I want to use the dropdown component (basically copy-pasted the dark mode toggle element from the docs, and it says that it cannot find the "@radix-ui/react-dropdown-menu" . Does it also have to do with the setting up correctly the shadcn-ui to be used by the cli?

**Comment by wangshaoyi9738** [comment]
I had this problem tI had this problem too, but I've solved it by enabling CSS variables.
However, dark mode is not affected in next.js by whether CSS variables are enabled or not.
Would like to be able to alert the need to enable CSS variables or make it consistent with next.js in vite dark mode pages.oo, but I've solved it by enabling CSS variables.

**Comment by wangshaoyi9738** [comment]
I had this problem too, but I've solved it by enabling CSS variables.
However, dark mode is not affected in next.js by whether CSS variables are enabled or not.
Would like to be able to alert the need to enable CSS variables or make it consistent with next.js in vite dark mode pages.

**Comment by wangshaoyi9738** [comment]
I had this problem too, but I've solved it by enabling CSS variables.
However, dark mode is not affected in next.js by whether CSS variables are enabled or not.
Would like to be able to alert the need to enable CSS variables or make it consistent with next.js in vite dark mode pages.
