### ISSUE TITLE
Sheet: Using open and onOpenChange props on Sheet component causes the application to freeze and break

### ISSUE THREAD

**Issue by Syammed2429** [shadcn-ui/ui#1776]
`<Button variant='outline' onClick={() => setOpenSheet(true)}>
            Filters
          </Button>
          {openSheet && (
            <FilesFilterSheet
              onApply={(data: any) => filteredData(data)}
              openSheet={openSheet}
            />
          )}`

**Comment by SweydManaf** [comment]
how do u solved this?

**Comment by SweydManaf** [comment]
OH, I solved putting this on my global css

body {
  pointer-events: auto !important;
}

The shadcn Sheet is changing to none...

**Comment by lbabay892** [comment]
This solution needs to be everywhere. spent hours trying to fix the sheet and adding this completely fixed my issues

**Comment by lbabay892** [comment]
for context, all the ways i've seen people using sheets, didn't really fit my use case. when a user clicks an item from a drop down menu, it triggers the setIsEditing(true) state, which renders my sheet with a form inside it. 

most of the other examples i've seen have been leveraging the `<SheetTrigger />` component, which i'm not
```
isEditing ?
          <Sheet open={isEditing} onOpenChange={() => {setIsEditing(false)}}>
            <SheetContent side={"top"}>
            <SheetHeader>
              <SheetTitle>Editing Transaction</SheetTitle>
              <SheetDescription>make changes to the current transaction and click "Submit"</SheetDescription>
            </SheetHeader>
              <TransactionForm formType="edit" setEditingTransactionState={setIsEditing} />
            </SheetContent>
          </Sheet> :
          null
        }
```
