### ISSUE TITLE
tailwindcss style not working with vite + React

### ISSUE THREAD

**Issue by jiechen257** [shadcn-ui/ui#1782]
Here's the [use case repository code](https://github.com/jiechen257/shadcn-app), and here's a screenshot (the actual tailwindcss style doesn't take effect when I click on the dialog)

before:
![image](https://github.com/shadcn-ui/ui/assets/73946940/2792090d-603c-41db-8fbc-37a778097dbb)

after click dialog button:
![image](https://github.com/shadcn-ui/ui/assets/73946940/461b0ec6-85db-4f37-9663-c04822d8a08d)

After googling, I found that the problem is that the `app/globals.css` is not working, but my project is built exactly according to the official website documentation. Hoping I can get a reply

**Comment by minhson3012** [comment]
If you import `app/globals.css` into `App.tsx` the styles will be applied.

**Comment by jiechen257** [comment]
> If you import `app/globals.css` into `App.tsx` the styles will be applied.

Thanks, it worked for me. But I would like to know why building a project according to the official documentation tutorial will occur this problem, and if this is the solution, this step should be one of the steps in the official documentation

**Comment by minhson3012** [comment]
> > > If you import `app/globals.css` into `App.tsx` the styles will be applied.
> > 
> > 
> > Thanks, it worked for me. But I would like to know why building a project according to the official documentation tutorial will occur this problem, and if this is the solution, this step should be one of the steps in the official documentation
> 
> Is it that where I am inconsistent with the construction steps of the documentation?

I believe you misconfigured `components.json` at this step

`Where is your global CSS file? › › src/index.css`

The default value for the global CSS file is `app/globals.css` (Nextjs's default global css file), you have to change it to `src/index.css`, otherwise you'll have to manually import it

**Comment by jiechen257** [comment]
> > > > If you import `app/globals.css` into `App.tsx` the styles will be applied.
> > > 
> > > 
> > > Thanks, it worked for me. But I would like to know why building a project according to the official documentation tutorial will occur this problem, and if this is the solution, this step should be one of the steps in the official documentation
> > 
> > 
> > Is it that where I am inconsistent with the construction steps of the documentation?
> 
> I believe you misconfigured `components.json` at this step:
> 
> `Where is your global CSS file? › › src/index.css`
> 
> The default value for the global CSS file is `app/globals.css` (Nextjs's default global css file), you have to change it to `src/index.css`, otherwise you'll have to manually import it

I re-created the project twice from the documentation, and the results were the same. I know the problem is `global.css` was not imported properly, and I wanted to explore why it occur the problem to build according the documentation. 

The normal situation is to build the project according to the documentation, it should be smooth

**Comment by minhson3012** [comment]
Please check this part of the documentation

![image](https://github.com/shadcn-ui/ui/assets/22538900/846bda53-975b-4ad7-be90-56dafc85c4e6)


If you are setting up using the CLI, you should change the global CSS file to 'src/index.css` instead of the default value

**Comment by jiechen257** [comment]
> Please check this part of the documentation
> 
> ![image](https://user-images.githubusercontent.com/22538900/276878608-846bda53-975b-4ad7-be90-56dafc85c4e6.png)
> 
> If you are setting up using the CLI, you should change the global CSS file to `src/index.css` instead of the default value

I understand what you mean, thank you

In addition, if the CLI detects it to create a project with VITE, can the default value provided by this item be `src/index.css`？

**Comment by pouyapanahandeh** [comment]
> If you import `app/globals.css` into `App.tsx` the styles will be applied.

Thank you, it solves our problem!
