### ISSUE TITLE
Horizontal scroll not available on scroll-area component

### ISSUE THREAD

**Issue by yahia-berashish** [shadcn-ui/ui#1783]
I just wanted to ask why the `orientation` prop is not exposed in the `scroll-area` component.
When the file is manually modified and the prop is exposed, the component seems to work just fine, is there a specific reason for not exposing the `orientation` prop?

The only PR related to this issue I found is #1515 - and I'm not sure why it wasn't merged.

**Comment by shadcn** [comment]
I merged the PR. Thank you.
