### ISSUE TITLE
#Combobox is not working properly

### ISSUE THREAD

**Issue by al-imam** [shadcn-ui/ui#1785]
Issue is combobox transforming the main value to lowercase for example 'Imam' it's converting it to 'imam' it is not expected behaviour i guess, please do something!

**Comment by shadcn** [comment]
@al-imam `cmdk` converts all values to lowercase. See this [note](https://github.com/pacocoursey/cmdk#command-cmdk-root).

You can pass in a custom `value` props if you need to.
