### ISSUE TITLE
Select having backdrop behaviour

### ISSUE THREAD

**Issue by Sandeep13-web** [shadcn-ui/ui#1809]
Whenever i open the select, the body is not scrollable. Is there something i need to pass as props in order to solve this problem?

**Comment by alexsilvar** [comment]
I have the same problem when I put my select inside a Dialog, if I set `modal={false}` on the Dialog it works as expected. I'm still seeking for the proper fix.

**Comment by matheralvs** [comment]
@Sandeep13-web & @alexsilvar I wrapped my Select content in a ScrollArea component and it worked.

**Comment by shadcn** [comment]
@Sandeep13-web This is a known issue (or maybe intended behavior?). There's a PR here https://github.com/radix-ui/primitives/pull/2253 waiting for feedback from the Radix team.

I'll close this one for now and continue tracking there. Feel free to reopen if you have any other question. Thank you.

**Comment by leognmotta** [comment]
that is still a problem
