### ISSUE TITLE
Alert padding doesn't work on Firefox

### ISSUE THREAD

**Issue by emicba** [shadcn-ui/ui#181]
Since [Firefox doesn't support the `:has` pseudo-class](https://caniuse.com/css-has), the icon overlaps with the title.

Here is a screenshot using Mozilla Firefox 112.0.1 on Linux.
![image](https://user-images.githubusercontent.com/31087818/232538087-f0ce6700-9ca1-44d2-b148-00342b62df94.png)

**Comment by HoldUpFjord** [comment]
Just came here to mention the same issue! 

Good eye @emicba 

![shadcdnIssue](https://user-images.githubusercontent.com/93451889/232628064-aa3f8ab4-b414-4736-834e-e39952d7a75a.gif)

**Comment by emicba** [comment]
This was fixed in https://github.com/shadcn-ui/ui/pull/1059.
