### ISSUE TITLE
404 This page could not be found, on Any Route in NextJS

### ISSUE THREAD

**Issue by yhoungdev** [shadcn-ui/ui#1821]
My Application was working fine. but after initializing ShadCN with pnpm dlx shadcn-ui@latest init
inito my next, i can no longer get any route again. 

I started getting 404 page 
![Screenshot from 2023-10-24 04-57-36](https://github.com/shadcn-ui/ui/assets/54102389/1492772c-3bf4-4c35-bfbe-a97355b1e8c9)

**Comment by stefandim91** [comment]
I had the same problem. Somehow there were two `app `folders. One on the root level and one in `src`. After I deleted the outer one, started to work as expected.

**Comment by timconnorz** [comment]
> I had the same problem. Somehow there were two `app `folders. One on the root level and one in `src`. In both of them, there was `global.css`. Maybe I did something wrong when initializing the project. I moved the `global.css` from the outer to the inner `app` folder, deleted the outer and the problem was solved.

I ran into this same issue. thanks for sharing your fix!

**Comment by yhoungdev** [comment]
> I had the same problem. Somehow there were two `app `folders. One on the root level and one in `src`. In both of them, there was `global.css`. Maybe I did something wrong when initializing the project. I moved the `global.css` from the outer to the inner `app` folder, deleted the outer and the problem was solved.

No you didn't do anything wrong.

  This was the reason why you might be facing that.

* You create a new nextJs application
* And after that you wanna init shadCN UI 
With `pnpm dlx shadcn-ui@latest init` this process makes it look like it is initialising another project.

Because sometimes it can create a  tailwind.config.js and tailwind.config.ts

**Comment by devdumpling** [comment]
This happened to me too. For reference, I have a `src` folder that houses `app` and am thinking maybe the shadcn CLI didn't account for it... but only for the globals weirdly?

**Comment by yhoungdev** [comment]
> This happened to me too. For reference, I have a `src` folder that houses `app` and am thinking maybe the shadcn CLI didn't account for it... but only for the globals weirdly?

by Default when setting NextJs, it asks if you want to use SRC dir / if yes then it will create an SRC folder that is gonna house the App folder

**Comment by shadcn** [comment]
@devdumpling the cli should handle `src` dir. Any chance you can post an overview of your project structure so that I can take a look?

**Comment by yhoungdev** [comment]
> @devdumpling the cli should handle `src` dir. Any chance you can post an overview of your project structure so that I can take a look?

YEa @devdumpling you should post an overview

**Comment by ex3ndr** [comment]
I just hit the same problem: it didn't detect an existing src folder during setup and i didn't change path to css so it created a new folder.

**Comment by yhoungdev** [comment]
How where you able to resolve it.

   And @shadcn has this issue been resolved?🙏

**Comment by ex3ndr** [comment]
I have merged generated file to the right place and updated components.json

**Comment by nicolaerusan** [comment]
where do things go specifically here? I've also hit this issue.

@shadcn it happens on the path of the installation instructions - if you're using `pnpm` and follow instructions directly and just hit enter through everything you get this issue:

https://ui.shadcn.com/docs/installation/next

**Comment by yhoungdev** [comment]
Awesome

**Comment by shadcn** [comment]
@nicolaerusan Thanks for the updates. I'll mark this as a bug and look into it.

**Comment by nicolaerusan** [comment]
Let me know if there's anything I can do to help debug & thanks @shadcn!

Any workaround suggestions for installing?

I tried to move the files around to the appropriate spots but the tailwind config was still broken so must not have caught all the pieces needed

**Comment by luanfvieira** [comment]
The problem happens because `globals.css` is being created in the root of the project.

Delete the app folder in the root and restart the development server and it will work.

![image](https://github.com/shadcn-ui/ui/assets/8730936/f32d680e-5c13-4456-8a0b-4d1b11218d64)

**Comment by Obsidian-AI** [comment]
I noticed that during my original installation that I had the same issue, and then was easily able to fix once i was moved globals.css

**Comment by hou-man** [comment]
Not intuitive but if your `globals.css` is at `src/app/globals.css` you should include the `src` when answering the following prompt or a duplicate `app` directory and `globals.css` is created.

<img width="447" alt="Screenshot 2023-12-26 at 10 15 30 PM" src="https://github.com/shadcn-ui/ui/assets/40189998/367b95d4-912e-4001-8e32-c605f35b7a76">

**Comment by lem0n4id** [comment]
> Not intuitive but if your `globals.css` is at `src/app/globals.css` you should include the `src` when answering the following prompt or a duplicate `app` directory and `globals.css` is created.
> 
> <img alt="Screenshot 2023-12-26 at 10 15 30 PM" width="447" src="https://private-user-images.githubusercontent.com/40189998/292969886-367b95d4-912e-4001-8e32-c605f35b7a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MjcyOTEsIm5iZiI6MTcwNDUyNjk5MSwicGF0aCI6Ii80MDE4OTk5OC8yOTI5Njk4ODYtMzY3Yjk1ZDQtOTEyZS00MDAxLThlMzItYzYwNWYzNWI3YTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA3NDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZjZjNTVlMWZiMmY1ZTMyMDYwODdjYzNjZTk4OGI4M2Y2MjQxMTEwZDMwNzk3YmZkZDVhYjJiZWVkNTM5NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GUQcvcGwoikaERQZczRdd1ERYog-Vc3VJ930yVJ5iSw">

This works! Maybe updating the cli default to `src/app/globals.css` will fix this issue!

**Comment by yhoungdev** [comment]
Has this issue been fixed on the Cli ? 

If yes the issue can be closed or moved to discussion

**Comment by lem0n4id** [comment]
> Has this issue been fixed on the Cli ?
> 
> If yes the issue can be closed or moved to discussion

Not yet. I am in process of submitting a PR fixing this

**Comment by yhoungdev** [comment]
This issue has already been fixed

**Comment by yhoungdev** [comment]
The team did a really great work 🤩
