### ISSUE TITLE
AlertDialogOverlay with unused children prop

### ISSUE THREAD

**Issue by Shubhdeep12** [shadcn-ui/ui#1827]
Children prop is defined in props for AlertDialogOverlay.

Is it intentionally added or skipped?

[like to code](https://github.com/shadcn-ui/ui/blob/c6917799ce188cb4cf48018b8c093bfebd6b3eac/apps/www/registry/default/ui/alert-dialog.tsx#L18C17-L18C25)

**Comment by Shubhdeep12** [comment]
Please confirm if this is a valid bug, I'll raise a pr for this fix.
Thanks

**Comment by shadcn** [comment]
Yeah. Looks like we can remove this and keep `{...props}`.

**Comment by Shubhdeep12** [comment]
i think we should also className along with props @shadcn
