### ISSUE TITLE
How to open all items in the accordion component.

### ISSUE THREAD

**Issue by thoushif** [shadcn-ui/ui#1848]
How to open all items in the accordion component

**Comment by j-fdion** [comment]
Set the type prop in Accordion to "multiple"

`
<Accordion type="multiple" className="w-full">
    ...
</Accordion>
`

**Comment by thoushif** [comment]
this allows the accordion to open multiple (not collapsing others when one open).
But I need to keep all the items open on load of the accordion to the page.

**Comment by ianschmitz** [comment]
@thoushif you'll have to use `defaultValue` prop and specify all of the `value` of the children.

For example

```tsx
<Accordion defaultValue={["item-1", "item-2"]} type="multiple">
  <AccordionItem value="item-1">
    <AccordionTrigger>Trigger</AccordionTrigger>
    <AccordionContent>
      Item 1
    </AccordionContent>
  </AccordionItem>
  <AccordionItem value="item-2">
    <AccordionTrigger>Trigger</AccordionTrigger>
    <AccordionContent>
      Item 2
    </AccordionContent>
  </AccordionItem>
</Accordion>
```

**Comment by thoushif** [comment]
Perfect!, i did not see the string[] in the suggestion.
Thanks @ianschmitz!!

**Comment by ShammiWD** [comment]
@ianschmitz, Thank you. 
I was unable to set the value dynamically. Could you assist me with that?

**Comment by thoushif** [comment]
Copied from radix ui docs:
defaultValue:
The value of the item to expand when initially rendered and type is "single". Use when you do not need to control the state of the items.

So the default is just the initial render.
To make it dynamic, I have tried using data-state open/close.
But no luck.

How are you trying?
