### ISSUE TITLE
[FEATURE REQUEST] Select with Icons in options

### ISSUE THREAD

**Issue by yassineatik** [shadcn-ui/ui#1876]
It will be great to see an option to add icons to your Select Option

**Comment by coded58** [comment]
you can either extend the select component or display the icon when using the select option

**Comment by jhdcruz** [comment]
I was able to do this without tampering with the original component using a `flex` div inside `<SelectItem>`.

```tsx
<SelectItem
  key={paymentStatus.value}
  value={paymentStatus.value}
>
  <div className="flex items-center">
    <paymentStatus.icon className="mr-2 h-4 w-4" />
    {paymentStatus.label}
  </div>
</SelectItem
```

**Preview:**

![image](https://github.com/shadcn-ui/ui/assets/28413338/6a449e4f-828b-41fa-96eb-e15dee33c060)
