### ISSUE TITLE
Export all the components?

### ISSUE THREAD

**Issue by corysimmons** [shadcn-ui/ui#19]
![image](https://user-images.githubusercontent.com/224636/214755600-18b44e4c-b64b-44e7-b070-79f5e39c8127.png)

Why not export everything so users can just `yarn add shadui` then `import { AlertDialog,
  AlertDialogAction } from 'shadui'`?

**Comment by banuragaxioned** [comment]
I was thinking the same. Definitely sounds cool.

Though I read/see the rationale behind it now https://ui.shadcn.com/docs#is-it-available-as-an-npm-package

**Comment by corysimmons** [comment]
I can't entirely agree with the rationale.

Just add `{...rest}` to every element of these compound components, then let users override them with whatever they'd like.

E.g.

```tsx
// I can use the default stuff to tinker around with and make an MVP
import { Accordion } from 'shadui`

export default () {
  return <Accordion>...</Accordion>
}

// Or if I want to customize them
// MyCustomizedAccordion.tsx
import { Accordion } from 'shadui`

export default () {
  return <Accordion classNames="bg-red-500 ..." style={{ marginTop: '5px' }}>...</Accordion>
}
```

**Comment by its-monotype** [comment]
> 

Is your example related to the text that you wrote? Because I don't see any connection between the comment and the example

**Comment by corysimmons** [comment]
His rationale is something like

>Just copy/paste then you can extend the component to handle things like `onClick` yourself

My point was he can already enable that just by spreading props onto the element.

**Comment by shadcn** [comment]
@corysimmons Just a quick update here. I am considering this. 

https://twitter.com/shadcn/status/1620721685547847680?s=46&t=8-pyuY_WUGx6q9Q5FpMyGw

@corysimmons Let’s keep the discussion open.

**Comment by corysimmons** [comment]
I think everyone on Twitter is misreading as:

1. Do you want to just have the option to import pre-built stuff?
2. Do you want to be able to ✨ customize ✨?

I'm suggesting the best of both worlds (and how most huge UI kits like AntD, etc. handle it).

```tsx
import { SomeComponentFromALib } from 'some-lib'

<SomeComponentFromALib
  className="w-20 text-sm" // these will override the defaults if they clash
  onClick={async ({ defaultFn }) => {
    await doSomethingCustomOnAServer()
    defaultFn() // trigger the lib's code
  }}
/>
```

I think the implementation is something-something `{...rest}` spreading, or maybe something to do with React `Forward` APIs.

I'm going to unsubscribe but good luck on your lib! It looks really cool.

**Comment by corysimmons** [comment]
@rollingmoai He added a way to add components via a shadcn-ui specific CLI.

That is, look at the Button component docs: https://ui.shadcn.com/docs/components/button

You can still copy/paste if you'd like, or you can use https://npm.im/shadcn-ui to do all that for you.

![image](https://github.com/shadcn-ui/ui/assets/224636/5527f737-c4c6-423f-9d3f-7fc2b7eef8da)

https://ui.shadcn.com/docs/cli

It combines the two ideas so you don't have to `npm i radix-stuff` & copy/paste. Instead you can just do something like `https://ui.shadcn.com/docs/cli` and I'm guessing it will create a `./components/Button/...` directory with all the stuff you might need and update an `./components/index.ts` so you can just do something like:

```tsx
import { Button } from '@/components'
```

I haven't tested this. I'm just guessing that's what is going on.
