### ISSUE TITLE
Toast not displayed correclty on mobile

### ISSUE THREAD

**Issue by sebiwi** [shadcn-ui/ui#1908]
Hello,

The [toast](https://ui.shadcn.com/docs/components/toast) component is not displayed correctly on my project when on mobile.

When using the browser, it works fine:

<img width="483" alt="Screenshot 2023-11-03 at 14 35 25" src="https://github.com/shadcn-ui/ui/assets/1782142/d5f1725a-3744-4a6d-8419-ccd1d49ffa51">

Nevertheless, as soon as I switch to mobile navigation, the toast is displayed just outside of frame:

<img width="553" alt="Screenshot 2023-11-03 at 14 35 10" src="https://github.com/shadcn-ui/ui/assets/1782142/37022040-d3d6-4591-97d4-244ca19d03c3">

Am I doing something wrong? 

PS: Also, I'm using the `Toaster` component in my response, otherwise the toast never shows up. The documentation doesn't say this step is necessary, so maybe it's not up to date?

Thanks!

**Comment by TA9IO** [comment]
Have you tried using another browser? Sometimes old mobile browsers just sucks, also Safari does not support anything...
i faced the same probleme with the handmade pop-over component on iphone for some reason it just dont work

**Comment by TikiCat7** [comment]
@sebiwi I had the same issue. I moved the <Toaster /> component outside of my <main /> in the layout file and now it's working correctly.

**Comment by sebiwi** [comment]
Thanks! That worked like a charm!

Does anyone knows what the root cause of this issue is? Should it be documented?

**Comment by dong20191111** [comment]
这个问题我也发现了，浏览器在不同的宽度下效果有所区别。
大屏xl以上是没有问题的，md左右的情况是显示了一个边缘。小屏尤其是手机就看不到了，也看不到错误输出。
我们可以找一下引入的组件，尽可能的去找样式控制的部分。
![image](https://github.com/shadcn-ui/ui/assets/48936035/bf5e19b4-0d42-4f91-81e1-70a5607f4aa3)
可以看到ToastViewport部分，
![image](https://github.com/shadcn-ui/ui/assets/48936035/7fbc8c73-db43-4253-8f09-a11202f0159d)
这里有控制样式的内容，我们尝试修改可以看到在小屏下有作用。
`"fixed bottom-0 z-[100] flex max-h-screen w-4/5 md:w-1/2 xl:w-1/4 flex-col-reverse p-4 right-0",`
感觉是对sm的支持有问题，小屏情况并没有按sm:的有效执行。
我们尝试改一下这块的处理，如我提供的代码，效果如下：
小屏：
![image](https://github.com/shadcn-ui/ui/assets/48936035/474692cb-f8a6-412b-bf08-bd9d63da3ca1)
中屏：
![image](https://github.com/shadcn-ui/ui/assets/48936035/59865cd5-2ea7-4a97-b58c-62b1dd4a03b3)
大屏：
<img width="1391" alt="image" src="https://github.com/shadcn-ui/ui/assets/48936035/8a86822f-42ac-478d-ad70-3e38edb6dd83">

我目前只能在这里解决，具体为何原来的有问题需要深入组件实现的部分才清楚。目前按这种方式可以展示出来。如果那位大神发现更好的方式处理，可以告诉我。

**Comment by raymond-UI** [comment]
<img width="719" alt="image" src="https://github.com/user-attachments/assets/100517c5-a90d-4956-9afd-e3a87ea6ecaf" />

Moving the  Toaster above the sidebar and main did the magic.
