### ISSUE TITLE
NavigationMenu breaks page

### ISSUE THREAD

**Issue by beetauri** [shadcn-ui/ui#1918]
Whenever I add any NavigationMenu component to a page, I get these errors:
```

 ⨯ node_modules\@radix-ui\react-direction\dist\index.mjs (4:82) @ undefined
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\webpack-runtime.js:33:42)
    at eval (./src/components/ui/navigation-menu.tsx:18:89)
    at (rsc)/./src/components/ui/navigation-menu.tsx (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\app\page.js:184:1)       
    at __webpack_require__ (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:8:88)
    at (rsc)/./src/app/page.tsx (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\app\page.js:173:1)
    at Function.__webpack_require__ (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\webpack-runtime.js:33:42)
    at async Promise.all (index 0)
null
 ⨯ node_modules\@radix-ui\react-direction\dist\index.mjs (4:82) @ undefined
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\webpack-runtime.js:33:42)
    at eval (./src/components/ui/navigation-menu.tsx:18:89)
    at (rsc)/./src/components/ui/navigation-menu.tsx (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\app\page.js:184:1)       
    at __webpack_require__ (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:8:88)
    at (rsc)/./src/app/page.tsx (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\app\page.js:173:1)
    at Function.__webpack_require__ (C:\Users\beeta\Desktop\virgin-atlantic\.next\server\webpack-runtime.js:33:42)
null
```
![image](https://github.com/shadcn-ui/ui/assets/68471315/9095bfd3-3a3f-48c1-ae82-b971bb007d32)

**Comment by rahulbhadja** [comment]
@beetauri  can you please elaborate more :)

**Comment by TA9IO** [comment]
first why are you using webpack! , the new recomended way is VITE.

are you having this probleme with every component or just NavigationMenu !

also sharing your `package.json` will help but i recommend trying to update `react `and `react dom` and maybe `radixui`
`npm update react react-dom`

**Comment by SamsonStannus** [comment]
I had this issue when using NextJS!

What fixed it was adding `"use client"` to the top of the `components/ui/navigation-menu.tsx` file.

**Comment by beetauri** [comment]
> first why are you using webpack! , the new recomended way is VITE.
> 
> are you having this probleme with every component or just NavigationMenu !
> 
> also sharing your `package.json` will help but i recommend trying to update `react `and `react dom` and maybe `radixui` `npm update react react-dom`

I'm using Next.js. It's just the NavigationMenu component. 
They're all up to date, here's my package.json:
https://gist.github.com/beetauri/f74a526a2f4e8b055c52ad511eaf5c4e
@rahulbhadja @TA9IO 


> I had this issue when using NextJS!
> 
> What fixed it was adding `"use client"` to the top of the `components/ui/navigation-menu.tsx` file.

It didn't fix it for me.

**Comment by tristanghanks** [comment]
@SamsonStannus 
> What fixed it was adding "use client" to the top of the components/ui/navigation-menu.tsx file.

This will result in a new error:

```jsx
TypeError: (0 , _components_ui_navigation_menu__WEBPACK_IMPORTED_MODULE_3__.navigationMenuTriggerStyle) is not a function
    at RootLayout (./src/app/layout.js:69:142)
    at stringify (<anonymous>)
  28 |             <NavigationMenuItem>
  29 |             <Link href="/docs" legacyBehavior passHref>
> 30 |               <NavigationMenuLink className={navigationMenuTriggerStyle()}>
     |                                                                       ^
  31 |                 Documentation
  32 |               </NavigationMenuLink>
  33 |             </Link>
```
  
  Now, removing the `navigationMenuTriggerStyle()` will fix the error, but will remove the styling shown in the example from the navigation-menu docs.

**Comment by theonlyway** [comment]
I most certainly have ""use client" at the top of my tsx file that renders out my Navigation menu and I use it like it's in the docs

```tsx
    if (route.protected === true && isSignedIn) {
      return (
        <NavigationMenuItem>
          <Link href={route.href} legacyBehavior passHref>
            <NavigationMenuLink className={navigationMenuTriggerStyle()}>
              {route.name}
            </NavigationMenuLink>
          </Link>
        </NavigationMenuItem>
      );
    }
```

**Comment by simibac** [comment]
@beetauri I see the same issue. Have you found a fix?

![image](https://github.com/shadcn-ui/ui/assets/15369592/9be1894e-094f-4b45-ba1d-2a1bd3dcf649)

**Comment by mpopv** [comment]
I'm guessing you're all using app router?

shadcn-ui's internal dependency radix-ui seems to use React context internally in its NavigationMenu components. I don't think there's any way to server render them because React context isn't supported in app router server rendered components. So there's no easy solution here except replace the component or client-render the menu, unless radix-ui decides to migrate away from using React context.

**Comment by BryanAM** [comment]
Yeah this is a problem if you want Navigation on all pages without 
1) adding `'use client'` to your root layout, which disabled your ability to use the [meta functionality](https://nextjs.org/docs/app/building-your-application/optimizing/metadata) in nextJS
2) moving your "root" layout down to a new route e.g. `domain.com/` is your root html layout and `domain.com/home` is your actual root layout
3) If there is a way to "spoof" your root layout without adding another URL <- this would be ideal but not sure it's possible to render two layouts.... 
4)** A slightly messy but optimal way is to not render your Menu at root but once at root/page.tsx and then once at the next level layout where you can use `'use client'` for a layout

**Comment by theonlyway** [comment]
You are doing something very wrong/odd if you need to any of those steps. I have my root layout as a RSC with my nav rendered from the root layout. You keep your rootlayout as a RSC but just import the navigation inside of a client component.

For example this root layout.tsx is a server component and the navigation renders my top and side nav. Part of that nav is RSC (The top nav bar and the mobile sheet that slides in when someone opens the mobile version of the nav) then parts of the nav bar are client components (The avatar and the navigation menu)
```jsx
import 'css/globals.css';
import Navigation from '@/components/navigation';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from '@/lib/providers/themeProvider';
import { Metadata, Viewport } from 'next';
import RootContainer from '@/components/common/rootContainer';
import { Toaster } from '@/components/ui/toaster';
import ReactQueryProvider from '@/lib/providers/reactQueryProvider';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: 'Home',
  description: 'Home page',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
    >
      <html
        lang='en'
        suppressHydrationWarning
        className={`${GeistSans.variable} ${GeistMono.variable}`}
      >
        <body>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Navigation />
            <Toaster />
            <ReactQueryProvider>
              <RootContainer>{children}</RootContainer>
            </ReactQueryProvider>
          </ThemeProvider>
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}
```

**Comment by CyrusVorwald** [comment]
I have the same issue. navigationMenuTriggerStyle throws an error, even with "use client" at the top of the navigation-menu component.

**Comment by ybentz** [comment]
> You are doing something very wrong/odd if you need to any of those steps above steps for this situation. I have my root layout as an RSC with my nav rendered from the root layout. You keep your root layout as an RSC but just import the navigation inside of a client component.
> 
> For example, this root layout.tsx is a server component and the navigation renders my top and side nav. Part of that nav is RSC (The top nav bar and the mobile sheet that slides in when someone opens the mobile version of the nav) then parts of the nav bar are client components (The avatar and the navigation menu because they both rely on auth to conditionally render)
> 
> ```js
> import 'css/globals.css';
> import Navigation from '@/components/navigation';
> import { ClerkProvider } from '@clerk/nextjs';
> import { ThemeProvider } from '@/lib/providers/themeProvider';
> import { Metadata, Viewport } from 'next';
> import RootContainer from '@/components/common/rootContainer';
> import { Toaster } from '@/components/ui/toaster';
> import ReactQueryProvider from '@/lib/providers/reactQueryProvider';
> import { GeistSans } from 'geist/font/sans';
> import { GeistMono } from 'geist/font/mono';
> import { Analytics } from '@vercel/analytics/react';
> 
> export const metadata: Metadata = {
>   title: 'Home',
>   description: 'Home page',
> };
> 
> export default function RootLayout({
>   children,
> }: {
>   children: React.ReactNode;
> }) {
>   return (
>     <ClerkProvider
>     >
>       <html
>         lang='en'
>         suppressHydrationWarning
>         className={`${GeistSans.variable} ${GeistMono.variable}`}
>       >
>         <body>
>           <ThemeProvider
>             attribute='class'
>             defaultTheme='system'
>             enableSystem
>             disableTransitionOnChange
>           >
>             <Navigation />
>             <Toaster />
>             <ReactQueryProvider>
>               <RootContainer>{children}</RootContainer>
>             </ReactQueryProvider>
>           </ThemeProvider>
>           <Analytics />
>         </body>
>       </html>
>     </ClerkProvider>
>   );
> }
> ```
> 
> You get to pick and choose depending on my your requirements which parts are server and client (https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns). It's not an all or nothing... I mean it is in some situations but certainly not in this situation.

This worked for me! Thanks!
As a side note. idk if this is the only reason you're using the `suppressHydrationWarning` prop but this way I got a client side hydration warning. Instead of using the `suppressHydrationWarning` prop I imported the component that wraps the `NavigationMenu` dynamically using `next/dynamic` and that solved it for me.

**Comment by darrylmorley** [comment]
> I have the same issue. navigationMenuTriggerStyle throws an error, even with "use client" at the top of the navigation-menu component.

Did you manage to solve this issue? I've set `"use client"` in the navigation-menu.tsx component, but still have a warning for this. I'm guessing that I'm going to have to make my whole header component a client component but would rather not if there's another way.

**Comment by davidsonaguiar** [comment]
in my navigation component I used "use client" and it worked

**Comment by llzmgjzhy** [comment]
> I had this issue when using NextJS!
> 
> What fixed it was adding `"use client"` to the top of the `components/ui/navigation-menu.tsx` file.

it work for me.
very very thank you.
but a question.how it work

**Comment by cong85010** [comment]
> > I had this issue when using NextJS!
> > What fixed it was adding `"use client"` to the top of the `components/ui/navigation-menu.tsx` file.
> 
> it work for me. very very thank you. but a question.how it work

Because it is a client component, NextJS splits the server component & client component. CSR renders on the client and not from server.
