### ISSUE TITLE
Using `-start` and `-end` properties for better RTL support

### ISSUE THREAD

**Issue by yahia-berashish** [shadcn-ui/ui#1919]
I noticed that border, margin, padding, etc classes use `-left` and `-right` properties, which doesn't work well for RTL pages, I suppose using `-start` and `-end` properties like `ms-` instead of `me-` would be better for accessibility and would remove a lot of work for everyone wanting to use RTL languages with shadcnUI (like Arabic for example). 
The changes aren't hard to implement using text search, and I can open a PR if the idea is valid.

**Comment by TA9IO** [comment]
i'm doing it manualy every time i install a component i change the following classNames
`mr-`=> `ms-`
`ml-` => `me-`
`pl-` => `pe-`
`pr-` => `ps-`
also some stuff like `flexbox ` and `position ` ( like a closing button of modal )needs to fixed manualy
for example:
 `flex-start` => `rtl:flex-end`
`left-4` => `ltr:left-4 rtl:right-4`

I mean, the thought of adding RTL support came to my mind, but I don't have time to update the entire library. If you guys are interested, count me in.
![image](https://github.com/shadcn-ui/ui/assets/93702837/41f6aa90-c540-461c-93f4-e03052f6e00f)

**Comment by primemb** [comment]
there is pull request for RTL already but it is pending for a while i don't know what the plan is for that #1638

**Comment by nahasco** [comment]
Did that in a pull request for all components and all styles. Its is still pending but you can check it out here #1638

**Comment by shadcn** [comment]
@yahia-berashish Yep like @nahasco we'll add this to the cli. Thanks for the ping @nahasco I'll add this to the queue.

**Comment by sahandsn** [comment]
any update on this?
