### ISSUE TITLE
Passing in Form as prop in Shadcn/ui?

### ISSUE THREAD

**Issue by Apestein** [shadcn-ui/ui#1921]
Basically I move FormField to another component and I need to pass in Form a props, the way I'm currently doing doesn't give auto-complete because of UseFormReturn<any>.
```ts
export default function FormComponent() {
 const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      folderID: 0,
    },
  })
...
  return (
    <Form>
      <form onSubmit={form.handleSubmit(onSubmit)}>
        <FolderIdFormField form={form} />
      </form
    </Form>
}

export function FolderIdFormField({
  form
}: {
  form: UseFormReturn<any>;
}) {
  ...
  return (
    <FormField
      control={form.control}
      name='folderID'
      render={({ field }) => (
       ...
      )}
    />
  );
}
```
Alternatively, is there way to access to get the form object from another component using react-hook-form?

**Comment by KranzAklilu** [comment]
You need to pass in the form type inside the generics instead of any
`
form: UseFormReturn<z.infer<typeof formSchema>>
`

**Comment by Apestein** [comment]
> You need to pass in the form type inside the generics instead of any `form: UseFormReturn<z.infer<typeof formSchema>>`

Thanks, this works. Still, it's kinda annoying to pass a form object many components deep. Work be nice if react-hook-form provided a hook to get form object so we can avoid prop drilling.

**Comment by grvpocketfm** [comment]
> > You need to pass in the form type inside the generics instead of any `form: UseFormReturn<z.infer<typeof formSchema>>`
> 
> Thanks, this works. Still, it's kinda annoying to pass a form object many components deep. Would be nice if react-hook-form provided a hook to get form object so we can avoid prop drilling.

react-hook-form actually provides useFormContext hook by which you can access useForm props and methods.
check this out: https://react-hook-form.com/docs/formprovider

**Comment by proscinski2k** [comment]
The <Form {...form}></Form> component from Shadcn works with <FormProvider {...methods}></FormProvider> to provide form methods via context. Using useFormContext(), you can access these methods, like control, in nested components. For example:

```
const { control } = useFormContext();

<FormField
  control={control}
  name="username"
  render={({ field }) => (
    <FormItem>
      <FormControl>
        <Input
          placeholder="Username"
          {...field}
        />
      </FormControl>
    </FormItem>
  )}
/>
```
