### ISSUE TITLE
Sheet component is not working inside Dropdown Menu.

### ISSUE THREAD

**Issue by anayatkhan1** [shadcn-ui/ui#1925]
``Description:``

When attempting to select an item from the dropdown menu, the associated sheet fails to activate as expected.
 
 ``Expected Behavior:``

The selected item from the dropdown menu should activate and display the associated sheet.

``Actual Behavior:``

Upon selecting an item from the dropdown menu, the associated sheet does not activate, and the expected content is not displayed.

### **Code**

```js
 <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button>
              <PlusIcon className="-ml-0.5 mr-1.5 h-5 w-5" aria-hidden="true" />
              Add contacts
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuGroup>
              <DropdownMenuItem className="gap-2 px-4 py-2.5">
                <button className="flex items-center justify-start gap-2">
                  <CloudIcon />
                  <span className="text-sm font-normal leading-[17.92px] text-gray-800">
                    Import contacts
                  </span>
                </button>
              </DropdownMenuItem>
              <DropdownMenuItem className="gap-2 px-4 py-2.5">
                <Sheet>
                  <SheetTrigger asChild>
                    <button>
                      <PlusIcon className="h-5 w-5" aria-hidden="true" />
                      <span className="text-sm font-normal leading-[17.92px] text-gray-800">
                        Create a contacts
                      </span>
                    </button>
                  </SheetTrigger>
                  <SheetContent>
                    <SheetHeader>
                      <SheetTitle>Create contacts</SheetTitle>
                    </SheetHeader>
                  </SheetContent>
                </Sheet>
              </DropdownMenuItem>
            </DropdownMenuGroup>
          </DropdownMenuContent>
        </DropdownMenu>
```

``Screenshots:``

![dialog](https://github.com/shadcn-ui/ui/assets/73161735/e69dddda-0bfa-4bf5-992f-1e57a839a832)

 #### Thank you for your attention to this matter! Let me know if any additional information is needed.

**Comment by obah** [comment]
What was the fix to this? I am also experiencing a similar issue.

**Comment by obah** [comment]
I found a fix, don't use SheetTrigger, instead use isOpen prop to toggle the sheet. And separate the sheet component from the dropdown component

**Comment by edeuxk** [comment]
@obah can you please send us an example of fix ?
That would be awesome, thank you :)

**Comment by obah** [comment]
const [isOpen, setIsOpen] = useState<boolean>(false);
  const toggleSheet = () => setIsOpen(!isOpen);

  return (
    <Sheet open={isOpen} onOpenChange={toggleSheet}>
        <Button size={"full"} onClick={toggleSheet}>
            Open Sheet
        </Button>

        <SheetContent>
            ...
        </SheetContent>
    </Sheet>
  )
  
  Basically something like this. You will pass the states and function to the component where the sheet will be triggered from
