### ISSUE TITLE
NavigationMenu not working in Astro

### ISSUE THREAD

**Issue by polooner** [shadcn-ui/ui#1930]
Hi,

I tried starting up a quick project with Astro React, Tailwind and of course shadcn-ui. When I copy the NavigationMenuDemo from 
https://ui.shadcn.com/docs/components/navigation-menu and import it into my layout (or index.astro) it only highlights the buttons on hover, no dropdown appears.

Code:
https://github.com/polooner/diverse-stem

**Comment by cristopher-namchee** [comment]
Have you tried [hydrating it](https://docs.astro.build/en/core-concepts/framework-components/#hydrating-interactive-components)? By default, all library components in Astro are not interactive.

**Comment by polooner** [comment]
> Have you tried [hydrating it](https://docs.astro.build/en/core-concepts/framework-components/#hydrating-interactive-components)? By default, all library components in Astro are not interactive.

I am new to Astro and did not know it has a client directive, adding client:load to the component solved it.

**Comment by marsmars0x01** [comment]
> > Have you tried [hydrating it](https://docs.astro.build/en/core-concepts/framework-components/#hydrating-interactive-components)? By default, all library components in Astro are not interactive.
> 
> I am new to Astro and did not know it has a client directive, adding client:load to the component solved it.

do you have any issues with hydration? I am currently battling it since I am using same component and seems like it won't go away and has something to do with either radix or shadcn

**Comment by porobertdev** [comment]
In my case, replacing `<Link>` with `<a>` has fixed it. I had it nested in `<Button>` and button was in `<ButtonGroup.tsx`. Then I was using `<ButtonGroup>` in `Navbar1.tsx>`.
