### ISSUE TITLE
Cannot read properties of undefined (reading 'subscribe') Combobox Error

### ISSUE THREAD

**Issue by aymanechaaba1** [shadcn-ui/ui#1939]
```tsx
'use client';

import { serverClient } from '@/app/_trpc/serverClient';
import useCustomForm from '@/hooks/useCustomForm';
import React from 'react';
import { z } from 'zod';

import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import ProgressBar from './ProgressBar';
import { trpc } from '@/app/_trpc/client';
import { Button } from './ui/button';
import { Popover, PopoverTrigger } from './ui/popover';
import { subjects } from './AddTeacher';
import { cn } from '@/lib/utils';
import { Check, ChevronsUpDown, Command } from 'lucide-react';
import { PopoverContent } from '@radix-ui/react-popover';
import {
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
} from './ui/command';

const editFormSchema = z.object({
  email: z.string().email().optional(),
  phone: z.string().min(10).max(14).optional(),
  name: z.string().min(3).optional(),
  avatar: z.instanceof(File).nullable(),
  subject: z.string().min(3).optional(),
});

function EditTeacherForm({
  defaultValues,
}: {
  defaultValues: Awaited<ReturnType<(typeof serverClient)['getTeacher']>>;
}) {
  if (!defaultValues) return;

  const [form] = useCustomForm({
    formSchema: editFormSchema,
    defaultValues,
  });

  const [progress, setProgress] = React.useState(0);
  const [open, setOpen] = React.useState(false);
  const [subject, setSubject] = React.useState(defaultValues.subject);

  function onSubmit(values: z.infer<typeof editFormSchema>) {
    // Do something with the form values.
    // ✅ This will be type-safe and validated.
    console.log(values);
  }
  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
        <FormField
          control={form.control}
          name="email"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Email</FormLabel>
              <FormControl>
                <Input defaultValue={defaultValues.email} {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="phone"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Phone</FormLabel>
              <FormControl>
                <Input
                  type="tel"
                  defaultValue={defaultValues.phone!}
                  {...field}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="name"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Name</FormLabel>
              <FormControl>
                <Input defaultValue={defaultValues.name} {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="avatar"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Avatar</FormLabel>
              <FormControl>
                <>
                  <Input
                    type="file"
                    accept="image/png, image/jpeg"
                    onChange={(e) => {
                      if (e.target.files) {
                        field.onChange(e.target.files[0]);
                      }
                    }}
                  />
                  <ProgressBar progress={progress} setProgress={setProgress} />
                </>
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="subject"
          render={({ field }) => (
            <FormItem className="flex flex-col">
              <FormLabel>Subject</FormLabel>
              <Popover>
                <PopoverTrigger asChild>
                  <FormControl>
                    <Button
                      variant="outline"
                      role="combobox"
                      className={cn(
                        'w-[200px] justify-between',
                        !field.value && 'text-muted-foreground'
                      )}
                    >
                      {field.value
                        ? subjects.find(
                            (subject) => subject.value === field.value
                          )?.label
                        : 'Select subject'}
                      <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                    </Button>
                  </FormControl>
                </PopoverTrigger>
                <PopoverContent className="w-[200px] p-0">
                  <Command>
                    <CommandInput placeholder="Search subject..." />
                    <CommandEmpty>No subject found.</CommandEmpty>
                    <CommandGroup>
                      {subjects.map((subject) => (
                        <CommandItem
                          value={subject.label}
                          key={subject.value}
                          onSelect={(val) => {
                            form.setValue('subject', subject.value);
                          }}
                        >
                          <Check
                            className={cn(
                              'mr-2 h-4 w-4',
                              subject.value === field.value
                                ? 'opacity-100'
                                : 'opacity-0'
                            )}
                          />
                          {subject.label}
                        </CommandItem>
                      ))}
                    </CommandGroup>
                  </Command>
                </PopoverContent>
              </Popover>
              <FormMessage />
            </FormItem>
          )}
        />

        <Button type="submit">Save Changes</Button>
      </form>
    </Form>
  );
}

export default EditTeacherForm;
```

**Comment by adamkangas** [comment]
Having the same issue, did you end up making any progress? 🙏

**Comment by KGALLET** [comment]
Ahah i feel you @adamkangas 
I just get baited as well with the lucide-react icon import.
Lost like 1 hour trying to figure what's wrong and trying multiple solutions i found on github issues.. 😄

**Comment by MohanadOO** [comment]
> Ahah i feel you @adamkangas I just get baited as well with the lucide-react icon import. Lost like 1 hour trying to figure what's wrong and trying multiple solutions i found on github issues.. 😄

Well I made the same mistake but glad that I found this GitHub issue 🤣
![image](https://github.com/shadcn-ui/ui/assets/58554988/a97301e7-bb52-48be-ae86-e6c476f4d158)

**Comment by krachtstefan** [comment]
> D'oh, it's this: #809 – just tired and running on autopilot, picking up imports from `lucide-react` 🤦🏼‍♂️

I think this issue could be closed then?

**Comment by aymanechaaba1** [comment]
Thank you all for participation! 👏

**Comment by quyphuc2111** [comment]
> > Ahah i feel you @adamkangas I just get baited as well with the lucide-react icon import. Lost like 1 hour trying to figure what's wrong and trying multiple solutions i found on github issues.. 😄
> 
> Well I made the same mistake but glad that I found this GitHub issue 🤣 ![image](https://private-user-images.githubusercontent.com/58554988/285637831-a97301e7-bb52-48be-ae86-e6c476f4d158.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTc3NzQsIm5iZiI6MTcxMDkxNzQ3NCwicGF0aCI6Ii81ODU1NDk4OC8yODU2Mzc4MzEtYTk3MzAxZTctYmI1Mi00OGJlLWFlODYtZTZjNDc2ZjRkMTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA2NTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YTNjYTRjMDA4NTJiMzJjMzA5ZjBiNGFkMTQ3NDBkNzkyYWQyYmMwNDhiY2Q0Yzg4Mjg2YzVjY2ViMzYzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hUDuR1nOiFADtnc-rUVh1gc6X5U7hoKNX996xgvU53M)

You save my time =)) lol

**Comment by raveenrv904** [comment]
"use client";

import * as React from "react";
import { Check, ChevronsUpDown } from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
} from "@/components/ui/command";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";

const frameworks = [
  {
    value: "next.js",
    label: "Next.js",
  },
  {
    value: "sveltekit",
    label: "SvelteKit",
  },
  {
    value: "nuxt.js",
    label: "Nuxt.js",
  },
  {
    value: "remix",
    label: "Remix",
  },
  {
    value: "astro",
    label: "Astro",
  },
];

export function ComboboxDemo() {
  const [open, setOpen] = React.useState(false);
  const [value, setValue] = React.useState("");

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-[200px] justify-between"
        >
          {value
            ? frameworks.find((framework) => framework.value === value)?.label
            : "Select framework..."}
          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[200px] p-0">
        <Command>
          <CommandInput placeholder="Search framework..." />
          <CommandEmpty>No framework found.</CommandEmpty>
          <CommandGroup>
            {frameworks.map((framework) => (
              <CommandItem
                key={framework.value}
                value={framework.value}
                onSelect={(currentValue) => {
                  setValue(currentValue === value ? "" : currentValue);
                  setOpen(false);
                }}
              >
                <Check
                  className={cn(
                    "mr-2 h-4 w-4",
                    value === framework.value ? "opacity-100" : "opacity-0"
                  )}
                />
                {framework.label}
              </CommandItem>
            ))}
          </CommandGroup>
        </Command>
      </PopoverContent>
    </Popover>
  );
}



I am getting the same error.
Anybody help me to solve this.

**Comment by raveenrv904** [comment]
`"use client";

import * as React from "react";
import { Check, ChevronsUpDown } from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
} from "@/components/ui/command";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";

const frameworks = [
  {
    value: "next.js",
    label: "Next.js",
  },
  {
    value: "sveltekit",
    label: "SvelteKit",
  },
  {
    value: "nuxt.js",
    label: "Nuxt.js",
  },
  {
    value: "remix",
    label: "Remix",
  },
  {
    value: "astro",
    label: "Astro",
  },
];

export function ComboboxDemo() {
  const [open, setOpen] = React.useState(false);
  const [value, setValue] = React.useState("");

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-[200px] justify-between"
        >
          {value
            ? frameworks.find((framework) => framework.value === value)?.label
            : "Select framework..."}
          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[200px] p-0">
        <Command>
          <CommandInput placeholder="Search framework..." />
          <CommandEmpty>No framework found.</CommandEmpty>
          <CommandGroup>
            {frameworks.map((framework) => (
              <CommandItem
                key={framework.value}
                value={framework.value}
                onSelect={(currentValue) => {
                  setValue(currentValue === value ? "" : currentValue);
                  setOpen(false);
                }}
              >
                <Check
                  className={cn(
                    "mr-2 h-4 w-4",
                    value === framework.value ? "opacity-100" : "opacity-0"
                  )}
                />
                {framework.label}
              </CommandItem>
            ))}
          </CommandGroup>
        </Command>
      </PopoverContent>
    </Popover>
  );
}
`

Import from the correct path, but still getting the same error.
Help me please.

**Comment by ZinhleBu** [comment]
> `"use client";
> 
> import * as React from "react"; import { Check, ChevronsUpDown } from "lucide-react";
> 
> import { cn } from "@/lib/utils"; import { Button } from "@/components/ui/button"; import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, } from "@/components/ui/command"; import { Popover, PopoverContent, PopoverTrigger, } from "@/components/ui/popover";
> 
> const frameworks = [ { value: "next.js", label: "Next.js", }, { value: "sveltekit", label: "SvelteKit", }, { value: "nuxt.js", label: "Nuxt.js", }, { value: "remix", label: "Remix", }, { value: "astro", label: "Astro", }, ];
> 
> export function ComboboxDemo() { const [open, setOpen] = React.useState(false); const [value, setValue] = React.useState("");
> 
> return ( {value ? frameworks.find((framework) => framework.value === value)?.label : "Select framework..."} No framework found. {frameworks.map((framework) => ( <CommandItem key={framework.value} value={framework.value} onSelect={(currentValue) => { setValue(currentValue === value ? "" : currentValue); setOpen(false); }} > <Check className={cn( "mr-2 h-4 w-4", value === framework.value ? "opacity-100" : "opacity-0" )} /> {framework.label} ))} ); } `
> 
> Import from the correct path, but still getting the same error. Help me please.

Has anyone figured this out yet? I'm still getting the same issue.

**Comment by mastoj** [comment]
Same here, I'm 99% certain my imports are ok but I still get the issue.

**Comment by strumswell** [comment]
In case anyone has the same issue and already checked imports: See if your command components are correctly nested. In my case, I forgot to wrap a component (inside a test) that returns a `CommandGroup` in a `CommandList` and then `Command`.

```diff
    const { container } = providerfulRender(
      <SearchContext.Provider value={mockContext}>
+        <Command>
+          <CommandList>
            <SearchResults {...defaultProps} />
+          </CommandList>
+        </Command>
      </MagicSearchContext.Provider>,
    );
```

**Comment by aelfannir** [comment]
I had the same issue, Just check Command's tree if it's correct
