### ISSUE TITLE
How to create a reusable component?

### ISSUE THREAD

**Issue by Seeeev** [shadcn-ui/ui#2020]
Im not quite familiar with typescript and i cant figure out how to create a reusable component lets say a FormField. Normal behavior should be if the property "name" is filled with a string that is not present in the schema it should show a type error under the "name" property. I want to have this behavior on a custom component.

```
function customFormField(control: any, name: string, label: String) {
    return (
      <FormField
        control={control}
        name={name}
        render={({ field }) => (
          <FormItem>
            <FormLabel>{label}</FormLabel>
            <FormControl>
              <Input placeholder="shadcn" {...field} />
            </FormControl>
          </FormItem>
        )}
      />
    );
  }

// should show a type error because lastName is not in the schema
{customFormField(form.control, "lastName", "Last Name")}
```

**Comment by austinm911** [comment]
> You can do something like this, which uses generics to enforce that `name` is valid.
> 
> ```tsx
> export function customFormField<T extends FieldValues>(control: Control<T>, name: Path<T>, label: String) {
>     return (
>       <FormField
>         control={control}
>         name={name}
>         render={({ field }) => (
>           <FormItem>
>             <FormLabel>{label}</FormLabel>
>             <FormControl>
>               <Input placeholder="shadcn" {...field} />
>             </FormControl>
>           </FormItem>
>         )}
>       />
>     );
>   }
> ```

I had this question before and in my forms I have a lot of different type of components that I used, anywhere from an input, to single select, date picker, multi-select, and so on. Is it suggested to create multiple custom form fields with each unique field component (like custom-single-select, custom-multi-select), rather than trying to make the entire reusable FormControl reusable?

**Comment by Seeeev** [comment]
> You can do something like this, which uses generics to enforce that `name` is valid.
> 
> ```tsx
> export function customFormField<T extends FieldValues>(control: Control<T>, name: Path<T>, label: String) {
>     return (
>       <FormField
>         control={control}
>         name={name}
>         render={({ field }) => (
>           <FormItem>
>             <FormLabel>{label}</FormLabel>
>             <FormControl>
>               <Input placeholder="shadcn" {...field} />
>             </FormControl>
>           </FormItem>
>         )}
>       />
>     );
>   }
> ```
 Works perfectly thank you.
