### ISSUE TITLE
npx shadcn-ui@latest add ALL < installs all components >

### ISSUE THREAD

**Issue by Jarrodsz** [shadcn-ui/ui#2027]
Could we please have a 

```
npx shadcn-ui@latest add ALL < installs all components >
```

I keep needing to enter cli commands to install a certain component which is really cybersome!
If im building a UI i want access to all components.

Additional add a cleanup command that scans your whole codebase and removes unused components.

```
npx shadcn-ui@latest cleanup
```

That way you can 

1. install all components with the first cli comamnd
2. when project finished you can scan all non used components and remove them ( optional )

**Comment by servesh-chaturvedi** [comment]
You can install all components in a go by using `npx shadcn-ui@latest add` without specifying any component name. For removing deps, knip.dev is a popular option. Although, what you mentioned is a great potential implementation

**Comment by shadcn** [comment]
You can do this using `npx shadcn-ui@latest add --all`.

**Comment by madebyaris** [comment]
I got an error

`Command failed with exit code 1: npm install @radix-ui/react-accordion @radix-ui/react-alert-dialog @radix-ui/react-slot @radix-ui/react-aspect-ratio @radix-ui/react-avatar react-day-picker@8.10.1 date-fns embla-carousel-react recharts lucide-react @radix-ui/react-checkbox @radix-ui/react-collapsible cmdk@1.0.0 @radix-ui/react-dialog @radix-ui/react-context-menu vaul @radix-ui/react-dropdown-menu @radix-ui/react-label @hookform/resolvers zod react-hook-form @radix-ui/react-hover-card input-otp @radix-ui/react-menubar @radix-ui/react-navigation-menu @radix-ui/react-popover @radix-ui/react-progress @radix-ui/react-radio-group react-resizable-panels @radix-ui/react-scroll-area @radix-ui/react-select @radix-ui/react-separator @radix-ui/react-slider sonner next-themes @radix-ui/react-switch @radix-ui/react-tabs @radix-ui/react-toast @radix-ui/react-toggle @radix-ui/react-toggle-group @radix-ui/react-tooltip`

**Comment by Big-jpg** [comment]
> I got an error
> 
> `Something went wrong. Please check the error below for more details. If the problem persists, please open an issue on GitHub.
> 
> Command failed with exit code 1: npm install @radix-ui/react-accordion @radix-ui/react-alert-dialog @radix-ui/react-slot @radix-ui/react-aspect-ratio @radix-ui/react-avatar react-day-picker@8.10.1 date-fns embla-carousel-react recharts lucide-react @radix-ui/react-checkbox @radix-ui/react-collapsible cmdk@1.0.0 @radix-ui/react-dialog @radix-ui/react-context-menu vaul @radix-ui/react-dropdown-menu @radix-ui/react-label @hookform/resolvers zod react-hook-form @radix-ui/react-hover-card input-otp @radix-ui/react-menubar @radix-ui/react-navigation-menu @radix-ui/react-popover @radix-ui/react-progress @radix-ui/react-radio-group react-resizable-panels @radix-ui/react-scroll-area @radix-ui/react-select @radix-ui/react-separator @radix-ui/react-slider sonner next-themes @radix-ui/react-switch @radix-ui/react-tabs @radix-ui/react-toast @radix-ui/react-toggle @radix-ui/react-toggle-group @radix-ui/react-tooltip npm error code ERESOLVE npm error ERESOLVE unable to resolve dependency tree npm error npm error While resolving: next-scrap@0.1.0 npm error Found: date-fns@4.1.0 npm error node_modules/date-fns npm error date-fns@"^4.1.0" from the root project npm error npm error Could not resolve dependency: npm error peer date-fns@"^2.28.0 || ^3.0.0" from react-day-picker@8.10.1 npm error node_modules/react-day-picker npm error react-day-picker@"8.10.1" from the root project npm error npm error Fix the upstream dependency conflict, or retry npm error this command with --force or --legacy-peer-deps npm error to accept an incorrect (and potentially broken) dependency resolution. npm error npm error `

The error is listed right there buddy 👆 
This is ancient now and shadcn has already handled this in their latest version ever since they went huge... but you've got some dependency errors that can't be aligned with updates, so you will need to either use the --flag for `--force` or `--legacy-peer-deps`

I usually opt for the latter because you can always update the older deps as they catch up

**Comment by matbrgz** [comment]
2025 update, just use:

`npx shadcn@latest add --all`

**Comment by lirena00** [comment]
about cleanup command, I don't think it's going to be implemented soon, so last week I made this tool [compadcn](https://compadcn.lirena.in)

and one of it's command is `compadcn lint` which scans your project and identifies all unused shadcn/ui components, then lets you clean them up right away. Behind the scenes, it:

- detects which components aren’t imported anywhere
- lists them in an interactive prompt
- offers to remove them for you, optionally deleting the package dependency too at the same time

pretty much the same idea as what cleanup command that you described 
would love to hear the feedback honestly speaking

![Image](https://github.com/user-attachments/assets/01cd16b2-aac4-4edc-a526-b1940975ac50)

**Comment by ArshadHannan** [comment]
Hi, a small concern, what about for custom Shadcn registry: is there a way to install all custom-built registry items at once into a new project? Any guidance or suggestions would be greatly appreciated.

**Comment by sc-ishankalakshan** [comment]
> Hi, a small concern, what about for custom Shadcn registry: is there a way to install all custom-built registry items at once into a new project? Any guidance or suggestions would be greatly appreciated.

I'm actually facing the same issue as well. Haven't found a clear solution yet.

**Comment by VNRARA** [comment]
I had to remove all the crap I had tried installing via NPM and clean up the packages.json (delete the lockfile of it) and let it rebuild.
