### ISSUE TITLE
Datepicker is overlapping navigation bar in shadcn/ui website

### ISSUE THREAD

**Issue by williamk19** [shadcn-ui/ui#2047]
Image below shows that the datepicker component is above the navigation bar which it seems like a bug. Please let me know if it was meant to be like that or this can be changed?

<img width="500" alt="Screenshot_1" src="https://github.com/shadcn-ui/ui/assets/59714670/85869168-07f5-44e9-aae0-bce55f165b51">

**Comment by onurhan1337** [comment]
Since the DatePicker component can be used in many places (forms, dialog etc.), the z-index value must be high, so it is normal for such a bug to occur. However, optionally, the value can be reduced by overriding the z-index in the example in the document.
