### ISSUE TITLE
z-index of HoverContent not working.

### ISSUE THREAD

**Issue by thangvu33** [shadcn-ui/ui#2051]
I have a ProductCard component have a position relative property and i set z-index equal 20.  Althought HoverContent have z-index equal 50 but it still under ProductCard. Can someone help me explain this?
![Screenshot 2023-12-05 184317](https://github.com/shadcn-ui/ui/assets/126962913/a493e7a6-4550-4c99-a73f-61fc09b62854)

**Comment by saniyasaher20** [comment]
Please provide the github repo link, or the source code to understand it better
