### ISSUE TITLE
support for sveltekit

### ISSUE THREAD

**Issue by Animevariant** [shadcn-ui/ui#2078]
is there any plans to support svelte/sveltekit ongoing or in the future?

**Comment by ollema** [comment]
@Animevariant see https://www.shadcn-svelte.com/

**Comment by valiantlynx** [comment]
> @Animevariant see https://www.shadcn-svelte.com/

thanks its exatly what i wanted

**Comment by matbrgz** [comment]
@valiantlynx close the issue please.
