### ISSUE TITLE
How to display the tooltip component on the right of the element?

### ISSUE THREAD

**Issue by MenaiAla** [shadcn-ui/ui#2092]
Hi @shadcn ,

I'm still new to Shadcn and I did not find on the documentation a way ( prop) to set a position for the [tooltip component](https://ui.shadcn.com/docs/components/tooltip).

In my case, I'm implementing a vertical navigation bar and I would display the tooltip when the user hovers over each icon:

![image](https://github.com/shadcn-ui/ui/assets/20143684/fc591e64-03ef-456b-b06f-af2190440c50)

As you see in the image above, the tooltip appears on the bottom.

**Comment by kasin-it** [comment]
If you want a quick fix, simply copy tooltip.tsx => tooltip-right.tsx and edit its style 
![Screenshot 2023-12-11 201558](https://github.com/shadcn-ui/ui/assets/89151689/c803b941-1091-4eef-a2d6-6623403e54c3)

**Comment by kasin-it** [comment]
![obraz](https://github.com/shadcn-ui/ui/assets/89151689/e70a550f-77c6-4212-aa2b-0bf08b0bfdeb)

**Comment by MenaiAla** [comment]
Thank you @kasin-it .
