### ISSUE TITLE
How to change the color of the Switch component when is checked/unchecked?

### ISSUE THREAD

**Issue by MenaiAla** [shadcn-ui/ui#2096]
Hi @shadcn ,

I want to use the [Switch ](https://ui.shadcn.com/docs/components/switch)component but I struggle to change the default color from black to blue-500 when the user switches it on.

![image](https://github.com/shadcn-ui/ui/assets/20143684/75ddd652-3aa1-45bf-aadd-28426be4026c)

I tried `bg-blue-500` but it does not work.

This is my code snippet:

```tsx
 <div className='flex items-center space-x-2 py-2 w-full justify-between'>
                <Label htmlFor='airplane-mode'>Mehrfamilienhaus</Label>
                <Switch
                  id='airplane-mode'
                  checked={familyHome}
                  onCheckedChange={(event) => setFamilyHome(!familyHome)}
                />
              </div>
```

**Comment by boonyarit-iamsaard** [comment]
Please check this [radix](https://www.radix-ui.com/primitives/docs/components/switch) for more details.

```jsx
<Switch className="data-[state=checked]:bg-green-500 data-[state=unchecked]:bg-red-500" />
```

**Comment by MenaiAla** [comment]
Thank you @boonyarit-iamsaard. Worked as expected <3.

**Comment by LawrenceDarko** [comment]
Thank you @boonyarit-iamsaard this worked for me

**Comment by Umutesi23** [comment]
thanks

**Comment by subhajit100** [comment]
Just an addon if you are looking to customize the shadcn switch component:- By adding different icons for **checked** and **unchecked** state inside the circular area in a **switch**. 
Pass checked and unchecked values from your component which uses Switch:-
```
<Switch
      className="data-[state=checked]:bg-green-500 data-[state=unchecked]:bg-gray-400"
      checkedIcon={<FaCheck size={12} color="green" className="ml-1 mt-1" />}  // change the icons based on your need
      uncheckedIcon={<RxCross2 size={12} color="gray" className="ml-1 mt-1" />} // all the icons are taken from **react-icons** npm library
/>
```

Change the **switch.tsx** inside **components/ui** folder , I am pasting below the whole code for switch.tsx but find out where I have added comments to know where the change is:-
```
"use client";

import * as React from "react";
import * as SwitchPrimitives from "@radix-ui/react-switch";

import { cn } from "@/lib/utils";

const Switch = React.forwardRef<
  React.ElementRef<typeof SwitchPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root> & {
    checkedIcon: React.ReactElement;   // added the types along with other types
    uncheckedIcon: React.ReactElement;
  }
>(({ className, checkedIcon, uncheckedIcon, ...props }, ref) => (   // here we have added checkedIcon and uncheckedIcon as props
  <SwitchPrimitives.Root
    className={cn(
      "peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input",
      className
    )}
    {...props}
    ref={ref}
  >
    <SwitchPrimitives.Thumb
      className={cn(
        "pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0"
      )}
    >
      {props.checked ? checkedIcon : uncheckedIcon}  // added them here, based on present state (checked or unchecked)
    </SwitchPrimitives.Thumb>
  </SwitchPrimitives.Root>
));
Switch.displayName = SwitchPrimitives.Root.displayName;

export { Switch };
```

After making all changes, it will look something like below in unchecked and checked state:-
<img width="53" alt="github_shadcn_unchecked_switch" src="https://github.com/user-attachments/assets/8da24299-35d4-4849-95c4-d2aace2f3d83">
<img width="57" alt="github_shadcn_checked_switch" src="https://github.com/user-attachments/assets/e54d43b7-a534-4936-8a41-9e06be4623da">

**Comment by Subhadeep-CS** [comment]
import * as React from "react";
import * as SwitchPrimitives from "@radix-ui/react-switch";

import { cn } from "@/lib/utils";

const Switch = React.forwardRef<
  React.ElementRef<typeof SwitchPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root> & {
    checkedIcon: React.ReactElement;
    unCheckedIcon: React.ReactElement;
  }
>(({ className, checkedIcon, unCheckedIcon, ...props }, ref) => (
  <SwitchPrimitives.Root
    className={cn(
      "peer inline-flex h-3 w-14 shrink-0 cursor-pointer rounded-lg items-center border-transparent shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input",
      className
    )}
    {...props}
    ref={ref}
  >
    <SwitchPrimitives.Thumb
      className={cn(
        "pointer-events-none block h-6 w-8 rounded-lg bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-6 data-[state=unchecked]:translate-x-0 data-[state=checked]:outline outline-2 outline-green-500"
      )}
    >
      {props.checked ? checkedIcon : unCheckedIcon}
    </SwitchPrimitives.Thumb>
  </SwitchPrimitives.Root>
));
Switch.displayName = SwitchPrimitives.Root.displayName;

export { Switch };

You can Customise from switch.tsx that's localted in inside ui I did it

**Comment by Simran-1223** [comment]
> Please check this [radix](https://www.radix-ui.com/primitives/docs/components/switch) for more details.
> 
> ```js
> <Switch className="data-[state=checked]:bg-green-500 data-[state=unchecked]:bg-red-500" />
> ```

thank you so much

**Comment by entity-framework-corebio** [comment]
@boonyarit-iamsaard https://react-beautiful-dnd4.github.io/pv0bksfnhc0lqcvTDKJ9VrVoxzmoaE4hFjMAnz_XuBaDrvk6HGUeFJMZ-Q/
