### ISSUE TITLE
button ui component should have an size variant "xl"

### ISSUE THREAD

**Issue by GauravBurande** [shadcn-ui/ui#2101]
I needed my cta button to be bigger than the shadcn UI component button size variant.

So I added my xl variant for that: 
![image](https://github.com/shadcn-ui/ui/assets/100035026/f575f985-7b97-4aa4-a3e0-b1ca67d60897)

But many people would want this.
If yes let's add some other variants to the UI components if that's what people want.

**Comment by sovetski** [comment]
I agree for adding big sizes by default, it is useful especially when we have an icon at the top and a text at the bottom of a button

**Comment by joewinke** [comment]
@GauravBurande where can I find the button sizes/variants? I don't see anything here: https://ui.shadcn.com/docs/components/button
