### ISSUE TITLE
Update Shadcn Forms to support the useFormState and useFormStatus hooks

### ISSUE THREAD

**Issue by arvind-iyer-2001** [shadcn-ui/ui#2103]
[React - useFormState](https://react.dev/reference/react-dom/hooks/useFormState)

[Next.js useFormStatus](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#pending-states)

Next.js 14 now supports the usage of the React `useFormState` and `useFormStatus` hooks.
Can the Shadcn Form Component be updated to support these changes.

**Comment by shadcn** [comment]
Yes. This is in progress. I'll share updates soon.

**Comment by SSardorf** [comment]
Why was this closed @shadcn?

**Comment by JuniorCalva40** [comment]
I'm currently working on implementing a login  However, I noticed that when I don't use the action attribute in the form element, the pending status always returns false, but I need the validations in the onSubmit ``"use client";
import { FormEvent, useState } from "react";
import {
  Button,
  ButtonLoading,
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  Input,
} from "../../ui";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Eye, EyeOff } from "lucide-react";
import Link from "next/link";
import { useFormState, useFormStatus } from "react-dom";
import { authenticate } from "@/actions";
import { toast } from "sonner";

const schema = z.object({
  email: z.string().email({ message: "Ingresa un correo válido" }),
  password: z.string().min(5, { message: "Mínimo 5 caracteres" }),
});

export const Login = () => {
  const { pending } = useFormStatus();
  const [state, dispatch] = useFormState(authenticate, undefined);
  const [eye, setEye] = useState<boolean>(false);

  const form = useForm<z.infer<typeof schema>>({
    resolver: zodResolver(schema),
    defaultValues: {
      email: "",
      password: "",
    },
  });

 

  const onSubmit = async () => {
    try {
      const formData = form.getValues();
      const formDataToSend = new FormData();
      formDataToSend.append("email", formData.email);
      formDataToSend.append("password", formData.password);
      dispatch(formDataToSend);
    } catch (error) {}
  };

  return (
    <div className="flex flex-col mx-auto h-screen max-sm:w-[30rem] px-8 min-w-96 lg:px-0 lg:w-3/6 justify-center">
      <h1 className="text-center text-3xl font-extrabold mb-8 text-gray-700">
        Inicio Sesión
      </h1>{" "}
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Correo Electrónico</FormLabel>
                <FormControl>
                  <Input
                    className="bg-white rounded-xl h-10"
                    placeholder="usuario@email.com"
                    {...field}
                  />
                </FormControl>
                <FormMessage className="text-sm font-normal" />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Contraseña</FormLabel>
                <FormControl className="relative">
                  <div className="relative">
                    <Input
                      type={eye ? "text" : "password"}
                      className="bg-white rounded-xl h-10"
                      placeholder="Mínimo 5 caracteres"
                      {...field}
                    />
                    {eye ? (
                      <Eye
                        className="absolute cursor-pointer right-1 top-2"
                        strokeWidth={1.5}
                        onClick={() => setEye(!eye)}
                      />
                    ) : (
                      <EyeOff
                        className="absolute cursor-pointer right-1 top-2"
                        strokeWidth={1.5}
                        onClick={() => setEye(!eye)}
                      />
                    )}
                  </div>
                </FormControl>
                <FormMessage className="text-sm font-normal" />
              </FormItem>
            )}
          />
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <input
                type="checkbox"
                name="remember"
                id="remember"
                className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
              />
              <label
                htmlFor="remember"
                className="ml-2 block text-sm text-[#475368]"
              >
                Recuérdamelo
              </label>
            </div>
            <div className="text-sm">
              <Link
                href="/recovery-password"
                className="font-sm text-blue-500 hover:text-blue-600"
              >
                Olvidaste tu Contraseña?
              </Link>
            </div>
          </div>

          <Button
            className="w-full rounded-xl h-10"
            type="submit"
            variant="default"
          >
            Enviar
          </Button>
        </form>
      </Form>
      <div className=" flex space-x-1 mt-4 text-center">
        <p className="text-[#475368]">No tienes cuenta?</p>
        <Link href="/auth/register" className="text-blue-500 hover:underline">
          Regístrate aquí
        </Link>
      </div>
    </div>
  );
};
``

**Comment by Jbmanllr** [comment]
Hey any updates?

**Comment by Daumas-hugo** [comment]
Hello, will there be any updates ?

**Comment by YO-SC** [comment]
👀

**Comment by santivdt** [comment]
👀 👀

**Comment by JuniorCalva40** [comment]
👀

**Comment by frdemoulin** [comment]
👀

**Comment by alpacaPwaa** [comment]
👀

**Comment by neit98** [comment]
👀

**Comment by lacymorrow** [comment]
Any updates here?

**Comment by zlenczyk** [comment]
👀

**Comment by Muneebr7** [comment]
Still not working?

**Comment by redjohnsh** [comment]
Any news here?

**Comment by lacymorrow** [comment]
Discussion here: https://github.com/shadcn-ui/ui/discussions/5332
