### ISSUE TITLE
Can dropdown menu be opended by hover?

### ISSUE THREAD

**Issue by RonAlmog** [shadcn-ui/ui#2118]
I created a user menu with the dropdown menu component. it works fine when you click on the avatar, exactly like the examples. I would love the dropdown menu to be opened when the user hovers her mouse over the avatar/button, without clicking. is there a way to do that?

**Comment by mozanyazar** [comment]
Hello👋  I think you can use  [Navigation menu](https://ui.shadcn.com/docs/components/navigation-menu) component instead of dropdown menu, you can easily customize it.

**Comment by RonAlmog** [comment]
Thanks @mozanyazar , that's one option. problem is the navigation menu has that little arrow that goes up and down. I would remove it but i need it in the menu...  other option i'm looking at is the popover, that has a big advantage: the 'open' property that can be manipulated by simple onhover method.

**Comment by kasyap-007** [comment]
you can use [Hover card](https://ui.shadcn.com/docs/components/hover-card) and change the `openDelay` and `align` - [docs](https://www.radix-ui.com/primitives/docs/components/hover-card)

**Comment by RonAlmog** [comment]
thanks everybody, good ideas. closing.

**Comment by notflip** [comment]
Isn't it strange that we have to use hacks to get a dropdown on hover working, the tooltip (hover card) is not made to be a dropdown component.

**Comment by sebruiz** [comment]
Here's a simple way to achieve this. Without modifying the Dropdown component itself.

```ts
  const [isOpen, setIsOpen] = useState(false);

  return (
    <DropdownMenu open={isOpen} onOpenChange={(isOpen) => setIsOpen(isOpen)} modal={false}>
      <DropdownMenuTrigger>
        <div onMouseEnter={() => setIsOpen(true)}>Hover Me</div>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        onMouseLeave={() => setIsOpen(false)}
        onCloseAutoFocus={(e) => {
          e.preventDefault();
        }}
      >
        Your Content
      </DropdownMenuContent>
    </DropdownMenu>
)
```

**Comment by Amaan-Uddin** [comment]
@sebruiz thanks for this awesome code workaround. Keep up the good work.
