### ISSUE TITLE
Select not styled and is broken

### ISSUE THREAD

**Issue by DaYroXy** [shadcn-ui/ui#2126]
Hello guys, i tried to copy paste the [report-an-issue](https://github.com/shadcn-ui/ui/blob/main/apps/www/app/examples/cards/components/report-an-issue.tsx) card from the examples to see if i did something wrong but it is the same

Here is how it looks for me, and if the parent of the card isnt relative when i click on the select it will just go outside of the screen
![image](https://github.com/shadcn-ui/ui/assets/62742059/9acb8a8a-12e9-4b67-9e47-95b4143a7e67)

**Comment by dan5py** [comment]
Hi @DaYroXy, can you provide a code example where the issue occurs? I just tried to copy paste it on a empty project and it works just fine.

**Comment by DaYroXy** [comment]
> Hi @DaYroXy, can you provide a code example where the issue occurs? I just tried to copy paste it on a empty project and it works just fine.

Hello! thank you for answering im not sure what the bug is exactly but if i copy paste it as it is, it will break but if i remove all the content in the file save to let nextjs error and then paste it again, somehow it will render correctly with some gui issues like the button not in the middle exactly happened to me twice weird bug not sure what causes it
