### ISSUE TITLE
Is there a way to close sheet from nested component ?

### ISSUE THREAD

**Issue by azimari-toure-ikbal** [shadcn-ui/ui#2131]
I know my title may not be self explanatory but hear me out. I'm using <Sheet> component and the <SheetContent> is my <Navbar />. In the Navbar I have my actual <nav> and <NavLink> <NavItem /> </NavLink> component. Is there a way for me to have the sheet closed whenever i click on any <NavItem /> ?

<img width="667" alt="image" src="https://github.com/shadcn-ui/ui/assets/119160287/87f94c84-3c01-4259-a4dc-080038901e92">

<img width="586" alt="image" src="https://github.com/shadcn-ui/ui/assets/119160287/a2072bf5-bffe-46d0-b6f1-b0df7de29dab">

<img width="524" alt="image" src="https://github.com/shadcn-ui/ui/assets/119160287/a773607d-788f-4729-987d-ec37c29a2964">

**Comment by DenserMeerkat** [comment]
```jsx
import { useState } from "react";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";

export function SheetDemo() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <Sheet open={isOpen} onOpenChange={setIsOpen}>
      <SheetTrigger asChild>
        <Button variant="outline">Open</Button>
      </SheetTrigger>
      <SheetContent>
        ...
        <YourComponent onOpenChange={setIsOpen} />
      </SheetContent>
    </Sheet>
  );
}

const YourComponent = ({ onOpenChange }) => {
  return (
    <div>
      <Button onClick={() => onOpenChange(false)}>Close</Button>
    </div>
  );
};
```

Sheet also uses the Dialog Primitive of Radix
so declare a useState variable and pass the props down to children

For more reference check [Radix Dialog's API Reference](https://www.radix-ui.com/primitives/docs/components/dialog#api-reference)

**Comment by azimari-toure-ikbal** [comment]
Not all heroes wear capes. Thanks i'll try it asap!
