### ISSUE TITLE
Using a component that removes the scroll bar collides with using `overflow-y: scroll`

### ISSUE THREAD

**Issue by leonlarsson** [shadcn-ui/ui#2132]
I have `overflow-y: scroll` to always display a scroll bar to avoid flickering when it appears and disappears.

Using components like selects and dropdowns causes weird behaviour.
Opening the dropdown does not remove the scroll bar but adds extra space to compensate for the (not removed) scroll bar.

Scroll bar is there:
![2023-12-19_20-56-03](https://github.com/shadcn-ui/ui/assets/54620188/254cbe78-70f1-44bf-bf5f-e7ae06e2a09e)

Dropdown is open, but the scrollbar is still there, and extra space has been added:
![2023-12-19_20-56-14](https://github.com/shadcn-ui/ui/assets/54620188/384a2c1c-29c4-46af-9863-16025b66d995)

To test this yourself, go to https://the-finals-leaderboard.com/ and open a dropdown.

**Comment by leonlarsson** [comment]
Fixed by replacing `html { overflow-y: scroll; }` with `body { overflow-y: scroll; }`.

**Comment by LZYLRRY** [comment]
This fixed the problem. Thanks 🙏
