### ISSUE TITLE
How to customize background color of toast component

### ISSUE THREAD

**Issue by tjhoo** [shadcn-ui/ui#2157]
Hi,

From [the documentation](https://ui.shadcn.com/docs/components/toast#destructive), there is a `destructive` variant that will render the toast in red background,
```javascript
toast({
  variant: "destructive",
  title: "Uh oh! Something went wrong.",
  description: "There was a problem with your request.",
})
```
May I know what are the other supported variants, and how can we customize the background color of the toast?

**Comment by jrTilak** [comment]
Navigate to `ui/toast.tsx`, 

there you will find _toast variants_ defined with their respective classnames probably at line 25, there you can define your own variants as much you want.

```javascript
const toastVariants = cva(
  'group pointer-events-auto relative flex w-full items-center justify-between space-x-4 overflow-hidden rounded-md border p-6 pr-8 shadow-lg transition-all data-[swipe=cancel]:translate-x-0 data-[swipe=end]:translate-x-[var(--radix-toast-swipe-end-x)] data-[swipe=move]:translate-x-[var(--radix-toast-swipe-move-x)] data-[swipe=move]:transition-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[swipe=end]:animate-out data-[state=closed]:fade-out-80 data-[state=closed]:slide-out-to-right-full data-[state=open]:slide-in-from-top-full data-[state=open]:sm:slide-in-from-bottom-full',
  {
    variants: {
      variant: {
        default: 'border bg-background text-foreground',
        destructive: 'destructive group border-destructive bg-destructive text-destructive-foreground',
        newVariant: 'bg-black-500 text-primary' //add your variants here
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  },
)
```
_You can modify any components installed to control the style and structure as much you want._

**Comment by tjhoo** [comment]
Thanks @jrTilak for your response.

Instead of modifying the default component, I found out we can actually pass in `className` to override the styles like this,
```javascript
toast({
  variant: "destructive",
  className: "bg-black",
});
```

**Comment by jrTilak** [comment]
Yeah definitely you can do that but like to reuse the classes, I think it is better to modify the components by add a new variant. For example if you want a toast for warning, instead of passing the classNames everytime, you can reuse by creating a new warning variant directly.🤠
