### ISSUE TITLE
npx shadcn-ui@latest init gives an error in react project

### ISSUE THREAD

**Issue by giorgimamardashvili** [shadcn-ui/ui#2161]
While using npx shadcn-ui@latest comand in react project, it gives an error:
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path C:\Users\OverLord\AppData\Roaming\npm
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat 'C:\Users\OverLord\AppData\Roaming\npm'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\OverLord\AppData\Local\npm-cache\_logs\2023-12-23T15_42_05_669Z-debug-0.log

node version is  v20.9.0

**Comment by jrTilak** [comment]
Maybe these helps:
- https://stackoverflow.com/questions/49620780/cant-install-any-npm-package-error-4058
- https://github.com/npm/npm/issues/17444#issuecomment-393761515

**Comment by giorgimamardashvili** [comment]
@jrTilak Thank you, updating npm helped
