### ISSUE TITLE
The carousel opts property has any type :confused:

### ISSUE THREAD

**Issue by JheanAntunes** [shadcn-ui/ui#2172]
# What can I do to resolve :flushed: ?
Hello, shadcn - ui :heart_eyes:

![Error types no contexto](https://github.com/shadcn-ui/ui/assets/120582814/14670b67-8b44-4c0e-bc91-2ddafb283408)
![DemoCarouselOpts](https://github.com/shadcn-ui/ui/assets/120582814/cc33ce02-21f0-4576-9d7b-7e0bcb14e47b)

## Solutions :nerd_face:
I modified the code to resolve this issue, but could this modification cause a bug? 
code below:

01: simpler :sunglasses:
path: node_modules > embla-carousel-react > esm > index.d.ts
> It's easier to click on the component that imports the carousel
 '@/components/ui/carousel' and click 'embla-carousel-react' that you will find this module.

![modificação-simple](https://github.com/shadcn-ui/ui/assets/120582814/a447be16-dde4-4ece-ad12-44056ed4b2eb)

apparently it's working !!! :exploding_head:
 
![funciono-simple](https://github.com/shadcn-ui/ui/assets/120582814/e65db858-a88e-42d9-8f40-c990c9f54310)
![component-funciono-simple](https://github.com/shadcn-ui/ui/assets/120582814/0021be77-49d5-442c-8151-a3c35a03ec18)

02:   Import directly from the embla-carousel module, perhaps from 'embla-carousel-react' :nerd_face:
![soluction-02](https://github.com/shadcn-ui/ui/assets/120582814/96b5994a-5ed4-4ed3-b70e-681156fe7d52)

03: without any modification :smiley:
![soluction-03](https://github.com/shadcn-ui/ui/assets/120582814/3190907a-3400-48a0-b9f3-581405cc70de)

**Comment by davidjerleke** [comment]
Hi @JheanAntunes and shadcn-ui maintainers, I’m the creator/maintainer of Embla Carousel,

[This is how](https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239) you solve the problem mentioned in this bug report.

Additionally, I would like to [recommend this](https://github.com/shadcn-ui/ui/discussions/2146#discussion-5990046). 

Thank you for your time!

Best,
David

**Comment by JheanAntunes** [comment]
Thanks for your attention 😱and thanks for creating the carousel component🤩😎, I really liked it.🥰😍🤩

**Comment by JheanAntunes** [comment]
Thanks for your attention, David 😍 and the carousel component is cool, I liked it 😎
