### ISSUE TITLE
How to disable the autofocus in Sheet component?

### ISSUE THREAD

**Issue by MenaiAla** [shadcn-ui/ui#2181]
Hi @shadcn ,

Today, I used the Sheet component, however I noticed that the first component I put inside the content it's auto-focused:

![image](https://github.com/shadcn-ui/ui/assets/20143684/1c0b2f85-2b47-4fa0-a2fd-2b327d91b13a)

Even in the [examples](https://ui.shadcn.com/docs/components/sheet) in the documentation,  I noticed that the form you used it's auto-focused, however I would not this feature in my case.

![image](https://github.com/shadcn-ui/ui/assets/20143684/ec075628-76f1-4355-9d2b-d969d3b3985f)

How to prevent the autofocus in Sheet?

**Comment by iShafi24** [comment]
You should add `onOpenAutoFocus={(e) => e.preventDefault()}` 
may be it will solve this issue

**Comment by MenaiAla** [comment]
I resolved the problem by adding an empty span with tabIndex=0, but your answers provide a better solution. Thank you guys <3.

**Comment by doldsimo** [comment]
@MenaiAla thanks for the hint. I used your soluition because I use the sheet component on the server side and there we cannot use onOpenAutoFocus.

**Comment by dninomiya** [comment]
I solved it this way.

```tsx
<SheetPrimitive.Close
  autoFocus // added
  className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-secondary"
>
  <X className="h-4 w-4" />
  <span className="sr-only">Close</span>
</SheetPrimitive.Close>
```

**Comment by SadmanYasar** [comment]
> I solved it this way.
> 
> <SheetPrimitive.Close
>   autoFocus // added
>   className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-secondary"
> >
>   <X className="h-4 w-4" />
>   <span className="sr-only">Close</span>
> </SheetPrimitive.Close>

This is working with MultipleSelector component as well. Thanks!
