### ISSUE TITLE
Resizeble Panel unable to set cookie for onCollapse

### ISSUE THREAD

**Issue by step2341** [shadcn-ui/ui#2206]
using something like the below with a ResizeablePanel:

` onCollapse={(collapsed: boolean) => {
            setIsCollapsed(collapsed)
            document.cookie = react-resizable-panels:collapsed=${JSON.stringify(
              collapsed
            )}
          }}`

i get this error: 

Type '(collapsed: boolean) => any' is not assignable to type 'PanelOnCollapse'.
  Target signature provides too few arguments. Expected 1 or more, but got 0.ts(2322)
Panel.d.ts(62, 5): The expected type comes from property 'onCollapse' which is declared here on type 'IntrinsicAttributes & Omit<HTMLAttributes<ElementType>, "id" | "onResize"> & { className?: string | undefined; ... 11 more ...; tagName?: ElementType | undefined; } & { ...; } & RefAttributes<...>'
(property) onCollapse?: PanelOnCollapse | undefined

i upgraded to the panels to 1.0.5 and have the same issue. I noticed in Shadcn's mail example he is doing something similar without issue? how are we supposed to correctly call the onCollapse handler?

**Comment by rishabhbizzle** [comment]
`onCollapse={(collapsed) => {
            setIsCollapsed(collapsed)
            document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(
              collapsed
      )}`
 }}`
 
 This is the correct way.

**Comment by rishabhbizzle** [comment]
``` onCollapse={(collapsed) => {
            setIsCollapsed(collapsed)
            document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(
              collapsed
            )}`
          }} ```
 
 This is the correct way.

**Comment by rishabhbizzle** [comment]
```javascript
onCollapse={(collapsed) => {
            setIsCollapsed(collapsed)
            document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(
              collapsed
       )}`
}}
```
This is the correct way.

**Comment by step2341** [comment]
@rishabhbizzle thanks for the quick reply. if i do the above i receive a type error and it still doesnt work..  

Type '(collapsed: any) => void' is not assignable to type 'PanelOnCollapse'.
  Target signature provides too few arguments. Expected 1 or more, but got 0.ts(2322)
Panel.d.ts(62, 5): The expected type comes from property 'onCollapse' which is declared here on type 'IntrinsicAttributes & Omit<HTMLAttributes<ElementType>, "id" | "onResize"> & { className?: string | undefined; ... 11 more ...; tagName?: ElementType | undefined; } & { ...; } & RefAttributes<...>'

**Comment by Koning3ton** [comment]
Either use the same version of `react-resizable-panels` as shadcn  used (`0.0.55`) or keep track of the state:
```js
onCollapse={() => {
  setIsCollapsed(true)
  document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(true)}`
}}
onExpand={() => {
  setIsCollapsed(false)
  document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(false)}`
}}
```
This should resolve the issue when using newer versions of `react-resizable-panels`.

**Comment by IannGeorges** [comment]
> Either use the same version of `react-resizable-panels` as shadcn used (`0.0.55`) or keep track of the state:
> 
> ```js
> onCollapse={() => {
>   setIsCollapsed(true)
>   document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(true)}`
> }}
> onExpand={() => {
>   setIsCollapsed(false)
>   document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(false)}`
> }}
> ```
> 
> This should resolve the issue when using newer versions of `react-resizable-panels`.

Thank you so much, this works! Was looking tirelessly to find a fix for this cookie issue

**Comment by yangfuzhang** [comment]
> Either use the same version of `react-resizable-panels` as shadcn used (`0.0.55`) or keep track of the state:
> 
> ```js
> onCollapse={() => {
>   setIsCollapsed(true)
>   document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(true)}`
> }}
> onExpand={() => {
>   setIsCollapsed(false)
>   document.cookie = `react-resizable-panels:collapsed=${JSON.stringify(false)}`
> }}
> ```
> 
> This should resolve the issue when using newer versions of `react-resizable-panels`.

This saves my day. Thank you! The document is not up to date. I'm using 1.0.5.

**Comment by Koning3ton** [comment]
For completeness: question was also answered here: https://github.com/bvaughn/react-resizable-panels/issues/245#issuecomment-1870077729

**Comment by BadisKefi** [comment]
``thanks that worked , but for those who got this error because of the "mail template" from the shadcn repository , they may need to take another step :
if error here : 

`const defaultCollapsed = collapsed ? JSON.parse(collapsed.value) : undefined;
`
then most likely the default collapsed.value === undefined
so do a manuel sheck :

```
const collapsed = cookies().get("react-resizable-panels:collapsed");
let defaultCollapsed = null;
if (collapsed?.value === undefined) {
  defaultCollapsed = false;
}
defaultCollapsed = collapsed ? JSON.parse(collapsed.value) : undefined;
```

**Comment by khoohz** [comment]
> ```tsx
> const defaultCollapsed = collapsed ? JSON.parse(collapsed.value) : undefined;
> ```

hey @rickymm, your simplified solution doesn't work for me, just showing my way as reference 
`  const defaultCollapsed = (collapsed.value != 'undefined' ? JSON.parse(collapsed.value) : undefined) ?? false;
`
