### ISSUE TITLE
Hydration failed for Pagination Components

### ISSUE THREAD

**Issue by Jahid-Unlock** [shadcn-ui/ui#2207]
Newly introduced Pagination showing Hydration failed in NextJS 14. 

`Component Stack
li
li
ul
nav
div
div
div
main`

it's rendering  `li` elements twice, I think it causing the error.

**Comment by sample-tayo** [comment]
I have the same error. 
![image](https://github.com/shadcn-ui/ui/assets/103777801/3503c8a5-bc9c-4a08-a404-b272ab6b887c)

**Comment by dayongkr** [comment]
```
```

```
const PaginationLink = ({
  className,
  isActive,
  size = 'icon',
  ...props
}: PaginationLinkProps) => (
  <PaginationItem>
    <a
      aria-current={isActive ? 'page' : undefined}
      className={cn(
        buttonVariants({
          variant: isActive ? 'outline' : 'ghost',
          size
        }),
        className
      )}
      {...props}
    />
  </PaginationItem>
)
```

**Comment by sample-tayo** [comment]
> ```js
> <Pagination>
>         <PaginationContent>
>           <PaginationLink href="#" isActive>
>             1
>           </PaginationLink>
>           <PaginationLink href="#">2</PaginationLink>
>           <PaginationLink href="#">3</PaginationLink>
>         </PaginationContent>
> </Pagination>
> ```
> 
> You have to write like this.
> 
> ```js
> // pagination.tsx
> const PaginationLink = ({
>   className,
>   isActive,
>   size = 'icon',
>   ...props
> }: PaginationLinkProps) => (
>   <PaginationItem>
>     <a
>       aria-current={isActive ? 'page' : undefined}
>       className={cn(
>         buttonVariants({
>           variant: isActive ? 'outline' : 'ghost',
>           size
>         }),
>         className
>       )}
>       {...props}
>     />
>   </PaginationItem>
> )
> ```
> 
> Because `PaginationLink` component was wrapped by `PaginationItem` Component (this Component is li element). 

Thank you, worked.

**Comment by TakuSemba** [comment]
I think the documentation can be updated on this. The code snippet uses `</PaginationItem>` which leads to this issue

https://ui.shadcn.com/docs/components/pagination

![Screenshot 2024-01-09 at 13 35 58](https://github.com/shadcn-ui/ui/assets/13956869/d56f18da-a8f3-40b0-a0f7-6ee9446640e0)
