### ISSUE TITLE
Query Regarding cursor-default Style in Dropdown UI Component

### ISSUE THREAD

**Issue by chuanxshi** [shadcn-ui/ui#2212]
I am reaching out to inquire about a specific styling choice in the dropdown UI component. I noticed that the cursor is explicitly set to `cursor-default`. This seems somewhat unusual, as conventionally dropdown elements typically use `cursor-pointer` to signify an interactive element.

Is there a specific rationale or design consideration behind using cursor-default instead of cursor-pointer?

Would it be more intuitive to switch to cursor-pointer to align with standard UI practices for dropdown elements, or is there a particular scenario where cursor-default enhances user experience?

I would appreciate any insights or explanations regarding this design choice. If a change to cursor-pointer is deemed beneficial, I am more than willing to contribute with a pull request.

**Comment by abdulbasithqb** [comment]
Agree, i feel the same, i just looked into some other component library, in all the case by default menu item is cursor-pointer

**Comment by shadcn** [comment]
The type of cursor used is about affordance, in this instance, the clickability of an element. 

Buttons (* see note below) and dropdown menu have high affordance so you generally don't need a `cursor-pointer` to indicate they are clickable. 

However, there's no agreed upon standard for this. Some prefer to always use `cursor-pointer` on clickable elements.

* Note: the pointer cursor for buttons are coming from Tailwind's reset which sets `cursor: inherit` on all buttons. See https://github.com/tailwindlabs/tailwindcss/blob/fb1743b4b028323d83f5b5f9866ec0f6595fe08c/src/css/preflight.css#L339

Hope this is helpful.

**Comment by kachkaev** [comment]
Just did a bit of research on cursor pointer vs default for interactive elements. Looks like Tailwind v4 will stop adding `cursor-pointer` to buttons: https://github.com/tailwindlabs/tailwindcss/issues/8961

Also found this:

> [Microsoft’s design guides](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742466%28v=vs.85%29.aspx) talk about weak affordance:
>
> Text and graphics links use a hand […] pointer […] because of their weak affordance. While links may have other visual clues to indicate that they are links (such as underlines and special placement), displaying the hand pointer on hover is the definitive indication of a link. To avoid confusion, it is imperative not to use the hand pointer for other purposes. For example, command buttons already have a strong affordance, so they don’t need a hand pointer. The hand pointer must mean “this target is a link” and nothing else.
>
> [Apple’s Human Interface Guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Pointers.html) states that the hand cursor should be used when “the content is a URL link”.
>
> [W3C User Interface guidelines](https://www.w3.org/TR/CSS21/ui.html#propdef-cursor) says the same thing again with “The cursor is a pointer that indicates a link”.
>
> From ["Buttons shouldn’t have a hand cursor" by Adam Silver](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b#.b33l7fivt)

[Source](https://github.com/tailwindlabs/tailwindcss/issues/8961#issuecomment-1533249212)

**Comment by daveycodez** [comment]
Is there an easy way via CSS to add cursor pointer to all interactive elements. I'm using this for buttons

```css
/*
Set the default cursor for buttons.
*/
button,
[role="button"] {
    cursor: pointer;
}

/*
Make sure disabled buttons don't get the pointer cursor.
*/
:disabled {
    cursor: default;
}
```

I will die on this hill, pointers are amazing for knowing what's clickable.
