### ISSUE TITLE
The inferred type of 'Command' cannot be named without a reference to `'.pnpm/@types+react@18.2.37/node_modules/@types/react'`.

### ISSUE THREAD

**Issue by sebiweise** [shadcn-ui/ui#2217]
I´m getting a strange error using the Command component any ideas on this one?

The inferred type of 'Command' cannot be named without a reference to `'.pnpm/@types+react@18.2.37/node_modules/@types/react'`.

![image](https://github.com/shadcn-ui/ui/assets/22999200/c642d28a-4b54-4573-ba8e-2a65a6bbe9ec)

The error is showing on const Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandSeparator and CommandItem.

**Comment by dan5py** [comment]
Hi @sebiweise, there's an issue in the Microsoft Typescript repo related to this error: https://github.com/microsoft/TypeScript/issues/42873

I hope it helps.

**Comment by sebiweise** [comment]
Perfekt thank you, worked for me.

**Comment by imranjami** [comment]
@sebiweise mind sharing what fix you used from the repo for this?

**Comment by andymerskin** [comment]
> @sebiweise mind sharing what fix you used from the repo for this?

Here's a oft-cited workaround reply in the thread. Unfortunately very buried in the hundreds of comments! I'm currently trying to solve for this and about to see what works, myself.

https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1519138189
