### ISSUE TITLE
Open Dialog implies go to top

### ISSUE THREAD

**Issue by ivansevillaa** [shadcn-ui/ui#2225]
Hello!

I'm using Dialog component. But if you have to scroll to get the trigger, then when you click the button the Dialog is opened, that's OK.

My problem is that scroll me to the top of the page, and then when I close the diolog, scroll me to the previous position. Exist a way to mantain the scroll position when I click the trigger?

**Comment by natac13** [comment]
I had a similar issue just now. And I was able to figure out that it was due to my use of  `height: 100%` on the `body` element. As soon as I changed to `min-height: 100%` it worked as expected.
