### ISSUE TITLE
Type error when I build with resizable

### ISSUE THREAD

**Issue by rhs419** [shadcn-ui/ui#2271]
Type error when I build with resizable in NextJs
I didnt edit anything

![image](https://github.com/shadcn-ui/ui/assets/73884732/0d2a61d1-07b3-4a23-956c-1f090080b16d)

**Comment by efleury1** [comment]
@rhs419 Curious to know, how did you resolve this? Getting the same issue, and forcing version on 1.0.5 seems to fix it.

**Comment by rhs419** [comment]
@efleury1 we solved it by upgrading typescript version 4.95 to 5.0.0. sorry for rate checking
