### ISSUE TITLE
Tooltip suggestion , 

### ISSUE THREAD

**Issue by Ekefrancisokechukwu** [shadcn-ui/ui#2275]
Tooltip should have a placement option , whether to be on the  top, left, right or bottom . thank you

**Comment by jrTilak** [comment]
Hey @Ekefrancisokechukwu  Thanks for your valuable suggestion. But actually, we can already give the placement position value to the tooltip using `side` prop in `TooltipContent` component as shown below:

```typescript
<TooltipProvider>
        <Tooltip>
          <TooltipTrigger>Hover</TooltipTrigger>
          <TooltipContent side="left">  //"top" | "right" | "bottom" | "left"
            <p>Add to library</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
```
For detailed api references for Tooltip, you can check [here](https://www.radix-ui.com/primitives/docs/components/tooltip#content)
  
Thank you! ❤️

**Comment by Ekefrancisokechukwu** [comment]
> Hey @Ekefrancisokechukwu Thanks for your valuable suggestion. But actually, we can already give the placement position value to the tooltip using `side` prop in `TooltipContent` component as shown below:
> 
> ```ts
> <TooltipProvider>
>     <Tooltip>
>         <TooltipTrigger>Hover</TooltipTrigger>
>         <TooltipContent side="left">  //"top" | "right" | "bottom" | "left"
>              <p>Add to library</p>
>          </TooltipContent>
>       </Tooltip>
> </TooltipProvider>
> ```
> 
> For detailed api references for Tooltip, you can check [here](https://www.radix-ui.com/primitives/docs/components/tooltip#content)
> 
> Thank you! ❤️

Alright thank you so much

**Comment by koradiyayash26** [comment]
not work z-index,back ground elemnt show on front ,

**Comment by allenlinsh** [comment]
> I have solved this z-index issue with css: `[data-radix-popper-content-wrapper] { z-index: 1000 !important; }`

this worked for me!
