### ISSUE TITLE
Issue with PopoverTrigger

### ISSUE THREAD

**Issue by ddacot** [shadcn-ui/ui#2301]
Hi,

The example on https://ui.shadcn.com/docs/components/popover says we can use the _**\<PopoverTrigger\>**_ component with the _**asChild**_ prop as such:

`<PopoverTrigger asChild>
        <Button variant="outline">Open popover</Button>
      </PopoverTrigger>`

However, when I do so, I get the following error: 

<img width="898" alt="image" src="https://github.com/shadcn-ui/ui/assets/1522615/6e1c0152-fc5b-43ed-964e-be708d1f6e5d">

**Comment by quyettranvu** [comment]
Hello, I also applied the Popover Trigger in my codes and no issues encountered, can you upload how you applied your code?
Here is how I applied:
![image](https://github.com/shadcn-ui/ui/assets/79063319/16374ec3-e6ad-4989-8856-3af6e0c15049)

**Comment by shadcn** [comment]
@ddacot Can you share the code please?

**Comment by ddacot** [comment]
@shadcn and @quyettranvu apologize for the delay. 

What I am trying to achieve is to wrap a `<ContentEditable>` component with the `<PopoverTrigger>` component. Something like this: 
```
<PopoverTrigger asChild>
    <ContentEditable>
</PopoverTrigger>
```

My ContentEditable Component is implemented as such:

```
export function ContentEditable({
  className,
  id,
  style,
  tabIndex,
  ...rest
}: Props): JSX.Element {

   ...

  const ref = useCallback(
    (rootDiv: null | HTMLElement) => {
      setRootDiv(rootDiv);
    },
    [...],
  );

  return (
    <div
      {...rest}
      className={className}
      contentEditable={isEditable}
      id={id}
      ref={ref}  < ------- (1) 
      style={style}
      tabIndex={tabIndex}
    />
  );
}
```

Perhaps my issue is that I'm overriding the ref in (1) and I am trying to figure out a way to fix that. However, in another instance, where I tried to use the Tabs component, this code was working just fine: TabsTrigger would pass down all the props to ContentEditable AND the somehow got a hold of the ref of the div in ContentEditable, since I was able to switch tabs with no issue (perhaps walking thru the dom with a query selector or something): 

```
<TabsTrigger asChild>
    <ContentEditable>
</TabsTrigger>
```

What I've tried since posting the initial comment is modifying the PopoverTrigger component as such:

```
const PopoverTrigger = React.forwardRef<
  React.ElementRef<typeof PopoverPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof PopoverPrimitive.Trigger>
>(({ className, ...props }, ref) => (
  <PopoverPrimitive.Trigger
    ref={ref}
    className={cn("", className)}
    {...props}
  />
))
PopoverTrigger.displayName = PopoverPrimitive.Trigger.displayName

```

This got rid of the error message in my initial post, however the content doesn't pop up when I click on the Trigger. Perhaps this is an issue with my implementation, and now with how shadcn abstracts the radix components. 

fyi, I am a newbie in React, so I might have no clue what I am doing. And thanks for putting together this great library of components btw. Looks sick.
