### ISSUE TITLE
simpler InputProps

### ISSUE THREAD

**Issue by Vandivier** [shadcn-ui/ui#2316]
```
export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {}
```

in the current codebase can be simplified to
```
export type InputProps = React.InputHTMLAttributes<HTMLInputElement>
```

this change also fixes a lint error native to the t3 stack

**Comment by tanish-malekar** [comment]
Hi, I would like to pick up this issue.

**Comment by tanish-malekar** [comment]
#2320 Created a PR for the same

**Comment by dan5py** [comment]
https://github.com/shadcn-ui/ui/pull/2320#issuecomment-1887558886
