### ISSUE TITLE
Prevent AlertDialogAction button from closing the alert dialog

### ISSUE THREAD

**Issue by Iliannnn** [shadcn-ui/ui#2321]
Hey, I was questioning how I can prevent the AlertDialogAction button from closing the alert dialog when clicked. Thank you for the help in advance

**Comment by Miguerfi** [comment]
any solution?

**Comment by Iliannnn** [comment]
> any solution?

Yes, I found a solution. Basically you have to make the AlertDialogAction element hidden and give it an id. Then, you make a normal button with an onClick event, in that onClick you validate whether you want to close the dialog, if yes emit a click to the AlertDialogAction button using the id.

**Comment by ashutosh44ks-oodles** [comment]
I think this works fine as well. This is a react example but i think it's pretty readable

```
<AlertDialogAction asChild>
    <Button
        onClick={(e) => {
            e.preventDefault();
            // your function
            cancelRef.current.click();
        }}
        >
            {actionText}
    </Button>
</AlertDialogAction>
```
