### ISSUE TITLE
closeButton prop not working in Sonner

### ISSUE THREAD

**Issue by shrihari-prakash** [shadcn-ui/ui#2340]
Looks like adding the `closeButton` prop in Sonner component does not add anything at all. See a demo here:

https://github.com/shadcn-ui/ui/assets/35889246/cdf1a85c-d262-47b5-9d90-cddd184fb7a9

Same result on adding prop as `closeButton={true}` also

**Comment by MenaiAla** [comment]
I tried adding the prop and it's appeared :

![image](https://github.com/shadcn-ui/ui/assets/20143684/fd52dab0-7ab4-4b1b-ab4f-af1e571631d1)

## Code

```tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster closeButton />
      </body>
    </html>
  );
}

```

**Comment by shrihari-prakash** [comment]
@MenaiAla I just realized the close button appears only on hover :). Weird that the documentation of Sonner makes it look like the close button is there always. And in some cases, the hover does not work if there is a sheet UI. I guess it's a problem of Z index.

**Comment by MenaiAla** [comment]
> @MenaiAla I just realized the close button appears only on hover :). Weird that the documentation of Sonner makes it look like the close button is there always. And in some cases, the hover does not work if there is a sheet UI. I guess it's a problem of the Z index.

Yes, I expect that the independent components ( Modal, Dialog, Sheet ) have different Z-index values.
