### ISSUE TITLE
import { useMediaQuery } from "@/hooks/use-media-query" can't be found

### ISSUE THREAD

**Issue by NicoCaldo** [shadcn-ui/ui#2344]
I'm trying to follow this example [Drawer](https://ui.shadcn.com/docs/components/drawer) but when I add to my code

```
import { useMediaQuery } from "@/hooks/use-media-query"

const isDesktop = useMediaQuery("(min-width: 768px)")
```

I'm seeing the error that `use-media-query` can't be found

**Comment by dan5py** [comment]
Hi @NicoCaldo, the `use-media-query` doesn't come with the Drawer. However you can get it from the source code.
I'll it here just in case:
```tsx
import * as React from "react"

export function useMediaQuery(query: string) {
  const [value, setValue] = React.useState(false)

  React.useEffect(() => {
    function onChange(event: MediaQueryListEvent) {
      setValue(event.matches)
    }

    const result = matchMedia(query)
    result.addEventListener("change", onChange)
    setValue(result.matches)

    return () => result.removeEventListener("change", onChange)
  }, [query])

  return value
}
```

You can copy this and save it in the `hooks/use-media-query.tsx` file.

**Comment by NicoCaldo** [comment]
Thanks

**Comment by sandervspl** [comment]
Could this maybe be included in the docs? Would be much better than having to look around in the source code (or in my case, Google) :)

**Comment by lemmenri** [comment]
Explanation is missing from https://ui.shadcn.com/docs/components/combobox#responsive as well.
