### ISSUE TITLE
Skeleton component doesn't appear

### ISSUE THREAD

**Issue by hamza-ouaddi** [shadcn-ui/ui#2351]
The Skeleton component doesn't appear unless a background color is explicitly added to it. 

In the docs, it's mentioned that you can use it like this:
`<Skeleton className="w-[100px] h-[20px] rounded-full" />
`

but for me, I have to add bg-color to it
`<Skeleton className="w-[100px] h-[20px] rounded-full bg-gray-400" />
`
I don't know if there is a problem with it, or I should have done it like that from the beginning.

**Comment by V-Mokhun** [comment]
The Skeleton component itself has a bg-muted class, so I reckon either: 
a) You don't have a --muted variable in your css file
b) the --muted variable blends in with the surroundings

Could you check that?

**Comment by hamza-ouaddi** [comment]
> The Skeleton component itself has a bg-muted class, so I reckon either: a) You don't have a --muted variable in your css file b) the --muted variable blends in with the surroundings
> 
> Could you check that?

That's true, I have already deleted the tailwind.config.css that was generated by shadcn ui because I had my own config, and now I reinstalled it and made sure i have both shadcn config with my own one, and it's working fine.
Thank you!

**Comment by hamza-ouaddi** [comment]
> The Skeleton component itself has a bg-muted class, so I reckon either: a) You don't have a --muted variable in your css file b) the --muted variable blends in with the surroundings
> 
> Could you check that?

That's true, I have already deleted the tailwind.config.css that was generated by shadcn ui because I had my own config, and now I reinstalled it and made sure i have both shadcn config with my own one, and it's working fine.
Thank you!

**Comment by YoavG13** [comment]
I had the same issue: I removed the yes prefix and forgot to update the attributes. Thanks!
