### ISSUE TITLE
problem with form onSubmit

### ISSUE THREAD

**Issue by cblberlin** [shadcn-ui/ui#2371]
hi everyone, i'm writing a from which is multi-entries form, but after submit, it return an object not an array

the console.log show me the submit value as an object:
```
{
  {
    "school": "University A",
    "major": "Computer Science",
    "degree": "Bachelor's",
    "startdate": "2020-09-01",
    "enddate": "2024-06-01",
    "isCurrent": false
  },
  {
    "school": "University B",
    "major": "Graphic Design",
    "degree": "Master's",
    "startdate": "2025-09-01",
    "enddate": "2027-06-01",
    "isCurrent": false
  }
}

```
but it expect the output as an array otherwise it won't pass the validation:
```
[
  {
    "school": "University A",
    "major": "Computer Science",
    "degree": "Bachelor's",
    "startdate": "2020-09-01",
    "enddate": "2024-06-01",
    "isCurrent": false
  },
  {
    "school": "University B",
    "major": "Graphic Design",
    "degree": "Master's",
    "startdate": "2025-09-01",
    "enddate": "2027-06-01",
    "isCurrent": false
  }
]

```

here is my schema:
```
import * as z from "zod"

export const educationEntrySchema = z.object({
  school: z.string().min(2, {
    message: "please enter a valid school name.",
  }),
  major: z.string().min(2, {
    message: "please enter a valid major.",
  }),
  degree: z.string().min(2, {
    message: "please enter a valid degree.",
  }),
  startdate: z.coerce.date({
    errorMap: (issue, {defaultError}) => ({
      message: issue.code === "invalid_date" ? "please select a valid start day" : defaultError,
    }),
  }),
  isCurrent: z.boolean().optional(),
  enddate: z.coerce.date({
    errorMap: (issue, {defaultError}) => ({
      message: issue.code === "invalid_date" ? "please select a valid end day" : defaultError,
    }),
  }).optional(),
});

export type educationEntry = z.infer<typeof educationEntrySchema>;

export const educationschema = z.array(educationEntrySchema);
```

and here is the form:
```
"use client"

import React, { useState } from "react"

import { cn } from "@/lib/utils"
import { format } from "date-fns"

import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import * as z from "zod"

import { Button } from "@/components/ui/button"
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover"
import { Input } from "@/components/ui/input"
import { useToast } from "@/components/ui/use-toast"

import { Calendar } from "@/components/ui/calendar"
import { Checkbox } from "@/components/ui/checkbox"

import { CalendarIcon } from "lucide-react"
import { educationschema, educationEntry } from "./validators/education-schema"

export function Education() {
  const { toast } = useToast();

  // set education
  const [educations, setEducations] = useState<educationEntry[]>(
    [
      {
        school: "",
        major: "",
        degree: "",
        startdate: new Date(),
        enddate: new Date(),
        isCurrent: false,
      },
    ]
  );

  const currentYear = new Date().getFullYear()

  // 1. Define your form.
  const form = useForm<z.infer<typeof educationschema>>({
    resolver: zodResolver(educationschema),
    defaultValues: [
      {
        school: "",
        major: "",
        degree: "",
        startdate: new Date(),
        enddate: new Date(),
        isCurrent: false,
      },
    ],
  })
 
  // 2. Define a submit handler.
  function onSubmit(values: z.infer<typeof educationschema>) {
    console.log("submited values: ", form.getValues());
    toast({
      title: "You submitted the following values:",
      description: (
        <p className="mt-2 w-[340px] rounded-md bg-slate-950 p-4">
          <code className="text-white">{JSON.stringify(values, null, 2)}</code>
        </p>
      ),
    })
    console.log(values)
  }

  // allow to add more education entries
  function addEducation() {
    setEducations([
      ...educations, 
      {
        school: "",
        major: "",
        degree: "",
        startdate: new Date(),
        enddate: new Date(),
        isCurrent: false,
      },
    ]);
  };

  // delete education entry, but keep at least one entry
  function deleteEducation(index: number) {
    if (educations.length > 1) {
      const newEducations = [...educations];
      newEducations.splice(index, 1);
      setEducations(newEducations);
    } else {
      alert("at least one entry");
    }
  };

  const handleCurrentChange = (index: number, isCurrent: boolean) => {
    const updatedEducation = [...educations];
    updatedEducation[index].isCurrent = isCurrent;
    setEducations(updatedEducation);
  };
  
  console.log("submited values: ", form.getValues());
  console.log("Form errors:", form.formState.errors);

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8 my-4">
        {educations.map((edu, index) => (
          <div key={index}>
            <FormField
              control={form.control}
              name={`${index}.school`}
              render={({ field }) => (
                <FormItem>
                  <FormLabel>school</FormLabel>
                  <FormControl>
                    <Input 
                      placeholder="Université xxx" 
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name={`${index}.major`}
              render={({ field }) => (
                <FormItem>
                  <FormLabel>major</FormLabel>
                  <FormControl>
                    <Input placeholder="ex: Design" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name={`${index}.degree`}
              render={({ field }) => (
                <FormItem>
                  <FormLabel>degree</FormLabel>
                  <FormControl>
                    <Input placeholder="ex: Master Design" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name={`${index}.startdate`}
              render={({ field }) => (
                <FormItem className="flex flex-col">
                  <FormLabel>start day</FormLabel>
                  <Popover>
                    <PopoverTrigger asChild>
                      <FormControl>
                        <Button
                          variant={"outline"}
                          className={cn(
                            "w-[240px] pl-3 text-left font-normal",
                            !field.value && "text-muted-foreground"
                          )}
                        >
                          {field.value ? (
                            format(field.value, "PPP")
                          ) : (
                            <span>please select start day</span>
                          )}
                          <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                        </Button>
                      </FormControl>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar
                        mode="single"
                        selected={field.value}
                        onSelect={field.onChange}
                        disabled={(date) =>
                          date > new Date() || date < new Date("1900-01-01")
                        }
                        captionLayout="dropdown-buttons"
                        fromYear={1900}
                        toYear={currentYear}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* a checkbox isCurrent: if not selected then show enddate, else show nothing */}
            <FormField
              control={form.control}
              name={`${index}.isCurrent`}
              render={({ field }) => (
                <FormItem className="flex flex-col">
                  <FormLabel>is current?</FormLabel>
                  <FormControl>
                    <Checkbox 
                      checked={field.value}
                      onCheckedChange={(isCurrent) => handleCurrentChange(index, Boolean(isCurrent))}
                    />
                  </FormControl>
                </FormItem>
              )}
            />

            {!edu.isCurrent && (
              <FormField
                control={form.control}
                name={`${index}.enddate`}
                render={({ field }) => (
                  <FormItem className="flex flex-col">
                    <FormLabel>end day</FormLabel>
                    <Popover>
                      <PopoverTrigger asChild>
                        <FormControl>
                          <Button
                            variant={"outline"}
                            className={cn(
                              "w-[240px] pl-3 text-left font-normal",
                              !field.value && "text-muted-foreground"
                            )}
                          >
                            {field.value ? (
                              format(field.value, "PPP")
                            ) : (
                              <span>please select end day</span>
                            )}
                            <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                          </Button>
                        </FormControl>
                      </PopoverTrigger>
                      <PopoverContent className="w-auto p-0" align="start">
                        <Calendar
                          mode="single"
                          selected={field.value}
                          onSelect={field.onChange}
                          disabled={(date) =>
                            date > new Date() || date < new Date("1900-01-01")
                          }
                          captionLayout="dropdown-buttons"
                          fromYear={1900}
                          toYear={currentYear}
                          initialFocus
                        />
                      </PopoverContent>
                    </Popover>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}

            {index === educations.length - 1 && (
              <div className="flex-wrap-gap-2 mb-2">
                {index !== 0 && (
                  <Button
                    type="button"
                    variant="secondary"
                    onClick={() => deleteEducation(index)}
                  >
                    Delete
                  </Button>
                )}
                <Button type="button" onClick={addEducation}>
                  Add
                </Button>
              </div>
            )}
          </div>
        ))}
        <Button type="submit">Submit</Button>
      </form>
    </Form>
  )
}

```

i don't know at which step the submit result turn into an object instead of an array

**Comment by rahulpunase** [comment]
@cblberlin can you deploy this code somewhere?

**Comment by rahulpunase** [comment]
> > @cblberlin can you deploy this code somewhere?
> > tried to find a way to do that, like in codesandbox?

Yes... will be able to understand the code better. And can run it also

**Comment by cblberlin** [comment]
> > > @cblberlin can you deploy this code somewhere?
> > > tried to find a way to do that, like in codesandbox?
> 
> Yes... will be able to understand the code better. And can run it also

ok, i managed to deploy it on codesandbox here: [multiple-entries-form](https://codesandbox.io/p/github/cblberlin/example-education-multi-entries-form/master?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr915h1900063b6ix5vtp5x3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr915h1900023b6iusggxjvg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr915h1900043b6ilisyz1gn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr915h1900053b6ifr03vi7z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr915h1900023b6iusggxjvg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr915h1800013b6ieirefovc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr915h1900023b6iusggxjvg%2522%252C%2522activeTabId%2522%253A%2522clr915h1800013b6ieirefovc%2522%257D%252C%2522clr915h1900053b6ifr03vi7z%2522%253A%257B%2522id%2522%253A%2522clr915h1900053b6ifr03vi7z%2522%252C%2522activeTabId%2522%253A%2522clr91hv1200gs3b6i6dn05628%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clr91hv1200gs3b6i6dn05628%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr915h1900043b6ilisyz1gn%2522%253A%257B%2522id%2522%253A%2522clr915h1900043b6ilisyz1gn%2522%252C%2522activeTabId%2522%253A%2522clr91cclw002h3b6i4o8g3z5c%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr91agap011e3b6immlg0ab8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr91agc5000yefg7a4m52p82%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clr91cclw002h3b6i4o8g3z5c%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clr91chzz004i3b6i2cn80pdg%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) but it's toooooo slow, you can also check this repository: https://github.com/cblberlin/example-education-multi-entries-form, there is some chinese characters, but it's basically just some buttons like add, remove, submit

**Comment by rahulpunase** [comment]
I got what you are trying to do... 

I think you should create a new form every time you hit the add button and validate that form fields only instead of validating all the fields in one single form.

One you validate the 1st form, add the values to an array and then validate the second form and so on... and finally use the final array on `Submit` button. That way all the objects in your array will already be validated and the code will be much simpler.

**Comment by cblberlin** [comment]
> I got what you are trying to do...
> 
> I think you should create a new form every time you hit the add button and validate that form fields only instead of validating all the fields in one single form.
> 
> One you validate the 1st form, add the values to an array and then validate the second form and so on... and finally use the final array on `Submit` button. That way all the objects in your array will already be validated and the code will be much simpler.
> 
> You are using index and adding that to name field, which means the value property will always change and zod validation will most likely fail

that's a very good approach, i'll try to figure out how to fix this and i will submit my result

**Comment by cblberlin** [comment]
> I got what you are trying to do...
> 
> I think you should create a new form every time you hit the add button and validate that form fields only instead of validating all the fields in one single form.
> 
> One you validate the 1st form, add the values to an array and then validate the second form and so on... and finally use the final array on `Submit` button. That way all the objects in your array will already be validated and the code will be much simpler.
> 
> You are using index and adding that to name field, which means the value property will always change and zod validation will most likely fail

there is another possible approach is to use `useFieldArray` from `react-hook-form` to manage the add and delete actions, i will try both way

**Comment by rahulpunase** [comment]
Yup... works fine. But it never was a shadcn/ui issue. You can close it.

**Comment by cblberlin** [comment]
so i've implemented the multi-entries form
