### ISSUE TITLE
Error w/ Form Component

### ISSUE THREAD

**Issue by aaroncurtisyoga** [shadcn-ui/ui#2389]
### Discussed in https://github.com/shadcn-ui/ui/discussions/2388

<div type='discussions-op-text'>

<sup>Originally posted by **aaroncurtisyoga** January 11, 2024</sup>
I noticed that when using the shadcn-ui form component as instructed in [the docs ](https://ui.shadcn.com/docs/components/form), it results in a Web Browser Console error shown below when you load and reload the page

![Screenshot 2024-01-11 at 5 57 35 PM](https://github.com/shadcn-ui/ui/assets/77994989/aa5f99c6-f3cb-4326-9f5d-a3139329a891)

Here's[ a simple repo](https://github.com/aaroncurtisyoga/shad-cn-form-err) I created. It's just a Next.js boilerplate project w/ the shadcn form from the doc's added

Would love any help w/ figuring out how to get this probelem to go away. Or, if a solution has already been found, a pointer to that article</div>

**Comment by justindoinghisbest** [comment]
Your linked repo have no code to reproduce the issue.

I guest you're trying to server side render the form which contains some compoent that not support ssr.

Either adding `use client;` in the form component or making the whole route client side rendered. 

As in the docs, all shadcn component templates have `use client;` by default.

**Comment by aaroncurtisyoga** [comment]
> Your linked repo have no code to reproduce the issue.
> 
> I guest you're trying to server side render the form which contains some compoent that not support ssr.
> 
> Either adding `use client;` in the form component or making the whole route client side rendered.

Apologies. Here's an update:

1. The [repo](https://github.com/aaroncurtisyoga/shad-cn-form-err) now has code that can be viewed. It's the same code from Shadcn's' website. [This file](https://github.com/aaroncurtisyoga/shad-cn-form-err/blob/main/app/page.tsx) specifically has the form
2. I confirmed that `"use client"` is in fact at the top of the `page.tsx` page
3. Video below of the error


https://github.com/shadcn-ui/ui/assets/77994989/a3165700-cd33-486d-be49-f7013ad8875b

**Comment by aaroncurtisyoga** [comment]
Turns out, it was one of the plugins that I had installed on my browser!
