### ISSUE TITLE
"embla-carousel-react" has no exported member named 'EmblaCarouselType'. Did you mean 'UseEmblaCarouselType'?ts(2724)

### ISSUE THREAD

**Issue by developeratul** [shadcn-ui/ui#2399]
In the new carousel component,

```ts
import useEmblaCarousel, {
  type EmblaCarouselType as CarouselApi,
  type EmblaOptionsType as CarouselOptions,
  type EmblaPluginType as CarouselPlugin,
} from "embla-carousel-react"
```

These types were not exported from the `embla-carousel-react` package.

In that case, we need to install the `embla-carousel` package and import them from there. Like this:

```ts
import {
  type EmblaCarouselType as CarouselApi,
  type EmblaOptionsType as CarouselOptions,
  type EmblaPluginType as CarouselPlugin,
} from "embla-carousel";
import useEmblaCarousel from "embla-carousel-react";
```

Should I proceed with giving a PR regarding that? Pardon my mistakes.

**Comment by ridhosatriawan** [comment]
i am also getting this error, i think this should be merged soon
btw thanks for solution 👍

**Comment by 0xtito** [comment]
there is already a PR for this here: #2326

**Comment by shadcn** [comment]
@developeratul Closing this as duplicate of https://github.com/shadcn-ui/ui/issues/2281. Let's track there. Thanks.
