### ISSUE TITLE
Position of switch issue

### ISSUE THREAD

**Issue by jwoertink** [shadcn-ui/ui#24]
Love the look of this! Just saw this example on the demo site using Firefox 108 on Linux Pop!_OS 22.

![image](https://user-images.githubusercontent.com/2391/214897565-9b1afd04-2503-4d21-bf3b-d9e558d7c8e8.png)
![image](https://user-images.githubusercontent.com/2391/214897592-8e0326d1-2bf4-4ced-bd0a-78d5e6986586.png)
![image](https://user-images.githubusercontent.com/2391/214897621-e5257ffe-76aa-49bb-a2af-c7146aaf6fd3.png)

You can see the button looks like it's hanging outside a little. Super minor, so not really a big deal, but I figured I'd report it anymore. 

Thanks!

**Comment by DevMaxC** [comment]
Can confirm i also get a similar issue on chrome, my button is off center to the top, and whats weirder is that it changes how central it is with user zoom. 

90% Zoom
![image](https://user-images.githubusercontent.com/20259746/215299703-e74f2808-78ff-481e-ba75-e172bc4156d8.png)


100% Zoom
![image](https://user-images.githubusercontent.com/20259746/215299729-0da3d261-0cbb-4a6b-a47c-c78f22bc588f.png)

**Comment by shadcn** [comment]
@jwoertink @DevMaxC Are you both on Linux?

**Comment by lucaspessivaldo** [comment]
I got this issue as well, I'm on Linux. but this occurs on some screens sizes, If I change the zoom or the screen size.

I solve that by putting the **items-center** on in this part of **switch.tsx** ui component.

```tsx
 <SwitchPrimitives.Root
    className={cn(
      "peer inline-flex items-center h-[24px] w-[44px] shrink-0 ....",
      className
    )}
    {...props}
    ref={ref}
  >
```

**Comment by shadcn** [comment]
@lucaspessivaldo Thanks for the update.

@jwoertink @DevMaxC does adding `items-center` fix the issue for you as well? Can you confirm?

If yes, I'll make the change. @lucaspessivaldo Happy to accept a PR as well.

**Comment by lucaspessivaldo** [comment]
To me it's all right after that, I'll do the PR

**Comment by jwoertink** [comment]
Yeah, adding `items-center` seems to fix it :+1:
