### ISSUE TITLE
Carousel: Type Mismatch (using Vite + React + TS) preventing Build

### ISSUE THREAD

**Issue by Otacon2024** [shadcn-ui/ui#2421]
Hi,
It is my first time to "report" an issue, I will describe the context as well as possible: 

1. created React TypeScript project using Vite to test shadcn-ui.

> Those are my shadcn-ui specific settings : 
> 
> ✔ Would you like to use TypeScript (recommended)? … no / yes
> ✔ Which style would you like to use? › Default
> ✔ Which color would you like to use as base color? › Slate
> ✔ Where is your global CSS file? … src/index.css
> ✔ Would you like to use CSS variables for colors? … no / yes
> ✔ Are you using a custom tailwind prefix eg. tw-? (Leave blank if not) …
> ✔ Where is your tailwind.config.js located? … tailwind.config.js
> ✔ Configure the import alias for components: … @/components
> ✔ Configure the import alias for utils: … @/lib/utils
> ✔ Are you using React Server Components? … no / yes
> ✔ Write configuration to components.json. Proceed? … yes

2. I entered the shadcn CLI to install : 

> - the button component
> - the card and carousel components

Then I used the shadcn carousel.tsx in CarouselDemo.tsx and **it works** correctly.

3. If I open the carousel file I can read those 3 type error messages, does someone have an idea how to "fix" this ?

![CleanShot 2024-01-14 at 13 19 57@2x](https://github.com/shadcn-ui/ui/assets/79173984/4512f5a7-fdc2-4a5e-862f-45ad2fa4a0b5)
![CleanShot 2024-01-14 at 13 22 41@2x](https://github.com/shadcn-ui/ui/assets/79173984/65c6a1a0-fc44-40ab-9e5e-d3289e7a616b)
![CleanShot 2024-01-14 at 13 22 51@2x](https://github.com/shadcn-ui/ui/assets/79173984/8012d065-d2ce-4d38-a844-9d306e3e3866)
![CleanShot 2024-01-14 at 13 22 59@2x](https://github.com/shadcn-ui/ui/assets/79173984/95961992-e41b-482e-b82b-57c4a1922b6e)

4. Those error message does also block the build creation :

> - I tried to deploy the project using Vercel and I got the same error message than in my IDE

![CleanShot 2024-01-14 at 14 12 01@2x](https://github.com/shadcn-ui/ui/assets/79173984/6ddeea78-7775-4d48-b3cd-956bd0afda43)

Thanks for your time.

**Comment by rahulpunase** [comment]
hey, please refer to this #2322

**Comment by Otacon2024** [comment]
Thanks I will check your link.
I was also reading this one : https://github.com/shadcn-ui/ui/issues/2281

**Comment by zaaakher** [comment]
@Otacon2024 Make sure to import the types from `embla-carousel` package and not the react wrapper. See [this](https://github.com/shadcn-ui/ui/issues/2281#issuecomment-1881103338)
