### ISSUE TITLE
Resizable can't change size dynamically

### ISSUE THREAD

**Issue by shouheitakai9009** [shadcn-ui/ui#2431]
Hi, I've been using @shadcn/ui components in my product daily, and I find them to be the best-designed components among comparable libraries. However, I've encountered an issue with the Resizable component: It doesn't allow for dynamic size changes from within the program. I believe adding a new prop, size, to the ResizablePanel would address this limitation.

To illustrate, my app features a typical three-column layout for laptop apps: a sidebar area, a content area, and a utility area. Users expect the flexibility to customize the display, such as switching to a distraction-free writing mode or focusing solely on the utility area.

What are your thoughts on this feature request?

```tsx
import { useEffect, useState } from 'react';
import {
  ResizablePanel,
  ResizablePanelGroup,
} from '@/components/common/Resizable';

export const TopPage = () => {
  const [size, setSize] = useState({
    a: 20,
    b: 80,
  });

  useEffect(() => {
    // Can't change size.
    setTimeout(() => setSize({ a: 50, b: 50 }), 1000);
  }, []);

  return (
    <ResizablePanelGroup direction="horizontal">
      <ResizablePanel defaultSize={size.a}>
        <AComponent />
      </ResizablePanel>
      <ResizablePanel defaultSize={size.b}>
        <BComponent />
      </ResizablePanel>
    </ResizablePanelGroup>
  );
}
```

**Comment by Graveheart** [comment]
I believe what you want to do can be achieved using the [Imperative Panel API](https://react-resizable-panels.vercel.app/examples/imperative-panel-api):
```
import { useEffect, useState, useRef } from 'react';
import {
  ImperativePanelHandle,
} from "react-resizable-panels";
import {
  ResizablePanel,
  ResizablePanelGroup,
} from '@/components/common/Resizable';

export const TopPage = () => {
  const refA = useRef<ImperativePanelHandle>(null);
  const refB = useRef<ImperativePanelHandle>(null);

  useEffect(() => {
    // Can't change size.
    setTimeout(() => refA.resize(50), 1000);
  }, []);

  return (
    <ResizablePanelGroup direction="horizontal">
      <ResizablePanel defaultSize={20} ref={refA}>
        <AComponent />
      </ResizablePanel>
      <ResizablePanel defaultSize={80}>
        <BComponent />
      </ResizablePanel>
    </ResizablePanelGroup>
  );
}
```

**Comment by shouheitakai9009** [comment]
@Graveheart I appreciate it.
I realized `Resizable` is made by `react-resizable-panels` in your description.
And then, it worked !!

**Comment by Graveheart** [comment]
No worries, the new components are a bit different than the old ones in that regard. Instead of radix/ui, they're using other external libraries

**Comment by Kokleng-Dev** [comment]
> ImperativePanelHandle

Hello sir, please help me on vue js. how to make it work (size dynamic)?
