### ISSUE TITLE
Popover disappears Immediately after being clicked

### ISSUE THREAD

**Issue by bernard-official** [shadcn-ui/ui#2435]
I have a popover inside my dropdown menu  list. when i select the delete in the menulist the popover shows up but disappears immediately after ... also how do get the pop over to stay i the center of the screen ... here is a snippet of my code below 

<DropdownMenuItem>
          <Popover>
            <PopoverTrigger asChild>
              <button>Delete</button>
            </PopoverTrigger>
            <PopoverContent>
              <Card className="border w-[472px] h-[198px] p-6 space-y-5 items-center transition-all scale-110 opacity-100">
                <CardHeader>Delete Events?</CardHeader>
                <CardContent>
                  Deleting this means everything will be removed from the system
                  permanently. Are you sure of this?
                </CardContent>
                <div className="flex flex-row justify-start space-x-3">
                  <Button className=" w-24 border border-red-500 bg-slate-50 hover:bg-red-500 ">
                    cancel
                  </Button>
                  <Button className=" w-28">yes, Delete</Button>
                </div>
              </Card>
            </PopoverContent>
          </Popover>
        </DropdownMenuItem>
      </DropdownMenuContent>

**Comment by bbambery** [comment]
I think you pasted the wrong code

**Comment by jarodsmk** [comment]
Came across this issue and I was experiencing the same symptoms:
- The popover had no background or border styling applied (after some investigation, none of the classes were being applied to the one element)
- Trying to click on any input elements on the popover resulted in it closing immediately

So to save anyone else seeing this in the future - make sure the popover component being imported is from ShadCN and not the Radix UI import. 
A silly mistake on my part accepting the wrong import caused a few hours of frustration (and a couple grey hairs)
