### ISSUE TITLE
Hover Card works very slowly

### ISSUE THREAD

**Issue by alizada-hadi** [shadcn-ui/ui#2455]
While using the hover card component, I noticed it's prolonged and mostly ambiguous for users. Users usually take it by mistake with button or link and click over it. It would be great if it shows the content as soon as we hover the icon.

**Comment by Mfolmer** [comment]
The hover card component internally uses [radixs hover card](https://www.radix-ui.com/primitives/docs/components/hover-card) and exposes the props of that which support specifying `openDelay` and `closeDelay`.

So you should be able to do:
```
 <HoverCard openDelay={0}>
 ...
 </HoverCard>
```

**Comment by alizada-hadi** [comment]
Thanks
