### ISSUE TITLE
How to make my input look like this

### ISSUE THREAD

**Issue by mrlectus** [shadcn-ui/ui#2468]
![screenshot_2024-01-17T16:34:03](https://github.com/shadcn-ui/ui/assets/25666658/caf40c23-9b79-4f37-93fe-7fbcd66aa378)

**Comment by hedaukartik** [comment]
@mrlectus Change your  generated `input.tsx` component file className prop as below:

- change `border` to `border-b` or `border-b-2`
- remove `rounded-md`
