### ISSUE TITLE
Initializing library not asking for language and path for tailwind config.

### ISSUE THREAD

**Issue by AmanvC** [shadcn-ui/ui#2494]
Earlier while initializing library, the CLI used to ask for language(typescipt) and path for tailwind config, but now it is not asking, and setting path automatically to tailwind.config.js.

![image](https://github.com/shadcn-ui/ui/assets/21061848/e42aee58-5ea6-4174-a2fe-bcf8de63582e)

**Comment by launchthatbrand** [comment]
The new version does auto config detection.
