### ISSUE TITLE
Menubar component breaks if you move around too fast

### ISSUE THREAD

**Issue by maharshmellow** [shadcn-ui/ui#25]
When you move your cursor over the menu bar component, it stops displaying the dropdown once you start moving the cursor too fast. It doesn't show the dropdown again until you click a menu element. 

Tested this in chrome. 

![CleanShot 2023-01-26 at 12 30 57](https://user-images.githubusercontent.com/4590693/214932824-c5207200-9371-4084-b9f5-e1f5626cd450.gif)

**Comment by 0xATHERIS** [comment]
@shadcn I've found a fix to this issue if you're okay with me creating a PR?

**Comment by krishraiturkar** [comment]
Hi i have also knowledge about (ui)
If you are free call me 9546044877
