### ISSUE TITLE
Cra, no typescript

### ISSUE THREAD

**Issue by QuocLam-io** [shadcn-ui/ui#2500]
Hi, I'm working on an existing codebase that used cra and doesn't use typescript. How can I install shadcn?

**Comment by servesh-chaturvedi** [comment]
Hi did you check the typescript section on the installation page? [Link](https://ui.shadcn.com/docs/installation)

**Comment by QuocLam-io** [comment]
Thanks for the help, I was able to configure it

**Comment by justindoinghisbest** [comment]
Please close the issue after resolved.
