### ISSUE TITLE
[BUG] Context Menu position not updating

### ISSUE THREAD

**Issue by Taimoor-Tariq** [shadcn-ui/ui#2507]
The postion of the menu dose not update if the menu is already open and the user right clicks in another location in the same target.

This works properly in the "Radix UI" implimentation where the location of the menu changes properly.

In shadcn, the menu keeps repoening in the inital location no matter where in the target container the user clicks.

**Comment by BlueZ-95** [comment]
@Taimoor-Tariq Can you maybe provide more details by attaching video or something? I'd like to look into this if possible.

**Comment by BlueZ-95** [comment]
@shadcn I'd like to check this out if this is a valid bug.

**Comment by BlueZ-95** [comment]
@Taimoor-Tariq @shadcn, The problem arises when you rapidly click within the context menu. Otherwise it works perfect.

**Comment by Taimoor-Tariq** [comment]
can confirm that removing the `data-[state=closed]:animate-out` class fixes the issue

**Comment by BlueZ-95** [comment]
Yup, I've tested it. Removing the class fixes the bug but it will also remove the context menu's closing animation.

**Comment by BlueZ-95** [comment]
It seems this is the issue from Radix UI itself. @Taimoor-Tariq @shadcn, Do you guys think we can close this or you have something else in your mind to fix this?

**Comment by Taimoor-Tariq** [comment]
this issue is from the `tailwind-animate` package so I think we can close this here

**Comment by BlenderDefender** [comment]
I've found this to be working in the latest documentation of radix UI: https://www.radix-ui.com/primitives/docs/components/context-menu
Updating Radix UI to the latest version however doesn't fix the issue in ShadCN

**Comment by Flamenate** [comment]
This is still not fixed. Removing the animation is not fix, it's a workaround.
