### ISSUE TITLE
Where is examples?

### ISSUE THREAD

**Issue by DhanielB** [shadcn-ui/ui#2511]
Hello! I am interessed on examples showed at home of documentation. Is possible?
https://ui.shadcn.com/examples/mail
![image](https://github.com/shadcn-ui/ui/assets/82909711/fe0ad84c-8ce7-464c-b01a-a5d8e8c630ac)

**Comment by diogoribeirodev** [comment]
here https://github.com/shadcn-ui/ui/tree/main/apps/www/app/examples

**Comment by DhanielB** [comment]
Thanks
