### ISSUE TITLE
Open a dialog over another dialog

### ISSUE THREAD

**Issue by florianheysen** [shadcn-ui/ui#2515]
I'm trying to find out if it's possible to overlap two dialogs one on top of the other.

My example: 

I'm editing a user in a dialog with a form. There's a button in this dialog that lets me delete this user. When you click on the user, it opens a second dialog on top, asking for confirmation of the deletion.

Thank you in advance for your help!

**Comment by franfares10** [comment]
Hi Florian! It's possible, you've just to repeat the implementation of the Dialog component within another Dialog component.
In fact, you can intance a nested Dialog within any part of the root Dialog (Header, Content, Footer).

Regards, Fran.

**Comment by juanriglos** [comment]
it's not working on my end

**Comment by abhiDhantellius** [comment]
Can anyone please provide a code snippet for this?

**Comment by osmanahmadxai** [comment]
I had the same issue with a nested Dialog in shadcn. I searched Google for a solution and found this thread as the first result. In case anyone else runs into this, the fix is simple: set modal={true} on the nested Dialog. That made the inner dialog resolved the problem for me.

**Comment by FrancescoSaverioZuppichini** [comment]
now working for me

**Comment by cin12211** [comment]
you can add v-if to result this
```<Dialog v-if="isSettingsOpen" v-model:open="isSettingsOpen">```
for ensuse each modal open step by step 

example : here i have 3modals [ modal a , modal b , modal c ]

if you open modal a -> then modal b -> modal c this will be work c overlay b , b overlay a 
but modal b still here before you open modal a  -> your bugs

**Comment by brunopp** [comment]
#11214 (#11217) fixes this issue by adding forceRender to your inner dialogs:

```
<Dialog>
    <DialogContent overlayProps={{forceRender: true}}
...
```

It has not been merged yet, but you can add it manually.
