### ISSUE TITLE
Dialog freeze when use state for open/show dialog

### ISSUE THREAD

**Issue by fedyunin** [shadcn-ui/ui#2525]
Hello! 

`
export default function MyDialog(props) {

    const { open, onSave, onClose } = props;

    return <Dialog open={open}>
        <DialogContent>
            <DialogHeader>
                Title
            </DialogHeader>
            <div>Dialog content here<div/>
            <DialogFooter>
                <Button type="button" onClick={onSave}>Save</Button>
                <Button type="button" variant="secondary" onClick={onClose}>
                    Cancel
                </Button>
            </DialogFooter>
        </DialogContent>
    </Dialog>
}
`

Then I used this dialog in my other component where I use state for open/show Dialog:

`
export default function Main() {
    const [open, setOpen] = useState(false);

    const onShowDialog = () => {
        setOpen(true);
    }

    const onSave = () => {
	// save data 
        setOpen(false);
    }

    const onClose = () => {
        setOpen(false);
    }

    return <div>
                <Menubar>
                    <MenubarMenu>
                        <MenubarTrigger><MoreVertical /></MenubarTrigger>
                        <MenubarContent>
                            <MenubarItem onClick={onShowDialog}>Create</MenubarItem>
                        </MenubarContent>
                    </MenubarMenu>
                </Menubar>
            <MyDialog open={open} onClose={onClose} onSave={onSave} />
          </div>
}
`

When Click at menu item - Create, then dialog shows successfully. But when I try click at Save or Cancel - dialog freeze all page and
unable to do any actions.

The same implementation works if I change Dialog to AlertDialog.

**Comment by kelvinbush** [comment]
@fedyunin Have you found a solution for this?
I've just encountered a similar bug. Could you please share your solution if you found any?
Thank you!

**Comment by lawrence615** [comment]
I was facing the same issue but I was using a DropdownMenu to launch the dialog. I had to add `modal={false}` prop on the DropdownMenu as shown [here](https://github.com/shadcn-ui/ui/issues/544#issuecomment-1836353580). Below is my code:

```
    <>
      <AlertModal
        isOpen={open}
        onClose={() => setOpen(false)}
        onConfirm={handleDelete}
        loading={loading}
      />
      <DropdownMenu modal={false}>
        <DropdownMenuTrigger asChild>
          <Button variant="ghost" className="h-8 w-8 p-0">
            <span className="sr-only">Open menu</span>
            <MoreHorizontal className="h-4 w-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuLabel>Actions</DropdownMenuLabel>
          <DropdownMenuItem onClick={() => console.log('Edit clicked')}>
            <Edit className="mr-2 h-4 w-4" /> Update
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => setOpen(true)}>
            <Trash className="mr-2 h-4 w-4" /> Delete
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </>
    ```
