### ISSUE TITLE
CommandInput needs to be cleared completely to find matches after not finding them

### ISSUE THREAD

**Issue by crswll** [shadcn-ui/ui#256]
If you go to the [Command](https://ui.shadcn.com/docs/components/command) example and type "c" you'll see results, if you then type a "2" then delete it no results are listed. You need to clear the whole input before results are listed again which seems odd.

**Comment by AeroXi** [comment]
I have the same problem.
Solved by:
https://github.com/pacocoursey/cmdk/issues/40#issuecomment-1223397094

**Comment by evanlong0926** [comment]
> I have the same problem. Solved by: [pacocoursey/cmdk#40 (comment)](https://github.com/pacocoursey/cmdk/issues/40#issuecomment-1223397094)

How was it solved?
