### ISSUE TITLE
some of tailwind classes not working in react/vite

### ISSUE THREAD

**Issue by ezrnew** [shadcn-ui/ui#2582]
Hey, I just copied the entire table from dataTable tutorial and thats how it looks like in my project:
![image](https://github.com/shadcn-ui/ui/assets/53041849/e685ba22-a87e-44da-a28d-6af11347cf48)

while it should look like this:
![image](https://github.com/shadcn-ui/ui/assets/53041849/eeb47b44-d092-4883-90a4-9bfb194af726)

I have no idea why some styles are missing, i already reinstalled all shadcn stuff with everything default, here are my configuration files on my main project:

![image](https://github.com/shadcn-ui/ui/assets/53041849/afd17985-c366-4422-800f-f68ab8019da5)
![image](https://github.com/shadcn-ui/ui/assets/53041849/64d85e0c-0e74-4d56-a3fc-2748ae9d575a)
![image](https://github.com/shadcn-ui/ui/assets/53041849/c5074007-9870-47eb-8b55-9784f4c328fa)
![image](https://github.com/shadcn-ui/ui/assets/53041849/5e3ca1b0-234d-4c35-b898-611a371adeab)
![image](https://github.com/shadcn-ui/ui/assets/53041849/bb4a1f5c-0e43-47e8-93ad-c0e15ae6ab53)
![image](https://github.com/shadcn-ui/ui/assets/53041849/66c71c2d-2e23-440b-b798-3167e0a73728)
![image](https://github.com/shadcn-ui/ui/assets/53041849/fc296dca-02b3-439d-bac5-828153bc4ba0)

The second screenshot is from newly created vite app and all the styles work there, all the configs are exactly the same on my main project and that new one, the only difference i think are some extra dependencies on main project. Any ideas what might be causing the issue?

**Comment by dan5py** [comment]
Hi @ezrnew, I just tried to replicate your issue but it works fine to me. I see that you're using `emotion`, maybe it's causing a conflict with Tailwind but I'm not sure.
Can you share the affected repo?

**Comment by ezrnew** [comment]
> Hi @ezrnew, I just tried to replicate your issue but it works fine to me. I see that you're using `emotion`, maybe it's causing a conflict with Tailwind but I'm not sure. Can you share the affected repo?

Hey @dan5py, its on my company repo so I dont think I can. What do you mean by 'emotion'?

**Comment by ezrnew** [comment]
Okay just fixed it by copying identical DataTable component from working repo but i placed it next to App.tsx in folder structure, used it in App.tsx, and then switched back to use the previous table that hasnt been working before... I assume i might have had something fcked up in my cache maybe, because on my first shadcn installation on this project i have not configured it correctly?
