### ISSUE TITLE
`twMerge` in the templates must override/extend the `borderRadius` property

### ISSUE THREAD

**Issue by dalechyn** [shadcn-ui/ui#2583]
As Shadcn introduces a non-default `sm` value for `borderRadius`, it should modify the `twMerge` config in such a way that the class is marked to be conflicted with `twMerge`, otherwise it produces next results:

![Screenshot 2024-01-26 at 16 37 41](https://github.com/shadcn-ui/ui/assets/35642018/33a9bf9d-a3bb-4df3-8f4f-976a5ce84e46)

The value is not being marked as conflicting and overriding rounded behaviour becomes impossible.

**Comment by arsaizdihar** [comment]
I think that's not the case. `rounded-sm` and `rounded-b-none` are not conflicting. `rounded-sm` and `rounded-md` are.

**Comment by dalechyn** [comment]
> I think that's not the case. `rounded-sm` and `rounded-b-none` are not conflicting. `rounded-sm` and `rounded-md` are.

agreed, looks like I might need more sleep, thanks!
