### ISSUE TITLE
toast componets  does not apper when i try to use it  

### ISSUE THREAD

**Issue by mohamed-abd-elkahlk** [shadcn-ui/ui#2608]
hi there, i use toast from your components with astro and when i try to call it inside a react .tsx file like these i got nothing
![code](https://github.com/shadcn-ui/ui/assets/115940318/92feadf4-5608-4d45-b87c-459aba985fe3)
when i try to submit the form it dose not show up ,
i try 
![code](https://github.com/shadcn-ui/ui/assets/115940318/eddb36e5-ff14-41fb-8243-fdce1e026d5f)
and it still not working .
i hope you to find a solution.
thanks

**Comment by mohamed-abd-elkahlk** [comment]
@sarkartanmay393 yes in the main Layout
![code](https://github.com/shadcn-ui/ui/assets/115940318/17b55b09-00d1-4655-b131-89d3e0e0da9b)

**Comment by mohamed-abd-elkahlk** [comment]
i solved this issue by adding **clinet:idle** to toaster component in main file

**Comment by 5war00p** [comment]
Although I've used `client:only="react" (or client:load)` directives, sometimes toast simply won't showup. 
More details:
- Using Astro
- Serving static assets from Cloudflare

**Comment by Jefry16** [comment]
did you solve this? please share. in my case it shows unstyle
