### ISSUE TITLE
[Feat]: Add Bug report and Feature request templates

### ISSUE THREAD

**Issue by davidjerleke** [shadcn-ui/ui#2609]
Hello from the Embla Carousel side 👋!

## The problem
@shadcn and team, up until recently I also had a similar flood of issues that was pouring into my project repository. And it was stressing me out a bit. So I feel sorry for you guys seeing this flood of poor quality issues here.

### The issue type with fragments of code
Hi, great work on `shadcn-ui`! I'm having problems with the checkbox, here's my code:

```ts
const checkboxSize = 10
```

<img width="327" alt="screenshot" src="https://github.com/shadcn-ui/ui/assets/11529148/965f28ed-ce0e-43ca-86d7-d18c152101b4">

Can you please solve this bug?

---

### The issue type with a question no one except the author understands 
Hi, great work on `shadcn-ui`! Where is HTML?

---

### The issue type with screenshots of super unhelpful errors

Hi, great work on `shadcn-ui`! My component is crashing. Can you solve this buggy behavior?

<img width="354" alt="bug" src="https://github.com/shadcn-ui/ui/assets/11529148/e4204f6f-3a21-4c3a-b6b5-6733f4930326">

### The issue type with no helpful information whatsoever
Hi, great work on `shadcn-ui`! It's not working when I use it on my computer. On mobile it works.

## Goal
So yes, maybe I'm being a bit satirical here. Don't get me wrong though! Most **devs that create issues mean well** and want to **help out**. And that's a good thing! And of course we want devs to create issue if they find bugs and so on. But with no issue templates, many of the issues include little to no useful information that will lead to resolving it. This is incredibly time consuming for project maintainers.

With this issue and its related PR, **my intention is to reduce the flood of poor quality issues** pouring in to this repository, and instead improve the quality of feature requests and bug reports:

- We need to enforce devs creating issues here to do research efforts before they create issues.
- We need to remind them that they should do as much as possible themselves to help out.
- We need them to provide steps to reproduce and other crucial information for you maintainers so you can easily reproduce the same problem instead of spending a lot of time trying to figure out how to reproduce it.
- We need to improve the quality of the issue reports.
- We need to improve issue reports to make it easier for devs/contributors to take on issues, because with this change, every issue will include more useful information and details.

## What I've done
I've done the following:

- I've added a [bug report template](https://github.com/shadcn-ui/ui/pull/2610/files#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efR1).
- I've added a [feature request template](https://github.com/shadcn-ui/ui/pull/2610/files#diff-c6b098646bf32c644234bec14c2675ea2a3d9c2dc2df450a25aa0e7ff02323cdR1).
- Both templates are using the `.yml` format where it's possible to have **required inputs**. So devs can no longer skip mandatory stuff that should be there.
- I've added an [issue config](https://github.com/shadcn-ui/ui/pull/2610/files#diff-1c0d972ee49103af56fd608a77a28e1eb12f6908f263f0f183d46868fdcd8ea2R1) that enforces devs creating issues to pick between the two. With this config, they can't just start a blank template to avoid making efforts.
- Picking a template will automatically prefix the title with `[Feat]: <title_here>` for feature requests and `[Bug]: <title_here>` for bug reports.
- Picking a template will automatically add the labels `area: feat` and `bug` respectively.
 
Feel free to make adjustments to the templates. There might be stuff that I’ve missed that you think should be included.

I hope this helps!

Best,
David

**Comment by davidjerleke** [comment]
@shadcn why is this considered `stale`?

**Comment by shadcn** [comment]
@davidjerleke Not stale. This was labeled by the actions. Removed it. 

Thanks for the PR. I'll review and merge.

**Comment by davidjerleke** [comment]
@shadcn thanks for explaining. Sorry I missed that it was done automatically with an action.
