### ISSUE TITLE
Property className and ref does not exist on DropdownMenuProps

### ISSUE THREAD

**Issue by MartinaMilisic** [shadcn-ui/ui#2621]
I just got started with shadcn-ui and wanted to be able to style the DropdownMenu component by passing a className.

This is what i have in my `dropdown-menu.tsx`:
```
const DropdownMenu = React.forwardRef<
	React.ElementRef<typeof DropdownMenuPrimitive.Root>,
	React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Root>
>(({ className, ...props }, ref) => (
	<DropdownMenuPrimitive.Root ref={ref} className={cn(className)} {...props}>
		{props.children}
	</DropdownMenuPrimitive.Root>
))
DropdownMenu.displayName = DropdownMenuPrimitive.Root.displayName

```
I get a warning on both `className` and `ref` saying:
`Property className does not exist on type DropdownMenuProps` and `Property 'ref' does not exist on type 'IntrinsicAttributes & DropdownMenuProps`

Am I missing something? Help much appreciated, thanks!

Version of Radix dropdown: "@radix-ui/react-dropdown-menu": "^2.0.6",

**Comment by V-Mokhun** [comment]
I believe DropdownMenuPrimitive.Root is a wrapper for giving context to Dropdown trigger and content, so you won't be able to give className to it.

**Comment by MartinaMilisic** [comment]
Thank you @V-Mokhun I figured it out as well after a while :)
