### ISSUE TITLE
Mobile-nav is lagging when clicked

### ISSUE THREAD

**Issue by d0nda** [shadcn-ui/ui#2670]
Hey I noticed something wrong about the Mobile-nav, when I clicked it ..it's lagging for a couple of seconds not sure if it was intentional when it was made if not I'd like to work on  this issue if It hasnt been noticed, you can check the the mobile version of https://ui.shadcn.com nav.

**Comment by Cauatn** [comment]
I tested, and it's working fine. It's likely the browser, internet connection, or the phone's processing.
"I don't think it's an issue, unless more similar reports show up. But it's always good to notify when a problem arises.

**Comment by d0nda** [comment]
I tested it on two browsers , safari and brave browser they react the same way

**Comment by d0nda** [comment]
This is a recording I made to show the mobile-nav issue https://github.com/shadcn-ui/ui/assets/79589014/39bc280c-9588-427a-a484-d7d0ab2b3679
