### ISSUE TITLE
Scrolling Issue with ScrollArea Component When Content Exceeds Parent Size

### ISSUE THREAD

**Issue by marclelamy** [shadcn-ui/ui#2686]
Hi there,

I've encountered an issue with the ScrollArea component. The problem is that scrolling doesn't work as expected when the child elements' total height exceeds the parent container's height.

Here's a simplified code snippet demonstrating the issue. I used the doc of the combobox and just made the framework array longer, added `ScrollArea` in the `CommandGroup` and added max-h-64 to `CommandGroup`

``` jsx
"use client"

import * as React from "react"
import { Check, ChevronsUpDown } from "lucide-react"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import {
    Command,
    CommandEmpty,
    CommandGroup,
    CommandInput,
    CommandItem,
} from "@/components/ui/command"
import { ScrollArea } from "@/components/ui/scroll-area"
import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover"

let frameworks = [
    {
        value: "next.js",
        label: "Next.js",
    },
    {
        value: "sveltekit",
        label: "SvelteKit",
    },
    {
        value: "nuxt.js",
        label: "Nuxt.js",
    },
    {
        value: "remix",
        label: "Remix",
    },
    {
        value: "astro",
        label: "Astro",
    },
]
frameworks = [...frameworks, ...frameworks, ...frameworks, ...frameworks]

export default function ComboboxDemo() {
    const [open, setOpen] = React.useState(false)
    const [value, setValue] = React.useState("")

    return (
        <Popover open={open} onOpenChange={setOpen}>
            <PopoverTrigger asChild>
                <Button
                    variant="outline"
                    role="combobox"
                    aria-expanded={open}
                    className="w-[200px] justify-between"
                >
                    {value
                        ? frameworks.find((framework) => framework.value === value)?.label
                        : "Select framework..."}
                    <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                </Button>
            </PopoverTrigger>
            <PopoverContent className="w-[200px] p-0">
                <Command>
                    <CommandInput placeholder="Search framework..." />
                    <CommandEmpty>No framework found.</CommandEmpty>
                    <CommandGroup className="max-h-64">
                        <ScrollArea>
                            {frameworks.map((framework) => (
                                <CommandItem
                                    key={framework.value}
                                    value={framework.value}
                                    onSelect={(currentValue) => {
                                        setValue(currentValue === value ? "" : currentValue)
                                        setOpen(false)
                                    }}
                                >
                                    <Check
                                        className={cn(
                                            "mr-2 h-4 w-4",
                                            value === framework.value ? "opacity-100" : "opacity-0"
                                        )}
                                    />
                                    {framework.label}
                                </CommandItem>
                            ))}
                        </ScrollArea>
                    </CommandGroup>
                </Command>
            </PopoverContent>
        </Popover>
    )
}
```

I expected the content to become scrollable when there are more child elements than can fit in the parent container, but that's not happening. Is there a problem with how the ScrollArea component handles overflow, or am I misunderstanding its intended use?

Any insights or suggestions for fixing this would be greatly appreciated. Thanks! 😊

**Comment by alirezakasirzare** [comment]
same

**Comment by alirezakasirzare** [comment]
Setting type "scroll" for ScrollArea component will be fix it

**Comment by shahbaz-khan-hub** [comment]
> Setting type "scroll" for ScrollArea component will be fix it

how do we setup the scroll bar i want to enable it

**Comment by YuriiZadorozhnii** [comment]
I think this issue shouldn't be closed. The component didn't work properly out of the box

**Comment by shahbaz-khan-hub** [comment]
> I think this issue shouldn't be closed. The component didn't work properly out of the box

well I have tried to work on this it's simple I removed the scroll area component, and added styling to the tailwind.css file in which I hide the scroll, and  I used `overflow-y-scroll `simple,  sometimes as new developers we shouldnt rely on these ui libraries i guess

**Comment by saluonecity** [comment]
use this from your layout.tsx :
<div className="flex flex-col h-screen overflow-hidden">
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset className="flex-1 overflow-hidden">
          <NavHeader />
          <div className="flex-1 overflow-y-auto no-scrollbar">{children}</div>
        </SidebarInset>
      </SidebarProvider>
    </div>

and in your global css :
.no-scrollbar::-webkit-scrollbar {
  width: 0px;
  background: transparent;
}

.no-scrollbar {
  -ms-overflow-style: none; /* IE dan Edge */
  scrollbar-width: none; /* Firefox */
}

**Comment by 0xpanadol** [comment]
fixed by adding overflow-scroll to allow scrolling and style="scrollbar-width: none" to hide the default scrollbar in browsers

```
<ScrollArea class="flex-grow min-h-0 overflow-scroll" tyle="scrollbar-width: none">
</ScrollArea>
```

**Comment by alexfullbrazil** [comment]
Just add a 'flex' or 'grid' class to the parent container. Something like:

```
<div className='flex | grid'>
    <ScrollArea className='max-h-80'>
       <AVeryTallComponent/>
    </ScrollArea>
</div>
```

**Comment by noql1** [comment]
The trouble in the Popover (It doesn’t trap pointer or scroll events) and not in scrollArea, if you give Popover 'modal' prop, it works fine.

**Comment by ivanvolti** [comment]
If `<ScrollArea />` is inside a flex container, give it `min-height: 0` (`min-h-0`) — that makes it shrink properly and allows scrolling.

```tsx
<div className="h-dvh flex flex-col">
  <div className="h-10">Topbar</div>

  <ScrollArea type="auto" className="min-h-0 flex-1">
    <div className="p-6">
      Long content
    </div>
  </ScrollArea>
</div>
```

**Comment by rockysaputra** [comment]
<Popover modal={true}>

added modal property on Popover
it works for me

**Comment by zedwone** [comment]
If `<ScrollArea />` is inside a flex container: 
```
<div className="h-dvh flex flex-col min-h-0">
  <div className="h-10">Topbar</div>
  <div className="flex-1 flex min-h-0 relative">
    <ScrollArea className="flex-1">
      <div className="p-6">
        Long content
      </div>
    </ScrollArea>
  </div>
</div>
```
