### ISSUE TITLE
Toast component not working

### ISSUE THREAD

**Issue by LOG1997** [shadcn-ui/ui#2702]
when I copy the code to my project,the Toast component is not working。 When I clicked the button, the toast did not appear
and I am using react@18 + vite@5
![image](https://github.com/shadcn-ui/ui/assets/26322485/09c4f408-7cf4-46fd-bdc3-2fa7e2baf4ec)
![code](https://github.com/shadcn-ui/ui/assets/26322485/a3b6bbbf-cd9a-4b6f-8d5c-356fca5a1057)

**Comment by dromzeh** [comment]
You've added the `Toaster` component inside your layout, right? 

e.g:

```ts
// layout.tsx
import { Toaster } from "@/components/ui/toaster"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <main>{children}</main>
        <Toaster /> // <-- toaster component
      </body>
    </html>
  )
}
```

**Comment by paradimes** [comment]
what can i do if i'm using Vite? I don't have a layout.tsx and not sure how to make this work...

**Comment by llupon** [comment]
Sorry, where is the layout.tsx archive?

**Comment by llupon** [comment]
How can i place the Toaster in App.tsx? Sorry i'm new into this.
![Captura](https://github.com/user-attachments/assets/19ec7905-2f85-4c16-92e7-81b725bd7494)

**Comment by LOG1997** [comment]
@llupon 
This is my App.tsx file. In fact, you only need to place the Toast in a root file such as App.tsx or layout.tsx for it to take effect. For example, you can simply add <Toaster /> inside the div tag in your App.tsx.
![image](https://github.com/user-attachments/assets/70857e7b-e882-4e6f-b11f-7e09fb8add58)

**Comment by yuangnz** [comment]
What a great report, it solved my problem. It should be added in the documentation in case of using Vite.
