### ISSUE TITLE
In TypeScript, an error occurred with SheetContent!

### ISSUE THREAD

**Issue by ItsJohnny30** [shadcn-ui/ui#2703]
TypeScript Error:

```
Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & SheetContentProps & RefAttributes<unknown>'.ts(2559)
(alias) const SheetContent: React.ForwardRefExoticComponent<SheetContentProps & React.RefAttributes<unknown>>
import SheetContent
```

**Comment by necm1** [comment]
Still facing this issue till today. Any updates related to this issue? @ItsJohnny30

**Comment by mattmattmatt** [comment]
This might not work for everyone, but restarting VS Code removed that error for me.

**Comment by Ajeibi** [comment]
Restarting VS Code also worked for me .

**Comment by erichosick** [comment]
For me, this issue doesn't happen in VS Code but is happening when building in the command line using next.js (next build).

The issue happens with almost all components generated by shadecn-ui.

**Comment by devdumpling** [comment]
Also encountering this, happened when installing NavigationMenu for me.

**Comment by gokugoru** [comment]
@ItsJohnny30 still facing the issue

**Comment by zac** [comment]
I've also just experienced this on several shadcn/ui elements that I just started integrating in a new project. I get very similar errors relating to `children` and errors relating to `className` as well. No amount of restarting VSCode (Cursor in my case) seems to work. Similarly to above, it's stopping the nextjs build and not just editor-related type checking.

 Any help or guidance would be appreciated!

![CleanShot 2024-10-07 at 22 16 51@2x](https://github.com/user-attachments/assets/86f320fe-03f6-4ae8-9736-ca17a2340687)

![CleanShot 2024-10-07 at 22 15 14@2x](https://github.com/user-attachments/assets/f94859d6-83c7-406b-b13b-9cb4820d6854)

**Comment by refeals** [comment]
I did some digging on this, never had this issue with TS, but i got it using regular JS. I had to set `checkJs: false` on `jsconfig.js` so the errors disappear, but that isn't really a fix. 

Seems like React 18+ doesn't automatically export `children` on `props` anymore so I guess that's where the issue comes from.

I've been looking for a fix for this for weeks too, to no avail :/

**Comment by KrinsKumar** [comment]
Is there an update on this?

**Comment by albertkim** [comment]
I resolved this not by restarting VS Code, but by deleting my node modules/yarn.lock and running `yarn install` again.

**Comment by drinkingwine** [comment]
Ditto with what albertkim did...

**Comment by kwiscion** [comment]
For me it was `@radix-ui/react-dialog` not being installed. `npm i @radix-ui/react-dialog` fixed it
