### ISSUE TITLE
buttons below select items are clicked too

### ISSUE THREAD

**Issue by youssef579** [shadcn-ui/ui#2721]
Hello

When I click on an item of select items on mobile, the buttons below are clicked, too
which causes me a problem
Here is an example in the docs itself: 

https://github.com/shadcn-ui/ui/assets/85634961/4be5ab7e-b561-4860-992c-434fcbafea43

**Comment by mohit4bug** [comment]
This bug is coming straight from Radix UI. [Check here](https://github.com/radix-ui/primitives/issues/1658)

**Comment by mohit4bug** [comment]
This bug originates directly from Radix UI. Refer to [this](https://github.com/radix-ui/primitives/issues/1658) location for verification.

**Comment by youssef579** [comment]
@mohit4bug Thanks!

**Comment by Alixanb** [comment]
For anyone here, the best solution is to add this to the SelectContent :

  ref={(ref) => {
    if (!ref) return;
    ref.ontouchstart = (e) => e.preventDefault();
  }}
  
  it's the least 'hacky' solution that seems to work well

**Comment by SaatwikRishi** [comment]
> ref={(ref) => { if (!ref) return; ref.ontouchstart = (e) => e.preventDefault(); }}

It should be ontouchend, not touchstart.. with touch start, scroll isnt working mobile devices

**Comment by Elsass1** [comment]
I am still having trouble with this. Sadly nothing worked yet among the different fixes found by the community.

**Comment by iAbhinav** [comment]
i fixed it by adding 

```
  ref={(ref) => {
              if (!ref) return;
              ref.ontouchstart = (e) => e.preventDefault();
            }}
```
to my `SelectContent` component as suggested by @Alixanb.

Here is the final code:
```
const SelectContent = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>
>(({ className, children, position = "popper", ...props }, ref) => {
  return (
    <SelectPrimitive.Portal>
      <SelectPrimitive.Content
        ref={ref}
        className={cn(
          "relative z-50 max-h-96 min-w-[8rem] overflow-hidden rounded-md border border-zinc-200 bg-white text-zinc-950 shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-50",
          position === "popper" &&
            "data-[side=bottom]:translate-y-1 data-[side=left]:-translate-x-1 data-[side=right]:translate-x-1 data-[side=top]:-translate-y-1",
          className
        )}
        position={position}
        {...props}
      >
        <SelectScrollUpButton />
        <SelectPrimitive.Viewport
          className={cn(
            "p-1",
            position === "popper" &&
              "h-[var(--radix-select-trigger-height)] w-full min-w-[var(--radix-select-trigger-width)]"
          )}
        >
          <div
            ref={(ref) => {
              if (!ref) return;
              ref.ontouchstart = (e) => e.preventDefault();
            }}
          >
            {children}
          </div>
        </SelectPrimitive.Viewport>
        <SelectScrollDownButton />
      </SelectPrimitive.Content>
    </SelectPrimitive.Portal>
  );
});
```

**Comment by alexanderPastornicky** [comment]
still issue

**Comment by Gabrieelkn** [comment]
still issue

**Comment by Wiz1991** [comment]
still an issue

**Comment by AwaisYusaf** [comment]
> For anyone here, the best solution is to add this to the SelectContent :
> 
> ref={(ref) => { if (!ref) return; ref.ontouchstart = (e) => e.preventDefault(); }}
> 
> it's the least 'hacky' solution that seems to work well

Thanks

**Comment by pedromazini** [comment]
> For anyone here, the best solution is to add this to the SelectContent :
> 
> ref={(ref) => { if (!ref) return; ref.ontouchstart = (e) => e.preventDefault(); }}
> 
> it's the least 'hacky' solution that seems to work well

worked here, thanks bro

**Comment by chooblarin** [comment]
> For anyone here, the best solution is to add this to the SelectContent :
> 
> ref={(ref) => { if (!ref) return; ref.ontouchstart = (e) => e.preventDefault(); }}
> 
> it's the least 'hacky' solution that seems to work well

This will cause an issue in mobile Safari. Taps even inside select content will be disabled.

**Comment by jlondonobo** [comment]
Upgrading @radix-ui/react-select to a version later than 2.1.2 fixed the issue for me, as pointed by @mohit4bug
