### ISSUE TITLE
Destructive alerts have somewhat bad visibility when in dark mode

### ISSUE THREAD

**Issue by noahstreller** [shadcn-ui/ui#2728]
![image](https://github.com/shadcn-ui/ui/assets/65013011/fbe9f498-f5e8-4c5e-afb1-4a5bfed79243)
![image](https://github.com/shadcn-ui/ui/assets/65013011/17854490-740e-43c5-b212-588ba3c88f20)

In my opinion, it would be great if the contrast was a bit better, or the text was a bit thicker by default. In light mode, there are no issues.

**Comment by steyer-mika** [comment]
This issue is a duplicate of [Issue #281](https://github.com/shadcn-ui/ui/issues/281).

**Comment by noahstreller** [comment]
Closing as duplicate then
