### ISSUE TITLE
How to Apply RTL Support to Shadcn Components in Next.js ?

### ISSUE THREAD

**Issue by EhsanKey** [shadcn-ui/ui#2736]
I'm using Shadcn in Next.js. How can I apply RTL (right-to-left) support to Shadcn components?

File: layout.tsx

```tsx
import type { Metadata } from "next";
import "../globals.css";

import localFont from "next/font/local";
import { Provider } from "../../providers";
import { NextIntlClientProvider, useMessages } from "next-intl";

const iranSansFont = localFont({
  src: "../../fonts/iranSans.woff2",
  display: "swap",
  variable: "--font-iranSans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactElement;
  params: { locale: string };
}>) {
  const messages = useMessages();

  return (
    <html lang={locale} dir={locale === "fa" ? "rtl" : "ltr"}>
      <body
        className={`${iranSansFont.className} bg-background text-foreground px-4 py-4 font-bold`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Provider>{children}</Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
```

**Comment by aidanCQ** [comment]
shadcn/ui uses radix-ui, see https://www.radix-ui.com/primitives/docs/utilities/direction-provider

**Comment by ARiyou2000** [comment]
As described in the radix official doc:
```jsx
"use client"
import { DirectionProvider } from '@radix-ui/react-direction';

export default () => <DirectionProvider />;
```

and then in your top-level module (app layout or app.js)
```jsx
<DirectionProvider dir="rtl">{/* your app */}</DirectionProvider>
```


refrence: https://www.radix-ui.com/docs/primitives/utilities/direction-provider

**Comment by naseroish** [comment]
Only works on client side

**Comment by faizan-visiontechsolutions** [comment]
This should not be closed since it's only support in client side.

**Comment by ARiyou2000** [comment]
> Only works on client side

How? I'm using it with i18n just fine.

There is more critical issue about shadCn rtl support. That is to use `[m,p,...]-start` instead of `[m,p,...]-left`

**Comment by naseroish** [comment]
what i did is just used a normal html tag and added a dir='rtl' <div className='flex' dir='rtl'>

**Comment by elbasel-abdelrahman** [comment]
ShadCn needs to adjust it's component classNames to support rtl, components styles breaks when settings 'rtl' on either the html tag or using radix direction providers
![Peek 2024-12-25 13-44](https://github.com/user-attachments/assets/e77611c9-2d23-4d92-a30c-555b8e2f5d27)
![Peek 2024-12-25 13-45](https://github.com/user-attachments/assets/6e534d85-c529-4bca-a216-ab6c676105d1)

**Comment by choper725** [comment]
just time to do it as it getting into laravel starter kits

**Comment by m-farah** [comment]
Hi there 👋,

I recently faced the same problem and created a lightweight **TypeScript script**. It automatically converts ShadCN components into RTL-ready mode by transforming Tailwind classes in your `src/components` folder.

You can check it out here:
**[shadcn-rtl](https://github.com/m-farah/shadcn-rtl)**

**Comment by naseroish** [comment]
> Hi there 👋,
> 
> I recently faced the same problem and created a lightweight **TypeScript script**. It automatically converts ShadCN components into RTL-ready mode by transforming Tailwind classes in your `src/components` folder.
> 
> You can check it out here:
> **[shadcn-rtl](https://github.com/m-farah/shadcn-rtl)**

Thanks for the contribution, I just wanted to ask — with your solution, will I still be able to use LTR as well? Or does it fully switch everything to RTL? I’m aiming to support both Arabic and English in the same app.

**Comment by m-farah** [comment]
> > Hi there 👋,
> > I recently faced the same problem and created a lightweight **TypeScript script**. It automatically converts ShadCN components into RTL-ready mode by transforming Tailwind classes in your `src/components` folder.
> > You can check it out here:
> > **[shadcn-rtl](https://github.com/m-farah/shadcn-rtl)**
> 
> Thanks for the contribution, I just wanted to ask — with your solution, will I still be able to use LTR as well? Or does it fully switch everything to RTL? I’m aiming to support both Arabic and English in the same app.


Thanks @naseroish ! The script replaces LTR-specific classes with direction-aware ones like `ps-` and `text-start`, so components automatically follow the direction of the page or section — whether it's LTR or RTL.

No forced direction — it adapts based on the `dir` attribute.

**Comment by alsir2k** [comment]
I think all you need is to add `dir="rtl"` to the html tag, and add the following to the `globals.css` file:

```css
html[dir="rtl"] * {
  direction: rtl;
}

**Comment by mininaim** [comment]
@alsir2k
support needs to be implemented at the component level //
such as dropdowns, labels, etc /./ not just by adding RTL to the header as you mentioned above

**Comment by yelsayed** [comment]
> I think all you need is to add `dir="rtl"` to the html tag, and add the following to the `globals.css` file:
> 
> html[dir="rtl"] * {
>   direction: rtl;
> }

This worked for me! It's not perfect but it resolved a lot of the components for me.

**Comment by mininaim** [comment]
@yelsayed 

you need overwrite and custom CSS (inline-start/inline-end) and much more ..
the dir="rtl" is not enough 

quick example

the direction of items in the dropdown list 

<img width="432" height="417" alt="Image" src="https://github.com/user-attachments/assets/c04ff906-8f41-42d5-8a62-f347d9bbd0b6" />

quick example 

<img width="334" height="176" alt="Image" src="https://github.com/user-attachments/assets/1e10fac6-8a73-48ec-8244-28b346304268" />
