### ISSUE TITLE
How to make the body content dimmed or blurred when dialog is active?

### ISSUE THREAD

**Issue by milindgoel15** [shadcn-ui/ui#2749]
I want to make the body content dim or maybe blurred when any dialog is active. I currently did it using useEffect hook and manual state so if dialog becomes active, the body content except for dialog gets dimmed. But this is true only for 1 dialog, not for every dialog.

Could there be a feature where if any dialog becomes active, the body behind it gets dimmed? alternatively please suggest how to do it for all dialogs without declaring useState and useEffect wherever we use dialog component.

```tsx
   useEffect(() => {
      const body = document.getElementById("dashRoot");
      if (isDialogOpen) {
         body?.classList.add("dialogActive");
      } else {
         if (body?.classList.contains("dialogActive")) {
            body.classList.remove("dialogActive");
         }
      }
   }, [isDialogOpen]);
```

(I could make a custom hook that does this. but I wanted to do this without requiring to declare the hook as well)

**Comment by milindgoel15** [comment]
i meant dimmed as reduced opacity so the background doesn't scream along with dialog.

So it seems the DialogOverlay is not working for me. Do I have to import it to use it or I am missing something?

**Comment by servesh-chaturvedi** [comment]
Would be helpful if you could set up a codesandbox with a minimal reproducible example

**Comment by milindgoel15** [comment]
Not a fan of codesandbox or similar online IDE's but upon trying it in a fresh project with just shadcn dialog, the overlay seems to work. 

I guess some of my modifications to dialog component in my project made the overlay to not work. Need to figure out that then.

**Comment by milindgoel15** [comment]
Update: found out the cause. I had removed the class `bg-black/80` from the overlay, hence the issue. 

Many thanks for your time. I will close this issue now

**Comment by bennik88** [comment]
Is there an option to access the className attributes from the exposed components like <Dialog/> or anything else to change it without altering the source component? I tried everything I could but wasn't able to change the opacity.

**Comment by milindgoel15** [comment]
> Is there an option to access the className attributes from the exposed components like \u003CDialog/>

All the components do provide a prop to add any classnames you want.

**Comment by bennik88** [comment]
Thank you for your fast answer I really tried to add a depending prop to every part but it's not working for me to change the `bg-black/80` from the exposed component where would I add the className prop?

```
  <Dialog className=""> // I tried to set it here but it doesn't allow className here
        {/* <DialogContent className="" /> */} // I also added this exitra component for testing if it works to add this and add the className here but also no success
        <div>My Page Content</div>
        <DialogContent className="max-h-screen overflow-y-auto">
          <DialogHeader>d
            <DialogTitle></DialogTitle>
            <DialogDescription></DialogDescription>
          </DialogHeader>
          My Dialogs Content
        </DialogContent>
      </Dialog>
```

Where should I add the `className="bg-red-500/50"` prop to test it?

**Comment by milindgoel15** [comment]
> Where should I add the className=\"bg-red-500/50\" prop to test it?

Tbh it should work when you add it into the main Dialog component, to test, you could check if the styles are there in browser when you inspect element on it. If it seems to be not applying, one of the possible reasons I think could the black color is overriding your red color.

**Comment by bennik88** [comment]
I'm sorry but I think you're wrong. I tried to add it to the main Dialog lots of times and it never worked.

<img width="863" alt="Bildschirmfoto 2024-06-13 um 08 45 47" src="https://github.com/shadcn-ui/ui/assets/62398136/671c7302-91c4-4f53-87c8-f58c05d3de8b">
<img width="746" alt="Bildschirmfoto 2024-06-13 um 08 46 05" src="https://github.com/shadcn-ui/ui/assets/62398136/cd8a55d3-4541-4080-8d13-f2f5ff4aa2ff">

**Comment by Harikrishnareddyl** [comment]
Update `DialogOverlay` and `DialogContent` to accept additional parameter, so that you can have complete control over it

```tsx
const DialogOverlay = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Overlay>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Overlay> & { overlayOpacity: number }
>(({ overlayOpacity, className, ...props }, ref) => (
  <DialogPrimitive.Overlay
    ref={ref}
    className={cn(
      `fixed inset-0 z-50 ${overlayOpacity === 100 ? `bg-black` : `bg-black/${overlayOpacity}`}  data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0`,
      className
    )}
    {...props}
  />
))
DialogOverlay.displayName = DialogPrimitive.Overlay.displayName
```

And the `DialogContent`

```tsx
const DialogContent = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content> & { removeCloseIcon?: boolean, overlayOpacity?: number }
>(({ removeCloseIcon = false, overlayOpacity = 80, className, children, ...props }, ref) => (
  <DialogPortal>
    <DialogOverlay overlayOpacity={overlayOpacity} />
    <DialogPrimitive.Content
      ref={ref}
      className={cn(
        "fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg",
        className
      )}
      {...props}
    >
      {children}
      {!removeCloseIcon && (
        <DialogPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground">
          <Cross2Icon className="h-4 w-4" />
          <span className="sr-only">Close</span>
        </DialogPrimitive.Close>
      )}
    </DialogPrimitive.Content>
  </DialogPortal>
))
DialogContent.displayName = DialogPrimitive.Content.displayName
```

i have additional option to remove default close icon for my use case
