### ISSUE TITLE
Invalidating an Input component?

### ISSUE THREAD

**Issue by dBianchii** [shadcn-ui/ui#275]
I was wondering if there is recommended a way to show feeback to the user manually if the data provided in an input component is invalid ?
Show a red outline around the input and some error message for example.

**Comment by abhinav-anshul** [comment]
There are no official recommendations as Shadcn is based on Radix.  You can use native HTML methods for validation such as `onChange` or `pattern` attribute

**Comment by otatar** [comment]
There should be a clear way if doing this. Not everyone uses React Hook Form...
