### ISSUE TITLE
Less questions asked while installing

### ISSUE THREAD

**Issue by dv64bit** [shadcn-ui/ui#2761]
![image](https://github.com/shadcn-ui/ui/assets/72154120/4aaaabe1-0026-4634-9be9-f944f04f1ff5)
While installing the shadcn in my next js project I am begin asked less questions and I think that is causing problem in project

**Comment by aidanCQ** [comment]
Where are you configuring shadcn? I don't see any shadcn configuration happening in the image you sent.

**Comment by kevinmitch14** [comment]
This is Next.js installation.

**Comment by dan5py** [comment]
Hi @kevinmitch14, in the screenshot provided you're initializing the nextjs project, to add shadcn-ui you need to run:
```bash
npx shadcn-ui@latest init
```

For further info check the docs [here](https://ui.shadcn.com/docs/installation/next).

**Comment by kevinmitch14** [comment]
> Hi @kevinmitch14, in the screenshot provided you're initializing the nextjs project

This is not my issue @dan5py, @dv64bit posted it!

**Comment by dan5py** [comment]
> > Hi @kevinmitch14, in the screenshot provided you're initializing the nextjs project
> 
> This is not my issue @dan5py, @dv64bit posted it!

Sorry, wrong mention 😅

**Comment by dv64bit** [comment]
> Where are you configuring shadcn? I don't see any shadcn configuration happening in the image you sent.

Sorry guys added the wrong screenshot by mistake
here is the correct one
![image](https://github.com/shadcn-ui/ui/assets/72154120/f6da9334-a65f-4f73-8aff-bfef25f62900)

**Comment by jcohenho** [comment]
@kevinmitch14 what if you wanted to start over from scratch and use the default configs? A second run no longer provides you with the same questions.

**Comment by kevinmitch14** [comment]
Apologies I kinda misunderstood the issue - but check here https://github.com/shadcn-ui/ui/pull/2454

> now automatically detects paths for your tailwind.config.js, main globals.css file and your custom path aliases
> You're only prompted for style, baseColor and cssVariables.

Not sure if there is a way to set these via CLI atm, but you can check in your components.json file to see what it outputs and detect issues - https://ui.shadcn.com/docs/components-json

**Comment by dv64bit** [comment]
> Apologies I kinda misunderstood the issue - but check here https://github.com/shadcn-ui/ui/pull/2454
> 
> > now automatically detects paths for your tailwind.config.js, main globals.css file and your custom path aliases
> > You're only prompted for style, baseColor and cssVariables.
> 
> Not sure if there is a way to set these via CLI atm, but you can check in your components.json file to see what it outputs and detect issues - https://ui.shadcn.com/docs/components-json
> 
> You can use the older version of the CLI before these changes - `pnpm dlx shadcn-ui@0.7.0 init`. Then you will get all the old prompts like before.

Got it, thank you so much, it was really helpful ✨
