### ISSUE TITLE
Specify which folder the component gets copypasta to

### ISSUE THREAD

**Issue by kyhyco** [shadcn-ui/ui#2786]
Hello!

When you run `npx shadcn-ui@latest add sonner`, this will copy the component nested under the main component folder i.e. `src/components/ui/sonner`.

Is there a way to specify so that the components will be added to `src/components` instead of `src/components/ui`?

Thanks!

**Comment by kevinmitch14** [comment]
You can use -p or --path - https://ui.shadcn.com/docs/cli#add

```tsx
Usage: shadcn-ui add [options] [components...]

add a component to your project

Arguments:
  components         the components to add

Options:
  -y, --yes          skip confirmation prompt. (default: false)
  -o, --overwrite    overwrite existing files. (default: false)
  -c, --cwd <cwd>    the working directory. defaults to the current directory.
  -p, --path <path>  the path to add the component to.
  -h, --help         display help for command
```

**Comment by kyhyco** [comment]
Ah.... that worked! thank you!
