### ISSUE TITLE
ScrollArea Doesnt Work with @studio-freight/react-lenis

### ISSUE THREAD

**Issue by shahidx0x** [shadcn-ui/ui#2797]
i was following this [instruction](https://devdreaming.com/blogs/nextjs-smooth-scrolling-with-lenis-gsap) of smooth scroll with react-lenis after implementing this i found the scroll area of shadcn is not working i have to manually drag the scrollbar in order to work . is this bug or i am missing somthing . here is the code that i am using in my project

SmoothScroll.tsx
![image](https://github.com/shadcn-ui/ui/assets/34656196/b82a1ce5-c44b-4863-a698-eb8b0bad0bad)
Layout.tsx
![image](https://github.com/shadcn-ui/ui/assets/34656196/44b51c17-821b-4012-9fbb-e6092c455b44)

**Result**
ScrollArea of ShadCN not working

**Comment by Sellucas** [comment]
Did you find a solution?

**Comment by Sellucas** [comment]
Just add data-lenis-prevent to the component <div class="some-class" data-lenis-prevent></div>

**Comment by oswaldohuillca** [comment]
thank!
