### ISSUE TITLE
`TooltipContainer` should be wrapped on a `<Tooltip.Portal>`

### ISSUE THREAD

**Issue by pedroapfilho** [shadcn-ui/ui#2804]
There are some cases where you remove the tooltip trigger from the node, and the tooltip content goes into a weird state, where it's rendered on the page by default when you render the tooltip trigger back (when you put a tooltip on a `Sheet` component, for example.

For this, the `TooltipContent` could be simply wrapped into a Portal, like this:

```tsx
const TooltipContent = React.forwardRef<
  React.ElementRef<typeof TooltipPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Content>
>(({ className, sideOffset = 4, ...props }, ref) => (
  <TooltipPrimitive.Portal>
    <TooltipPrimitive.Content
      ref={ref}
      sideOffset={sideOffset}
      className={cn(
        "z-50 overflow-hidden rounded-md bg-primary px-3 py-1.5 text-xs text-primary-foreground animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
        className
      )}
      {...props}
    />
  </TooltipPrimitive.Portal>
))
```

This would solve the issue for this specific case. Is there any reason why the Portal wasn't used before?

**Comment by aidanCQ** [comment]
Couldn't you add your own Portal instead? I've had issues with the inclusion of portals by default, in particular the dropdown menu.

**Comment by pedroapfilho** [comment]
Oh, we could add another component for the Portal, but it would be nice to have it at least available as `TooltipPortal`

**Comment by zeroliu** [comment]
I find this inconsistent with Popover. PopoverContent has a portal wrapper by default but I was surprised that it isn't the case in TooltipContent

**Comment by zeroliu** [comment]
> Couldn't you add your own Portal instead? I've had issues with the inclusion of portals by default, in particular the dropdown menu.

@aidanCQ do you mind sharing more details about what was your issue?

**Comment by aidanCQ** [comment]
> > Couldn't you add your own Portal instead? I've had issues with the inclusion of portals by default, in particular the dropdown menu.
> 
> @aidanCQ do you mind sharing more details about what was your issue?

The dropdown menu was portalling content to the document body which I didn't want so I removed the portal in my own code.

```tsx
 <DropdownMenuPrimitive.Portal> //<-- REMOVED
    <DropdownMenuPrimitive.Content
      ref={ref}
      sideOffset={sideOffset}
      className={cn(
        "z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md",
        "data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
        className
      )}
      {...props}
    />
  </DropdownMenuPrimitive.Portal> //<-- REMOVED
```
