### ISSUE TITLE
Unhandled Runtime Error - "Cannot redefine property: googletag" in Next.js App

### ISSUE THREAD

**Issue by euhansarkar** [shadcn-ui/ui#2837]
I am creating a new Next.js app and encountered an error during installation of shadcn-ui. When I ran the command  "pnpm dev", I received the following error:

`Unhandled Runtime Error
TypeError: Cannot redefine property: googletag`

I am using Next.js version 14.1.0 and the following dependencies:
react: ^18
react-dom: ^18

![Screenshot_2](https://github.com/shadcn-ui/ui/assets/83771568/3aad4c8f-980a-406e-ba26-13a01ea90488)

I have tried restarting my development server and clearing my npm cache, but the issue persists.

**Comment by navjotsherry** [comment]
I am also facing the same issue...

**Comment by Kulbir-Singh** [comment]
I deleted the node modules folder and .next folder and reinstalled the node modules and it seemed to get rid of the issue for me.

**Comment by philipfrancis139** [comment]
I am also facing same error

**Comment by euhansarkar** [comment]
Hi everyone, I wanted to apologize for the previous issue. It turns out it was caused by a conflict with a browser extension I'm using called "Stands" (an ad blocker). Once I disabled it, the errors disappeared.

I just wanted to share this experience in case anyone else encounters similar problems. It might be helpful to temporarily disable all browser extensions and then re-enable them one by one to see if any are causing issues.

I hope this information is useful!

**Comment by francescotau** [comment]
Disabling "Stands" the error disappeared, but the following still persists:

`Uncaught SyntaxError: Identifier 'observeDomChanges' has already been declared (at ruleApplier.js:1:1)`

**Comment by JohannesHamann** [comment]
@euhansarkar Thank you for sharing! Had the same issue as well. Turning off "Stands" solved both issues 
  1) Unhandled Runtime Error TypeError: Cannot redefine property: googletag
  2) Uncaught SyntaxError: Identifier 'observeDomChanges' has already been declared (at ruleApplier.js:1:1)
for me.
