### ISSUE TITLE
Minor fix for Next.js font setup

### ISSUE THREAD

**Issue by dev-abir** [shadcn-ui/ui#2853]
I just followed the step-by-step guide written [here](https://ui.shadcn.com/docs/installation/next), but the fonts won't load. A simple fix is to just use className instead of CSS variable name on the body.
Basically, on **step 1**:
Change:
```Javascript
className={cn(
  "min-h-screen bg-background font-sans antialiased",
  fontSans.variable
)}
```
to:
```Javascript
className={cn(
  "min-h-screen bg-background font-sans antialiased",
  fontSans.className
)}
```
Just a small typo...

**Comment by lloydrichards** [comment]
I'm using the `.variable` method in just about all of my NextJS project, I can confirm that it works.  Did you make sure to add the font in your tailwind.config.ts too? 
```typescript
fontFamily: {
        sans: ["var(--font-sans)", ...fontFamily.sans],
      },
```
and then the utility class `font-sans` to the body of the html?

To check it working, just going into inspect and search you styles for the className with `--font-sans` in it

**Comment by dev-abir** [comment]
Yeah it was my fault. I actually changed the name of that variable to `--font-itim`.

Adding `fontSans.variable` basically introduces that font into the markup, next we add that variable to tailwind. Now on using `font-sans` class on an element it applies that font.
