### ISSUE TITLE
Scroll back to top on drawer closed

### ISSUE THREAD

**Issue by KyawZinLatt** [shadcn-ui/ui#2856]
Hi all, 

I am very new to react and Shadcn UI, I am using Shadcn UI in my Next.js project. I am trying to solve the behavior of scrolling back to top when the drawer is closed. But still not managed to find the effective solution

**Comment by shayant98** [comment]
Experiencing this as well, hoping for a possible fix

**Comment by shayant98** [comment]
@KyawZinLatt

Firstly make sure you have atleast  vaul: 0.9.0


to fix this add ```preventScrollRestoration``` to your Drawer root component ```<Drawer>```

it should look something like this:
```jsx

 <Drawer preventScrollRestoration>...</Drawer>
```

**Comment by DhruvKulkarni86** [comment]
> @KyawZinLatt
> 
> Firstly make sure you have at least
> 
> ```json
> "vaul": "^0.9.0"
> ```
> 
> to fix this add `preventScrollRestoration` to your Drawer root component `<Drawer>`
> 
> it should look something like this:
> 
> ```js
>  <Drawer preventScrollRestoration>...</Drawer>
> ```

![image](https://github.com/user-attachments/assets/fd3084c6-969c-46e6-a509-d2dbdfa7ad75)
That prop doesn't exist for the root drawer component
