### ISSUE TITLE
Calendar set's date to undefined when same date selected and this give inconsistent behavior!

### ISSUE THREAD

**Issue by Hussseinkizz** [shadcn-ui/ui#2857]
# Problem
Apparently what the calendar provides on select is inconsistent, it can be date or undefined, and when using the format to format this given date, it raises an error as the format function can't format an undefined date. 
The undefined date is given if the same date is selected twice, that is if previous selected date is same as new selected date...

# Hacky Solution:
I have to do some hack around this but it should be fixed in some way, this is what I did for now:
![date-selector](https://github.com/shadcn-ui/ui/assets/59565430/fccbc8ed-2ca8-4889-9371-70bcc6842264)

Utimately we should be able to select the same date without issues, also add ability to select a specific year, thanks!

**Comment by lloydrichards** [comment]
This might better addressed with the [React DayPicker](https://github.com/gpbl/react-day-picker) Issues since shadcn/ui is only injecting the components with tailwind classnames. 🤷‍♂️

**Comment by Hussseinkizz** [comment]
Hmm sure, your right!
