### ISSUE TITLE
Card overflow hidden best practices?

### ISSUE THREAD

**Issue by joewagner** [shadcn-ui/ui#2885]
I'm using the Card component and I want the tailwind `overflow-hidden` class on every card, and I'm wondering what best practices are for using shadcn/ui.
Some ideas:
 - Update the copy/pasted component, but when a new release of this component becomes available I'll potentially lose my customizations.
 - Add the class to every place I use the Card. This seems obviously wrong. 
 - Create a component that uses the shadcn component with the added class.
 - Open a PR here with the added class.  I can't imagine someone wanting the Card to have anything but overflow: hidden, or overflow: scroll.  Maybe the fact there's two obvious options is the reason the Card component doesn't already have some overflow defined?

Thanks for any guidance/opinions/rants, and thanks for making this code available,

**Comment by servesh-chaturvedi** [comment]
You can include that class in the `/components/ui/card.tsx` (however you've organised if not using defaults) which looks like [this](https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/card.tsx)
```diff
const Card = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
-      "rounded-lg border bg-card text-card-foreground shadow-sm",
+      "rounded-lg border bg-card text-card-foreground shadow-sm overflow-hidden",
      className
    )}
    {...props}
  />
))
Card.displayName = "Card"
```

This lets all the card get that default overflow-hidden which you can modify like  `Card className='overflow-visible'`

Here is a great article to help you understand the flow better : https://manupa.dev/blog/anatomy-of-shadcn-ui

**Comment by joewagner** [comment]
That makes sense, thanks for the help!
