### ISSUE TITLE
Radix and Shadcn conflict in Next.js 14

### ISSUE THREAD

**Issue by meddhiaka** [shadcn-ui/ui#2895]
Does installing both `Radix` and `Shadcn` dependencies in the same `Next.js 14` project lead to  conflicts such as module naming issues? 

if so, how can I prevent these conflicts from occurring?

**Comment by shadcn** [comment]
No. You do not install `shadcn/ui`. Use the cli and it will scaffold the components and add  the radix dependencies for you. From there, you can manage the radix dependencies like any other project.
