### ISSUE TITLE
popover placement

### ISSUE THREAD

**Issue by hamzasaleem2** [shadcn-ui/ui#2900]
### Feature description

possible to make placement inside popover? regular: right,left,top,bottom 

example:
`<popover placement="right"/>
`
### Affected component/components

popover

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by Nagalsky** [comment]
@hamzasaleem2 https://www.radix-ui.com/primitives/docs/components/popover#content - take a look side and align props

**Comment by hamzasaleem2** [comment]
can't believe i missed it. thanks!

needed two things to make it look like this, just incase anyone else is looking for it.

<img width="477" alt="image" src="https://github.com/shadcn-ui/ui/assets/133140745/906f28c3-771f-4d3e-9821-e5280443508d">


`add side to className`
`include side={side} in content ref`
`set align to "start"`

```
const PopoverContent = React.forwardRef<
  React.ElementRef<typeof PopoverPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof PopoverPrimitive.Content> >(
  (
    { className, align = "start", side = "right", sideOffset = 4, ...props },
    ref
  ) => (
    <PopoverPrimitive.Portal>
      <PopoverPrimitive.Content
        ref={ref}
        align={align}
        side={side}
        sideOffset={sideOffset}
        className={cn(
          "z-50 w-72 rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
          className
        )}
        {...props}
      />
    </PopoverPrimitive.Portal>
  )
)
```
