### ISSUE TITLE
[feat]: Tabs Component same as shadcn website

### ISSUE THREAD

**Issue by Hitesh-Sisara** [shadcn-ui/ui#2928]
### Feature description

I would like to propose the addition of another tabs component, similar/same to the one used on [ui.shadcn.com](https://ui.shadcn.com/docs/components/tabs) ---

<img width="607" alt="Screenshot 2024-03-07 at 12 33 28 AM" src="https://github.com/shadcn-ui/ui/assets/72780174/ad53e7a8-1b4a-4fec-aa08-fb5fa633aa67">

### Affected component/components

Tabs

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by premiare** [comment]
Here is the code from the documentation. When the TabsList and TabsTrigger are being used, the className's added overwrite the components styles - allows customization. If you wanted to create variants, you can create variants in the `ui\tabs.tsx` file with `cva` or you can just alter the styles completely in there

```tsx
<TabsList className="w-full justify-start rounded-none border-b bg-transparent p-0">
  <TabsTrigger
    value="preview"
    className="relative rounded-none border-b-2 border-b-transparent bg-transparent px-4 pb-3 pt-2 font-semibold text-muted-foreground shadow-none transition-none data-[state=active]:border-b-primary data-[state=active]:text-foreground data-[state=active]:shadow-none"
  >
    Preview
  </TabsTrigger>
  <TabsTrigger
    value="code"
    className="relative rounded-none border-b-2 border-b-transparent bg-transparent px-4 pb-3 pt-2 font-semibold text-muted-foreground shadow-none transition-none data-[state=active]:border-b-primary data-[state=active]:text-foreground data-[state=active]:shadow-none"
  >
    Code
  </TabsTrigger>
</TabsList>
```

Before:
![image](https://github.com/shadcn-ui/ui/assets/64188227/f44602be-1b97-458f-80c5-cd2f5496499c)
After:
![image](https://github.com/shadcn-ui/ui/assets/64188227/121f2a9f-da0a-4ac9-a775-e4d23cd07aa4)

**Comment by Hitesh-Sisara** [comment]
> Here is the code from the documentation. When the TabsList and TabsTrigger are being used, the className's added overwrite the components styles - allows customization. If you wanted to create variants, you can create variants in the `ui\tabs.tsx` file with `cva` or you can just alter the styles completely in there
> 
> ```tsx
> <TabsList className="w-full justify-start rounded-none border-b bg-transparent p-0">
>   <TabsTrigger
>     value="preview"
>     className="relative rounded-none border-b-2 border-b-transparent bg-transparent px-4 pb-3 pt-2 font-semibold text-muted-foreground shadow-none transition-none data-[state=active]:border-b-primary data-[state=active]:text-foreground data-[state=active]:shadow-none"
>   >
>     Preview
>   </TabsTrigger>
>   <TabsTrigger
>     value="code"
>     className="relative rounded-none border-b-2 border-b-transparent bg-transparent px-4 pb-3 pt-2 font-semibold text-muted-foreground shadow-none transition-none data-[state=active]:border-b-primary data-[state=active]:text-foreground data-[state=active]:shadow-none"
>   >
>     Code
>   </TabsTrigger>
> </TabsList>
> ```
> 
> Before: ![image](https://private-user-images.githubusercontent.com/64188227/311073275-f44602be-1b97-458f-80c5-cd2f5496499c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODU3NDIsIm5iZiI6MTcwOTg4NTQ0MiwicGF0aCI6Ii82NDE4ODIyNy8zMTEwNzMyNzUtZjQ0NjAyYmUtMWI5Ny00NThmLTgwYzUtY2QyZjU0OTY0OTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA4MTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NWI4ZWE5ODJlMTlkNDc4MzNiZmE2YTBjOTdhMWVhM2EwMzUwYzFlMTE2OTI0MmYyMDRmNTNmYmQzMDFlMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H98r1DWaqoS_GWQqKyfs8jA1X7K0XcdMe5MpVRXEvv4) After: ![image](https://private-user-images.githubusercontent.com/64188227/311073112-121f2a9f-da0a-4ac9-a775-e4d23cd07aa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODU3NDIsIm5iZiI6MTcwOTg4NTQ0MiwicGF0aCI6Ii82NDE4ODIyNy8zMTEwNzMxMTItMTIxZjJhOWYtZGEwYS00YWM5LWE3NzUtZTRkMjNjZDA3YWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA4MTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlM2JlZGY0Yzc0ZGQxMjk0ZGM4Y2I5YjEwYWY3MDc5OTViMzFkMjhlYjZhNmFkZGQ5YzliNDBmNDY2MmJlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GB5ZLilHs781wC7XeYlZzpD8eQKBRNfsH5uTkiSEwSk)

thanks
