### ISSUE TITLE
[Bug]: Dialog not working properly when used with accordion

### ISSUE THREAD

**Issue by arthurMancioSales** [shadcn-ui/ui#2929]
### Describe the bug

I have a page that has an accordion with some cards inside of it. Each accordion trigger also has a button that works as a trigger to open a modal, with a form to update some aspects of the accordion. However, if I interact with the modal when it's open, the accordion toggles between open and close. I  also noticed that the modal closes when my cursor leaves the modal area. The same happens if I switch between browser tabs or desktop windows, so I can't even use inspector to find out why this is happening. 

I tried to use states to control both accordion and modal but found no change in this behavior. Any idea of why this is happening?

### Affected component/components

Accordon, dialog

### How to reproduce

1. Insert an accordion in a page
2. Insert a dialog trigger inside the accordion trigger
3. Open the modal and interact with it

### System Info

```bash
SO: Ubuntu 22.04
Browser: Vivaldi
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by krouskystepan** [comment]
like this:
```
      <Dialog>
        <Accordion type="single" className="w-80" collapsible>
          <AccordionItem value="item-1">
            <AccordionTrigger>Dialog?</AccordionTrigger>
            <AccordionContent>
              <DialogTrigger>Open</DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Are you absolutely sure?</DialogTitle>
                  <DialogDescription>
                    This action cannot be undone. This will permanently delete
                    your account and remove your data from our servers.
                  </DialogDescription>
                </DialogHeader>
              </DialogContent>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </Dialog>
```

**Comment by Tom-DK** [comment]
For me passing `onClick={e => e.stopPropagation()}` both as parameter for components `DialogTrigger` and `DialogContent` also did the job.
