### ISSUE TITLE
[Bug]: Documentation - The code for responsive Breadcrumb is empty and the Breadcrumb is not responsive.

### ISSUE THREAD

**Issue by alamenai** [shadcn-ui/ui#2977]
### Describe the bug

![image](https://github.com/shadcn-ui/ui/assets/20143684/0adbcb88-0645-41ac-b347-865c92b0b62a)

### Affected component/components

Breadcrumb

### How to reproduce

.

### System Info

```bash
.
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by xcv367** [comment]
Can confirm when you click on the "Code" tab for Responsive breadcrumb, no code is shown.

Maybe the code isn't available in the storybook? This might not be a bug, just unavailable example code.

**Comment by alamenai** [comment]
@xcv367 , It is resolved , I can see the Drawer now.
