### ISSUE TITLE
[feat]: How to disable Dialog and click on the background to close the window

### ISSUE THREAD

**Issue by qianmoQ** [shadcn-ui/ui#3004]
### Feature description

Describe your feature request...How to disable Dialog and click on the background to close the window

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by kevinmitch14** [comment]
I think this should do the trick
```tsx
<Dialog modal={false}>
```

**Comment by kevinmitch14** [comment]
Just to make sure, you want to disable the ability to close the dialog by clicking outside? 

For this, use `<AlertDialog />`, https://ui.shadcn.com/docs/components/alert-dialog

**Comment by shishirdeshmukh** [comment]
i have solved this issue by adding  onPointerDownOutside={(e) => e.preventDefault()} in my DialogContent 

See Below:
 <Dialog open={isOpen} onOpenChange={onClose}>
        <DialogContent
          className="sm:max-w-[425px]"
          onPointerDownOutside={(e) => e.preventDefault()}
        >
          {content}
        </DialogContent>
      </Dialog>
