### ISSUE TITLE
[Bug]:  Tailwind breaks completely  after adding shadcn

### ISSUE THREAD

**Issue by ImamJanjua** [shadcn-ui/ui#3020]
### Describe the bug

My whole app was working fine till i wanted to add this library which broke the Tailwind of the application.

<img width="1440" alt="Bildschirmfoto 2024-03-15 um 16 21 38" src="https://github.com/shadcn-ui/ui/assets/137432044/dacecab0-8b53-4ea9-a671-b865d382e8db">
<img width="1440" alt="Bildschirmfoto 2024-03-15 um 16 21 44" src="https://github.com/shadcn-ui/ui/assets/137432044/553e3d63-59de-4dff-a4f3-df430bdab31c">
<img width="1440" alt="Bildschirmfoto 2024-03-15 um 16 22 01" src="https://github.com/shadcn-ui/ui/assets/137432044/78ba7fef-4003-4f16-b6ac-5580473ecf56">
<img width="1440" alt="Bildschirmfoto 2024-03-15 um 16 21 51" src="https://github.com/shadcn-ui/ui/assets/137432044/1ce9b594-deca-4745-9b70-8ef664582a2c">
<img width="1440" alt="Bildschirmfoto 2024-03-15 um 16 22 07" src="https://github.com/shadcn-ui/ui/assets/137432044/33dad27a-c766-4278-b6d4-d5c0fd1b2ecb">

### Affected component/components

Button

### How to reproduce

...

### Codesandbox/StackBlitz link

.

### Logs

```bash
.
```

### System Info

```bash
Vite app
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by servesh-chaturvedi** [comment]
Can you try making the `rsc` to false in `components.json` file as it only works in Next.js application. Then remove the previous components and add them again. Not really sure it will solve the problem but that configuration is wrong.

**Comment by ImamJanjua** [comment]
didn't helped

**Comment by shaman-004** [comment]
Hi, @ImamJanjua So you can resolve this by importing [import 'tailwindcss/tailwind.css'] in your main.jsx I am not sure about in vite but in nextjs you can import in layout.ts or layout.js.

**Comment by servesh-chaturvedi** [comment]
It would be helpful to get a repo or sandbox link if the issue is still not resolved.

**Comment by ImamJanjua** [comment]
> Hi, @ImamJanjua So you can resolve this by importing [import 'tailwindcss/tailwind.css'] in your main.jsx I am not sure about in vite but in nextjs you can import in layout.ts or layout.js.

It works, but than tailwind config don't work correctly since its than not using the the dependent styles from index.css
<img width="1440" alt="Bildschirmfoto 2024-03-17 um 16 46 38" src="https://github.com/shadcn-ui/ui/assets/137432044/cef21077-fa47-4a27-9402-aae96769e7db">
