### ISSUE TITLE
[Bug]: ComboBox - PopoverContent box width wont change to match the Input 

### ISSUE THREAD

**Issue by a1danw** [shadcn-ui/ui#3045]
### Describe the bug

After a lot of hacking this thing to bits ive managed to get the input selector to change to 100% width but now I cant get the PopoverContent to match. I find it bizzare that these can only be fixed widths. Surely the widths should be adjustable for responsiveness. All I want is both widths to be 100% :(
<img width="815" alt="Screenshot 2024-03-18 at 19 26 46" src="https://github.com/shadcn-ui/ui/assets/81640788/9e6fff03-98b3-4085-8abe-9e43b0b76930">

### Affected component/components

Combobox

### How to reproduce

Literally try anything to make the width 100% or responsive
<img width="815" alt="Screenshot 2024-03-18 at 19 26 46" src="https://github.com/shadcn-ui/ui/assets/81640788/234a7c9b-586d-46fe-ab69-cb9fe60f6394">

### System Info

```bash
n/a
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by junwen-k** [comment]
You can add `w-[--radix-popover-trigger-width]` or `w-[var(--radix-popover-trigger-width)]` class to your popover content so that it will automatically fits based on the trigger width. For reference, see [here](https://www.radix-ui.com/primitives/docs/components/popover#constrain-the-content-size).

```tsx
<PopoverContent
  className="w-[--radix-popover-trigger-width] ..."
>
  ...
</PopoverContent>
```

**Comment by wasimsandhu** [comment]
`w-[var(--radix-popover-trigger-width)]` worked for me with Tailwind 4!

**Comment by TharukaDananjaya** [comment]
w-[--radix-popover-trigger-width] this is worked for me. thank you @junwen-k

**Comment by Aspireve** [comment]
This is a serious life-saver, Thanks @junwen-k

**Comment by thisisbintang** [comment]
> You can add `w-[--radix-popover-trigger-width]` or `w-[var(--radix-popover-trigger-width)]` class to your popover content so that it will automatically fits based on the trigger width. For reference, see [here](https://www.radix-ui.com/primitives/docs/components/popover#constrain-the-content-size).
> 
> <PopoverContent
>   className="w-[--radix-popover-trigger-width] ..."
> >
>   ...
> </PopoverContent>
> 
> If you are using Tailwind V4, you can also use the CSS variable syntax `w-(--radix-popover-trigger-width)`.

thanks bro, you saved my cat.

**Comment by ChoaibMouhrach** [comment]
style={{ width: "var(--radix-popper-anchor-width)" }}

**Comment by suiramdev** [comment]
Alternatively I used to use https://www.npmjs.com/package/@radix-ui/react-use-size but I prefer the `style` solution! Good catch
