### ISSUE TITLE
[Bug]: `Module '"input-otp"' has no exported member 'OTPInputContext'.ts(2305)` 

### ISSUE THREAD

**Issue by flixlix** [shadcn-ui/ui#3064]
### Describe the bug

Since the last commit, I noticed that there is a new context being imported from `input-otp`.
I tried reinstalling this module but I still get the error that this context is not exported from the package.

### Affected component/components

InputOTP

### How to reproduce

1. Open project in `apps/www/registry/default/ui/input-otp.tsx`
2. See this error:
<img width="761" alt="image" src="https://github.com/shadcn-ui/ui/assets/61006057/353902c5-0605-4a88-b5fd-2baee9a5773b">

### Codesandbox/StackBlitz link

N/A

### System Info

```bash
MacOS, VSCode
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by guilhermerodz** [comment]
hi @flixlix make sure you have ran `npm i input-otp@-latest` to ensure it's the latest version.

let me know if that works?

**Comment by flixlix** [comment]
yep, that fixed it, thanks!
