### ISSUE TITLE
when i use `<Toaster/>` in app/layout.js page it show me hydration error in Next.js (14.2.0-canary.33)

### ISSUE THREAD

**Issue by abhishek9473** [shadcn-ui/ui#3071]
when i use `<Toaster/>` in app/layout.js page it show me hydration error 

i mention the file below

error show - Expected server HTML to contain a matching `<div>` in `<body>`.

app/layout.js file -
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryClientProvider from "@/providers/ReactQueryClientProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ResumeFits",
  description: "resumefits homepage",
};

export default function RootLayout({ children }) {
  return (
    `<html lang="en">`
      `<ReactQueryClientProvider>`
        `<body className={inter.className}>`
          {children}
        `<Toaster/>`
        `</body>`
      `</ReactQueryClientProvider>`
    `</html>`
  );
}

_Originally posted by @abhishek9473 in https://github.com/shadcn-ui/ui/discussions/3070_

**Comment by suhailkassar11** [comment]
try this inside the function where you used the toast

const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  if (!isMounted) {
    return null;
  }

**Comment by rohith02b** [comment]
Create a client component having the <Toaster /> component and import it in the layout or create a client layout.

**Comment by HatunaPatata** [comment]
> Create a client component having the Toaster component and import it in the layout or create a client layout.

Perfect! Thank you very much.
