### ISSUE TITLE
[Bug]: clicking inside Drawer component often closes the drawer

### ISSUE THREAD

**Issue by capaj** [shadcn-ui/ui#3093]
### Describe the bug

click on plus or minus multiple times. 
![image](https://github.com/shadcn-ui/ui/assets/1305378/f4415792-5b73-4c76-86b5-86c5411e4080)

result: drawer gets closed

expected result: drawer stays open

### Affected component/components

Drawer

### How to reproduce

open https://ui.shadcn.com/docs/components/drawer

and try to click on + or - multiple times

### System Info

```bash
dunno
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by capaj** [comment]
works like a charm, thanks!

**Comment by AndonMitev** [comment]
Hey i have updated vaul from `0.9.0` to `0.9.1` but still closing after clicking a button i also control it with a boolean for open which state is true but modal is getting closed any ideas?

cc @capaj @ylyra

**Comment by capaj** [comment]
@AndonMitev nuke you node_modules and let us know if that does not work for you.
