### ISSUE TITLE
[Bug]: cmdk version 1.0.0 broken in Astro app

### ISSUE THREAD

**Issue by desiboli** [shadcn-ui/ui#3127]
### Describe the bug

Using the latest cmdk component with cmdk version 1.0.0 is not working properly, the dialog opens as usual but you cannot select or hover an item.

### Affected component/components

Command

### How to reproduce

Setup new Astro project with shadcn ui and add the Command component.

### Codesandbox/StackBlitz link

https://stackblitz.com/edit/withastro-astro-1dtsvr?file=src%2Fstyles%2Fglobals.css

### System Info

```bash
.
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by desiboli** [comment]
Downgrading to `"cmdk": "^0.2.1"` works.

**Comment by gustaveWPM** [comment]
Same issue here!

**Comment by Jamess-Lucass** [comment]
Should be resolved by changing the disabled related classes within `CommandItem`

Before:
`data-[disabled]:pointer-events-none data-[disabled]:opacity-50`

After:
`disabled:pointer-events-none disabled:opacity-50`

Example.
```typescript
const CommandItem = React.forwardRef<
  React.ElementRef<typeof CommandPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof CommandPrimitive.Item>
>(({ className, ...props }, ref) => (
  <CommandPrimitive.Item
    ref={ref}
    className={cn(
      "relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground disabled:pointer-events-none disabled:opacity-50",
      className
    )}
    {...props}
  />
))

```

**Comment by gustaveWPM** [comment]
> Should be resolved by changing the disabled related classes within `CommandItem`
> 
> Before: `data-[disabled]:pointer-events-none data-[disabled]:opacity-50`
> 
> After: `disabled:pointer-events-none disabled:opacity-50`
> 
> Example.
> 
> ```ts
> const CommandItem = React.forwardRef<
>   React.ElementRef<typeof CommandPrimitive.Item>,
>   React.ComponentPropsWithoutRef<typeof CommandPrimitive.Item>
> >(({ className, ...props }, ref) => (
>   <CommandPrimitive.Item
>     ref={ref}
>     className={cn(
>       "relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground disabled:pointer-events-none disabled:opacity-50",
>       className
>     )}
>     {...props}
>   />
> ))
> ```

It fixes my problem. Thanks a lot!

**Comment by Jamess-Lucass** [comment]
Also related #3024
