### ISSUE TITLE
[feat]: Links that look like button

### ISSUE THREAD

**Issue by Jatinchhabra21** [shadcn-ui/ui#3129]
### Feature description

Buttons are used wherever we want to perform actions if they are clicked by users. For redirecting users to a new page anchor tags should be used. I ran into a scenario where I wanted to redirect user to another page (login/signup) but want those links to look like button.

### Affected component/components

Button

### Additional Context

For now I have updated Button component, but the implementation is really poor and have many edge cases that are not covered and it only supports my use case. I believe this can be implemented in much more elegant way.

```typescript
export interface ButtonProps
	extends React.ButtonHTMLAttributes<HTMLButtonElement>,
		VariantProps<typeof buttonVariants> {
	asChild?: boolean;
	role?: 'button' | 'link';
	to?: string;
	ctaText?: string;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
	(
		{ className, variant, size, role, to, ctaText, asChild = false, ...props },
		ref
	) => {
		if (role === undefined || role === 'button') {
			const Comp = asChild ? Slot : 'button';
			return (
				<Comp
					className={cn(buttonVariants({ variant, size, className }))}
					ref={ref}
					{...props}
				/>
			);
		} else {
			return (
				<Link
					className={cn(buttonVariants({ variant, size, className }))}
					to={to ?? '#'}
				>
					{ctaText}
				</Link>
			);
		}
	}
);
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by ylyra** [comment]
you can use the asChild to get the same result, like:

```tsx
<Button asChild>
  <Link href="/hello">Hello World</Link>
</Button>
```

More about it here: [radix-slots](https://www.radix-ui.com/primitives/docs/utilities/slot)

**Comment by Jatinchhabra21** [comment]
oh, I didn't know it could be done this way, thanks for letting me know. Closing this issue.
