### ISSUE TITLE
[bug]: Input with number type doesn't respond to fast clicks

### ISSUE THREAD

**Issue by theDanielJLewis** [shadcn-ui/ui#3220]
### Describe the bug

The "number" input does not increment for fast mouse clicks on the increment or decrement buttons.

For example, I would expect a double-click to increment the number twice, but it increments only once.

In fact, if I keep clicking at the same fast pace, the number never increments.

It seems limited to around one increment per second.

### Affected component/components

Input

### How to reproduce

1. Insert an Input component onto a page: `<Input type="number" />`.
2. Load the page in a browser.
3. Click the input increment or decrement buttons faster than once per second.

### System Info

```bash
Arc (Chrome), macOS, Next.js 14
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by theDanielJLewis** [comment]
Strange! I changed my design to put this input in a form, and now the number works properly!

**Comment by zhouzi** [comment]
It's working well for me, perhaps this issue can be closed @theDanielJLewis?

**Comment by theDanielJLewis** [comment]
Sorry, I just can't afford the time to test this further. I got it working for me by putting it in an input form and I moved on. If I run into this again in the future, I'll reopen this ticket.
