### ISSUE TITLE
Carousel Component Feature Request

### ISSUE THREAD

**Issue by caleb654** [shadcn-ui/ui#337]
Not sure if this is the right place for a feature request but a great accessible carousel with keyboard controls, and good swipe support on mobile, would be awesome. 

By the way, I love all these components so far, great job. The attention to detail on the design is top-notch.

**Comment by jsm94** [comment]
I've done some research on how to approach this component with the good accessibility we used to see in Radix UI. [There is a discussion about a future Radix carousel primitive](https://github.com/radix-ui/primitives/issues/388) so to keep following the best practices of this library, I think we have to wait until the component is finished and then integrate into shadcn/ui.

Also, if someone knows of another tiny library with good accesibility that we can integrate into this library and @shadcn approves, I'm willing to help.

**Comment by its-monotype** [comment]
We can use embla carousel for this

**Comment by FleetAdmiralJakob** [comment]
Great Request

**Comment by dninomiya** [comment]
Do you plan to add dot navigation? 🙏🏻

https://codesandbox.io/p/sandbox/embla-carousel-arrow-dots-react-l8k8jf?file=%2Fsrc%2Fjs%2Findex.tsx

<img width="1056" alt="image" src="https://github.com/shadcn-ui/ui/assets/5842851/87d0e469-48a9-4629-96e9-f9efe7c96169">

**Comment by EggsLeggs** [comment]
> Do you plan to add dot navigation? 🙏🏻
> 
> https://codesandbox.io/p/sandbox/embla-carousel-arrow-dots-react-l8k8jf?file=%2Fsrc%2Fjs%2Findex.tsx
> 
> <img alt="image" width="1056" src="https://private-user-images.githubusercontent.com/5842851/292659454-87d0e469-48a9-4629-96e9-f9efe7c96169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDcwOTUsIm5iZiI6MTcwMzUwNjc5NSwicGF0aCI6Ii81ODQyODUxLzI5MjY1OTQ1NC04N2QwZTQ2OS00OGE5LTQ2MjktOTZlOS1mOWVmZTdjOTYxNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMTIxOTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2VkNjM5Y2E1MDcyZjRmYzQ5ZDk3NThlZmU4NTZlYjI5ZTI5ODY2ZDVmMDJjNmVmZWZkZTFmNmVmMmRiMDYzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZdhiMgZw0OH0rIFGSRrYsSow9Gm1QhBxDPnwRUMqEaw">

You can quite easily add dot navigation using the api and button component, and if u want this to sit on top of the carousel just add it outside the CarouselItem:
```js
{Array.from(Array(count).keys()).map((i) => (
          <Button
            key={i}
            className={`mx-1 h-1.5 flex-grow rounded-full p-0  ${
              i === current - 1
                ? "bg-white hover:bg-white"
                : "bg-neutral-600/75"
            }`}
            onClick={() => api?.scrollTo(i)}
          />
        ))}
```

Hope this helps

**Comment by shadcn** [comment]
Going to mark this as done. We'll figure out the dots navigation in another PR. Thanks everyone.

**Comment by casualzach** [comment]
while this is closed here is a dots components you can just add to the carousel component in the ui folder following the structure of the existing components:
```
const CarouselDots = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>((props, ref) => {
  const { api } = useCarousel();
  const [updateState, setUpdateState] = React.useState(false);
  const toggleUpdateState = React.useCallback(
    () => setUpdateState((prevState) => !prevState),
    []
  );

  React.useEffect(() => {
    if (api) {
      api.on('select', toggleUpdateState);
      api.on('reInit', toggleUpdateState);

      return () => {
        api.off('select', toggleUpdateState);
        api.off('reInit', toggleUpdateState);
      };
    }
  }, [api, toggleUpdateState]);

  const numberOfSlides = api?.scrollSnapList().length || 0;
  const currentSlide = api?.selectedScrollSnap() || 0;

  if (numberOfSlides > 1) {
    return (
      <div ref={ref} className={`flex justify-center ${props.className}`}>
        {Array.from({ length: numberOfSlides }, (_, i) => (
          <Button
            key={i}
            className={`mx-1 h-1.5 w-1.5 rounded-full p-0 ${
              i === currentSlide
                ? 'scale-125 transform bg-gray-500 hover:bg-gray-500'
                : 'bg-gray-300 hover:bg-gray-300'
            }`}
            aria-label={`Go to slide ${i + 1}`}
            onClick={() => api?.scrollTo(i)}
          />
        ))}
      </div>
    );
  } else {
    return <></>;
  }
});
CarouselDots.displayName = 'CarouselDots';
```

**Comment by 7hourspg** [comment]
If you're looking to add a dot indicator to your carousel, here's a simple way to do it. The idea is to maintain a state variable that keeps track of the current active index. Then, you can use this state variable to render the indicator dots and highlight the active one.

First, you'll need to set up your state variables:
```js
const [api, setApi] = React.useState<CarouselApi>();
const [current, setCurrent] = React.useState(0);
const [count, setCount] = React.useState(0);
```

Then, in a useEffect hook, you can update the count and current state variables based on the api object:
```js
React.useEffect(() => {
  if (!api) {
    return;
  }

  setCount(api.scrollSnapList().length);
  setCurrent(api.selectedScrollSnap() + 1);

  api.on("select", () => {
    setCurrent(api.selectedScrollSnap() + 1);
  });
}, [api]);
```
Finally, you can render the indicator dots and use the current state variable to highlight the active dot:
```js
<div className="flex justify-center mt-4">
  {Array.from({ length: count }).map((_, index) => (
    <span
      key={index}
      className={`inline-block w-3 h-3 rounded-full bg-gray-400 mx-2 ${
       index + 1 === current ? "bg-[#FF407D]" : ""
      }`}
      onClick={() => api && api.scrollTo(index)}
    />
  ))}
</div>
```

You should also explore the `api` there's a lot of things to do 👀

**Comment by 684efs3** [comment]
> while this is closed here is a dots components you can just add to the carousel component in the ui folder following the structure of the existing components:
> 
> ```
> const CarouselDots = React.forwardRef<
>   HTMLDivElement,
>   React.HTMLAttributes<HTMLDivElement>
> >((props, ref) => {
>   const { api } = useCarousel();
>   const [updateState, setUpdateState] = React.useState(false);
>   const toggleUpdateState = React.useCallback(
>     () => setUpdateState((prevState) => !prevState),
>     []
>   );
> 
>   React.useEffect(() => {
>     if (api) {
>       api.on('select', toggleUpdateState);
>       api.on('reInit', toggleUpdateState);
> 
>       return () => {
>         api.off('select', toggleUpdateState);
>         api.off('reInit', toggleUpdateState);
>       };
>     }
>   }, [api, toggleUpdateState]);
> 
>   const numberOfSlides = api?.scrollSnapList().length || 0;
>   const currentSlide = api?.selectedScrollSnap() || 0;
> 
>   if (numberOfSlides > 1) {
>     return (
>       <div ref={ref} className={`flex justify-center ${props.className}`}>
>         {Array.from({ length: numberOfSlides }, (_, i) => (
>           <Button
>             key={i}
>             className={`mx-1 h-1.5 w-1.5 rounded-full p-0 ${
>               i === currentSlide
>                 ? 'scale-125 transform bg-gray-500 hover:bg-gray-500'
>                 : 'bg-gray-300 hover:bg-gray-300'
>             }`}
>             aria-label={`Go to slide ${i + 1}`}
>             onClick={() => api?.scrollTo(i)}
>           />
>         ))}
>       </div>
>     );
>   } else {
>     return <></>;
>   }
> });
> CarouselDots.displayName = 'CarouselDots';
> ```

Works great!

**Comment by grvv** [comment]
Added a PR for Carousal Dot components: 

https://github.com/shadcn-ui/ui/pull/3320

**Comment by sohaibfurqan92** [comment]
> > while this is closed here is a dots components you can just add to the carousel component in the ui folder following the structure of the existing components:
> > ```
> > const CarouselDots = React.forwardRef<
> >   HTMLDivElement,
> >   React.HTMLAttributes<HTMLDivElement>
> > >((props, ref) => {
> >   const { api } = useCarousel();
> >   const [updateState, setUpdateState] = React.useState(false);
> >   const toggleUpdateState = React.useCallback(
> >     () => setUpdateState((prevState) => !prevState),
> >     []
> >   );
> > 
> >   React.useEffect(() => {
> >     if (api) {
> >       api.on('select', toggleUpdateState);
> >       api.on('reInit', toggleUpdateState);
> > 
> >       return () => {
> >         api.off('select', toggleUpdateState);
> >         api.off('reInit', toggleUpdateState);
> >       };
> >     }
> >   }, [api, toggleUpdateState]);
> > 
> >   const numberOfSlides = api?.scrollSnapList().length || 0;
> >   const currentSlide = api?.selectedScrollSnap() || 0;
> > 
> >   if (numberOfSlides > 1) {
> >     return (
> >       <div ref={ref} className={`flex justify-center ${props.className}`}>
> >         {Array.from({ length: numberOfSlides }, (_, i) => (
> >           <Button
> >             key={i}
> >             className={`mx-1 h-1.5 w-1.5 rounded-full p-0 ${
> >               i === currentSlide
> >                 ? 'scale-125 transform bg-gray-500 hover:bg-gray-500'
> >                 : 'bg-gray-300 hover:bg-gray-300'
> >             }`}
> >             aria-label={`Go to slide ${i + 1}`}
> >             onClick={() => api?.scrollTo(i)}
> >           />
> >         ))}
> >       </div>
> >     );
> >   } else {
> >     return <></>;
> >   }
> > });
> > CarouselDots.displayName = 'CarouselDots';
> > ```
> 
> Works great!

Thanks for this! Hope your code is made a standard feature for shadcn's carousel component :)

**Comment by gary-lo** [comment]
> while this is closed here is a dots components you can just add to the carousel component in the ui folder following the structure of the existing components:
> 
> ```
> const CarouselDots = React.forwardRef<
>   HTMLDivElement,
>   React.HTMLAttributes<HTMLDivElement>
> >((props, ref) => {
>   const { api } = useCarousel();
>   const [updateState, setUpdateState] = React.useState(false);
>   const toggleUpdateState = React.useCallback(
>     () => setUpdateState((prevState) => !prevState),
>     []
>   );
> 
>   React.useEffect(() => {
>     if (api) {
>       api.on('select', toggleUpdateState);
>       api.on('reInit', toggleUpdateState);
> 
>       return () => {
>         api.off('select', toggleUpdateState);
>         api.off('reInit', toggleUpdateState);
>       };
>     }
>   }, [api, toggleUpdateState]);
> 
>   const numberOfSlides = api?.scrollSnapList().length || 0;
>   const currentSlide = api?.selectedScrollSnap() || 0;
> 
>   if (numberOfSlides > 1) {
>     return (
>       <div ref={ref} className={`flex justify-center ${props.className}`}>
>         {Array.from({ length: numberOfSlides }, (_, i) => (
>           <Button
>             key={i}
>             className={`mx-1 h-1.5 w-1.5 rounded-full p-0 ${
>               i === currentSlide
>                 ? 'scale-125 transform bg-gray-500 hover:bg-gray-500'
>                 : 'bg-gray-300 hover:bg-gray-300'
>             }`}
>             aria-label={`Go to slide ${i + 1}`}
>             onClick={() => api?.scrollTo(i)}
>           />
>         ))}
>       </div>
>     );
>   } else {
>     return <></>;
>   }
> });
> CarouselDots.displayName = 'CarouselDots';
> ```

@casualzach You're the real MVP.

**Comment by abanob0adel** [comment]
const CarouselDots = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>((props, ref) => {
  const { api } = useCarousel();
  const [updateState, setUpdateState] = React.useState(false);
  const toggleUpdateState = React.useCallback(
    () => setUpdateState((prevState) => !prevState),
    []
  );

  React.useEffect(() => {
    if (api) {
      api.on("select", toggleUpdateState);
      api.on("reInit", toggleUpdateState);

      return () => {
        api.off("select", toggleUpdateState);
        api.off("reInit", toggleUpdateState);
      };
    }
  }, [api, toggleUpdateState]);

  const numberOfSlides = api?.scrollSnapList().length || 0;
  const currentSlide = api?.selectedScrollSnap() || 0;

  if (numberOfSlides > 1) {
    return (
      <div ref={ref} className={`flex justify-center mt-4 ${props.className}`}>
        {Array.from({ length: numberOfSlides }, (_, i) => (
          <button
            key={i}
            className={`mx-1 h-[6px] lg:w-[70px] w-[30px] rounded-full p-0 ${
              i === currentSlide ? "bg-[#0FBCB3]" : "bg-[#E7E6F2]"
            }`}
            aria-label={`Go to slide ${i + 1}`}
            onClick={() => api?.scrollTo(i)}
          />
        ))}
      </div>
    );
  } else {
    return <></>;
  }
});
CarouselDots.displayName = "CarouselDots";

**Comment by Victorious-loggworks** [comment]
> while this is closed here is a dots components you can just add to the carousel component in the ui folder following the structure of the existing components:
> 
> ```
> const CarouselDots = React.forwardRef<
>   HTMLDivElement,
>   React.HTMLAttributes<HTMLDivElement>
> >((props, ref) => {
>   const { api } = useCarousel();
>   const [updateState, setUpdateState] = React.useState(false);
>   const toggleUpdateState = React.useCallback(
>     () => setUpdateState((prevState) => !prevState),
>     []
>   );
> 
>   React.useEffect(() => {
>     if (api) {
>       api.on('select', toggleUpdateState);
>       api.on('reInit', toggleUpdateState);
> 
>       return () => {
>         api.off('select', toggleUpdateState);
>         api.off('reInit', toggleUpdateState);
>       };
>     }
>   }, [api, toggleUpdateState]);
> 
>   const numberOfSlides = api?.scrollSnapList().length || 0;
>   const currentSlide = api?.selectedScrollSnap() || 0;
> 
>   if (numberOfSlides > 1) {
>     return (
>       <div ref={ref} className={`flex justify-center ${props.className}`}>
>         {Array.from({ length: numberOfSlides }, (_, i) => (
>           <Button
>             key={i}
>             className={`mx-1 h-1.5 w-1.5 rounded-full p-0 ${
>               i === currentSlide
>                 ? 'scale-125 transform bg-gray-500 hover:bg-gray-500'
>                 : 'bg-gray-300 hover:bg-gray-300'
>             }`}
>             aria-label={`Go to slide ${i + 1}`}
>             onClick={() => api?.scrollTo(i)}
>           />
>         ))}
>       </div>
>     );
>   } else {
>     return <></>;
>   }
> });
> CarouselDots.displayName = 'CarouselDots';
> ```

Thank you

**Comment by ronnaph** [comment]
> while this is closed here is a dots components you can just add to the carousel component in the ui folder following the structure of the existing components:
> 
> ```
> const CarouselDots = React.forwardRef<
>   HTMLDivElement,
>   React.HTMLAttributes<HTMLDivElement>
> >((props, ref) => {
>   const { api } = useCarousel();
>   const [updateState, setUpdateState] = React.useState(false);
>   const toggleUpdateState = React.useCallback(
>     () => setUpdateState((prevState) => !prevState),
>     []
>   );
> 
>   React.useEffect(() => {
>     if (api) {
>       api.on('select', toggleUpdateState);
>       api.on('reInit', toggleUpdateState);
> 
>       return () => {
>         api.off('select', toggleUpdateState);
>         api.off('reInit', toggleUpdateState);
>       };
>     }
>   }, [api, toggleUpdateState]);
> 
>   const numberOfSlides = api?.scrollSnapList().length || 0;
>   const currentSlide = api?.selectedScrollSnap() || 0;
> 
>   if (numberOfSlides > 1) {
>     return (
>       <div ref={ref} className={`flex justify-center ${props.className}`}>
>         {Array.from({ length: numberOfSlides }, (_, i) => (
>           <Button
>             key={i}
>             className={`mx-1 h-1.5 w-1.5 rounded-full p-0 ${
>               i === currentSlide
>                 ? 'scale-125 transform bg-gray-500 hover:bg-gray-500'
>                 : 'bg-gray-300 hover:bg-gray-300'
>             }`}
>             aria-label={`Go to slide ${i + 1}`}
>             onClick={() => api?.scrollTo(i)}
>           />
>         ))}
>       </div>
>     );
>   } else {
>     return <></>;
>   }
> });
> CarouselDots.displayName = 'CarouselDots';
> ```

It works wonderfully, but I'm encountering an issue in one specific case. When the width is set to basis-1/3 and there are a total of 5 slides, it shows 4 dots in the pagination, whereas it should only display 3. As a result, when I click on the 4th dot, nothing happens. Could you assist with this? 
Thank you so much.
