### ISSUE TITLE
[bug]: combobox example page and command component runtime & function error

### ISSUE THREAD

**Issue by o0vO** [shadcn-ui/ui#3474]
All codes I use is from the shadcn doc.

### Describe the bug

In the [link](https://ui.shadcn.com/docs/components/combobox), the first preview example will cause error:
![image](https://github.com/shadcn-ui/ui/assets/157351579/99622f2f-f867-417a-ac73-5f38685226e6)
It needs to wrap with `CommandList`, but after that, all items is unselected, [code](https://ui.shadcn.com/docs/components/combobox#popover)
![image](https://github.com/shadcn-ui/ui/assets/157351579/578e2295-cb19-41c6-a339-b59a49206032)

### Affected component/components

combobox, Command

### How to reproduce

build a latest nextjs project
1. copy code at [here](https://ui.shadcn.com/docs/components/combobox)
2. import in the main page.

### System Info

```bash
"next": "14.1.4",
"react": "^18",
"react-dom": "^18",
"@radix-ui/react-avatar": "^1.0.4",
"@radix-ui/react-dialog": "^1.0.5",
"@radix-ui/react-dropdown-menu": "^2.0.6",
"@radix-ui/react-label": "^2.0.2",
"@radix-ui/react-popover": "^1.0.7",
"@radix-ui/react-scroll-area": "^1.0.5",
"@radix-ui/react-separator": "^1.0.3",
"@radix-ui/react-slot": "^1.0.2",
```
```


### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by laurentlahmy** [comment]
npm i cmdk@0.2.1

**Comment by o0vO** [comment]
> npm i cmdk@0.2.1
> 
> (check existing issues for context)

thanks, will try. actually I met context null problem as well.

**Comment by o0vO** [comment]
> npm i cmdk@0.2.1
> 
> (check existing issues for context)

That helps, thank you.

**Comment by satishkumarsajjan** [comment]
> > npm i cmdk@0.2.1
> > (check existing issues for context)
> 
> That helps, thank you.

so the issue is solved?

**Comment by o0vO** [comment]
> > > npm i cmdk@0.2.1
> > > (check existing issues for context)
> > 
> > 
> > That helps, thank you.
> 
> so the issue is solved?

Yep, close it still need some updates in repo
