### ISSUE TITLE
[bug]: "New" label gets underline during hover in sidebar

### ISSUE THREAD

**Issue by imMatheus** [shadcn-ui/ui#3481]
### Describe the bug

Small UI issue in the sidebar, when hovering over an option with the "new" label, it gets an underline, and looking at the code there seems to be a `group-hover:no-underline` class on the label, so it should not get an underline. The issue lies with the order of CSS specificity, and this can very easily be solved by just swapping the logic to only add the hover effect to the text and not the entire `li` and then removing the underline for the label only. I am more than willing to make a small PR fixing this 🙏 

![Screenshot 2024-04-14 at 16 08 44](https://github.com/shadcn-ui/ui/assets/77362975/63d01b12-438a-4089-8710-74319d0b362b)

### Affected component/components

apps/www/components/sidebar-nav.tsx

### How to reproduce

1. Go to [https://ui.shadcn.com/docs](https://ui.shadcn.com/docs)
2. Hover over any option in the right sidebar that has the green "New" label (either Breadcrump or Input OTP)

### Codesandbox/StackBlitz link

No codesandbox

### Logs

```bash
No logs
```

### System Info

```bash
Macbook pro m2 chip, google chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by pratikwaware** [comment]
Raised a PR for this fix.
