### ISSUE TITLE
Couldn't find tsconfig.json

### ISSUE THREAD

**Issue by ayodhyaw2002** [shadcn-ui/ui#3523]
### Describe the bug

Failed to load jsconfig.json. Couldn't find tsconfig.json  ===> I this error happend.. even I dont using Ts for my projecr, its JS

### Affected component/components

all

### How to reproduce

.

### Codesandbox/StackBlitz link

bug

### System Info

```bash
.
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Ayo-J** [comment]
===== > If you Create your jsconfig.json file inside main folder then it will be works.
