### ISSUE TITLE
[bug]: ScrollArea not working inside ResizablePanel

### ISSUE THREAD

**Issue by burakcan** [shadcn-ui/ui#3548]
### Describe the bug

When ScrollArea is rendered under a ResizablePanel (doesn't matter at which level), scroll doesn't work. It just acts like overflow-hidden.

### Affected component/components

ResizablePanel, ScrollArea

### How to reproduce

1. Create a layout with 2 ResizablePanels and put SrollArea inside them with some long content.
2. Try to scroll

### System Info

```bash
Latest Chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by burakcan** [comment]
Noticed it's probable a me problem. Closing

**Comment by shirecoding** [comment]
i seem to have the same issue can you explain how you solved it? thanks

**Comment by b3nab** [comment]
I have a similar problem putting a ScrollArea inside a Collapsible or CollapsibleContent (which is similar to a ResizablePanel).

Someone could give us an hint?

**Comment by BartJesper** [comment]
I have the same problem with putting it inside of a horizontal resizable panel. Because of the varying height of the resizable group it is very hard to determine what height to give the scroll area.

**Comment by rakibulhasanbu** [comment]
Using height inside a div and making overflow auto then it works fine.
```
<ResizablePanel defaultSize={50} minSize={20}>
        <div className="h-[calc(100dvh-222px)] overflow-y-auto p-4">
               // text here
         </div>
</ResizablePanel>
```

**Comment by fitzgibbonjack** [comment]
I'm having the same issue - `ScrollArea` within a `ResizablePanel` component is not working.

**Comment by marianif** [comment]
in my case i just added h-screen to the div wrapped by the <ResizablePanel /> 

`    <div className="flex h-screen w-full relative">
      <SidebarProvider>
        <AppSidebar
          type={pathname === "/dashboard" ? "dashboard" : "workspace"}
          variant="inset"
        />
        <SidebarInset>
          <ResizablePanelGroup direction="horizontal" className="h-full flex-1">
            <ResizablePanel defaultSize={650}>
              <div className="flex w-full h-screen">{children}</div>
            </ResizablePanel>

            {pathname !== "/dashboard" && (
              <>
                <ResizableHandle withHandle />
                <ResizablePanel defaultSize={350}>
                  <div className=" right-0 bottom-0 m-4">
                    <Chat className="h-full rounded-lg" />
                  </div>
                </ResizablePanel>
              </>
            )}
          </ResizablePanelGroup>
        </SidebarInset>
      </SidebarProvider>
    </div>`

**Comment by marianif** [comment]
in my case was sufficient adding a h-screen class to the div wrapped by the Resizable Panel:

`          <ResizablePanelGroup direction="horizontal" className="h-full flex-1">
            <ResizablePanel defaultSize={650}>
              <div className="flex w-full h-screen">{children}</div>
            </ResizablePanel>

            {pathname !== "/dashboard" && (
              <>
                <ResizableHandle withHandle />
                <ResizablePanel defaultSize={350}>
                  <div className=" right-0 bottom-0 m-4">
                    <Chat className="h-full rounded-lg" />
                  </div>
                </ResizablePanel>
              </>
            )}
          </ResizablePanelGroup>`

**Comment by alexandr2110pro** [comment]
For anybody who stumbled upon this too, Setting the height (h-full, or any specific value) on the ScrollArea component usually helps
```jsx
<ResizablePanelGroup direction="horizontal">
  <ResizablePanel defaultSize={30} minSize={30}>
    <ScrollArea className="h-full pr-3">
      <YourLeftContent />
    </ScrollArea>
  </ResizablePanel>
  <ResizableHandle withHandle className="mx-2" />
  <ResizablePanel defaultSize={30} minSize={30}>
    <ScrollArea className="h-full pr-3">
      <YourRightContent />
    </ScrollArea>
  </ResizablePanel>
</ResizablePanelGroup>
```
If it still doesn't fix the problem, that is most likely because your outer component has unknowable height (see https://www.joshwcomeau.com/css/height-enigma/#knowable-heights-2 for example)
Yeah.. it is tricky sometimes. 😄
