### ISSUE TITLE
Installation using pnpm doesn't work

### ISSUE THREAD

**Issue by torn4dom4n** [shadcn-ui/ui#356]
I try to use pnpm to setup a project following [this document](https://ui.shadcn.com/docs/installation). Firstly, I added `pnpm create next-app -e https://github.com/shadcn/next-template` in the `cmd` and named it **shadcnui-starter**. After that, I opened **shadcnui-starter** folder and ran `pnpm dev`. Here is the error I found:

![image](https://github.com/shadcn/ui/assets/27698189/b3bf2397-1249-4830-a5a2-6c91b00ad4a1)

Everything looks fine when I use npm.

**Comment by kratos-respawned** [comment]
try pnpm up --latest  && pnpm i then try running the dev server

**Comment by shadcn** [comment]
@torn4dom4n Yep. I'll update next-template. Thanks for the heads up.
