### ISSUE TITLE
[feat]: add hot toast to the library

### ISSUE THREAD

**Issue by a0m0rajab** [shadcn-ui/ui#3633]
### Feature description

The toast that we have right now does not give much flexibility to the user it would be great to add hot toast library as component to enable the user for more flexibility, or have a similar functionality in the toaster component 

https://react-hot-toast.com/

### Affected component/components

taost

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by kasyap-007** [comment]
`Sonner` Component is already available in shadcn-ui - [docs](https://ui.shadcn.com/docs/components/sonner).
usage: [Sonner](https://sonner.emilkowal.ski/)

**Comment by a0m0rajab** [comment]
@kasyap-007 thank you for the information, I did not notice it supports the positioning of the toast. Closing this PR.
