### ISSUE TITLE
[feat]: Open Drawer on swipe up 

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [shadcn-ui/ui#3651]
### Feature description

Open Drawer on swipe up like ios like animation

### Affected component/components

Drawer

### Additional Context

![image](https://github.com/shadcn-ui/ui/assets/37482171/80e531b0-9d73-44af-af08-0b5908c5fa99)

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by marvsman** [comment]
I've implemented something like that a while ago. 
Just check the snappoint example of the [Vaul Package](https://github.com/emilkowalski/vaul).
Just don't use the drawer as a dialog component and don't allow closing the drawer.

Here is the Snappoint Example: [Codebox](https://codesandbox.io/p/sandbox/drawer-non-dismissable-forked-jchtff?file=/app/my-drawer.tsx:1,1)

**Comment by rahulkumarsingh73690** [comment]
@marvsman Thanks for sharing, Is it possible to open drawer on swipe not using @click

**Comment by marvsman** [comment]
> ...Is it possible to open drawer on swipe not using @click

Yeah it is! The drawer has build in swipe gestures. If the **Drawer** is always visible, you can move from one snappoint to the next via swipe gestures!

**Comment by Qodestackr** [comment]
The drawer is not responsive on  mobile and closes entired screen

**Comment by marvsman** [comment]
> The drawer is not responsive on  mobile and closes entired screen

Thats not right, you can handle this yourself. Although for this, the drawer needs to be always open. I suggest giving it space in a fixed footer container.
