### ISSUE TITLE
Command is not working properly. 

### ISSUE THREAD

**Issue by HamidShaikh1499** [shadcn-ui/ui#3685]
### Describe the bug

I can't use mouse to select an item from list(CommandList). I attached below video please see.

https://github.com/shadcn-ui/ui/assets/50068289/d8892010-7ae9-48eb-91df-f873de3b2724

### Affected component/components

Command, CommandList and CommandItem

### How to reproduce

i used code from [https://github.com/shadcn-ui/ui/pull/2773](url). and also used different variant of multi select and also tried to modify but failed. due to commandList.

### System Info

```bash
No
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by HamidShaikh1499** [comment]
I found issue in className of CommadItem 

previous one: "relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50",

Changed: "relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground"

I just removed: "data-[disabled]:pointer-events-none data-[disabled]:opacity-50"

what is use of data-[disabled]:pointer-events-none data-[disabled]:opacity-50?

**Comment by loiclefloch** [comment]
Hello, the code you removed will make the item with an opacity of 50 when the item is marked as disabled.
I would suggest you to look at this on going pull request that is doing the right fix for this : https://github.com/shadcn-ui/ui/pull/3680

**Comment by ABthewebdev** [comment]
this man is a lifesaver thank you, I agree too this pr should be looked at

**Comment by HamidShaikh1499** [comment]
Okay, i got solution from that PR. Thanks @loiclefloch. So i am closing this one....

**Comment by imxfrq** [comment]
@ricardoraposo thankkkssss .. ui -> command.tsx -> [search] CommandPrimitive.Item -> [Copy Paste]
ClassName={cn(
"relative flex cursor-pointer select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 0"

**Comment by JonathanToker** [comment]
Yeah I had it too just now, @loiclefloch is right, do not delete - it's just a matter of changing the utility classes to when there is a disabled property on the CommandItem component, just change: data-[disabled]:pointer-events-none data-[disabled]:opacity-50
to:
data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50
This way if you will have a disabled property you will see it in the UI. Thanks Guys.
