### ISSUE TITLE
[bug]: Script not found

### ISSUE THREAD

**Issue by Boby900** [shadcn-ui/ui#3738]
### Describe the bug

While running the cmd `bunx --bun shadcn-ui@latest init`
I am getting the `error: Script not found "shadcn-ui@latest"`

### Affected component/components

Not able to install the project

### How to reproduce

Use this cmd `bunx --bun shadcn-ui@latest init` in Windows using the Git Bash
![Screenshot (459)](https://github.com/shadcn-ui/ui/assets/111265239/a23cfffb-322f-4860-9350-efefb937a0d6)

### Codesandbox/StackBlitz link

https://github.com/Boby900/yogurt

### Logs

```bash
$ bunx --bun shadcn-ui@latest init
error: Script not found "shadcn-ui@latest"
```

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
    Memory: 594.21 MB / 3.92 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    bun: 1.1.6 - ~\AppData\Roaming\npm\bun.CMD
  Browsers:
    Chrome: 124.0.6367.207
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.3636
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by websaid** [comment]
Please fix :)

**Comment by Boby900** [comment]
using the bun with a space worked for me.
`bun x --bun shadcn-ui@latest init`

**Comment by braswelljr** [comment]
> using the bun with a space worked for me. `bun x --bun shadcn-ui@latest init`



> using the bun with a space worked for me. `bun x --bun shadcn-ui@latest init`

this works

**Comment by Boby900** [comment]
yes @braswelljr
`bun x` is an alias for `bunx`.

**Comment by AmodeusR** [comment]
Is this a shadcnui problem or a bun problem? Nonetheless, shadcnui could at least change docs code prompt to be the one that works.

**Comment by dalalsoham** [comment]
> using the bun with a space worked for me. `bun x --bun shadcn-ui@latest init`

first i run this command : "bun add -g shadcn-ui"

**Comment by dalalsoham** [comment]
at the first install the shadcn in globally using this command : "bun add -g shadcn-ui"
then run this command :  "bunx shadcn-ui@latest init"
and this method work for me.

**Comment by withabhinay** [comment]
> at the first install the shadcn in globally using this command: "bun add -g shadcn-ui" then run this command : "bunx shadcn-ui@latest init" and this method work for me.
does it work the same ? as ->  bun x --bun shadcn-ui@latest init

**Comment by kelvinwop** [comment]
You should use

`bun x` instead of `bunx`
