### ISSUE TITLE
[bug]: Unable to install

### ISSUE THREAD

**Issue by Joepolymath** [shadcn-ui/ui#3762]
### Describe the bug

Tried installing with the command, "npx shadcn-ui@latest init". But it keeps throwing the following error.
```
FetchError: request to https://ui.shadcn.com/registry/styles/index.json failed, reason: connect ECONNREFUSED 76.76.21.93:443
    at ClientRequest.<anonymous> (file:///Users/equallyai/.npm/_npx/125ee17d583c4e03/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:526:28)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  erroredSysCall: 'connect'
}
Failed to fetch styles from registry.
```

### Affected component/components

Installation

### How to reproduce

Just run "npx shadcn-ui@latest init" on your project.

### System Info

```bash
MacOS
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by kris08052000** [comment]
Hey Joe,

1. Try installing with VPN from any other countries.
2. Try with some other network provider or internet or sim provider.

Thanks

**Comment by Joepolymath** [comment]
> Hey Joe,
> 
> 1. Try installing with VPN from any other countries.
> 2. Try with some other network provider or internet or sim provider.
> 
> Thanks

Thank you. Just tried that.

**Comment by Joepolymath** [comment]
Works now with vpn

**Comment by sajjadgol** [comment]
it doesn't work with vpn !!!!

**Comment by swapnil9898** [comment]
The issue was resolved by the system administrator, who granted me full access and added the necessary certificate. After that, the issue was resolved.
