### ISSUE TITLE
[feat]: Need a Rating component

### ISSUE THREAD

**Issue by rayaanr** [shadcn-ui/ui#3778]
### Feature description

I think its good to have a rating component something like this.

https://www.npmjs.com/package/@smastrom/react-rating

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by birobirobiro** [comment]
https://github.com/shadcn-ui/ui/pull/2951
