### ISSUE TITLE
[bug]: `bun add` fails when running add components in a monorepo

### ISSUE THREAD

**Issue by wladpaiva** [shadcn-ui/ui#3819]
### Describe the bug

This is actually a bug in Bun itself when running `bun add` from a monorepo but since shadcn-cli is using it we need an issue here to keep track of this.
https://github.com/oven-sh/bun/issues/3502

A short term solution could be replacing `bun add` with `bun install` (it somehow works exactly the same)

<img width="642" alt="Screenshot 2024-05-24 at 18 34 38" src="https://github.com/shadcn-ui/ui/assets/1843792/bd432d51-c62d-4c08-9c33-49d504ec8824">

### Affected component/components

all

### How to reproduce

create a turbosrepo, add shadcn on ui package

### System Info

```bash
N/A
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Jarred-Sumner** [comment]
This is a bug in Bun which we fixed in Bun v1.1.9. Please upgrade to Bun v1.1.10 - `bun upgrade`

**Comment by wladpaiva** [comment]
Confirmed. It seems that it is working correctly on v1.1.10. Cheers @Jarred-Sumner
