### ISSUE TITLE
[bug]: Cannot Modify div with style="min-width:100%;display:table" in ScrollArea Component, Causes Overflow

### ISSUE THREAD

**Issue by Leon-azerty** [shadcn-ui/ui#3833]
### Describe the bug

The ScrollArea component in the shadcn/ui library contains a div element with the style min-width:100%;display:table. This div cannot be modified without directly altering the files in the node_modules directory. As a result, the element takes up the entire width and overflows the screen.

### Affected component/components

ScrollArea

### How to reproduce

Import and use the ScrollArea component from shadcn/ui in a project.
Observe that there is a div with style="min-width:100%;display:table" within the component structure.
Notice that this div causes the component to take up the entire width of the screen and overflow.

page.tsx
```
<ScrollArea className="@container">
        <GoodMorning />
        <Recommendations />
</ScrollArea>
```

good-morning.tsx
```
export default function GoodMorning() {
  return (
    <section
      className={cn(
        'grid max-w-full gap-4 grid-cols-4 grid-rows-2',
      )}
    >
      {list.map((item) => (
        <GridElement title={item.title} src={item.src} key={item.title} />
      ))}
    </section>
  )
}
```

![image](https://github.com/shadcn-ui/ui/assets/72023373/d3a04688-db8a-4ff8-98f1-9b0cd49ab841)
![image](https://github.com/shadcn-ui/ui/assets/72023373/d4f5cee5-a364-46cc-9e03-c4e59b90ca73)

### Codesandbox/StackBlitz link

https://github.com/leon3108/spotiflex

### System Info

```bash
I use Brave as browser
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by vinitkesh** [comment]
The link you provided, isn't working for some reason.

**Comment by leon3108** [comment]
Yes, I have changed the visibility.

**Comment by Anton-Cherniuk** [comment]
Same problem

**Comment by makotodejima** [comment]
This is an issue with the underlying radix-ui's component `ScrollArea`. 
See the issue in radix-ui: https://github.com/radix-ui/primitives/issues/926#issuecomment-2203592086
There's also a suggested workaround there.

**Comment by Leon-azerty** [comment]
I applied these changes : https://github.com/radix-ui/primitives/issues/926#issuecomment-1447283516
and it worked. Thanks you @makotodejima

**Comment by sjordan1975** [comment]
Looks like any fix was recently reverted and as of today this remains broken. Just ran into it.

**Comment by golddydev** [comment]
```typescript
<ScrollArea className="[&_[data-slot=scroll-area-viewport]>div]:block!">
</ScrollArea>
```

This one will fix
