### ISSUE TITLE
[bug]: Sheet has no style

### ISSUE THREAD

**Issue by Devlop-er** [shadcn-ui/ui#3839]
### Describe the bug

I installed the component and when I call it I have only the overlay without the element shown??
Why this happend?

We should copy / paste and have a working component

I need to add top-0 class to make it work... WHY ?

### Affected component/components

Sheet

### How to reproduce

Copy / Paste component

### System Info

```bash
ARC
NextJS
Typescript
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by kevinguebert** [comment]
Can you provide an example codesandbox/reproduction link?

**Comment by Devlop-er** [comment]
All good something was duplicate between Shadcn and NextUI Thanks 👍
