### ISSUE TITLE
[bug]: charts needs improvements in vue

### ISSUE THREAD

**Issue by kaizenics** [shadcn-ui/ui#3874]
### Describe the bug

shadcn ui charts needs to be improved especially in vue. after i apply the charts there is no design displayed as output

### Affected component/components

Charts

### How to reproduce

![image](https://github.com/shadcn-ui/ui/assets/94561281/07de3a5d-d937-4d71-8e35-ba241716e611)

### System Info

```bash
System
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by nuradiyana** [comment]
I think vue repo is https://github.com/radix-vue/shadcn-vue

You can report there

**Comment by kaizenics** [comment]
oh thanks!
