### ISSUE TITLE
[bug]: Default styles are not applied when using Remix + Vite.

### ISSUE THREAD

**Issue by alex-mironov** [shadcn-ui/ui#3881]
### Describe the bug

I've installed Remix + Shadcn as described [here](https://ui.shadcn.com/docs/installation/remix). Unfortunately the default styling doesn't seem to be applied.

```jsx
    <div className="px-2 flex flex-col gap-2 w-[100px]">
      <Button>Click me</Button>
      <Button variant={'secondary'}>Click me</Button>
      <Button variant={'outline'}>Click me</Button>
    </div>
```

Here is the image of how button looks like:
<img width="135" alt="image" src="https://github.com/shadcn-ui/ui/assets/2544767/ba996c3b-edbc-41a8-9425-8d51df7756a7">

Here is the newly created repo with all the source code - https://github.com/alex-mironov/remix-shadcn.

Here is the project structure and config files:
<img width="846" alt="image" src="https://github.com/shadcn-ui/ui/assets/2544767/ae3b268f-a599-4708-940c-57ff8f9adb50">

`tailwind.config.ts`
<img width="542" alt="image" src="https://github.com/shadcn-ui/ui/assets/2544767/5a2a41bf-f3a2-45c5-aaaa-80fa5a46ebc5">

`globals.css`
<img width="463" alt="image" src="https://github.com/shadcn-ui/ui/assets/2544767/ded00f2a-f584-4a7d-9f2c-216907cf0384">

`components.json`
```json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "app/globals.css",
    "baseColor": "slate",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "app/components",
    "utils": "app/lib/utils"
  }
}
```

`vite.config.ts`
```
import { vitePlugin as remix } from "@remix-run/dev";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [
    remix({
      future: {
        v3_fetcherPersist: true,
        v3_relativeSplatPath: true,
        v3_throwAbortReason: true,
      },
    }),
    tsconfigPaths(),
  ],
});
```

### Affected component/components

Button

### How to reproduce

1. Follow instructions in the documentation https://ui.shadcn.com/docs/installation/remix.
2. Install any component, e.g. button:
```
npx shadcn-ui@latest add button
```
3. Use the button:
```
    <div className="px-2 flex flex-col gap-2 w-[100px]">
      <Button>Click me</Button>
      <Button variant={'secondary'}>Click me</Button>
      <Button variant={'outline'}>Click me</Button>
    </div>
```
Result: 
<img width="135" alt="image" src="https://github.com/shadcn-ui/ui/assets/2544767/99e05bdd-e096-4382-bb6f-7c8489ea1ff0">

### Codesandbox/StackBlitz link

https://github.com/alex-mironov/remix-shadcn

### System Info

```bash
macos, any browser
Node.js - v20.14.0
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by alex-mironov** [comment]
Resolved the issue, apparently wrong css file was specified in `components.json`:
```
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    
    // HERE: instead of this
    // "css": "app/globals.css",
    // use this
    // "css": "app/tailwind.css",    
    "baseColor": "slate",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "app/components",
    "utils": "app/lib/utils"
  }
}
```

Merged both `global.css` and `tailwind.css` and removed `global.css`.

**Comment by vitalijalbu** [comment]
> Resolved the issue, apparently wrong css file was specified in `components.json`:
> 
> ```
> {
>   "$schema": "https://ui.shadcn.com/schema.json",
>   "style": "default",
>   "rsc": true,
>   "tsx": true,
>   "tailwind": {
>     "config": "tailwind.config.ts",
>     
>     // HERE: instead of this
>     // "css": "app/globals.css",
>     
>     // use this
>     "css": "app/tailwind.css", 
> 
>     "baseColor": "slate",
>     "cssVariables": true,
>     "prefix": ""
>   },
>   "aliases": {
>     "components": "app/components",
>     "utils": "app/lib/utils"
>   }
> }
> ```
> 
> Merged both `global.css` and `tailwind.css` and removed `global.css`.

Hi, so the name always must be tailwind.css? Or I can give whatever name I want?

**Comment by yigsvnsla** [comment]
> > Se resolvió el problema, aparentemente se especificó un archivo CSS incorrecto en `components.json`:
> > ```
> > {
> >   "$schema": "https://ui.shadcn.com/schema.json",
> >   "style": "default",
> >   "rsc": true,
> >   "tsx": true,
> >   "tailwind": {
> >     "config": "tailwind.config.ts",
> >     
> >     // HERE: instead of this
> >     // "css": "app/globals.css",
> >     
> >     // use this
> >     "css": "app/tailwind.css", 
> > 
> >     "baseColor": "slate",
> >     "cssVariables": true,
> >     "prefix": ""
> >   },
> >   "aliases": {
> >     "components": "app/components",
> >     "utils": "app/lib/utils"
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Se fusionaron ambos `global.css`y `tailwind.css`y se eliminaron `global.css`.
> 
> Hola, ¿el nombre siempre debe ser tailwind.css? ¿O puedo darle el nombre que quiera?

the one you want
