### ISSUE TITLE
[bug]: Combobox example breaks on https://ui.shadcn.com/docs/components/combobox

### ISSUE THREAD

**Issue by ritmillio** [shadcn-ui/ui#3903]
### Describe the bug

If I click on the Combobox on the official site it breaks the entire app

### Affected component/components

Combobox

### How to reproduce

Go to https://ui.shadcn.com/docs/components/combobox
Try the first example

### System Info

```bash
Arc Browser
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Rekl0w** [comment]
Duplicate of #3900. I submitted a PR about it.
