### ISSUE TITLE
[bug]: ComboBox > Form preview breaks the site.

### ISSUE THREAD

**Issue by imohitarora** [shadcn-ui/ui#3907]
### Describe the bug

The documentation for shadcn ui breaks on clicking Combobox > Form preview.

### Affected component/components

Combobox

### How to reproduce

https://github.com/shadcn-ui/ui/assets/7965137/77e4e312-b8c5-423f-bfba-c4c69063056f

### System Info

```bash
Tried in Chrome and Arc browser, 

Opening the current documentation on https://ui.shadcn.com/docs/components/combobox
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by AbduRahmanS** [comment]
A similar issue happen on /examples/playground when  you click on "Load a preset.." Combobox

**Comment by MaximMaximS** [comment]
Same fix as https://github.com/shadcn-ui/ui/commit/06cc0cdf3d080555d26abbe6639f2d7f6341ec73

**Comment by Warchant** [comment]
Had same problem, wrapping into CommandList solved.
