### ISSUE TITLE
[bug]: OTP Input DIGITS_AND_CHARS 

### ISSUE THREAD

**Issue by ssynowiec** [shadcn-ui/ui#3941]
### Describe the bug

If i use REGEXP_ONLY_DIGITS_AND_CHARS in OTP Input on computer i can input chars and numbers but on the phone is opening only digits keyboard.

### Affected component/components

Input OTP

### How to reproduce

1. Open page with InputOTP on smartphone
2. Click Input
3. Opened only digits keyboard

### Codesandbox/StackBlitz link

https://gist.github.com/ssynowiec/7c79976a3daf2d73ae5ecf5c99559f33

### System Info

```bash
Android 14
Samsung One UI 6.1
Chrome 125.0.6422.165
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by ssynowiec** [comment]
Yes, it's works. Thank you

**Comment by adrianfahmi23** [comment]
it doesn't work for me
