### ISSUE TITLE
[bug]: Error in examples/forms/account when clicked on Languages Trigger button

### ISSUE THREAD

**Issue by Z3RO-O** [shadcn-ui/ui#3962]
### Describe the bug

 When clicked on Languages Trigger button on examples in form on shadcn website the app crashes due to undefined value in that popover component.
![image](https://github.com/shadcn-ui/ui/assets/105493363/0843b232-49fe-41ba-bba9-ceef8ab05758)

### Affected component/components

Popover

### How to reproduce

1. Go to examples/forms/account
2. Click on Language Button
3. Error Page

### Codesandbox/StackBlitz link

https://github.com/shadcn-ui/ui/tree/06cc0cdf3d080555d26abbe6639f2d7f6341ec73/apps/www/app/(app)/examples/forms/account

### System Info

```bash
Brave Brower
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Rekl0w** [comment]
I submitted a PR about it.

**Comment by greatstefan** [comment]
It happens the same with the combobox form. Please check

**Comment by Z3RO-O** [comment]
@Rekl0w Ok thanks for letting me know

**Comment by Z3RO-O** [comment]
@greatstefan yes it is the same.

**Comment by greatstefan** [comment]
Yes, the problem was because I had a "CommandGroup" component directly in <Command> and I had to wrap the "CommandGroup" in another component called "CommandList" and now works. So:

<CommandList>
    <CommandGroup></CommandGroup>
</CommandList>
