### ISSUE TITLE
[bug]: Combobox Form example errors when you click Select Language

### ISSUE THREAD

**Issue by murderteeth** [shadcn-ui/ui#3976]
### Describe the bug

- Go here https://ui.shadcn.com/docs/components/combobox
- Scroll to bottom, "Form"
- Click "Select Language"

![image](https://github.com/shadcn-ui/ui/assets/89237203/30d37b66-743b-4658-9888-af098c508faa)
![image](https://github.com/shadcn-ui/ui/assets/89237203/50dcfaff-19a4-4fd4-bc9d-690057c4eb4f)

Also why is it called "combobox"? The shadcn-ui's combobox component doesn't work like the comboboxes I see here,
https://en.wikipedia.org/wiki/Combo_box
https://learn.microsoft.com/en-us/windows/apps/design/controls/combo-box
https://headlessui.com/react/combobox
https://jquense.github.io/react-widgets/docs/Combobox

### Affected component/components

Combobox

### How to reproduce

- Go here https://ui.shadcn.com/docs/components/combobox
- Scroll to bottom, "Form"
- Click "Select Language"

### System Info

```bash
able to reproduce in Chrome, Brave, and Arc
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

related issues
https://github.com/shadcn-ui/ui/issues/3907
https://github.com/shadcn-ui/ui/issues/3903
https://github.com/shadcn-ui/ui/issues/3900

**Comment by Nilomiranda** [comment]
@shadcn I've opened a PR #3980 providing a fix for it.

**Comment by shadcn** [comment]
Fixed.
