### ISSUE TITLE
[bug]: There is a vulnerability in shadcn-ui@0.8.0 > lodash.template@4.5.0

### ISSUE THREAD

**Issue by tar-aldev** [shadcn-ui/ui#3978]
### Describe the bug

When running `pnpm audit`  Ican see that there is a vulnerabilty in lodash and lodash is used by shadcn-ui under the hood.
high                             │ Command Injection in lodash  
│ Package                    │ lodash.template
│ Vulnerable versions │ <=4.5.0
│ Patched versions     │ <0.0.0
│ Paths                        │ . > shadcn-ui@0.8.0 > lodash.template@4.5.0
│ More info                 │ https://github.com/advisories/GHSA-35jh-r3h4-6jhm

### Affected component/components

shadcn-ui

### How to reproduce

Install "shadcn-ui": "^0.8.0" using pnpm

### System Info

```bash
"shadcn-ui": "^0.8.0",
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by jimmyntu** [comment]
Hi shadcn team, could you help to address this high security issue?

**Comment by JensAstrup** [comment]
Bumping this as it's high severity, any timeline on upgrading the dependency? I'm happy to open a PR if one isn't already opened

**Comment by gdragotto** [comment]
The PR in #4397 looks great, thanks @JensAstrup. Any news on the approval status?

**Comment by JensAstrup** [comment]
I have no idea who I'm waiting on for approval 😛

**Comment by gdragotto** [comment]
@shadcn ?

**Comment by vikasbhandari2** [comment]
Guys, it is a high vulnerability. any updates?

**Comment by ecsbeats** [comment]
+1

**Comment by mynlexi** [comment]
also waiting here

**Comment by SMaurischat** [comment]
Same!

**Comment by rjsprague** [comment]
+1
Better question, why even rely on Lodash. Seems to me it isn't well maintained. I always avoid Lodash due to frequent high severity vuln issues like this with it. Looks like we're all just supposed to head back to shadcn 1.0 for now?

**Comment by dcollien** [comment]
+1

**Comment by marulijames** [comment]
+1

**Comment by js-4** [comment]
May I add, there is the same problem in the shadcn package itself (not the cli) in the current main: https://github.com/shadcn-ui/ui/blob/1081536246b44b6664f4c99bc3f1b3614e632841/packages/shadcn/package.json#L62

Should I open another GH issue?

Thank you in advance!
