### ISSUE TITLE
Toast component missing imports & code

### ISSUE THREAD

**Issue by Eirfire** [shadcn-ui/ui#401]
Toast has a missing code from an import and incorrect installation or docs. these are some of the errors I can see, of course, this is easy to fix however it would be nice to have them installed by default.
![image](https://github.com/shadcn/ui/assets/77374574/5697f305-feca-432d-98ff-251693f7d5dd)
another issue I ran into is that the toaster component wasn't created so that code was missing

### What needs to be added or changed
- cva being added to the package.json just like `@radix-ui/react-toast` 
- `toaster.tsx` needs to be created 
- X icon could have a comment next to it or add the UI library or alternatively, the SVG could be added
- `cn` now this is defined in [taxonomy](https://github.com/shadcn/taxonomy) under lib in the [utils file](https://github.com/shadcn/taxonomy/blob/main/lib/utils.ts) again this would be nice to be in the `toast.tsx` file
    - `"tailwind-merge"`  and `clsx` being added in the package.json

**Comment by FranciscoMessina** [comment]
Some of the errors are solved with the the installation steps (Not for a specific component, but the general installation), telling you that you need to install CVA, tailwind and create the `cn` util, maybe you missed this step? Regarding the Icon, you should change it with whatever icon package you prefer if not using lucide. Why would the `cn` function be defined in the `toats.tsx` file, it is meant to be used in various components so I think it fits better in the `utils` folder, however you can of course move it to where you prefer. 

The `toaster.tsx` might be a bug that is missing from the CLI installation. Anyway this is just my opinion, hopefully the first part helps you fix some of the problems.

**Comment by Eirfire** [comment]
Ah ok I completely missed that step as I just skipped to the component as that's all I wanted that is my bad.

However it would still be nice if the cli tool checked those things when adding the component.

And yeh I'm assuming that there is a bug with adding the 
`toaster.tsx`component
