### ISSUE TITLE
[bug]: fix @media Queries for notbook screens documentation website

### ISSUE THREAD

**Issue by weldson01** [shadcn-ui/ui#4012]
### Describe the bug

The documentation needs specific media queries for notebook screens.

Screen resolution test: 1366x769.

![image](https://github.com/shadcn-ui/ui/assets/56852794/1496a0b5-90ac-40dd-9361-0e828d0674ed)

### Affected component/components

website documentation

### How to reproduce

1. Open documentation website https://ui.shadcn.com/docs/components/data-table
2. Open the devmode from chrome
3. Press ctrl+shift+M
4. Try a width greater than 768
5. It's here your bug

### System Info

```bash
SO: Windows 10 - 64bits,
Browser: Brave 1.67.116,
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by PranitPatil03** [comment]
hey @weldson01 

I've tried to reproduce the issue, but there isn't a bug here. [Check out the video.](https://www.loom.com/share/60c3ddb5eb7b4d37b8692c5a5d157823?t=23&sid=085ddd70-8e38-41e3-86f8-8d1113e9075c)
