### ISSUE TITLE
[feat]: able to change the @/components directory

### ISSUE THREAD

**Issue by FlareShip** [shadcn-ui/ui#4014]
### Feature description

It would be great if I can change where components go when I type `npx shadcn-ui@latest add ...`.

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by jolbol1** [comment]
I think you can already do this with `-p` or `--path`. See [here] for all available options.

Do you mean something else?

**Comment by FlareShip** [comment]
I want to configure that in `components.json` so I don't have to manually type `npx shadcn-ui@latest add [component] -p ...` every time I add a new component.

**Comment by jolbol1** [comment]
Ah, I believe you can do this by adding a "UI" alias in the components.json

So in `components.json` if I put 
```js
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/shadcn-ui"
  }
 ```

The add command installs my components to @/shadcn-ui folder. See this PR for more: https://github.com/shadcn-ui/ui/pull/2266

Not sure how/why this is different to the component alias?

**Comment by FlareShip** [comment]
Ok, thanks.
