### ISSUE TITLE
[feat]: Make the toast description React Node

### ISSUE THREAD

**Issue by alamenai** [shadcn-ui/ui#4023]
### Feature description

The current type for the description is `string`, however most of the type, I figured out that I use React Node also.

```ts
 toast({
      title: "Neu Strombedarf",
      description: "Friday, February 10, 2023 at 5:57 PM",
    })
```
I would suggest making the React Node as default also instead of change it from the code each time.

### Affected component/components

Toast

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by GIMMI42PIASTRATO** [comment]
description has already type ReactNode
