### ISSUE TITLE
[bug]: Input OTP Clicking Any Slot Just Selects The Last One

### ISSUE THREAD

**Issue by jacob-leger** [shadcn-ui/ui#4046]
### Describe the bug

# What Is The Problem?

When using the Input OTP component, I can navigate using the arrow keys.

<details><summary>Uses of Each Arrow Key</summary>
<p>

- Up: Navigate to the first slot
- Down: Navigate to the last (inputtable) slot
- Left: Move one slot to the left
- Right: Move one slot to the right

</p>
</details>

**However, I cannot navigate it with my mouse. If a slot is clicked, it will *always* select the last selectable one.**

## How Was This Discovered

I was browsing [the docs](https://ui.shadcn.com/docs), when I saw the [Input OTP component](https://ui.shadcn.com/docs/components/input-otp). After playing around, I noticed this bug.

## An Additional Thought

Additionally, I can not even use the arrow keys to select an empty space (not including the one following the last inputted digit). For all I know, this may be intentional.

## Thank You

Thank you all for your time spent reading this.

### Affected component/components

Input OTP

### How to reproduce

1. Access the component (either on your own machine or [in the docs](https://ui.shadcn.com/docs/components/input-otp), where you can just use the default example)
2. Type any random numbers. E.g., 123456
3. Navigate Using The Arrow Keys
4. Try to click on a cell (not including the last filled), and it will just select the last cell, not matter what 😭

### System Info

```bash
I am using Chrome Version 126.0.6478.114 (Official Build, 64 Bit) on a Windows 11 PC.

The issue was found using the docs, so ShadCN/UI was using the version in production on 6/19/2024.
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Leiloukou** [comment]
@moderators,
I suggest adding the `area: component`, `a11y`, and `component: input-otp` tags.

**Comment by NiklasPor** [comment]
Seems like this is also the case in the base repo: https://input-otp.rodz.dev
Maybe the issue should be moved there? https://github.com/guilhermerodz/input-otp

**Comment by jacob-leger** [comment]
> Seems like this is also the case in the base repo: https://input-otp.rodz.dev Maybe the issue should be moved there? https://github.com/guilhermerodz/input-otp

Done! https://github.com/guilhermerodz/input-otp/issues/76

Sorry I took so long lol
