### ISSUE TITLE
[feat]: More Maintainers

### ISSUE THREAD

**Issue by CC52-dev** [shadcn-ui/ui#4056]
### Feature description

This library just seems unmaintained. There are over 500 unresolved issues and over 540 pull requests.

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by CC52-dev** [comment]
@shadcn No offense btw but you could use some help

**Comment by hamidradical** [comment]
Yes, u are right. and i have been following from long time. I noticed this thing as well. And library is so cool i am using it in my two projects. Those two looks so good.

@shadcn please take an action.

**Comment by royjr** [comment]
I was really excited to start using shadcn-ui for my project because it looks great, but as others have mentioned, the amount of issues and PRs that are ready to merge from last year are really concerning. It doesn't seem dead given there are still recent commits. Could you please provide an update on the status and plans for the library? @shadcn  Thanks!

**Comment by renatoka** [comment]
Although I am not using this project personally, I would like to give my best show to start contributing as the way of expanding my knowledge. @shadcn count me in in case you need help!

**Comment by hamidradical** [comment]
@shadcn?

**Comment by shadcn** [comment]
Hi everyone. Just a quick update: I'm looking into it (and also working on a plan for handling all the open source projects) - I'll come up with a plan and update. Thanks for starting the conversation. Appreciate it!

**Comment by CC52-dev** [comment]
> Hi everyone. Just a quick update: I'm looking into it (and also working on a plan for handling all the open source projects) - I'll come up with a plan and update. Thanks for starting the conversation. Appreciate it!

I'm open if you need people to help maintain.

**Comment by xixixao** [comment]
@shadcn any updates on the plans?

**Comment by yf-hk** [comment]
One year has passed, there are more open issues now. And I can see that there is a very anoying bug that has been around for at least 6 months. Is there any plan of fixing them or adding more hands? @shadcn

**Comment by HasanMothaffar-OSG** [comment]
+1
