### ISSUE TITLE
Change action button position in sonner toast

### ISSUE THREAD

**Issue by TJ324694** [shadcn-ui/ui#4070]
### Feature description

I am currently trying to render a toast message, with a title, description and action button. And then when the action button is clicked, do a totally different thing. This is possible of course. But my issue is that my description is a bit long, like more than 40 letters, so this makes this toast message very hard to read an a bad UI.

Is there a way to change the action button in sonner toast to be at the bottom and not the right of the toast?

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by bhaskarkhoraja** [comment]
You can try changing flex direction to column while calling toast method

```jsx
<Button
  variant={"default"}
  onClick={() => {
    toast("Summer Vibes", {
      className: "flex-col", // change flex direction to column (action will be at bottom)
      description:
        "Immerse yourself ...  a lazy afternoon.", // Really really long text
      action: {
        label: "Noice",
        onClick: () => console.log("Noice"),
      },
    });
  }}
>
  Show Toast
</Button>
```

Output:
![image](https://github.com/shadcn-ui/ui/assets/87307200/09929374-6084-4fd8-8780-d1a5eddd4fb3)

**Comment by TJ324694** [comment]
> You can try changing flex direction to column while calling toast method
> 
> ```js
> <Button
>   variant={"default"}
>   onClick={() => {
>     toast("Summer Vibes", {
>       className: "flex-col", // change flex direction to column (action will be at bottom)
>       description:
>         "Immerse yourself ...  a lazy afternoon.", // Really really long text
>       action: {
>         label: "Noice",
>         onClick: () => console.log("Noice"),
>       },
>     });
>   }}
> >
>   Show Toast
> </Button>
> ```
> 
> Output: ![image](https://private-user-images.githubusercontent.com/87307200/342041368-09929374-6084-4fd8-8780-d1a5eddd4fb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTI0NzAsIm5iZiI6MTcxOTE1MjE3MCwicGF0aCI6Ii84NzMwNzIwMC8zNDIwNDEzNjgtMDk5MjkzNzQtNjA4NC00ZmQ4LTg3ODAtZDFhNWVkZGQ0ZmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE0MTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMDhiYjk3YmM4NDEyNzU3NjYwZDg4M2JlMjRlZGFhM2RiNDFjOThiZGM3YThjMjc2YzUyN2ZiMTUzNGY0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fjm2O9BL7mWTK2R1XtPwbnOktseCLCBXQbqozivT_rI)

This works as you've shown your screenshot. But if you have an icon say `toas.info`, the icon now goes to the middle.

**Comment by TJ324694** [comment]
> You can try changing flex direction to column while calling toast method
> 
> ```js
> <Button
>   variant={"default"}
>   onClick={() => {
>     toast("Summer Vibes", {
>       className: "flex-col", // change flex direction to column (action will be at bottom)
>       description:
>         "Immerse yourself ...  a lazy afternoon.", // Really really long text
>       action: {
>         label: "Noice",
>         onClick: () => console.log("Noice"),
>       },
>     });
>   }}
> >
>   Show Toast
> </Button>
> ```
> 
> Output: ![image](https://private-user-images.githubusercontent.com/87307200/342041368-09929374-6084-4fd8-8780-d1a5eddd4fb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTI0NzAsIm5iZiI6MTcxOTE1MjE3MCwicGF0aCI6Ii84NzMwNzIwMC8zNDIwNDEzNjgtMDk5MjkzNzQtNjA4NC00ZmQ4LTg3ODAtZDFhNWVkZGQ0ZmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE0MTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMDhiYjk3YmM4NDEyNzU3NjYwZDg4M2JlMjRlZGFhM2RiNDFjOThiZGM3YThjMjc2YzUyN2ZiMTUzNGY0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fjm2O9BL7mWTK2R1XtPwbnOktseCLCBXQbqozivT_rI)

This works as you've shown, but if I have an icon in the toast, say for `toast.info`, the icon goes to the center. Setting `className` as you've shown me to `grid` solves it though, so the icon goes to the beginning. My question is that how can I make the button take the whole width, like apply styles to the button specifically?

**Comment by TJ324694** [comment]
> > This works as you've shown, but if I have an icon in the toast, say for `toast.info`, the icon goes to the center. Setting `className` as you've shown me to `grid` solves it though, so the icon goes to the beginning. My question is that how can I make the button take the whole width, like apply styles to the button specifically?
> 
> You can apply styles only to the button as well, like in [Sonner Docs](https://sonner.emilkowal.ski/styling#tailwind-css)
> 
> ```js
> <Button
>   variant={"default"}
>   onClick={() => {
>     toast.info("Summer Vibes", {
>       classNames: {
>         toast: "flex-col items-start", // or use grid like you mentioned above
>         actionButton: "w-full justify-center",
>       },
>       description:
>         "Immerse yourself in the carefree spirit of summer with this vibrant and refreshing collection of content, perfect for soaking up the sun on a lazy afternoon.",
>       action: {
>         label: "Noice",
>         onClick: () => console.log("Noice"),
>       },
>     });
>   }}
> >
>   Show Toast
> </Button>
> ```
> 
> Output: ![image](https://private-user-images.githubusercontent.com/87307200/342190286-e717da09-10c9-4ccc-ad89-95dac52ea314.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjk4NTgsIm5iZiI6MTcxOTIyOTU1OCwicGF0aCI6Ii84NzMwNzIwMC8zNDIxOTAyODYtZTcxN2RhMDktMTBjOS00Y2NjLWFkODktOTVkYWM1MmVhMzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDExNDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NWM2NmVhYjJiMTVhMmYzYmRmNzc0YzhhODk3YWYyYTZjZGRhZmQwOTdmYjFlMTQwODU5MmZjMjYyYzc3NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RZIrm5VZbHWj0rINH73Q-thDziCSewBrM7kKbvOZbnk)

Turns out that the style you suggested works, but then one can't style stuffs like the color of the button without passing `unsettled: true` in the `toast`. I tried rendering my own jsx, but then the issue of the toast no longer closing automatically shows up.

**Comment by bhaskarkhoraja** [comment]
> Turns out that the style you suggested works, but then one can't style stuffs like the color of the button without passing `unsettled: true` in the `toast`. I tried rendering my own jsx, but then the issue of the toast no longer closing automatically shows up.

I think you meant to say `unstyled: true`, but you can change the color of button by using important in tailwind [Sonner (#321)](https://github.com/emilkowalski/sonner/issues/321). Also you must use `group-[.toast]:` for action or cancel button to properly target it.

```jsx
<Button
  variant={"default"}
  onClick={() => {
    toast.info("Styled Button", {
      classNames: {
        toast: "flex-col items-start",
        actionButton: "w-full justify-center group-[.toast]:!bg-red-500 group-[.toast]:!text-white", // mark the class as important.
      },
      description: "Testing styled component",
      action: {
        label: "Styled",
        onClick: () => console.log("Styled"),
      },
    })
  }}
>
  Show Styled Toast
</Button>
```

output:
![image](https://github.com/shadcn-ui/ui/assets/87307200/2fc4a0d2-0af3-416e-b6d3-aa7fa03ea21d)

For custom jsx, its working perfectly fine for me and the toast closes automatically as expected (without clicking the action button).
```jsx
<Button
  variant={"default"}
  onClick={() => {
    toast.custom((t) => (
      <div>
        This is a custom component
        <button onClick={() => toast.dismiss(t)}>close</button>
      </div>
    ))
  }}
>
  Show Custom Toast
</Button>
```

**Comment by TJ324694** [comment]
@bhaskarkhoraja thank you for assistance so far, they made me go further into wanting to solve it.

Your solutions somehow wasn't just working for me, don't know why. But I took your inspiration using the `!important` in tailwind, so from there I just override the things I want. This was what worked.

Posting my solution incase someome comes across the same issue and doesn't want to go the mile of looking into the **sonner** styling that much, but just wants a quick fix:

```ts
<Button
      variant="outline"
      onClick={() =>
        toast.info("Accept birthday card", {
          description:
            "We want to send you a birthday card. Do you agree?",
          closeButton: true,
          duration: Infinity,
          action: {
            label: "Accept",
            onClick: () =>
              requestBirthdayCard({
                name: user.name,
                email: user.email,
                phoneNumber: user.phoneNumber,
              }),
          },
          classNames: {
            toast: "flex-col items-start gap-4",
            actionButton:
              "!h-8 w-full !justify-center !whitespace-nowrap !rounded-md !bg-primary !px-3 !font-medium !text-primary-foreground",
          },
        })
      }
    >
      Accept
</Button>
  ```

**Comment by kerryj89** [comment]
I don't understand why Sonner chose not to have any container div structure to group alike items like icon+text and dismiss/action buttons.  This would be super trivial if it did that instead of the hacks shown here which add their own design opinionations like an icon in its own row or full width buttons.  I tried using css grid and setting elements to the same col/row will cause it to overlap... if only we had a container div.  We could still "ignore" the container div if necessary with `display:contents`.  Poor structuring, imo.
