### ISSUE TITLE
Unexpected behavior on table horizontal scrolling

### ISSUE THREAD

**Issue by moreei** [shadcn-ui/ui#416]
Hi @shadcn! Many thanks for this repo, amazing work 👏

Just noticed a strange behavior on the table component. When the content of the table is larger than the screen, a white space the size of the overflow is created. I have tried several things to fix this but nothing that works properly so far.

https://github.com/shadcn/ui/assets/15351304/1e2d097a-866d-449a-ac80-164dc82f796f

**Comment by PixeledCode** [comment]
opened up a PR that solves this overflow issue #428

**Comment by moreei** [comment]
Hey! Implemented in my code, it works fine 👌 Thanks for you contribution ❤️

**Comment by Cesar90** [comment]
Hey folks, perhaps this could work for someone

First watch of change of size of parent div using useLayoutEffect and ResizeObserver to observe changes to the div's size and save state in useState

```
const [elementWidth, setElementWidth] = React.useState(0);
React.useLayoutEffect(() => {
        // Function to update the width of the div using getElementById
        const updateWidth = () => {
            const element = document.getElementById('main-content');
            if (element) {
                setElementWidth(element.clientWidth - 70);
            }
        };

        // Create a ResizeObserver instance to observe changes to the div's size
        const resizeObserver = new ResizeObserver(() => {
            updateWidth(); // Call updateWidth when the div is resized
        });

        const element = document.getElementById('main-content');
        if (element) {
            resizeObserver.observe(element); // Start observing the div
        }

        // Initial width calculation
        updateWidth();

        // Cleanup function to disconnect the observer
        return () => {
            if (element) {
                resizeObserver.unobserve(element);
            }
        };
}, []);
```

Second I use elementWidth on the parent div of `<Table />` like this

![image](https://github.com/user-attachments/assets/067014a2-9750-480a-b909-b1b213685803)

With this the size of table can change when screen change.

**Comment by brandontle** [comment]
Thanks @Cesar90! This was the only solution that worked for me

**Comment by repovic** [comment]
In case someone want a version with the ScrollArea you can use this:

```ts
const Table = React.forwardRef<
    HTMLTableElement,
    React.HTMLAttributes<HTMLTableElement>
>(({ className, ...props }, ref) => (
    <ScrollArea className="w-full overflow-auto grid grid-cols-1 h-full">
        <table
            ref={ref}
            className={cn("relative w-full caption-bottom text-sm", className)}
            {...props}
        />
        <ScrollBar orientation="horizontal" />
        <ScrollBar orientation="vertical" />
    </ScrollArea>
));
Table.displayName = "Table";
```

**Comment by kylesurfs** [comment]
Thanks @repovic, `<ScrollArea>` is exactly what I needed to solve an issue with the table extending horizontally beyond the container.

**Comment by kylesurfs** [comment]
@repovic I followed your advice and have the exact same snippet as your example. Everything almost worked for me. However, if I scroll right past my last column, I'm able to go beyond the columns and then see a bunch of emptiness.

Does anyone know what may be going on or have advice?

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/ac066aff-6b04-4368-89bc-c8a6c0689ed3" />

**Comment by kylesurfs** [comment]
I solved my issue by using `overflow-contain`:

```
const TableCustom = React.forwardRef<
  HTMLTableElement,
  React.HTMLAttributes<HTMLTableElement>
>(({ className, ...props }, ref) => (
  <ScrollArea className="overflow-contain grid h-full w-full grid-cols-1">
    <table
      ref={ref}
      className={cn("w-full caption-bottom text-sm", className)}
      {...props}
    />
    <ScrollBar orientation="horizontal" />
    <ScrollBar orientation="vertical" />
  </ScrollArea>
));
TableCustom.displayName = "TableCustom";
```

**Comment by VesperQuartz** [comment]
> overflow-contain

there is not overflow-contain property in tailwindcss

**Comment by kylesurfs** [comment]
Good point -- the secret I guess was actually just removing `overflow-auto` altogether. `overflow-contain` isn’t a real Tailwind utility (and contain isn’t even a valid value for the CSS overflow property). Tailwind’s JIT compiler simply can’t match that token, so it generates no CSS rule for it. The class name is still left in the markup, but it does absolutely nothing. It worked because `overflow-auto` was removed (just updated my code to test this). Thanks

**Comment by zohaib650** [comment]
@kylesurfs Thank you

**Comment by ilhamgepe** [comment]
> In case someone want a version with the ScrollArea you can use this:
> 
> const Table = React.forwardRef<
>     HTMLTableElement,
>     React.HTMLAttributes<HTMLTableElement>
> >(({ className, ...props }, ref) => (
>     <ScrollArea className="w-full overflow-auto grid grid-cols-1 h-full">
>         <table
>             ref={ref}
>             className={cn("relative w-full caption-bottom text-sm", className)}
>             {...props}
>         />
>         <ScrollBar orientation="horizontal" />
>         <ScrollBar orientation="vertical" />
>     </ScrollArea>
> ));
> Table.displayName = "Table";

work form me tahnks @repovic
