### ISSUE TITLE
[bug]: Cursor is default on <DropdownMenuPrimitive.Item />

### ISSUE THREAD

**Issue by John-Baik** [shadcn-ui/ui#4166]
### Describe the bug

On hover, the cursor is on default when it should be pointer. 

### Affected component/components

DropdownMenuPrimitive.Item

### How to reproduce

Hover on DropdownMenuPrimitive.Item and the cursor will be on default.
Why is it set to default and not pointer?

### System Info

```bash
N/A
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by shadcn** [comment]
Please note that this is intentional. See https://github.com/shadcn-ui/ui/issues/2212#issuecomment-1880000745

If you'd like to customize it in your apps, that's of course totally fine.
