### ISSUE TITLE
Components are installed in the a directory called "@" instead of "src" when using Vite and Bun [bug]: 

### ISSUE THREAD

**Issue by nico188f** [shadcn-ui/ui#4172]
### Describe the bug

I was following the [Shadcn/ui Vite installation guide](https://ui.shadcn.com/docs/installation/vite) but when I tried to download a button it downloaded it in the wrong place.

Since the guide has been written a new version of vite has come out which separates out the tsconfig into 3 files: tsconfig.json, tsconfig.app.json, and tsconfig.node.json.

I decided to add the base URL and path to tsconfig.app.json since it contained the "compilerOptions". Here is my tsconfig.app.json:
```typescript
{
   "compilerOptions": {
      "composite": true,
      "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
      "target": "ES2020",
      "useDefineForClassFields": true,
      "lib": ["ES2020", "DOM", "DOM.Iterable"],
      "module": "ESNext",
      "skipLibCheck": true,

      /* Bundler mode */
      "moduleResolution": "bundler",
      "allowImportingTsExtensions": true,
      "resolveJsonModule": true,
      "isolatedModules": true,
      "moduleDetection": "force",
      "noEmit": true,
      "jsx": "react-jsx",

      /* Linting */
      "strict": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "noFallthroughCasesInSwitch": true,

      /* Paths */
      "baseUrl": ".",
      "paths": {
         "@/*": ["./src/*"]
      }
   },
   "include": ["src"]
}
``` 
Here is my component.json:
```typescript
{
   "$schema": "https://ui.shadcn.com/schema.json",
   "style": "default",
   "rsc": false,
   "tsx": true,
   "tailwind": {
      "config": "tailwind.config.js",
      "css": "src/index.css",
      "baseColor": "neutral",
      "cssVariables": true,
      "prefix": ""
   },
   "aliases": {
      "components": "@/components",
      "utils": "@/lib/utils"
   }
}
``` 
And here is my vite.config.ts
```typescript
import path from "path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
   plugins: [react()],
   resolve: {
      alias: {
         "@": path.resolve(__dirname, "./src"),
      },
   },
});
``` 

### Affected component/components

All

### How to reproduce

1. Initiate Vite using Bun.
2. Follow the steps on [Shadcn/ui Vite installation guide](https://ui.shadcn.com/docs/installation/vite) but instead of using npm and npx use bun and bunx.
3. Try to install any component

### System Info

```bash
windows 11 Version 23H2 (OS Build 22631.3737), bash 5.2.26(1)-release, bun (1.1.17+bb66bba1b),
Package.json:
{
  "name": "frontend",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "bunx --bun vite",
    "build": "bunx --bun vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@radix-ui/react-slot": "^1.1.0",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "lucide-react": "^0.400.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "tailwind-merge": "^2.3.0",
    "tailwindcss-animate": "^1.0.7"
  },
  "devDependencies": {
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@typescript-eslint/eslint-plugin": "^7.13.1",
    "@typescript-eslint/parser": "^7.13.1",
    "@vitejs/plugin-react": "^4.3.1",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.57.0",
    "eslint-plugin-react-hooks": "^4.6.2",
    "eslint-plugin-react-refresh": "^0.4.7",
    "postcss": "^8.4.39",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.2.2",
    "vite": "^5.3.1"
  }
}
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by thelastpiece** [comment]
Something in the tsconfig.json files created by Vite changed between Vite version 5.2 and 5.3 (latest) -- causing this bug to occur.

I solved this by creating a project with Vite@5.2, copying those tsconfig files and moving them into my Vite@5.3 project.

Unsure what unintended consequences of this will be, but at least the UI code is being generated in the correct place.

**Comment by hsnfirdaus** [comment]
I fixed this in latest vite by adding:
```json5
{
         /* Other Config */
	"compilerOptions": {
		/* Other Config */
		"baseUrl": ".",
		"paths": {
			"@/*": ["./src/*"]
		}
	}
}
```
To all tsconfig file! (`tsconfig.app.json`, `tsconfig.json`, `tsconfig.node.json`). Not sure which one is used by shadcn cli, but it's fixed my problem in latest vite version.

**Comment by nico188f** [comment]
> ```js
> "compilerOptions": {
> 		/* Other Config */
> 		"baseUrl": ".",
> 		"paths": {
> 			"@/*": ["./src/*"]
> 		}
> 	}
> ```

This fixed it, didn't realize that shad/cn referenced tsconfig.json specifically.
Anyways thanks!
