### ISSUE TITLE
[bug]: in combobox page from docs

### ISSUE THREAD

**Issue by GurbanmyradowSerdar** [shadcn-ui/ui#4180]
### In combobox page, i got the error, when i tried to use one of yours component. Here i will provide schreenshots of error

**I clicked to select language**

![Screenshot 2024-07-06 025649](https://github.com/shadcn-ui/ui/assets/115923465/952442e2-2883-41da-8423-2afe5577a460)
### Application error: a client-side exception has occurred (see the browser console for more information).
![image](https://github.com/shadcn-ui/ui/assets/115923465/585e2d31-ca81-4b90-acd7-98fafc647567)

### Affected component/components

Combobox

### How to reproduce

1. Opened https://ui.shadcn.com/docs/components/combobox page
2. scrolled to last component in the page
3. clicked select language

### Logs

```bash
Application error: a client-side exception has occurred (see the browser console for more information).

Error below got from browsers console
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at O (69016-e46275a046c77977.js:1:8485)
    at M (69016-e46275a046c77977.js:1:7484)
    at 69016-e46275a046c77977.js:1:6256
    at 69016-e46275a046c77977.js:1:14852
    at Map.forEach (<anonymous>)
    at 69016-e46275a046c77977.js:1:14841
    at aI (eb2a38ac-8c1a930f3b668d8a.js:1:72883)
    at aU (eb2a38ac-8c1a930f3b668d8a.js:1:72943)
    at aV (eb2a38ac-8c1a930f3b668d8a.js:1:73382)
```

### System Info

```bash
chrome
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by manjushsh** [comment]
Hi @GurbanmyradowSerdar , I have created PR to fix this: #4097

**Comment by fredle09** [comment]
Just wrap `<CommandEmpty>`, and `<CommandGroup>` into `<CommandList>` to fix this error

**Comment by GurbanmyradowSerdar** [comment]
Thanks for yours support, i will try it!
