### ISSUE TITLE
[feat]: Realtime charts

### ISSUE THREAD

**Issue by guptaashwanee** [shadcn-ui/ui#4205]
### Feature description

Implementation of realtime charts, which will animate on data update.

### Affected component/components

Chart

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by vallamost** [comment]
Do you have an example with fake data showing that the charts don't animate upon new updates? Recharts out of the box supports this, so it's strange that it wouldn't be included..

**Comment by aabassiouni** [comment]
Recharts already does this. You just have to update whatever you're passing in to the data prop.

**Comment by guptaashwanee** [comment]
Yes, I have gone through the Recharts documentation, it works well with realtime data update. There was a tiny mistake from my side. Thanks for your efforts @vallamost @aabassiouni .
