### ISSUE TITLE
[bug]: Charts examples code can't be viewed on desktop in /charts

### ISSUE THREAD

**Issue by Maqed** [shadcn-ui/ui#4210]
### Describe the bug

When I press "View code" button on desktop in https://ui.shadcn.com/charts , the code isn't shown. This is what is get: 
![image](https://github.com/shadcn-ui/ui/assets/67274056/d7e7b37f-d296-4655-a5f8-cd8df706cd10)
This happens when I press the theme button as well. There's no scroll 

But the code is shown on mobile view
![charts ](https://github.com/shadcn-ui/ui/assets/67274056/50a611ac-752e-4c14-b87b-14b17efe800d)

### Affected component/components

Charts examples in /charts

### How to reproduce

On Desktop:
1. Go to https://ui.shadcn.com/charts
2. Click Press View Code Button
3. The **code won't be shown** in the sheet, **only the chart**

On Mobile:
1. Go to https://ui.shadcn.com/charts
2. Click Press View Code Button
3. The **chart won't be shown** in the drawer, **only the code**

### System Info

```bash
Google Chrome Browser
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by xSenny** [comment]
Try to zoom out, using `ctrl + -`

**Comment by Maqed** [comment]
> Try to zooming out, using `ctrl + -`

![image](https://github.com/shadcn-ui/ui/assets/67274056/2632ca74-386c-4d74-a670-c968cfec2153)
Yeah it worked, But I hope a hide button for the chart to be added.

**Comment by shadcn** [comment]
which resolution is this? can you help me reproduce?

**Comment by Maqed** [comment]
> which resolution is this? can you help me reproduce?
My screen resolution is 1366 x 768
