### ISSUE TITLE
[bug]: Charts tooltip formatter doesn't work if value = 0 

### ISSUE THREAD

**Issue by VeiaG** [shadcn-ui/ui#4214]
### Describe the bug

While using custom formatter for ChartTooltip , if value =0 , formatter function not using in tooltip.
![image](https://github.com/shadcn-ui/ui/assets/41997946/430589f9-bb35-45d6-93b8-62c9786cbb9a)
![image](https://github.com/shadcn-ui/ui/assets/41997946/6cd71022-d41b-4777-8c2f-0ce73ced7a70)

```
<ChartTooltip
    cursor={false}
    content={<ChartTooltipContent
        labelFormatter={(value) =>
            new Date(value).toLocaleDateString()
        }
        formatter={
            (value) => getNumbersBySeconds(value as number)
        }
        hideIndicator />}
/>
```

Fixed ,by changing this line 
```
 {formatter && item.value && item.name ? (
     formatter(item.value, item.name, item, index, item.payload)
    ) : ...
 ```
to 
```
formatter && (item?.value !== undefined) && item.name ? ...
```

### Affected component/components

ChartTooltip

### How to reproduce

1. Create chart with data, that contains 0 .
2. Add ChartTooltip with custom formatter function

### System Info

```bash
Windows
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Rekl0w** [comment]
PR submitted.

**Comment by hitecSmartHome** [comment]
Still doesn't work with 0

**Comment by hitecSmartHome** [comment]
Oh, yeah. It was the same thing.

I had to modify from

```jsx
{item.value && (
  <span className="font-mono font-medium tabular-nums text-foreground">
    {valueFormatter
      ? valueFormatter(item.value)
      : item.value.toLocaleString()}
  </span>
)}
```

to

```jsx
{item.value != undefined && (
  <span className="font-mono font-medium tabular-nums text-foreground">
    {valueFormatter
      ? valueFormatter(item.value)
      : item.value.toLocaleString()}
  </span>
)}
```
