### ISSUE TITLE
[bug]: Dialog opening without trigger?

### ISSUE THREAD

**Issue by OhYello** [shadcn-ui/ui#4220]
### Describe the bug

I'm using the example from https://ui.shadcn.com/docs/components/dialog and when I use the component, the Dialog automatically opens without any trigger? Also I can't close it. Is this a bug or am I doing something wrong?

```
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function DialogDemo() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Edit Profile</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Edit profile</DialogTitle>
          <DialogDescription>
            Make changes to your profile here. Click save when you're done.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="name" className="text-right">
              Name
            </Label>
            <Input
              id="name"
              defaultValue="Pedro Duarte"
              className="col-span-3"
            />
          </div>
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="username" className="text-right">
              Username
            </Label>
            <Input
              id="username"
              defaultValue="@peduarte"
              className="col-span-3"
            />
          </div>
        </div>
        <DialogFooter>
          <Button type="submit">Save changes</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
```

### Affected component/components

Dialog

### How to reproduce

Copied the Dialog example and when I use the component, the Dialog automatically opens without clicking on any trigger plus I can't seem to close the Dialog when it's opened.

### System Info

```bash
macOs, Chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by 25zeeshan** [comment]
Hi @OhYello ,

I was going through this issue and trying to resolve it, but I need more details to understand and replicate the problem.

Could you share the relevant code snippet where you’re using the Dialog component?  OR you could provide the actual project repository or a minified version of the project in a new repository. This will help in reproducing the issue.

Any additional information or context you can provide would be extremely helpful. Thanks

**Comment by OhYello** [comment]
@25zeeshan looks like I found the problem, `forceMount` was being used in the `<DialogPortal>` component
