### ISSUE TITLE
[bug]: Gray box on hover on new Charts

### ISSUE THREAD

**Issue by RHaughton** [shadcn-ui/ui#4233]
### Describe the bug

Hi, I'm having a weird interaction between shadcn, Tailwind and recharts.
When I hover a BarChart I get a weird gray block on it.

![image](https://github.com/shadcn-ui/ui/assets/24850599/fa0ca0aa-efc4-4972-9235-966e4e18eef6)

If I uncheck --muted in the developper tools the gray box turns black.

![image](https://github.com/shadcn-ui/ui/assets/24850599/8bc03fd8-5893-466a-b8a9-340f98d9912e)

![image](https://github.com/shadcn-ui/ui/assets/24850599/02543e0f-4660-4e3f-a62f-f6d7d103f546)

### Affected component/components

ShadCN Charts with Rechart BarChart

### How to reproduce

Create a barchart with ShadCN tailwind and recharts. hover a category.

### System Info

```bash
Chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by 0OZ** [comment]
I encountered the same issue. To resolve it, ensure that the `<ChartTooltip />` element is placed above the `<XAxis />` element in your component hierarchy. This arrangement ensures that the <path /> element is rendered above other elements in the DOM, maintaining the correct layering order.

```jsx
<ChartContainer config={chartConfig}>
  <BarChart accessibilityLayer data={data}>
    <CartesianGrid vertical={false} />
    <ChartTooltip content={<ChartTooltipContent />} />
    <XAxis />
    <Bar dataKey="value" name={'Count'} radius={4} />
  </BarChart>
</ChartContainer>
```

**Comment by RHaughton** [comment]
This was it. Thanks you so much for your help!

**Comment by J0hnRoger** [comment]
It save many minutes, thanks @0OZ !

**Comment by vinula-senarathne** [comment]
Answer from @0OZ didn't work for me. Changing the fill color from `muted` to `transparent` in the `ChartContainer` within the `chart.tsx` file solved my issue.

```ts
[&_.recharts-rectangle.recharts-tooltip-cursor]:fill-transparent
```
