### ISSUE TITLE
[bug]: Input inside Accordion

### ISSUE THREAD

**Issue by YerayAlonso** [shadcn-ui/ui#4246]
### Describe the bug

If you have an Input inside an Accordion, when you focus that input, the border is cut:

![imagen](https://github.com/shadcn-ui/ui/assets/1788228/42c325cd-8dd9-4aa5-b051-ff576763d573)

### Affected component/components

Accordion with Input

### How to reproduce

Add an Accordion
Add an Input into the accordion
Run and put the cursor inside the input

### Codesandbox/StackBlitz link

https://stackblitz.com/edit/stackblitz-starters-1kauuu?file=app%2Fpage.tsx

### System Info

```bash
Tested in Windows 10 both with Firefox 127 and and Brave 126
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by manjushsh** [comment]
Hi @YerayAlonso, It looks like margin issue:
```javascript
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Input } from '@/components/ui/input';

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between text-sm lg:flex">
        <Input />
        <Accordion type="single" defaultValue="item-1">
          <AccordionItem value="item-1">
            <AccordionTrigger>Input inside accordion</AccordionTrigger>
            <AccordionContent className="m-1">
              <Input  />
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </main>
  );
}
```

**Comment by YerayAlonso** [comment]
I'm pretty sure I tried it but it wasn't working for some reason.
Sorry and thanks!

**Comment by MehbubRashid** [comment]
This is not yet fixed. not sure why you have closed this without having an actual solution

**Comment by YerayAlonso** [comment]
> This is not yet fixed. not sure why you have closed this without having an actual solution

Adding a little margin solved the issue for me. Didn't it work for you?

```jsx
<AccordionContent className="m-1">
```

I'm happy with it. That's why I closed it.
If you find the components should add that margin automatically, you can open an issue yourself.

**Comment by MehbubRashid** [comment]
Adding margin is only a workaround. The input field not having margin by default is not the issue. The issue is AccordionContent forcing overflow hidden. Yeah, I guess I have to open the issue myself.
