### ISSUE TITLE
[bug]: Vite Alias Configuration Issue - Incorrect Root Path

### ISSUE THREAD

**Issue by burakndmr** [shadcn-ui/ui#4253]
### Describe the bug

I am following the Vite section of the documentation. When I create a new shadcn component, it creates the alias in the root directory instead of within the src directory.

### Affected component/components

all components

### How to reproduce

1. Create a Vite React TypeScript project.
2. Follow the Vite section of the shadcn documentation.
3. Add a button component using shadcn.
4. Observe that the components and lib directories, which should be created inside the src directory, are instead created in the root directory under the @ alias.

### System Info

```bash
- **Operating System:** Windows 11 pro
- **Node.js version:** v20.10.0
- **NPM/Yarn version:** 10.6.0
- **Vite version:** vite/5.3.3 win32-x64 node-v20.10.0
- **Browser:** Google Chrome 126.0.6478.127
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Mayvis** [comment]
I also face this situation. This is not working for me, ref: https://github.com/shadcn-ui/ui/issues/4172

```json
{
	"compilerOptions": {
		"baseUrl": ".",
		"paths": {
			"@/*": ["./src/*"]
		}
	}
}
```

**Comment by burakndmr** [comment]
> ref: #4172
> 
> I paste tsconfig.app.json, tsconfig.json tsconfig.node.json with below code, and it work. But I would like to know why?😅
> 
> ```json
> {
> 	"compilerOptions": {
> 		"baseUrl": ".",
> 		"paths": {
> 			"@/*": ["./src/*"]
> 		}
> 	}
> }
> ```

Thank you very much, it solved it surprisingly well 😅
