### ISSUE TITLE
[bug]: ScrollArea and Carousel issue

### ISSUE THREAD

**Issue by cwysong85** [shadcn-ui/ui#4258]
### Describe the bug

I'm unsure if this is a bug or if I'm possibly coding this improperly. Below are two screen shots of using `<Carousel>` with the default scrollbar from the browser and one using the `<ScrollArea>` component:

Default Browser Scrollbar
![default scrollbar](https://github.com/shadcn-ui/ui/assets/2041279/532d7ffb-1337-4a2c-aee0-23c6079052ce)

`<ScrollArea>` Component
![radix scrollbar](https://github.com/shadcn-ui/ui/assets/2041279/2c503272-d52c-4967-a364-4ae2b88c89cf)

As you can see, the default browser scrollbar overflow and sizing works as you'd expect. But once I introduce the `<ScrollArea>` component, the sizing of the Carousel Images blow up and the overflow is off the page.

Here is the code from my `<SubscriptionPanel>` component:

```JSX
return (
    <AnimationPanel className="h-full w-full px-4 py-4">
      <div className="flex h-full flex-1 flex-col gap-4">
        {isSuccess && (
          <ScrollArea>
            <div className="flex h-full w-full flex-col gap-4">
              {publishedDocs.map((d) => {
                const {
                  docId,
                  author,
                  tags,
                  summary,
                  publishedDate,
                  docTitle,
                } = destructData(d);

                return (
                  <Card key={docId} className="p-4">
                    <CardHeader>
                      <CardTitle className="text-xl font-bold">
                        {docTitle}
                      </CardTitle>
                      <CardDescription className="flex flex-col gap-2 text-sm dark:text-white/70">
                        Published by {author} on {publishedDate}
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="flex flex-col gap-2">
                      <DocumentTags tags={tags} />
                      <p>{`${summary.slice(0, 400)}...`}</p>
                      <DocumentMedia documentId={docId} />
                    </CardContent>
                    <CardFooter className="flex justify-end gap-3">
                      <Button
                        className="flex gap-2"
                        variant="outline"
                        onClick={() => handleViewDocument(docTitle, summary)}
                      >
                        View
                        <ChevronRight className="h-4 w-4" />
                      </Button>
                      <Button
                        className="flex gap-2"
                        onClick={() => handleSubscribeToDocument(docId)}
                      >
                        Subscribe
                        <FileHeart className="h-4 w-4" />
                      </Button>
                    </CardFooter>
                    <div className="bg-border-light dark:bg-border-dark/70 h-[1px] w-full rounded"></div>
                  </Card>
                );
              })}
            </div>
          </ScrollArea>
        )}
      </div>
      {modal}
    </AnimationPanel>
  );
```

Here's the code from my `<DocumentMedia>` component:

```JSX
  return (
    <div className="relative w-full">
      <Carousel
        className="w-full"
        opts={{
          align: "start",
        }}
      >
        <CarouselContent className="flex gap-2">
          {mediaBlobs.map((blob, index) => (
            <CarouselItem
              key={index}
              className="basis-full sm:basis-1/2 md:basis-1/3 lg:basis-1/4 xl:basis-1/5"
            >
              <div className="p-1">
                <Card>
                  <CardContent
                    className="flex aspect-square items-center justify-center p-6"
                    onClick={() => handleMediaClick(blob)}
                  >
                    <Image
                      src={createBlobUrl(blob)}
                      alt={`Document Media ${index + 1}`}
                      width={150}
                      height={150}
                      className="h-full w-full object-cover"
                    />
                  </CardContent>
                </Card>
              </div>
            </CarouselItem>
          ))}
        </CarouselContent>
        <CarouselPrevious className="absolute left-0 top-1/2 z-10 -translate-y-1/2 transform" />
        <CarouselNext className="absolute right-0 top-1/2 z-10 -translate-y-1/2 transform" />
      </Carousel>
      {modal}
    </div>
  );
  ```

What feels like is happening is the heights, widths, etc aren't being calculated properly since the media from the `<Carousel>` items is being loaded (API call) within the `<DocumentMedia documentId={docId} />` component. I've noticed the carousel images when first loaded for a split second are normal and then they are resized to the larger images and the overflow, widths, height are messed up. This only happens when the `<ScrollArea>` component is introduced. Any help is greatly appreciated!

### Affected component/components

ScrollArea, Carousel

### How to reproduce

1. Create a carousel component that loads in images
2. Create a component that uses the ScrollArea component that consumes the component that uses the Carousel.

### System Info

```bash
Windows 11, Chrome Version 126.0.6478.127
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by F-z-Coder** [comment]
Same issue , basically this happing because of "@radix-ui/react-scroll-area" component which   add "display: table" style to disable overflow   [`](https://github.com/radix-ui/primitives/blob/8175208cdbb8577e53f1165678ee0ce28a801837/packages/react/scroll-area/src/ScrollArea.tsx#L178)      {/**
           * `display: table` ensures our content div will match the size of its children in both
           * horizontal and vertical axis so we can determine if scroll width/height changed and
           * recalculate thumb sizes. This doesn't account for children with *percentage*
           * widths that change. We'll wait to see what use-cases consumers come up with there
           * before trying to resolve it.
           */}
          <div ref={context.onContentChange} style={{ minWidth: '100%', display: 'table' }}>
            {children}
          </div>`

**Comment by F-z-Coder** [comment]
**Quick solution just add  [&>div]:!block in viewport component** 
```
<ScrollAreaPrimitive.Viewport className="h-full w-full rounded-[inherit] [&>div]:!block">
      {children}
    </ScrollAreaPrimitive.Viewport>
```

**Comment by cwysong85** [comment]
That fixed it! Thank you for the quick response.
