### ISSUE TITLE
[feat]: open accordion items conditionally

### ISSUE THREAD

**Issue by hashim-rana-hub** [shadcn-ui/ui#4296]
### Feature description

i want to set default open value for accordion conditionally
like when number in the url changes then another section sets to default open

### Affected component/components

Accordion

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by rahul-metaphy** [comment]
@hashim-rana-hub 
Since Shadcn UI uses Radix UI Accordian you can use the [[Expanded by default](https://www.radix-ui.com/primitives/docs/components/accordion#expanded-by-default)](https://www.radix-ui.com/primitives/docs/components/accordion#expanded-by-default)

**Comment by hashim-rana-hub** [comment]
> @hashim-rana-hub Since Shadcn UI uses Radix UI Accordian you can use the [[Expanded by default](https://www.radix-ui.com/primitives/docs/components/accordion#expanded-by-default)](https://www.radix-ui.com/primitives/docs/components/accordion#expanded-by-default)
> 
> you can pass undefined the defaultValue incase you don't want to show it

actually i have set it conditionally by having state with initially value of desired sections to be open by default then i change the state on the basis or url by extracting hash from location object 
```

  function updateAccordionAndScroll(citationId) {
    setAccordionValues(prevValues => (prevValues.includes(REFERENCES) ? prevValues : [...prevValues, REFERENCES]));

    const timeoutId = setTimeout(() => {
      scrollToSection(citationId);
    }, 200);

    return timeoutId;
  }

 useEffect(() => {
    const citationId = location.hash.substring(1);
    if (!citationId) return;

    const timeoutId = updateAccordionAndScroll(citationId);

    return () => cleanupTimeout(timeoutId);
  }, [location.hash, REFERENCES, setAccordionValues]);
```
