### ISSUE TITLE
[bug]: datepicker get a wrong css

### ISSUE THREAD

**Issue by jizhi0v0** [shadcn-ui/ui#4361]
### Describe the bug

Not displayed as expected

### Affected component/components

Date Picker

### How to reproduce

1.Click on datepicker component

![Google Chrome 2024-07-21 20 41 32](https://github.com/user-attachments/assets/ca457a4f-6bea-4d88-93a5-ee9d5d169e11)

### System Info

```bash
Browsers
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by plutack** [comment]
I have been battling this for the past 12hrs no cap. Since I am not very familiar with shadcn and r act components, I was under the assumption I am doing something wrong.
I am also getting some errors after installing calendar. 
Caption does not seem to exist in type partial <classnames> . I can't also seem to find it any where after navigating through the UI types where something like caption _label can be found.
Same thing for iconLeft which is suppose to exist in partial <customComponents>

**Comment by activemonkeys** [comment]
Did you install the new react-day-picker v9.0.0? That one seems to come with several breaking changes. When using react-day-picker 8.10.1 you will probably be fine for the moment.

**Comment by plutack** [comment]
@activemonkeys I will try that now. I have v9 installed

**Comment by jizhi0v0** [comment]
> Did you install the new react-day-picker v9.0.0? That one seems to come with several breaking changes. When using react-day-picker 8.10.1 you will probably be fine for the moment.

It works,Thank you so much!

**Comment by jizhi0v0** [comment]
> I have been battling this for the past 12hrs no cap. Since I am not very familiar with shadcn and react components, I was under the assumption I am doing something wrong. I am also getting some errors after installing calendar. Caption does not seem to exist in type partial < classnames > . I can't also seem to find it any where after navigating through the UI types where something like caption _label can be found. Same thing for iconLeft which is suppose to exist in partial < customComponents >

You should run the below command
```
npm i react-day-picker@8.10.1
```

**Comment by firdoesdev** [comment]
> Did you install the new react-day-picker v9.0.0? That one seems to come with several breaking changes. When using react-day-picker 8.10.1 you will probably be fine for the moment.

Thank You! it's work 👍

**Comment by masewo** [comment]
Tried to migrate the shadcn Calendar to react-date-picker 9.x.x but I gave up since I cannot find out how to attach the hover styles to the day button and not to the day cell...

<details>
  <summary>Click me</summary>
  
  ```tsx
import * as React from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { DayPicker } from "react-day-picker";

import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";

export type CalendarProps = React.ComponentProps<typeof DayPicker>;

function Calendar({
  className,
  classNames,
  showOutsideDays = true,
  ...props
}: CalendarProps) {
  return (
    <DayPicker
      showOutsideDays={showOutsideDays}
      className={cn("p-3", className)}
      classNames={{
        months: "flex flex-col sm:flex-row space-y-4 sm:space-x-4 sm:space-y-0",
        month: "space-y-4",
        month_caption: "flex justify-center pt-1 relative items-center",
        caption_label: "text-sm font-medium",
        nav: "space-x-1 flex items-center",
        button_previous: cn(
          buttonVariants({ variant: "outline" }),
          "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100",
          "absolute left-10 top-[70px] z-10",
        ),
        button_next: cn(
          buttonVariants({ variant: "outline" }),
          "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100",
          "absolute right-6 top-[70px] z-10",
        ),
        month_grid: "w-full border-collapse space-y-1",
        weekdays: "flex",
        weekday:
          "text-muted-foreground rounded-md w-9 font-normal text-[0.8rem]",
        week: "flex w-full mt-2",
        day: "h-9 w-9 text-center text-sm p-0 relative [&:has([aria-selected])]:bg-accent first:[&:has([aria-selected])]:rounded-l-md last:[&:has([aria-selected])]:rounded-r-md focus-within:relative focus-within:z-20",
        day_button: cn(
          buttonVariants({ variant: "ghost" }),
          "h-9 w-9 p-0 font-normal aria-selected:opacity-100",
        ),
        selected:
          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
        today: "bg-accent text-accent-foreground",
        outside: "text-muted-foreground opacity-50",
        disabled: "text-muted-foreground opacity-50",
        range_middle:
          "aria-selected:bg-accent aria-selected:text-accent-foreground",
        hidden: "invisible",
        ...classNames,
      }}
      components={{
        Chevron: (props) =>
          props.orientation === "left" ? (
            <ChevronLeft className="h-4 w-4" />
          ) : (
            <ChevronRight className="h-4 w-4" />
          ),
      }}
      {...props}
    />
  );
}
Calendar.displayName = "Calendar";

export { Calendar };

  ```
</details>

**Comment by efgomes** [comment]
![image](https://github.com/user-attachments/assets/f474595e-8910-4d96-8d0b-ff70bad88639)
I'm using 9.0, and my calendar is like this

**Comment by Geeraldv** [comment]
> Thank You! it's work for me  👍

**Comment by Geeraldv** [comment]
> > Did you install the new react-day-picker v9.0.0? That one seems to come with several breaking changes. When using react-day-picker 8.10.1 you will probably be fine for the moment.
> 
> Thank You! it's work for me 👍

**Comment by kachkaev** [comment]
PR with a fix: https://github.com/shadcn-ui/ui/pull/4421

**Comment by tresorama** [comment]
In meantime, if someone want to use both v8 and v9 at the same time, it's possible to have both

https://medium.com/weekly-webtips/how-to-install-multiple-versions-of-the-same-package-in-npm-71c29b12e253

**Comment by LuisMFG1992** [comment]
The current [shadcn/ui](https://ui.shadcn.com/) does not show the latest version. For a proper integration, please refer to [date-picker.luca-felix.com](https://date-picker.luca-felix.com/). 

You can find this information in the official webpage from daypicker https://daypicker.dev/docs/styling

**Comment by retailwolfmonaro** [comment]
It seems that react 19 does not support react-day-picker in version 8.10.1, can anyone using react 19 with date-picker tell me how they solved the problem?

**Comment by PurrCat101** [comment]
> It seems that react 19 does not support react-day-picker in version 8.10.1, can anyone using react 19 with date-picker tell me how they solved the problem?

I use the Date Time Picker from https://github.com/huybuidac/shadcn-datetime-picke), and it works well in my project.

![Image](https://github.com/user-attachments/assets/d522e15e-af53-4305-bd37-a5433ed1bffa)

**Comment by legion40216** [comment]
Does anyone know how to style the new day picker v9 shadcn ui + nextjs + tailwind v4  ?

**Comment by mukhammadxuja** [comment]
> Did you install the new react-day-picker v9.0.0? That one seems to come with several breaking changes. When using react-day-picker 8.10.1 you will probably be fine for the moment.

Thank you
