### ISSUE TITLE
[feat]: Select element ref

### ISSUE THREAD

**Issue by V0IDL355** [shadcn-ui/ui#4370]
### Feature description

Is it possible to add the ref prop to https://ui.shadcn.com/docs/components/select ?

### Affected component/components

Select

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by akash191095** [comment]
@V0IDL355 you can pass the ref prop to the  `<SelectTrigger/>` component

**Comment by V0IDL355** [comment]
Found another way to solve my issue but thanks for the help anyways :)

**Comment by BeeAwwad** [comment]
Please what was the other way you used?

**Comment by Bread-Ch4n** [comment]
> @Bread-Ch4n how did you solve it?

It's been very long that i forgot 🤣
I think i was just making the select items into a list or smth
