### ISSUE TITLE
[bug]: Will got error on charts if build on nextjs 15 canary

### ISSUE THREAD

**Issue by vincentzhangz** [shadcn-ui/ui#4376]
### Describe the bug

I got error when test building on Next.JS 15 canary 76. 
Hope it will got to check the code, so when Next.JS 15 release, we can upgrade it smoothly.

<img width="981" alt="Screenshot 2024-07-22 at 18 43 40" src="https://github.com/user-attachments/assets/8da68ec9-caea-423a-90dd-9f57808616de">

### Affected component/components

Charts

### How to reproduce

Build shadcn-ui on Next.JS 15 canary 

### Logs

```bash
$ next build
 ⚠ Configuration with next.config.ts is currently an experimental feature, use with caution.
  ▲ Next.js 15.0.0-canary.76
  - Environments: .env.local

   Creating an optimized production build ...
 ✓ Compiled successfully

Failed to compile.

./src/components/ui/chart.tsx
6:3  Error: 'NameType' is defined but never used.  @typescript-eslint/no-unused-vars
7:3  Error: 'Payload' is defined but never used.  @typescript-eslint/no-unused-vars
8:3  Error: 'ValueType' is defined but never used.  @typescript-eslint/no-unused-vars
77:7  Error: '_' is defined but never used.  @typescript-eslint/no-unused-vars

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
   Linting and checking validity of types  .error: script "build" exited with code 1
```

### System Info

```bash
macOS, bun 1.1.20
```

### Before submitting

- [ ] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by MJomaa** [comment]
Just install "recharts": "2.13.0-alpha.4" and add an override for "react-is". I would also override "next", "react" and "react-dom".

**Comment by vincentzhangz** [comment]
> Just install "recharts": "2.13.0-alpha.4" and add an override for "react-is". I would also override "next", "react" and "react-dom".

I tried to upgrade the recharts to the alpha version, but still the same, I think the _ error is on the charts.tsx one need to change (?)

**Comment by vincentzhangz** [comment]
The error already fixed after the latest canary version. Just because of some linter in the nextjs.

**Comment by MJomaa** [comment]
@vincentzhangz Did you `npm run build` the project?

**Comment by numanjvd82** [comment]
I am still getting this issue
![image](https://github.com/user-attachments/assets/a31a613f-d85f-4acb-9817-ad62b0c144b8)
on more than on file when making a build

**Comment by vincentzhangz** [comment]
on what version are you using for the nextjs and the eslint ?
