### ISSUE TITLE
[feat]: shadcn-ui and nextui combination

### ISSUE THREAD

**Issue by webscriptmaster** [shadcn-ui/ui#4480]
### Feature description

Hi everyone.
I am one of the developers who loves Tailwind CSS.
Recently, I developed a website by using Shadcn-ui and Nextui components.

**https://github.com/shadcn-ui/ui
https://github.com/nextui-org/nextui**

In my opinion, Shadcn-ui is easy to update and easy to use.
NextUI is also beautiful and easy to use.
However, recently, NextUI has been rapidly attracting the attention of developers.

**When using the two libraries, some components do not work properly.
I would like to ask for your help in determining the cause and the correct way to use them.**

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by webscriptmaster** [comment]
It's mainly related the `<NextUIProvider>` and `<ThemeProvider>`.
I found the issue by myself.
Thanks for your attention.

**Comment by mi6paulino** [comment]
![IMG_5820](https://github.com/user-attachments/assets/d98062bd-4afb-4af6-8dd2-9bb65ce70679)
Burntfurniture.weebly.com

**Comment by webscriptmaster** [comment]
Hi @mi6paulino 
What's this?
