### ISSUE TITLE
[feat]: shadcn-ui in angular 

### ISSUE THREAD

**Issue by mdex-geek** [shadcn-ui/ui#4496]
### Feature description

just like you guys have shadcn in react make this in angular

### Affected component/components

all component

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by iAbhinav** [comment]
checkout [Spartan UI](https://www.spartan.ng/), this is a project that is specifically doing the same.

**Comment by imMatheus** [comment]
> checkout [Spartan UI](https://www.spartan.ng/), this is a project that is specifically doing the same.

Damn, pretty cool actually good on them!
