### ISSUE TITLE
Update the docs

### ISSUE THREAD

**Issue by thiagodebugs** [shadcn-ui/ui#4505]
### Describe the bug

# Problem

While following the shadcn/ui documentation to create a new project, I encountered an error when running the command:

`bunx --bun create-next-app@latest my-app --typescript --tailwind --eslint`

Result: `error: Script not found "create-next-app@latest"`

The error seems to be related to the use of the `create-next-app` command, which is not recognized by Bun. According to the official Bun documentation, the correct command is `create next-app`. I believe the shadcn/ui documentation should be fixed to prevent other users from facing the same issue.

# Suggested Solution

Update the documentation to use the correct command as per the [official Bun documentation](https://bun.sh/guides/ecosystem/nextjs):

`bunx --bun create next-app@latest my-app --typescript --tailwind --eslint`

### Affected component/components

All

### How to reproduce

1. Follow the shadcn/ui documentation.
2. Run the provided command to create a new project with Bun.
3. Observe the resulting error.

### System Info

```bash
Windows
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by CODEX108** [comment]
---

Hey @thiagodebugs,

I encountered the same issue with the error: `Script not found "create-next-app@latest"`. However, I managed to resolve it by using the following command in Windows:

```bash
bun x --bun create next-app@latest my-app --typescript --tailwind --eslint
```

For me, the key was to use `bun x` instead of `bunx` when installing all the ShadCN components.

I hope this helps!

---
