### ISSUE TITLE
[bug]: Carousel orientation="vertical" not working.

### ISSUE THREAD

**Issue by Sandeep13-web** [shadcn-ui/ui#4512]
### Describe the bug

When i use the carousel orientation to vertical then it is not working as in docs. Is there anything that i missed? Below is the code i have attached.

```  
<Carousel
        opts={{
          align: "start",
          loop: true,
        }}
        plugins={[
          Autoplay({
            delay: 2000,
          }),
        ]}
        orientation="vertical"
        className="w-full max-w-xs"
      >
        <CarouselContent>
          {Array.from({ length: 5 }).map((_, index) => (
            <CarouselItem key={index} className="pt-1 md:basis-1/2">
              <div className="p-1">
                <Card>
                  <CardContent className="flex justify-center items-center p-6">
                    <span className="text-3xl font-semibold">{index + 1}</span>
                  </CardContent>
                </Card>
              </div>
            </CarouselItem>
          ))}
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
      </Carousel>
      ```
      
      
![image](https://github.com/user-attachments/assets/5c2a3f1b-df34-43d2-8d47-204d4090917d)

### Affected component/components

Carousel

### How to reproduce

.

### System Info

```bash
Google chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by dithom** [comment]
@Sandeep13-web The issue is closed, did you figure out, how to set it up correctly? I can not scroll vertically. All slides snap back into initial position and the controls are disabled.
