### ISSUE TITLE
[bug]: y-axis is showing the sum of two area charts

### ISSUE THREAD

**Issue by jacobhjkim** [shadcn-ui/ui#4533]
### Describe the bug

As you can see from the screenshot below, the y-axis is showing the sum of the two area charts' values. The y-axis domain is `0 ~ 600`, but it should be somewhere around `0 ~ 350`.

<img width="669" alt="Screenshot 2024-08-08 at 4 06 50 PM" src="https://github.com/user-attachments/assets/a916e16b-c0d7-483a-9dae-d57bcaecafd6">

### Affected component/components

Chart

### How to reproduce

Go to current [`Area Chart - Axes`](https://ui.shadcn.com/charts) example, or check out its source code [https://github.com/shadcn-ui/ui/blob/9f156a1b890cc043b8fe01037abb6625bd3f588a/apps/www/registry/default/block/chart-area-axes.tsx#L47](https://github.com/shadcn-ui/ui/blob/9f156a1b890cc043b8fe01037abb6625bd3f588a/apps/www/registry/default/block/chart-area-axes.tsx#L47)

### Codesandbox/StackBlitz link

https://v0.dev/r/9emk04YW83c

### System Info

```bash
I added a v0 link.
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by ralphgerbs** [comment]
Also is it possible to have the y-axis start from a number greater than zero? In your screenshot for example, how do you make it plot from `~100 - 350`?

**Comment by sifact** [comment]
Use different stackId in Area component.
`  <Area dataKey="Testing" type="bump" fill="url(#fillMobile)" stroke="var(--color-mobile)" stackId="a" />
            <Area dataKey="Installs" type="bump" fill="url(#fillDesktop)" stroke="var(--color-desktop)" stackId="b" />`

**Comment by jacobhjkim** [comment]
thanks @sifact, submitted a PR to fix the chart example. https://github.com/shadcn-ui/ui/pull/4541 👍
