### ISSUE TITLE
[feat]: Option to disable keybindings like left/right keys for switching slides

### ISSUE THREAD

**Issue by seleckis** [shadcn-ui/ui#4579]
### Feature description

I'm using form elements in carousel slides and left/right keys are needed to move caret in an input. Unfortunately it is not possible because carousel slides are being switched using these buttons. Would be great to have an option to disable key events or a particular key combination.

### Affected component/components

Carousel

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by ImEins** [comment]
I believe this may be related to accessibility considerations. For your specific use case, you might consider enhancing your components to provide options for handling this scenario. Alternatively, you could comment out the line that is causing the problem.

**Comment by seleckis** [comment]
Yes, I have added `disableKeyNavigation` prop for `carousel` component and changed line:
```
onKeyDownCapture={handleKeyDown}
```
to
```
onKeyDownCapture={disableKeyNavigation ? undefined : handleKeyDown}
```

**Comment by did-studio** [comment]
that worked
