### ISSUE TITLE
I can't click anywhere after using alert dialog.

### ISSUE THREAD

**Issue by wCatly** [shadcn-ui/ui#468]
I wanted to implement alert-dialog into my dropdown menu but after I click to buttons I can't click anymore I had to refresh site.

code:
```ts
"use client"

import { ColumnDef } from "@tanstack/react-table"
import { ArrowUpDown, Eye, EyeOff, MoreHorizontal } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"

import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
    AlertDialogTrigger,
  } from "@/components/ui/alert-dialog"

import { useRouter, useSearchParams } from "next/navigation"
import { useState } from "react"

export type Category = {
  id: string
  name: string
  products: number
  visibility: "public" | "private"
}



export const columns: ColumnDef<Category>[] = [
    
  {
    id: "select",
    header: ({ table }) => (
      <Checkbox
        checked={table.getIsAllPageRowsSelected()}
        onCheckedChange={(value:any) => table.toggleAllPageRowsSelected(!!value)}
        aria-label="Select all"
      />
    ),
    cell: ({ row }) => (
      <Checkbox
        checked={row.getIsSelected()}
        onCheckedChange={(value:any) => row.toggleSelected(!!value)}
        aria-label="Select row"
      />
    ),
    enableSorting: false,
    enableHiding: false,
  },
  {
    accessorKey: "name",
    header: "Kategori",
    cell: ({ row }) => <div>{row.getValue("name")}</div>,
  },
  {
    accessorKey: "products",
    header: "Ürün Sayısı",
    cell: ({ row }) => <div>{row.getValue("products")}</div>,
  },
  {
    accessorKey: "visibility",
    header: "Görünürlük",
    cell: ({ row }) => (
      <div>
        {row.getValue("visibility") === "public" ? 
          <><Eye className="mr-2 inline flex-1 text-sm text-muted-foreground" size={20}/>Herkese açık</> : 
          <><EyeOff className="mr-2 inline flex-1 text-sm text-muted-foreground" size={20}/>Gizli</>
        }
      </div>
    ),
  },
  {
    id: "actions",
    enableHiding: false,
    cell: ({ row }) => {
      const category = row.original
      // eslint-disable-next-line react-hooks/rules-of-hooks
      const router = useRouter()
      const handleDelete = () => {
        // Perform delete action here
        // For example:
        // deleteCategory(category.id)
        // .then(() => router.push('/categories'))
      }
      // eslint-disable-next-line react-hooks/rules-of-hooks
      const [isAlertDialogOpen, setAlertDialogOpen] = useState(false)
      
      return (
        <>
            <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" className="h-8 w-8 p-0">
              <span className="sr-only">Open menu</span>
              <MoreHorizontal className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>Eylemler</DropdownMenuLabel>
            <DropdownMenuSeparator />
            


            <DropdownMenuItem onClick={() => setAlertDialogOpen(true)}>Kategoriyi Sil</DropdownMenuItem>

            <DropdownMenuItem onClick={() => router.push(`/categories/edit/${category.id}`)}>Katogori Görünürlük</DropdownMenuItem>
            
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={() => router.push(`/categories/edit/${category.id}`)}>Kategoriyi Düzenle</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        
        <AlertDialog open={isAlertDialogOpen} onOpenChange={setAlertDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Emin misiniz?</AlertDialogTitle>
            <AlertDialogDescription>
              Bu eylem geri alınamaz. Bu eylem kategoriyi kalıcı olarak silecek.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
          <AlertDialogCancel onClick={() => setAlertDialogOpen(false)}>İptal</AlertDialogCancel>
            <AlertDialogAction>Devam et</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>

        </AlertDialog>
        </>
      )
      
    },
  },


]
```

**Comment by UnknownBigBrain** [comment]
Me too I have the same issue.  
I took the implementation from taxonomy but after i close the alert-dialog all events are disabled exept for text selection :)

**Comment by samjowen** [comment]
Hi @wCatly, did you try this? 

"To activate the Dialog component from within a Context Menu or Dropdown Menu, you must encase the Context Menu or Dropdown Menu component in the Dialog component. For more information, refer to the linked issue [here](https://github.com/radix-ui/primitives/issues/1836)."

From the documentation here: https://ui.shadcn.com/docs/components/dialog

**Comment by bahadirk5** [comment]
Get in the same trouble. I take an example from the taxonomy still not working.

**Comment by UnknownBigBrain** [comment]
Hi @samjowen  thx for the response. 
Popover worked but Menu still have the same issue


Popover: 
`

        <Dialog open={showDeleteAlert} onOpenChange={setShowDeleteAlert}>
            <Popover open={open} onOpenChange={setOpen}>
                <PopoverTrigger className="flex h-8 w-8 items-center justify-center rounded-md border transition-colors hover:bg-muted">
                    <Icons.ellipsis className="h-4 w-4" />
                    <span className="sr-only">Open</span>
                </PopoverTrigger>

                <PopoverContent className="w-[200px] p-0">
                    <Button
                        className="flex cursor-pointer items-center text-destructive focus:text-destructive"
                        onClick={() => setShowDeleteAlert(true)}
                    >
                        Delete
                    </Button>
                </PopoverContent>
            </Popover>
     

            <DialogContent>
                <DialogHeader>
                    <DialogTitle>
                        Are you sure you want to delete this post?
                    </DialogTitle>
                    <DialogDescription>
                        This action cannot be undone.
                    </DialogDescription>
                </DialogHeader>
                <DialogFooter>
                    <DialogTrigger>Cancel</DialogTrigger>
                    <DialogTrigger
                        onClick={async (event) => {
                            event.preventDefault();
                            setIsDeleteLoading(true);

                            // const deleted = await deletePost(post.id)

                            // if (deleted) {
                            setIsDeleteLoading(false);
                            setShowDeleteAlert(false);
                            router.refresh();
                            // }
                        }}
                        className="bg-red-600 focus:ring-red-600"
                    >
                        {isDeleteLoading ? (
                            <Icons.spinner className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                            <Icons.trash className="mr-2 h-4 w-4" />
                        )}
                        <span>Delete</span>
                    </DialogTrigger>
                </DialogFooter>
            </DialogContent>
        </Dialog>
`

Menu: 
`





     <Dialog open={showDeleteAlert} onOpenChange={setShowDeleteAlert}>
            <DropdownMenu>
                <DropdownMenuTrigger>
                    <Icons.ellipsis className="h-4 w-4" />
                    <span className="sr-only">Open</span>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                    <DropdownMenuItem>
                        <Link
                            href={`/editor/${product.id}`}
                            className="flex w-full"
                        >
                            Edit
                        </Link>
                    </DropdownMenuItem>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem
                        className="flex cursor-pointer items-center text-destructive focus:text-destructive"
                        onSelect={() => setShowDeleteAlert(true)}
                    >
                        Delete
                    </DropdownMenuItem>
                </DropdownMenuContent>
            </DropdownMenu>

            <DialogContent>
                <DialogHeader>
                    <DialogTitle>
                        Are you sure you want to delete this post?
                    </DialogTitle>
                    <DialogDescription>
                        This action cannot be undone.
                    </DialogDescription>
                </DialogHeader>
                <DialogFooter>
                    <DialogTrigger>Cancel</DialogTrigger>
                    <DialogTrigger
                        onClick={async (event) => {
                            event.preventDefault();
                            setIsDeleteLoading(true);

                            // const deleted = await deletePost(post.id)

                            // if (deleted) {
                            setIsDeleteLoading(false);
                            setShowDeleteAlert(false);
                            router.refresh();
                            // }
                        }}
                        className="bg-red-600 focus:ring-red-600"
                    >
                        {isDeleteLoading ? (
                            <Icons.spinner className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                            <Icons.trash className="mr-2 h-4 w-4" />
                        )}
                        <span>Delete</span>
                    </DialogTrigger>
                </DialogFooter>
            </DialogContent>
        </Dialog>
`

**Comment by Angulo66** [comment]
```
'use client'
import { DropdownMenuTrigger } from '@radix-ui/react-dropdown-menu'
import { SlidersHorizontal } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuItem,
} from '@/components/ui/dropdown-menu'
import { Dialog, DialogTrigger } from '@/components/ui/dialog'
import { AddGroupDialogContent } from '../../forms/components/add-group-dialog-content'
import { Sheet, SheetTrigger } from '@/components/ui/sheet'
import { AddItemSheetContent } from '../../forms/components/add-item-sheet-content'
import { EstimateType } from '@prisma/client'
import React from 'react'

export function AddItemsDropdown() {
  const [openSheet, setOpenSheet] = React.useState<boolean>(false)
  const [itemType, setItemType] = React.useState<EstimateType>('MATERIAL')
  return (
    <div>
      <Dialog>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant='outline' size='sm' className='ml-auto hidden h-8 lg:flex'>
              <SlidersHorizontal className='mr-2 h-4 w-4' />
              Add Items
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align='end' className='w-[150px]'>
            <DropdownMenuLabel>Add Items</DropdownMenuLabel>
            <DialogTrigger className='w-full'>
              <DropdownMenuItem>{'Add Group'}</DropdownMenuItem>
            </DialogTrigger>
            <DropdownMenuItem
              onSelect={() => {
                setOpenSheet(true)
                document.body.style.pointerEvents = ""
              }}
            >
              {'Add Material'}
            </DropdownMenuItem>
            <DropdownMenuSeparator />
          </DropdownMenuContent>
        </DropdownMenu>
        <AddGroupDialogContent />
      </Dialog>
      <Sheet open={openSheet} onOpenChange={setOpenSheet}>
        <SheetTrigger>
          <Button>{'Open'}</Button>
        </SheetTrigger>
        <AddItemSheetContent type={itemType} />
      </Sheet>
    </div>
  )
}

```
In my case it appears that when i open my sheet within a DropdownMenuItem and closing the sheet afterwards the pointer event on the body remains none my fix was using `document.body.style.pointerEvents = ""`

**Comment by ataki** [comment]
To add to prev answer: the consistent way is to modify the `DialogPrimitive.Close` component. You have to do the setTimeout. It's not great, hoping we clean this up in a separate fix but I'm not exactly sure what the better fix is here.

```
<DialogPrimitive.Close
        className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground"
        onClick={() => {
          // yes, you have to set a timeout
          setTimeout(() => (document.body.style.pointerEvents = ""), 500);
        }}
      >
        <X className="h-4 w-4" />
        <span className="sr-only">Close</span>
      </DialogPrimitive.Close>
```

**Comment by holy-dev** [comment]
Any update on this?

**Comment by prawpash** [comment]
`        <DropdownMenu>
          <DropdownMenuTrigger asChild={true}>
            <Button variant="ghost" className="h-8 w-8 p-0">
              <span className="sr-only">Open Menu</span>
              <span className="h-4 w-4">
                <MoreHorizontal />
              </span> </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>Actions</DropdownMenuLabel>
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <DropdownMenuItem
                  className="bg-green-500 hover:bg-green-700 hover:text-white"
                  onSelect={(e) => e.preventDefault()}
                >
                  <Eye className="w-4 h-4 mr-2" /> Show Detail
                </DropdownMenuItem>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>
                    Are you sure?
                  </AlertDialogTitle>
                  <AlertDialogDescription>
                    Hahahahaha
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Cancel</AlertDialogCancel>
                  <AlertDialogAction>Continue</AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
            <DropdownMenuItem className="bg-yellow-500 hover:bg-yellow-700 hover:text-white">
              <Pencil className="w-4 h-4 mr-2" /> Edit
            </DropdownMenuItem>
            <DropdownMenuItem className="bg-red-500 text-white hover:bg-red-700">
              <Trash className="w-4 h-4 mr-2" /> Delete
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu >
`
if you still have this problem, you can try using this code, i manage to open alert dialog inside the dropdown menu

**Comment by makelsevilla** [comment]
This fix worked.

https://github.com/radix-ui/primitives/issues/1836#issuecomment-1674338372

**Comment by jad-eljerdy** [comment]
If it helps anyone, ran into the same problem and inspired by the comments above I solved it using this:

``` jsx      
<AlertDialog
    open={deleteDialogOpen}
    onOpenChange={() => { setTimeout(() => (document.body.style.pointerEvents = ""), 100) }}
>
```

Seems to be working well so for now.

**Comment by braian-bernatto** [comment]
In my case l've got that error because on my dialog component I've imported by error this line of code `import { DialogDescription } from '@radix-ui/react-dialog'` instead of `import { DialogDescription } from './ui/dialog'`. Once I've changed it back it works as it should.

**Comment by shadcn** [comment]
Thanks for the updates @braian-bernatto

**Comment by Kiranism** [comment]
Setting <DropdownMenu modal={false}> solved the problem bcs i had two modal in place.

> If it helps anyone, ran into the same problem and inspired by the comments above I solved it using this:
> 
> ```js
> <AlertDialog
>     open={deleteDialogOpen}
>     onOpenChange={() => { setTimeout(() => (document.body.style.pointerEvents = ""), 100) }}
> >
> ```
> 
> Seems to be working well so for now.

**Comment by bakikucukcakiroglu** [comment]
Thanks @Kiranism ! I was using a Dropdown with a Button trigger. DropdownItems was opening a modal. After closing that modal anything was not clickable anymore. Setting `modal={false}` solved the issue.

**Comment by dalalRohit** [comment]
here's  what i found to solve:

1. update `@radix-ui/react-dropdown-menu` to `2.1.1`
2. set `modal={false}` on `DropdownMenu`

hope it helps.

**Comment by nataliamanosso** [comment]
Thanks @dalalRohit! Solved the modal and dropdown menu problem, but I still have a problem, inside my modal I have a component that uses Popover (component for date selection), when I solve the Modal problem, I can't select any value in the Popover. Does anyone have any suggestions on how to resolve it? I thought of some ways but they are not very suitable.

`export function InputDate({ label, placeholder, name, value, onChange }: InputDateProps) {

  const [date, setDate] = React.useState<Date>()

  const handleDateSelect = (date: any) => {
    setDate(date)
    onChange({ target: { name, value: date } })
  }

  return (
    <Popover>
      <PopoverTrigger className='text-left'>
        <p className='mb-1 text-sm font-medium'>{label}</p>
        <Button className={cn(!date && 'text-muted-foreground' )} variant='input' size='input' >
          {date ? format(date, 'dd/MM/yyyy') : <span>{placeholder}</span>}
          <CalendarIcon className='ml-2 h-4 w-4' />
        </Button>
      </PopoverTrigger>
      <PopoverContent className='w-auto p-0'>
        <Calendar mode='single' selected={date} onSelect={handleDateSelect} initialFocus />
      </PopoverContent>
    </Popover>
  )
}`

**Comment by nh-tu-z** [comment]
> here's what i found to solve:
> 
> 1. update `@radix-ui/react-dropdown-menu` to `2.1.1`
> 2. set `modal={false}` on `DropdownMenu`
> 
> hope it helps.

only second option worked on me, thanks @dalalRohit

**Comment by iamrishan** [comment]
if you are using any popover/alertdialog/modal inside dropdown-menu set the modal=false on DropdownMenu fixes this issue

<DropdownMenu modal={false}>

**Comment by Minozzzi** [comment]
Here just when updating from 2.0.6 to 2.1.1 it worked

Thanks!!

**Comment by viteesourav** [comment]
Huge shout-out to whoever posted this query! I've been struggling with the exact same issue for days, and somehow I stumbled upon this thread. Finally, the solution worked perfectly for me !

This  solution Worked for me ...
`<DropdownMenu modal={false}>`

Thank you ! Really...

**Comment by Finn-ferd** [comment]
![image](https://github.com/user-attachments/assets/1724e83c-29dc-4f4e-8470-641b96a1d704)
My case is a bit different. I use an 'AlertDialog' at the same level as the dialog, but it will display a warning when the user accidentally exits the form. When 'leave' is selected, the dialog will close, but buttons and other elements outside of it are no longer interactable.

**Comment by aziz-codes** [comment]
I have the same issue, after closing the AlertDialogue  , The UI freezes and I am not able to click any where, until I refresh the page?
Any one knows how to fix it

**Comment by aziz-codes** [comment]
It's actually adding 'pointer event' = "none" to the body, when the alert is closed, so we have to set the pointer event to "", to make it work.

**Comment by tonsisouvanh** [comment]
> Huge shout-out to whoever posted this query! I've been struggling with the exact same issue for days, and somehow I stumbled upon this thread. Finally, the solution worked perfectly for me !
> 
> This solution Worked for me ... `<DropdownMenu modal={false}>`
> 
> Thank you ! Really...

You save a lot of my times, Thanks a lot

**Comment by 0xSeb** [comment]
> modal={false}

You saved me also, thanks a lot sir.

**Comment by arxkdev** [comment]
Tried ``modal={false}`` on a ContextMenu and did not work sadly. Using latest version from radix.

**Comment by SanditZZ** [comment]
> Setting `<DropdownMenu modal={false}>` solved the problem bcs i had two modal in place.
> 
> > If it helps anyone, ran into the same problem and inspired by the comments above I solved it using this:
> > ```js
> > <AlertDialog
> >     open={deleteDialogOpen}
> >     onOpenChange={() => { setTimeout(() => (document.body.style.pointerEvents = ""), 100) }}
> > >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems to be working well so for now.

This worked for me. Thank you!

**Comment by highflyer12** [comment]
Setting <DropdownMenu modal={false}> worked for me

**Comment by baxsm** [comment]
> My case is a bit different. I use an 'AlertDialog' at the same level as the dialog, but it will display a warning when the user accidentally exits the form. When 'leave' is selected, the dialog will close, but buttons and other elements outside of it are no longer interactable. This is because the body still has style="pointer-events: none;" instead of being removed as it normally should. ![image](https://github.com/user-attachments/assets/ada45e56-49f5-4467-a280-fc562fdd44a6) I had to use a Dialog instead of an AlertDialog to fix the current issue.

Here's a workaround for Dialog and AlertDialog in the same level.

```javascript
// Example: Creating api key in one dialog and showing a copy api key button in another dialog
const [isCreateOpen, setIsCreateOpen] = useState(false)
const [isCopyOpen, setIsCopyOpen] = useState(false)

const onSubmit = (values: ValuesType) => {
    ...
   setIsCopyOpen(true)
   setIsCreateOpen(false)
};

return (
    <>
      {!isCopyOpen && (
        <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
          <DialogTrigger>
            Create API Key
          </DialogTrigger>
          <DialogContent>
           <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)}>
                  ...
                 <Button>Create</Button>
              </form>
           </Form>
          </DialogContent>
        </Dialog>
      )}

      <AlertDialog open={isCopyOpen} onOpenChange={setIsCopyOpen}>
        <AlertDialogContent>
            ...
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
```

**Comment by onyedikachi23** [comment]
> This trick worked.
> 
> [radix-ui/primitives#1836 (comment)](https://github.com/radix-ui/primitives/issues/1836#issuecomment-1674338372)
> 
> you may also want to disable the modal of DropdownMenu by setting the value to false.

For anyone looking for the easiest approach, use this method. 

Saved me hours of debugging.

**Comment by Jaime5Alvarez** [comment]
> Setting DropdownMenu modal={false} worked for me

This worked for me :)

**Comment by techcoder2007** [comment]
![Image](https://github.com/user-attachments/assets/d1f4e720-6a5c-49d9-9743-19e0f6325d70)

this steps solve my issues

**Comment by arausmatias** [comment]
Here's my solution. 

1. Wrap the DropdownMenu with AlertDialog
2. Wrap the DropdownMenuItem with AlertDialogTrigger
3. Add the class name `w-full` to AlertDialogTrigger, and remove any prop `asChild`

The code is here:
```
<AlertDialog>
  <DropdownMenu>
    <DropdownMenuTrigger asChild>
      <Button variant="ghost" className="h-8 w-8 p-0">
        <span className="sr-only">Open menu</span>
        <MoreHorizontal className="h-4 w-4" />
      </Button>
    </DropdownMenuTrigger>
    <DropdownMenuContent align="end">
      <DropdownMenuLabel>Actions</DropdownMenuLabel>
      <DropdownMenuItem>Publish</DropdownMenuItem>
      <DropdownMenuItem>Unpublish</DropdownMenuItem>
      <AlertDialogTrigger className="w-full">
        <DropdownMenuItem>Delete</DropdownMenuItem>
      </AlertDialogTrigger>
    </DropdownMenuContent>
  </DropdownMenu>
  <AlertDialogContent>
    <AlertDialogHeader>
      <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
      <AlertDialogDescription>
        This action cannot be undone. This will permanently delete the item.
      </AlertDialogDescription>
    </AlertDialogHeader>
    <AlertDialogFooter>
      <AlertDialogCancel>Cancel</AlertDialogCancel>
      <AlertDialogAction>Continue</AlertDialogAction>
    </AlertDialogFooter>
  </AlertDialogContent>
</AlertDialog>
```

**Comment by iskanderovv** [comment]
> Setting `<DropdownMenu modal={false}>` solved the problem bcs i had two modal in place.
> 
> > If it helps anyone, ran into the same problem and inspired by the comments above I solved it using this:
> > <AlertDialog
> >     open={deleteDialogOpen}
> >     onOpenChange={() => { setTimeout(() => (document.body.style.pointerEvents = ""), 100) }}
> > >
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems to be working well so for now.

you are life saver man

**Comment by ms007** [comment]
const [isDropdownOpen, setIsDropdownOpen] = useState(false)
const [isAlertDialogOpen, setIsAlertDialogOpen] = useState(false)  

useEffect(() => {
    const observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (
          mutation.type === "attributes" &&
          mutation.attributeName === "style" &&
          **document.body.style.pointerEvents === "none"** &&
          !isAlertDialogOpen
        ) {
          document.body.style.pointerEvents = ""
        }
      })
    })

    observer.observe(document.body, {
      attributes: true,
      attributeFilter: ["style"],
    })

    return () => observer.disconnect()
  }, [isAlertDialogOpen, isDropdownOpen])

return (
    <AlertDialog open={isAlertDialogOpen} onOpenChange={setIsAlertDialogOpen}>
      <DropdownMenu open={isDropdownOpen} onOpenChange={setIsDropdownOpen}>
        ........
      </DropdownMenu>
    </AlertDialog>
  )

**Comment by dungnguyen2534** [comment]
`<DropdownMenu modal={false}>` works for me.

**Comment by maxktz** [comment]
> here's what i found to solve:
> 
> 1. update `@radix-ui/react-dropdown-menu` to `2.1.1`
> 2. set `modal={false}` on `DropdownMenu`
> 
> hope it helps.

THANKS!

**Comment by BrianLe188** [comment]
add pointerEvents = unset for body tag with !important in css file

**Comment by sourav0809** [comment]
The fix is this 

<img width="1207" height="550" alt="Image" src="https://github.com/user-attachments/assets/4ba833d8-7c45-4f5d-ad21-6a90afd96bae" />

**Comment by Novianto778** [comment]
It happen to me today when using dialog component, and there is two solution for the fix.
1. Make the dropdown controlled using state, it happen because the dialog portal and dropdown menu is conflict so ensures the dropdown menu properly closes before the dialog opens, to preventing the conflict that was causing the UI blocking issue.
2. Set the dialog props modal={false}, but this is cause the behaviour of dialog change(user can interact outside the dialog)
