### ISSUE TITLE
[bug]: Having global.scss instead of global.css, doesn't init shadncn

### ISSUE THREAD

**Issue by Wiper-R** [shadcn-ui/ui#4689]
### Describe the bug

While running `pnpm dlx shadncn@latest init` I was getting a error saying no tailwind configuration found. Because the library was looking for global.css. But I have valid configuration using global.scss.

Expected behavior was library should detect scss and sass files too.

### Affected component/components

Not Applicable

### How to reproduce

-

### Codesandbox/StackBlitz link

-

### System Info

```bash
OS: Arch Linux 
Browser: Not applicable
Library: NextJs Latest (App Router)
CSS processor: sass
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by aghwotu** [comment]
I have the same issue but with React + Vite using SCSS and TypeScript.

**Comment by lucafaggianelli** [comment]
I have the same problem but I'm not using SCSS, I'm using Vite though and I run `shadcn init` on a clean Vite project just after following the Installation guide for Vite: https://ui.shadcn.com/docs/installation/vite

**Comment by evmoh** [comment]
Same problem. If i create "global.css" everything works. But with scss it not working.

![image](https://github.com/user-attachments/assets/e5347ac5-c704-4bdc-a6bf-f9aa5e4eb8c3)
