### ISSUE TITLE
[bug]: Received malformed response from registry for ""

### ISSUE THREAD

**Issue by OrgDrReach** [shadcn-ui/ui#4699]
### Describe the bug

sudeepta@IdeaPad-Flex-5-14ALC05:maa-tarini-electricals$ npx shadcn@latest init
✔ Preflight checks.
✔ Verifying framework. Found Next.js.
✔ Validating Tailwind CSS.
✔ Validating import alias.
✔ Which style would you like to use? › Default
✔ Which color would you like to use as the base color? › Neutral
✔ Would you like to use CSS variables for theming? … no / yes
✔ Writing components.json.
✔ Checking registry.
✔ Updating tailwind.config.ts
✔ Updating app/globals.css
⠴ Installing dependencies.
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: yarn add tailwindcss-animate class-variance-authority lucide-react  clsx tailwind-merge
error Received malformed response from registry for "". The registry may be down.
yarn add v1.22.22
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### Affected component/components

None

### How to reproduce

type `npx shadcn@latest init` you will get to see thee bug

### System Info

```bash
# System Details Report
---

## Report details
- **Date generated:**                              2024-09-01 22:20:06

## Hardware Information:
- **Hardware Model:**                              Lenovo IdeaPad Flex 5 14ALC05
- **Memory:**                                      16.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 5700U with Radeon™ Graphics × 16
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            GJCN34WW
- **OS Name:**                                     Ubuntu 24.04.1 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.0-41-generic
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by trondi** [comment]
in my case, i removed yarn.lock and try again "npx shadcn@latest init"

**Comment by sudsarkar13** [comment]
@trondi thanks it works

**Comment by OrgDrReach** [comment]
@trondi Thanks it works

**Comment by eioluseyi** [comment]
This didn't work when I was using `Default`

I had to switch to `New York` for the installation to work, after which I changed the value in the `components.json` file back to `Default`

**Comment by alnandr** [comment]
Same as @eioluseyi, had to use `New York` instead of `Default`. On Windows 10 using PowerShell and using `npm shadcn@latest init`.
