### ISSUE TITLE
[bug]: New CLI astro installation instructions lead to No Tailwind error

### ISSUE THREAD

**Issue by coobeeyon** [shadcn-ui/ui#4701]
### Describe the bug

Followed exact instructions for astro new project creation.  When I got to `npx shadcn@latest init` I received errors about not finding tailwind.

### Affected component/components

CLI

### How to reproduce

Follow astro installation instructions at https://ui.shadcn.com/docs/installation/astro

### Logs

```bash
``✔ Preflight checks.
✔ Verifying framework. Found Astro.
✖ Validating Tailwind CSS.
✖ Validating import alias.

No Tailwind CSS configuration found at /home/username/HotWebsite.
It is likely you do not have Tailwind CSS installed or have an invalid configuration.
Install Tailwind CSS then try again.
Visit https://tailwindcss.com/docs/guides/astro to get started.

No import alias found in your tsconfig.json file.
Visit https://ui.shadcn.com/docs/installation/astro to learn how to set an import alias``
```

### System Info

```bash
Ubuntu 22.04 LTS
node v18.17.1
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by aghwotu** [comment]
I have the same issue with React + Vite using SCSS and TypeScript. 
This is the error I am getting:

```bash
✔ Preflight checks.
✔ Verifying framework. Found Vite.
✖ Validating Tailwind CSS.
✔ Validating import alias.

No Tailwind CSS configuration found at /project-folder-path.
It is likely you do not have Tailwind CSS installed or have an invalid configuration.
Install Tailwind CSS then try again.
```

**Comment by OpoJack** [comment]
I was able to get around this by adding the standard tailwind config in global styles.
Tailwind's docs don't require this for Astro but the cli seems to be looking for @tailwind base in `packages/shadcn/src/utils/get-project-info.ts` -> getTailwindConfigFile()

```ts
    if (contents.includes("@tailwind base")) {
      return file
    }
```

In your global styles:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by shadcn** [comment]
Looks like we need to update the astro docs for `applyBaseStyles`. Let me take a look.

**Comment by shadcn** [comment]
https://github.com/shadcn-ui/ui/pull/4723

**Comment by shadcn** [comment]
I fixed this yesterday. Added new docs. Let me know if this works.

**Comment by romashmalcev** [comment]
I still have this problem.

**Comment by romashmalcev** [comment]
I use vite configurations

**Comment by roblesbraun** [comment]
I have the same issue with vanilla react and vite.  Shadcn is not recognizing tailwindcss installation

**Comment by Chameleonl** [comment]
> I fixed this yesterday. Added new docs. Let me know if this works.

Hi, still having this issue with Vite React + TS, following all instructions at https://ui.shadcn.com/docs/installation/vite, the workaround with styles.css described in this thread helped.

**Comment by Dylbobin** [comment]
Hey Everyone, 

Here is the Fix....At least using Vite + JS

Step01) Validate that you followed the instructions here: [https://ui.shadcn.com/docs/installation/vite]

** Note ** you only need to create a jsconfig.json file and paste:

{
    "compilerOptions": {
      // ...
      "baseUrl": ".",
      "paths": {
        "@/*": [
          "./src/*"
        ]
      }
      // ...
    }
  }

Step02) Update your tailwind.config.js:

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

Step03) go to index.css under src and paste this at the top of the file:

*** Note *** Not sure if this is necessary or not but worked for me

@tailwind base;
@tailwind components;
@tailwind utilities;

**Comment by imrishit98** [comment]
I have same issue for Next.js

**Comment by roblesbraun** [comment]
I am still unable to create a new project with Vite. Any updates?

**Comment by novanda1** [comment]
> I have same issue for Next.js

In my case, adding index.css at the root of project solve the issue.

```css
https://github.com/tailwind base;
https://github.com/tailwind components;
https://github.com/tailwind utilities;
```

**Comment by SwimmingPolar** [comment]
I had the same issue. Followed exact instructions on Astro docs. The problem was that for some reason, cli didn't created `components.json` file during scaffolding. So, no `components.json` file at project root. Here's basic Astro project setup that has `tailwind`, `react` and `shadcn`.

<img width="1620" alt="image" src="https://github.com/user-attachments/assets/20d5c32e-c2c2-4a51-a1b9-ab6b9753612b">

**Comment by onattech** [comment]
For React + Vite, here's the fix. https://github.com/shadcn-ui/ui/issues/4677#issuecomment-2323108511

**Comment by prashantbhudwal** [comment]
Followed the astro guide and got this error.

Progress: resolved 170, reused 170, downloaded 0, added 170, done
✔ Preflight checks.
✔ Verifying framework. Found Astro.
✔ Validating Tailwind CSS.
✖ Validating import alias.

No import alias found in your tsconfig.json file.
Visit https://ui.shadcn.com/docs/installation/astro to learn how to set an import alias.



`{
  "extends": "astro/tsconfigs/strict",
  "include": [".astro/types.d.ts", "**/*"],
  "exclude": ["dist"],
  "baseUrl": ".",
  "paths": {
    "@/*": ["./src/*"]
  },
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react"
  }
}
`
