### ISSUE TITLE
[bug]: Command failed with exit code 1 when running shadcn init

### ISSUE THREAD

**Issue by niassuh1** [shadcn-ui/ui#4722]
### Describe the bug

When running `npx shadcn@latest init`, and after answering all the questions, it goes through installing all the dependencies, and throws an error before finishing like so:
```
Writing components.json.
✔ Checking registry.
✔ Updating tailwind.config.ts
✔ Updating app\globals.css
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: yarn add tailwindcss-animate class-variance-authority lucide-react  clsx tailwind-merge
error Received malformed response from registry for "". The registry may be down.
yarn add v1.22.22
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

However, when I try running `yarn add tailwindcss-animate class-variance-authority lucide-react  clsx tailwind-merge` by myself, it works just fine.

### Affected component/components

None

### How to reproduce

1. Creating a new NextJS app
2. Default answer for all questions
3. Running `npx shadcn@latest init` command
4. Answers:
 - Which style would you like to use? » **Default**
 - Which color would you like to use as the base color? » **Gray**
 -  Would you like to use CSS variables for theming?  **yes**
6. Error occurs after the `installing dependencies` step in the cli

### Codesandbox/StackBlitz link

Not needed

### Logs

```bash
Writing components.json.
✔ Checking registry.
✔ Updating tailwind.config.ts
✔ Updating app\globals.css
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: yarn add tailwindcss-animate class-variance-authority lucide-react  clsx tailwind-merge
error Received malformed response from registry for "". The registry may be down.
yarn add v1.22.22
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### System Info

```bash
Windows 11, Node v18.19.1, Yarn v1.22.22
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by niassuh1** [comment]
Oddly enough... When I answered the questions differently as follows:
```
√ Which style would you like to use? » New York
√ Which color would you like to use as the base color? » Neutral
√ Would you like to use CSS variables for theming? ... yes
✔ Writing components.json.
✔ Checking registry.
✔ Updating tailwind.config.ts
✔ Updating app\globals.css
✔ Installing dependencies.
✔ Created 1 file:
  - lib\utils.ts

Success! Project initialization completed.
You may now add components.
```

It worked just fine

**Comment by adrianhelvikspond** [comment]
This command reproduces the issue:
```bash
yarn add tailwindcss-animate class-variance-authority lucide-react "" clsx tailwind-merge
```

Empty strings need to be removed from the command parameters.

**Comment by adrianhelvikspond** [comment]
Verified. This is the out put I get:
```
[
  'tailwindcss-animate',
  'class-variance-authority',
  'lucide-react',
  '',
  'clsx',
  'tailwind-merge'
]
```

after adding this console.log to the command.

```
function He(e,t,r){if(e=Array.from(new Set(e)),!e?.length)return;console.log(e);r={silent:!1,...r};let i=w("Installing dependencies.",{silent:r.silent})?.start(),n=await J(t.resolvedPaths.cwd);await nr(n,[n==="npm"?"install":"add",...e],{cwd:t.resolvedPaths.cwd}),i?.succeed()}
```

**Comment by adrianhelvikspond** [comment]
https://github.com/shadcn-ui/ui/pull/4724

**Comment by baken667** [comment]
Windows 11, node v20.17.0. Git Bash

$ npx shadcn@latest init
npm error code ENOENT
npm error syscall lstat
npm error path C:\Users\baken\AppData\Roaming\npm
npm error errno -4058
npm error enoent ENOENT: no such file or directory, lstat 'C:\Users\baken\AppData\Roaming\npm'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: C:\Users\baken\AppData\Local\npm-cache\_logs\2024-09-03T16_13_16_318Z-debug-0.log

[2024-09-03T16_13_16_318Z-debug-0.log](https://github.com/user-attachments/files/16851734/2024-09-03T16_13_16_318Z-debug-0.log)
log file

**Comment by niassuh1** [comment]
Thank you all for your efforts!
