### ISSUE TITLE
[bug]: Calendar Component is not displaying properly

### ISSUE THREAD

**Issue by whatisagi** [shadcn-ui/ui#4735]
### Describe the bug

The `Calendar` component relies on react-day-picker@8.7.1 and date-fns@2.30.0. However, manual installation instruction doesn't specify these versions; the latest versions are therefore installed, and the Calendar component stops displaying correctly. 

### Affected component/components

Calendar

### How to reproduce

Just try to follow the steps to install and use the `Calendar` component on the website

### System Info

```bash
Mac, Chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by whatisagi** [comment]
Already reported

**Comment by Walidnurudin** [comment]
change react-day-picker version to 8.9.1, it's work on me
