### ISSUE TITLE
[bug]: Component Design is Inconsistent

### ISSUE THREAD

**Issue by rdrigos** [shadcn-ui/ui#4804]
### Describe the bug

I started a project with Next.js (14.2.8), ShadcnUI (latest version), and TailwindCSS (3.4.1), and I'm experiencing inconsistencies in the project design. When I used it on my home computer, some components displayed almost correctly, but the Dialog appeared transparent in certain areas, as shown in the image below:
![image](https://github.com/user-attachments/assets/9eb1015b-97ad-4f31-aa83-a958b1c17f45)

On another computer, the Dialog was also transparent, and the colors were inverted:
![image](https://github.com/user-attachments/assets/dbfd0068-6e10-4bca-a3de-3ae9f1237e51)
![image](https://github.com/user-attachments/assets/85449597-74e3-412e-b11a-22ba82ec5312)

Can someone help me?
Code: https://github.com/rdrigos/entity-ui
Published project: https://entity-ui.vercel.app/

### Affected component/components

All

### How to reproduce

I left the source code and example images. I just installed and ran ```npm run dev```

### System Info

```bash
W11 PRO
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by jsdev-robin** [comment]
modifie you global css file and replace this 

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
} 

into 

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

**Comment by rdrigos** [comment]
It worked! Thank you very much!

**Comment by jsdev-robin** [comment]
This worked according to the previous version. However, the new version has many bugs. There are also issues with the Tailwind config file.

**Comment by rdrigos** [comment]
> Isso funcionou bem na versão anterior, mas a nova versão introduziu muitos bugs. Também há problemas com o arquivo de configuração do Tailwind, e os gráficos não são mais funcionais na nova versão.

I hope they fix this soon... Because trying has already made me very stressed, and I decided to ask the community for help, because there must be more people with the same problem! Thank you very much for your help.

**Comment by rdrigos** [comment]
@jsdev-robin Can you tell me how to revert to the previous version of shadcnui? Apparently it was a mistake to start the project with the latest version.

**Comment by jsdev-robin** [comment]
> @jsdev-robin  Can you tell me how to revert to the previous version of shadcnui? Apparently it was a mistake to start the project with the latest version.

You can select version here https://www.npmjs.com/package/shadcn-ui/v/0.9.0?activeTab=versions
