### ISSUE TITLE
[bug]: Command Input Custom TailwindCSS Not Working

### ISSUE THREAD

**Issue by DevJobalia** [shadcn-ui/ui#4833]
### Describe the bug

Can't apply custom TailwindCSS 

### Affected component/components

Command Input

### How to reproduce

1. Call CommandInput component
2. 
              <CommandInput
                placeholder="Search country..."
                className="border-yellow-200"
              />

### Codesandbox/StackBlitz link

https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/command.tsx

### System Info

```bash
WINDOWS 11
CHROME BROWSER

Not applicable for this issue.
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by shadcn** [comment]
See https://github.com/shadcn-ui/ui/pull/4834#issuecomment-2351458441
