### ISSUE TITLE
[bug]: Type error found in command.tsx at CommandDialogProps

### ISSUE THREAD

**Issue by Prathamesh-chougale-17** [shadcn-ui/ui#4909]
### Describe the bug

The error suggests

An interface declaring no members is equivalent to its supertype.eslint[@typescript-eslint/no-empty-object-type](https://typescript-eslint.io/rules/no-empty-object-type)

![Screenshot 2024-09-20 101738](https://github.com/user-attachments/assets/d40c0f81-b005-45de-ac6a-db76c67843f6)

at interface CommandDialogProps extends DialogProps {} in new-york style

### How to reproduce

It has came after installing the command from cli

### System Info

```bash
HP windows
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by anubhavadarsh** [comment]
I don't think this is bug, Eslint tells you that you are creating an interface `CommandDialogProps` derived from another interface `DialogProps` and since you are not adding additional members to this `CommandDialogProps` is same as it's super type `DialogProps`.

**Comment by Prathamesh-chougale-17** [comment]
Ohh i see. Thank for letting me know that. Had I new insite today. Though it was a bug
