### ISSUE TITLE
[bug]: foreground and background don't change when toggle dark mode

### ISSUE THREAD

**Issue by sapenlei** [shadcn-ui/ui#4923]
### Describe the bug

when I toggle dark mode,  foreground and background don't change .

![CleanShot 2024-09-21 at 08 39 00@2x](https://github.com/user-attachments/assets/0c8a5f4b-23df-4d3d-afc4-aa2ade1c8771)

### Affected component/components

none

### How to reproduce

1. init nextjs project
2. init shadcn
3. set up dark mode
4. click on the mode toggle button
5. click the dark

### Codesandbox/StackBlitz link

https://codesandbox.io/p/github/sapenlei/global-style-demo/main

### System Info

```bash
Darwin 192.168.2.19 23.6.0 Darwin Kernel Version 23.6.0
root:xnu-10063.141.2~1/RELEASE_ARM64_T6020 arm64
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by jeremyarrabe** [comment]
Did you manage to find a solution? Im having the same problem.

**Comment by sapenlei** [comment]
> Did you manage to find a solution? Im having the same problem.

https://github.com/shadcn-ui/ui/pull/4922
wait to merge
