### ISSUE TITLE
[bug]: Large empty space in "Radial Chart - Stacked"

### ISSUE THREAD

**Issue by JoakimThorne** [shadcn-ui/ui#4934]
### Describe the bug

I've added the component "Radial Chart - Stacked" according to the examples at https://ui.shadcn.com/charts.
But the chart has a lot (~50%) of dead space below the graph, making it hard to use in dashboard where I want to stack multiple smaller charts. 

### Affected component/components

charts

### How to reproduce

1. Add charts to repo
2. Add code for Radial Chart - Stacked from the examples: https://ui.shadcn.com/charts

### System Info

```bash
All
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by JoakimThorne** [comment]
```
      <ChartContainer
          config={chartConfig}
          className="m-auto w-full max-w-[200px]"
        >
          <RadialBarChart
            cy={"80%"}
            data={chartData}
            endAngle={180}
            innerRadius={80}
            outerRadius={130}
          >
```

Not a bug, can be solved with code above

**Comment by johnpwilkinson** [comment]
> ```
>       <ChartContainer
>           config={chartConfig}
>           className="m-auto w-full max-w-[200px]"
>         >
>           <RadialBarChart
>             cy={"80%"}
>             data={chartData}
>             endAngle={180}
>             innerRadius={80}
>             outerRadius={130}
>           >
> ```
> 
> Not a bug, can be solved with code above

You are a SAINT! Heaven forbid they put this in the docs. jfc

**Comment by johnpwilkinson** [comment]
> ```
>       <ChartContainer
>           config={chartConfig}
>           className="m-auto w-full max-w-[200px]"
>         >
>           <RadialBarChart
>             cy={"80%"}
>             data={chartData}
>             endAngle={180}
>             innerRadius={80}
>             outerRadius={130}
>           >
> ```
> 
> Not a bug, can be solved with code above

How does one maintain responsiveness when setting a max-w
