### ISSUE TITLE
[bug]: CLI not working with Remix

### ISSUE THREAD

**Issue by alanwallaceross** [shadcn-ui/ui#4967]
### Describe the bug

I created a fresh Remix project using the blues stack, and then when I tried to use the CLI I'm getting this error:
![image](https://github.com/user-attachments/assets/3c8cd1ce-460c-4eba-aed6-886f3a96f349)

### Affected component/components

All

### How to reproduce

Create Remix Blues Stack template app
Follow the setup instructions
Then try to use the CLI to install a component or even do npx shadcn@latest init
Then it gives the error shown

### System Info

```bash
Windows 11, x64
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Fluf22** [comment]
Hey 👋🏻 

Stumbled upon the same issue this morning. It seems some templates have a different base config than the default stacks recommended by Remix.
I made a PR to fix that (it was actually a TODO in the cli code)

Let's see if it gets accepted!
