### ISSUE TITLE
[bug]: border-border styling not applying to the component

### ISSUE THREAD

**Issue by H4zlq** [shadcn-ui/ui#4983]
index.css file:
![image](https://github.com/user-attachments/assets/fb5f357b-7c8a-4303-a013-151ef9c11d85)

shadcn component using border-border styling:
![image](https://github.com/user-attachments/assets/fe707b72-5960-4a38-b64e-412166ef0372)

Output using border-border styling:
![image](https://github.com/user-attachments/assets/3eaab007-5b24-4f96-bad9-566bb3948b9e)

shadcn component using border styling:
![image](https://github.com/user-attachments/assets/1473dafa-d2e3-47a7-b20a-d3a40cdb08aa)

Output using border styling:
![image](https://github.com/user-attachments/assets/f69107f0-d913-4204-a2f6-65293e067606)

Isn't the styling should be like `border` for `border-border` or i am mistaken?

### Affected component/components

Every components that used border-border styling

### How to reproduce

...

### Codesandbox/StackBlitz link

https://stackblitz.com/edit/vitejs-vite-4zwmdh?file=src%2FApp.tsx

### System Info

```bash
Browsers
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by joseph0926** [comment]
“border-boder” is the styling for the color of ”border”
I think “border boder-boder” would be correct to achieve the behavior you want

**Comment by H4zlq** [comment]
> “border-boder” is the styling for the color of ”border” I think “border boder-boder” would be correct to achieve the behavior you want

So it is not a bug?, because i tried to use a old version for shadcn and it did work as example with `Output using border styling` thing

**Comment by joseph0926** [comment]
> > “border-boder” is the styling for the color of ”border” I think “border boder-boder” would be correct to achieve the behavior you want
> 
> So it is not a bug?, because i tried to use a old version for shadcn and it did work as example with `Output using border styling` thing

I don't know if it's a bug, but if you just use “boder”, the logic below will turn it into “border boder-boder”

https://github.com/shadcn-ui/ui/blob/a2abc4ad958c06260600a2b977dfe320e1388ab8/packages/shadcn/src/utils/transformers/transform-css-vars.ts#L138
