### ISSUE TITLE
[feat]: how to add shadcn

### ISSUE THREAD

**Issue by tvone** [shadcn-ui/ui#5204]
### Feature description

how to add shadcn? i can't use shadcn

npx shadcn@latest init
✔ Preflight checks.
✖ Verifying framework.

We could not detect a supported framework.
Visit https://ui.shadcn.com/docs/installation/manual to manually configure your project.
Once configured, you can use the cli to add components.

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by tvone** [comment]
I use electron vite

**Comment by oviedo97fer** [comment]
please check this!
