### ISSUE TITLE
[bug]: Shadcn Tailwindcss config bug

### ISSUE THREAD

**Issue by madebyvalco** [shadcn-ui/ui#5213]
### Describe the bug

So I have a variable in my tailwindcss config. Everytime I add a component it will make the variable a string. For example.

before adding a component.
![image](https://github.com/user-attachments/assets/a9c98aa8-edaa-4673-8d18-2d0e463c1e29)

after.
![image](https://github.com/user-attachments/assets/02489896-1bcb-44fb-bf21-4d04e01d3821)

### Affected component/components

All

### How to reproduce

Make a variable based text color and then add a component.

### System Info

```bash
Windows 10
Brave Browser
Vscode

October 6, 2024
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Sama-004** [comment]
use main: `${themeColor}`

**Comment by madebyvalco** [comment]
Thank you

**Comment by madebyvalco** [comment]
@Sama-004 I tried that and it did not work.
