### ISSUE TITLE
[bug]: No tailwind css configuration found

### ISSUE THREAD

**Issue by Shriikantpawar** [shadcn-ui/ui#5216]
### Describe the bug

I have created a new Vite project and made all the changes as described on shadcn docs but after using `npx shadcn@latest init` the command, I am getting an error. That's why I am not able to use shadcn components.

Following error will be displayed:

![image](https://github.com/user-attachments/assets/f67fad4e-fc46-4382-a898-e6ba62eecd3b)

### Affected component/components

All

### How to reproduce

1. Create a Vite project
2. Make changes as described on Vite installation docs
3. Use command `npx shadcn@latest init`

### System Info

```bash
Windows 11
Node v22.9.0
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Sama-004** [comment]
Install tailwind first then use the shadcn command

https://tailwindcss.com/docs/guides/vite

**Comment by MrLebre** [comment]
I have the same problem.
Tailwind already is installed for me.

**Comment by cbowdon** [comment]
Had the same issue but managed to make it work by adding the tailwind directives to index.css. Looks to me like the shadcn docs are missing a step.

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by itxtoledo** [comment]
> Had the same issue but managed to make it work by adding the tailwind directives to index.css. Looks to me like the shadcn docs are missing a step.
> 
> ```
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```

thank you

**Comment by djechlin** [comment]
AFAICT nextjs/postcss/tailwind can presently work without any css files at all, whereas shadcn explicitly checks for a css file importing tailwind base (https://github.com/shadcn-ui/ui/blob/main/packages/cli/src/utils/get-project-info.ts#L149). Maybe just a simple bug where that check can get removed, or do a more complicated check for the right setup/versioning, especially if itxtoledo's WA worked.

**Comment by Chiichen** [comment]
The following code in `index.css` would cause the error
```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```
But the following code in `index.css` works for me
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by WDLieqi** [comment]
shadcn/ui should be one step less, after installing tailwindcss, it needs to be configured so that shadcn/ui can correctly check tailwindcss.
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by yingw787** [comment]
Not sure if anybody else has this issue, but I'm installing shadcn in an Nx monorepo where I have multiple tailwind.config.js. Just tried to update shadcn/ui, but it's saying that there's no tailwind.config.js in the root directory. How can I work around this?

Happy to open up a new issue if need be, but figured this was something minor.

**Comment by krishnadubagunta** [comment]
I don't think this works with monorepos. I have a monorepo too with turborepo and it couldn't recognize a valid tailwind config.

**Comment by shadcn** [comment]
Fixed.

**Comment by BruceRoyce** [comment]
Hmm...

No Tailwind CSS configuration found at D:\_Projects\Web\your-project.
It is likely you do not have Tailwind CSS installed or have an invalid configuration.
Install Tailwind CSS then try again.
Visit https://tailwindcss.com/docs/guides/nextjs to get started.

`package.json`
```json
// other stuff
"devDependencies": {
		"@chromatic-com/storybook": "^1.6.1",
		"@storybook/addon-essentials": "^8.1.11",
		"@storybook/addon-interactions": "^8.1.11",
		"@storybook/addon-links": "^8.1.11",
		"@storybook/addon-onboarding": "^8.1.11",
		"@storybook/blocks": "^8.1.11",
		"@storybook/nextjs": "^8.1.11",
		"@storybook/react": "^8.1.11",
		"@storybook/test": "^8.1.11",
		"@tailwindcss/postcss": "^4.0.0",
		"@types/node": "^20",
		"@types/react": "^18",
		"@types/react-dom": "^18",
		"@types/sanitize-html": "^2.13.0",
		"@types/uuid": "^9.0.8",
		"eslint": "^9.20.1",
		"eslint-config-next": "14.2.3",
		"eslint-plugin-storybook": "^0.8.0",
		"postcss": "^8",
		"storybook": "^8.1.11",
		"tailwindcss": "^4.0.6",
		"typescript": "^5"
	}
// other stuff
```

`tailwind.config.js` (in root):
```javascript
/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./src/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/app/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/components/**/*.{js,ts,jsx,tsx,mdx}",
	],
	theme: {
		extend: {
			colors: {
				// Custom colors can be added here
			},
			spacing: {
				// Custom spacing values can be added here
			},
			// Additional theme customizations can be added here
		},
	},
	plugins: [],
};
```

**Comment by mcmiro** [comment]
i created a fresh t3 stack project and manually installed shadcn — same issue popped up again. ended up fixing it by checking the components.json file. the tailwind object was missing the config path:

```
tailwind: { 
config: ""
}
```

```
tailwind: { 
"config": "tailwind.config.ts"
}
```

maybe this fix will help someone else if they run into the same problem later.

**Comment by ohabash** [comment]
> How do you circumvent this problem in Next.js?

also need to know. Thank you

**Comment by rahulbangaon** [comment]
> Not sure if anybody else has this issue, but I'm installing shadcn in an Nx monorepo where I have multiple tailwind.config.js. Just tried to update shadcn/ui, but it's saying that there's no tailwind.config.js in the root directory. How can I work around this?
> 
> Happy to open up a new issue if need be, but figured this was something minor.

Same here, I tried to installing shadcn in nx monorepo in my apps/web app which is a Nextjs app and have both files tailwind.config.js and postcss.config.js but getting same error.
Do you got any solution ?

**Comment by rahulbangaon** [comment]
> > Not sure if anybody else has this issue, but I'm installing shadcn in an Nx monorepo where I have multiple tailwind.config.js. Just tried to update shadcn/ui, but it's saying that there's no tailwind.config.js in the root directory. How can I work around this?
> > Happy to open up a new issue if need be, but figured this was something minor.
> 
> Same here, I tried to installing shadcn in nx monorepo in my apps/web app which is a Nextjs app and have both files tailwind.config.js and postcss.config.js but getting same error. Do you got any solution ?
Update -
It worked for me by temporarily installing tailwindcss inside apps/web to make it work, then removing it and running pnpm install in the root so it uses the root tailwindcss.
This trick helped me with NX monorepo using Next.js 15. I think it’s a temporary workaround.

**Comment by rahulbangaon** [comment]
> > Not sure if anybody else has this issue, but I'm installing shadcn in an Nx monorepo where I have multiple tailwind.config.js. Just tried to update shadcn/ui, but it's saying that there's no tailwind.config.js in the root directory. How can I work around this?
> > Happy to open up a new issue if need be, but figured this was something minor.
> 
> Same here, I tried to installing shadcn in nx monorepo in my apps/web app which is a Nextjs app and have both files tailwind.config.js and postcss.config.js but getting same error. Do you got any solution ?

Update -
It worked for me by temporarily installing tailwindcss inside apps/web to make it work, then removing it and running pnpm install in the root so it uses the root tailwindcss.
This trick helped me with NX monorepo using Next.js 15. I think it’s a temporary workaround.
