### ISSUE TITLE
[bug]: Update text for controlled sidebar example

### ISSUE THREAD

**Issue by karthiknmenon** [shadcn-ui/ui#5443]
### Describe the bug

IMO, we should probably be using the inverse here, i.e., `Close sidebar` when the sidebar's open and `Open sidebar` when it's closed.

Unless, it was intentionally done so that we display sidebar's current open state.

Ref - 

![CleanShot 2024-10-19 at 18 40 51](https://github.com/user-attachments/assets/0791df46-4209-47fd-9319-b13f77bb4b96)

### Affected component/components

Sidebar

### How to reproduce

1. Go to https://ui.shadcn.com/docs/components/sidebar
2. Go to `Controller sidebar` example
3. The text for open/closed state of the sidebar should be inverse

### System Info

```bash
Browser: Arc
OS: Mac OS
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Jacksonmills** [comment]
also had a PR open for this one https://github.com/shadcn-ui/ui/pull/5428

**Comment by Jacksonmills** [comment]
Can be closed now
