### ISSUE TITLE
[feat]: Customizable Base Directory and Alias Resolution

### ISSUE THREAD

**Issue by paul-vd** [shadcn-ui/ui#5475]
### Feature description

In some projects, you may organize your `ui` folder under a different directory than the defaults used by the CLI. It would be helpful to specify a custom base directory, and even better, to configure resolutions for each alias.

#### Problem Example

In my current project, I have the following folder structure:

```
📁 app (current app)
 ├─ 📁 lib
 │   └─🗒️ utils.ts
 ├─ 📁 components
 │   └─📁 ui
📁 src (legacy app referenced in `app` for non-migrated components/features)
```

After running the CI, it incorrectly placed new components under `src/components/ui`, even though my `tsconfig` aliases do not point there, and I don’t have any existing UI components in `src`. 

#### Suggested Solution

It would be beneficial to have the ability to configure these resolutions in `components.json`. This would allow proper placement of components in the intended directories, and prevent files like `lib/utils.ts` from being generated repeatedly (though I haven't tested if this happens with `utils`).

#### Example `components.json` Configuration:

```json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "new-york",
  "rsc": false,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "app/tailwind.css",
    "baseColor": "zinc",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "~/components",
    "utils": "~/lib/utils",
    "ui": "~/components/ui",
    "lib": "~/lib",
    "hooks": "~/hooks"
  },
  "baseDir": "./app",  // When this is defined, aliases will resolve as usual but with the app directory as the base
  "baseDir": {
    "components": "./app/components/ui",
    // Additional custom base directories for other aliases can be added here
  }
}
```

#### Additional Context

Here's an example of my `tsconfig.json`. I'm not sure if this also affects how the CI resolves paths:

```json
{
  "baseUrl": ".",
  "paths": {
    "~/*": ["./app/*"],
    "~v2/*": ["./src/*"]
  }
}
```

---

This feature would provide more control over file placement and avoid issues caused by the default behavior of the CLI. Thank you for considering this improvement!

### Affected component/components

cli

### Additional Context

This is similar to the `tailwind::config` and `tailwind::css` options.

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by ivan-plotnikov** [comment]
The paths parameter in your tsconfig.json is exactly what is responsible for the base directory to host the files. This used to work, but after recent updates it is broken. This problem is detailed in #5433

**Comment by paul-vd** [comment]
Thanks @ivan-plotnikov , I see it has since been resolved in https://github.com/shadcn-ui/ui/issues/5433, I will close this now, and re-open it if there are still issues after running the command again.
