### ISSUE TITLE
[bug]: There is a linting issue in input component - no-empty-object-type

### ISSUE THREAD

**Issue by ayuugoyal** [shadcn-ui/ui#5489]
### Describe the bug

I am getting build error on vercel. did anyone got the same issue? or any way to solve this? @shadcn 

`+ typescript 5.6.3
Done in 16.7s
Detected Next.js version: 14.2.15
Running "pnpm run build"
> ruleengine@0.1.0 build /vercel/path0
> next build
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
  ▲ Next.js 14.2.15
   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types ...
Failed to compile.
./components/ui/input.tsx
5:18  Error: An interface declaring no members is equivalent to its supertype.  @typescript-eslint/no-empty-object-type
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
`

### Affected component/components

input

### How to reproduce

1. Install Input component from the shahcn lib 
2. use the input component
3. try to deploy it on vercel
4. see the deployment error

### System Info

```bash
system - Ubuntu-linux
Browser - firefox
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by SamuelChojnacki** [comment]
same in next js 15 projet on my mac

**Comment by SamuelChojnacki** [comment]
configure your .eslintrc.json with   "rules": { "@typescript-eslint/no-empty-object-type": "off" }
