### ISSUE TITLE
[bug]: `Sidebar` isn't opening within div it is placed in

### ISSUE THREAD

**Issue by JolomiTee** [shadcn-ui/ui#5495]
#### Firstly, i would like to apologize for the amount of pictures.. please continue..

The sidebar component works well so far, but I have a specific use case where the sidebar should not open from the very edge of the screen but rather after the first element that is already there acting as a sidebar. Take the below UI redesign of the Discord Application; the space that carries the 'Messages' and 'Friends' Tab Switcher component (implemented with shadcn-ui, btw) is the component I want to put within the sidebar. The problem I seem to have is that the sidebar still behaves like a sheet in the sense that it defaults to opening from the edges of the screen, not from within the div in which the `Sidebar` component is placed.

![Messages](https://github.com/user-attachments/assets/70c840c7-0f8e-4798-ac92-e9383527ddd3)

Now I tried to explore if it's actually a bug but my methods were rather crude, but I can clearly describe my issues with the following images

Firstly, notice the two column layout I tried to achieve in the chat area, the button that opens the sidebar is at an initial position, then when it is open, the button moves, but the sidebar appears from the side.

![image](https://github.com/user-attachments/assets/5626748b-e366-4637-9fdc-687ecdc6baca)

![image](https://github.com/user-attachments/assets/b60fb879-9844-44ab-a19f-773ef98e7ddb)

### Affected component/components

Sidebar

### How to reproduce

1. create a three column layout with flexbox: 
```
<div className="flex relative w-screen h-screen">
   <div className="w-1/3"></div>
   <div className="w-full">
      # place the sidebar component here
   </div>
   <div className="w-1/3"></div>
</div>

```

### System Info

```bash
OS: Linux Mint
Browser: Microsoft Edge
Code Editor: VSCode
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by JolomiTee** [comment]
The only way I've seen to achieve close to what I need is using the collapsible prop, which restricts the sidebar to the expected div, but then it makes it... well, not collapsible.

**Comment by JolomiTee** [comment]
I found a way to achieve what I want..

First, I added a 'relative' class to the className of the div that isn't in a mobile or collapsed state (the last return statement of the `Sidebar` component in the `sidebar.tsx` file).

![carbon](https://github.com/user-attachments/assets/51b38762-e68b-49e2-8ee5-517ab8ef1a29)

Then I replaced the 'fixed' classname of the second child div in the div mentioned above, with an 'absolute'

![carbon](https://github.com/user-attachments/assets/ee0ac40d-0c35-4d80-bbf6-c9204baa858b)

The code(stripped down):
![carbon](https://github.com/user-attachments/assets/4a8c6f2f-7aa1-4f1b-be73-d3b04b17c2ac)

The result:
(Closed State)
![Screenshot_21-10-2024_234225_localhost](https://github.com/user-attachments/assets/74beaa30-4cfb-4a25-85aa-8c76bcb50f1e)

(Open State)
![Screenshot_21-10-2024_234312_localhost](https://github.com/user-attachments/assets/88ad1801-ac1f-451c-8bd4-b258d725f1b2)

**Comment by EducatedAI-kaisera** [comment]
Same issue for me. I'll give this a try.

**Comment by Clev7** [comment]
Just ran into this issue. Doesn't seem to have an official fix yet.

**Comment by JolomiTee** [comment]
@Clev7 check this old issue out, it should help:
https://github.com/shadcn-ui/ui/issues/5651
