### ISSUE TITLE
[bug]: Page Reloads on Sidebar Navigation 

### ISSUE THREAD

**Issue by kaleem-uet** [shadcn-ui/ui#5501]
### Describe the bug

Sidebar Issue :
I am encountering an issue with the newly added sidebar component using **ShadCN** in my Next.js project. When I click on a link in the sidebar, such as "Orders" or "Chat," the page reloads instead of navigating smoothly as expected in a single-page application (SPA).

![Archiwiz-GoogleChrome2024-10-2210-23-49-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/49cc223d-ae52-4e93-95a3-ba812cf8a8f6)

### Affected component/components

SideBar

### How to reproduce

1. Implement the sidebar by copying the updated sidebar component from ShadCN.
2. Replace the links with my own, such as /orders and /chat.
3. Click on any of the sidebar links.

### System Info

```bash
using chrome in the window
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Adnankhan4565** [comment]
yes very annoying issue if someone can fix would help a lot.

**Comment by achemnomaer** [comment]
"components/nav-main.jsx" or wherever the sidebar links are rendered,

![image](https://github.com/user-attachments/assets/fe27cd07-10ae-4c7f-8492-efdeda4d386b)


Replaced "a" tag:

`<a href={subItem.url}>
   <span>{subItem.title}</span>
</a>
`

with nextjs "Link" component:

<Link href={subItem.url}>
   <span>{subItem.title}</span>
</Link>

**Comment by kaleem-uet** [comment]
fixed

**Comment by doctorDAlvarez** [comment]
Nice

**Comment by AikidoSensei** [comment]
Awesome!!! Fix this was a pain in the 🍑

**Comment by FnayouSeif** [comment]
Damn. AI replace dev my a**. Spent AI debugging for 15 minutes just to find this @achemnomaer  in one minute and one shot fix it. kudos
