### ISSUE TITLE
[bug]: sidebar type error with some refs

### ISSUE THREAD

**Issue by doriancollier** [shadcn-ui/ui#5512]
### Describe the bug

Getting build error on multiple refs in sidebar. Tried adjusting my linting rules, my tsconfig, and even having AI try to fix the error. No dice. Please help

### Affected component/components

sidebar (SidebarGroupAction, SidebarMenuButton, etc)

### How to reproduce

1. install sidebar using npm 
`npx shadcn@latest add sidebar`

2. build 
`npm run build`

### Logs

```bash
From Command Line
----

Linting and checking validity of types  ...Failed to compile.

./components/ui/sidebar.tsx:440:7
Type error: Type 'string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null' is not assignable to type '((string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement>) & (((instance: HTMLElement | null) => void) | RefObject<...>)) | null | undefined'.
  Type 'string' is not assignable to type '((string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement>) & (((instance: HTMLElement | null) => void) | RefObject<...>)) | null | undefined'.

  438 |   return (
  439 |     <Comp
> 440 |       ref={ref}
      |       ^
  441 |       data-sidebar="group-label"
  442 |       className={cn(
  443 |         "duration-200 flex h-8 shrink-0 items-center rounded-md px-2 text-xs font-medium text-sidebar-foreground/70 outline-none ring-sidebar-ring transition-[margin,opa] ease-linear focus-visible:ring-2 [&>svg]:size-4 [&>svg]:shrink-0",
```

### System Info

```bash
"next": "^14.2.7",
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Eldevia** [comment]
same error

**Comment by doriancollier** [comment]
I'm able to get rid of the error by removing the Slots
```
//const Comp = asChild ? Slot : "a"
    const Comp = 'a';
```

**Comment by shadcn** [comment]
@doriancollier which react version?

**Comment by iPanamas** [comment]
Hello, I also have a issue with the ref in the components (SidebarGroupLabel, SidebarGroupAction, SidebarMenuButton, SidebarMenuAction, SidebarMenuSubButton).

"react": "^18.2.0",
"next": "^14.2.15",


> @doriancollier which react version?

**Comment by drrius** [comment]
Doing this works for me and you can keep the Slots:

```
type SidebarGroupActionProps = Omit<React.ComponentProps<'button'>, 'ref'> & {
  asChild?: boolean;
};

const SidebarGroupAction = React.forwardRef<
  HTMLButtonElement,
  SidebarGroupActionProps
>(({ className, asChild = false, ...props }, ref) => {
  const Comp = asChild ? Slot : 'button';

  return (
    <Comp
      ref={ref}
      data-sidebar="group-action"
      className={cn(
        'absolute right-3 top-3.5 flex aspect-square w-5 items-center justify-center rounded-md p-0 text-sidebar-foreground outline-none ring-sidebar-ring transition-transform hover:bg-sidebar-accent hover:text-sidebar-accent-foreground focus-visible:ring-2 [&>svg]:size-4 [&>svg]:shrink-0',
        // Increases the hit area of the button on mobile.
        'after:absolute after:-inset-2 after:md:hidden',
        'group-data-[collapsible=icon]:hidden',
        className,
      )}
      {...props}
    />
  );
});
SidebarGroupAction.displayName = 'SidebarGroupAction';
```

**Comment by Julianpletz** [comment]
> Hello, I also have a issue with the ref in the components (SidebarGroupLabel, SidebarGroupAction, SidebarMenuButton, SidebarMenuAction, SidebarMenuSubButton).
> 
> "react": "^18.2.0", "next": "^14.2.15",
> 

I've got the same problem in these files.

    "react": "^18.3.1",
     "next": "^14.2.16",

**Comment by ridem** [comment]
I was still using `@types/react@18.2`, simply upgrading the [types package to its latest version](https://www.npmjs.com/package/@types/react) fixed the issue for me. 
```
npm update @types/react
```
```
yarn up -R @types/react
```

**Comment by doriancollier** [comment]
It's working correctly for me, but I've made so many changes that I'm not sure what fixed it. 

I believe my problem was caused by using the newest version of eslint along with the flatfile format, and used the [recommended lint config in the Next.js docs](https://nextjs.org/docs/app/building-your-application/configuring/eslint). I've since reverted to eslint v8.57.1, upgraded to Nextjs 15, updated all of the radix components to their latest versions, etc.

```
// .eslintrc.json
{
    "root": true,
    "extends": ["next/core-web-vitals"],
    "rules": {
        //...
    }
}
```





```
// package.json

{
  "private": true,
  "scripts": {
    //...
  },
  "dependencies": {
    //..
    "@next/third-parties": "15.0.1-canary.2",
    "@radix-ui/react-alert-dialog": "^1.1.2",
    "@radix-ui/react-avatar": "^1.1.1",
    "@radix-ui/react-checkbox": "^1.1.2",
    "@radix-ui/react-collapsible": "^1.1.1",
    "@radix-ui/react-context-menu": "^2.2.2",
    "@radix-ui/react-dialog": "^1.1.2",
    "@radix-ui/react-dropdown-menu": "^2.1.2",
    "@radix-ui/react-hover-card": "^1.1.2",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.1.0",
    "@radix-ui/react-navigation-menu": "^1.2.1",
    "@radix-ui/react-popover": "^1.1.2",
    "@radix-ui/react-progress": "^1.1.0",
    "@radix-ui/react-radio-group": "^1.2.1",
    "@radix-ui/react-scroll-area": "^1.2.0",
    "@radix-ui/react-select": "^2.1.2",
    "@radix-ui/react-separator": "^1.1.0",
    "@radix-ui/react-slider": "^1.2.1",
    "@radix-ui/react-slot": "^1.1.0",
    "@radix-ui/react-switch": "^1.1.1",
    "@radix-ui/react-tabs": "^1.1.1",
    "@radix-ui/react-toast": "^1.2.2",
    "@radix-ui/react-toggle": "^1.1.0",
    "@radix-ui/react-tooltip": "^1.1.3",
    "@types/node": "20.5.7",
    "next": "^15.0.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "ts-node": "^10.9.2",
    //...
  },
  "devDependencies": {
    "@babel/preset-typescript": "^7.24.7",
    "@types/react": "npm:types-react@19.0.0-rc.1",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1",
    "eslint": "^8.57.1",
    "eslint-config-next": "^15.0.1",
    "typescript": "^5.1.6"
     //...
  },
  "engines": {
    "node": ">=20"
  },
  "overrides": {
    "@types/react": "npm:types-react@19.0.0-rc.1",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
  }
}

```

Godspeed

**Comment by travistylervii** [comment]
I was able to do it by removing the commented out line and replacing it with Omit<React.ComoonentsProps...

```typescript
const SidebarMenuButton = React.forwardRef<
  HTMLButtonElement,
  //React.ComponentProps<"button"> //Removed this
  Omit<React.ComponentProps<'button'>, 'ref'> & { //Added this
    asChild?: boolean
    isActive?: boolean
    tooltip?: string | React.ComponentProps<typeof TooltipContent>
  } & VariantProps<typeof sidebarMenuButtonVariants>
>(
  (
    {
      asChild = false,
      isActive = false,
      variant = "default",
      size = "default",
      tooltip,
      className,
      ...props
    },
    ref
  ) => {
    const Comp = asChild ? Slot : "button"

    const { isMobile, state } = useSidebar()

    const button = (
      <Comp
        ref={ref}
        data-sidebar="menu-button"
        data-size={size}
        data-active={isActive}
        className={cn(sidebarMenuButtonVariants({ variant, size }), className)}
        {...props}
      />
    )
```

**Comment by ddolboghi** [comment]
I got the same error at
"next": "^14.2.15",
"@types/react": "18.2.46",

I modified it to `React.ComponentPropsWithRef` instead of `React.ComponentProps` so that `ref` is always recognised.

```tsx
const SidebarGroupAction = React.forwardRef<
  HTMLButtonElement,
  React.ComponentPropsWithRef<"button"> & { asChild?: boolean }
>(({ className, asChild = false, ...props }, ref) => {
  const Comp = asChild ? Slot : "button";

  return (
    <Comp
      ref={ref}
      data-sidebar="group-action"
      className={cn(
        "absolute right-3 top-3.5 flex aspect-square w-5 items-center justify-center rounded-md p-0 text-sidebar-foreground outline-none ring-sidebar-ring transition-transform hover:bg-sidebar-accent hover:text-sidebar-accent-foreground focus-visible:ring-2 [&>svg]:size-4 [&>svg]:shrink-0",
        // Increases the hit area of the button on mobile.
        "after:absolute after:-inset-2 after:md:hidden",
        "group-data-[collapsible=icon]:hidden",
        className
      )}
      {...props}
    />
  );
});
SidebarGroupAction.displayName = "SidebarGroupAction";
```
The components I modified are `SidebarGroupLabel`, `SidebarGroupAction`, `SidebarMenuButton`, `SidebarMenuAction`, and `SidebarMenuSubButton`.

**Comment by thisisfel1x** [comment]
Updating `@types/react` to version 18.3.12 fixed the issue

**Comment by AbdouraoufYoussouf** [comment]
meme probleme pour moi et ce qui m'a aidé 
c'est de remplacer React.ComponentProps  par  React.ComponentPropsWithRef dans les composant ou il y a le probleme
const SidebarMenuSubButton = React.forwardRef<
  HTMLAnchorElement,
  React.ComponentProps<"a"> & {
    asChild?: boolean
    size?: "sm" | "md"
    isActive?: boolean
  }
>(({ asChild = false, size = "md", isActive, className, ...props }, ref) => {
  const Comp = asChild ? Slot : "a"

  return (
    <Comp
      ref={ref}
      data-sidebar="menu-sub-button"
      data-size={size}
      data-active={isActive}
      className={cn(
        "flex h-7 min-w-0 -translate-x-px items-center gap-2 overflow-hidden rounded-md px-2 text-sidebar-foreground outline-none ring-sidebar-ring hover:bg-sidebar-accent hover:text-sidebar-accent-foreground focus-visible:ring-2 active:bg-sidebar-accent active:text-sidebar-accent-foreground disabled:pointer-events-none disabled:opacity-50 aria-disabled:pointer-events-none aria-disabled:opacity-50 [&>span:last-child]:truncate [&>svg]:size-4 [&>svg]:shrink-0 [&>svg]:text-sidebar-accent-foreground",
        "data-[active=true]:bg-sidebar-accent data-[active=true]:text-sidebar-accent-foreground",
        size === "sm" && "text-xs",
        size === "md" && "text-sm",
        "group-data-[collapsible=icon]:hidden",
        className
      )}
      {...props}
    />
  )
})
SidebarMenuSubButton.displayName = "SidebarMenuSubButton"

**Comment by nmerchant** [comment]
None of the other solutions worked for me, but upgrading @types fixed the issue (running Next.js 15).

> Updating `@types/react` to version 18.3.12 fixed the issue (prod still running on NextJS 14)

**Comment by ImAlejon** [comment]
Changing the React.ComponentProps lines to React.ComponentPropsWithRef did solve everything for me after updating @types/react.

> I modified it to `React.ComponentPropsWithRef` instead of `React.ComponentProps` so that `ref` is always recognised.

**Comment by AIchovy** [comment]
Same error. 
My version:
```
Next.js 14.2.8
@types/react 18.2.13
```
upgrade types/react version to 18.3.12 fixed my issue
