### ISSUE TITLE
[bug]: components get creates in the root folder of the project

### ISSUE THREAD

**Issue by abdoaitwihi** [shadcn-ui/ui#5527]
### Describe the bug

This is my tsconfig.json

{
    "compilerOptions": {
        "allowJs": true,
        "module": "ESNext",
        "moduleResolution": "bundler",
        "jsx": "react-jsx",
        "strict": true,
        "isolatedModules": true,
        "target": "ESNext",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "skipLibCheck": true,
        "noEmit": true,
        "paths": {
            "@/*": ["./resources/js/*"],
            "ziggy-js": ["./vendor/tightenco/ziggy"]
        }
    },
    "include": [
        "resources/js/**/*.ts",
        "resources/js/**/*.tsx",
        "resources/js/**/*.d.ts"
    ]
}

and this is components.json

{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "new-york",
  "rsc": false,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "resources/css/app.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  }
}

npx shadcn@latest add button creats the component in the root folder of the project 

### Affected component/components

all components get created in the root folder

### How to reproduce

I had a project with laravel interia and react.
I had also another project with the same config (laravel interia and react) which used to work fine , but know it has this problem of the comps being created in the root while they used to be created in the right location (resources/js/components/ui)

### System Info

```bash
Windows pc.
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by ivan-plotnikov** [comment]
Duplicates #5433
