### ISSUE TITLE
Hydration Error on Input Type Password

### ISSUE THREAD

**Issue by hmzakhalid** [shadcn-ui/ui#553]
I'm working on a personal project and decided to test out this UI lib. While creating the Login/Register Page. I got hydration errors and 
It took me an hour to narrow down what was generating the error. 

![image](https://github.com/shadcn/ui/assets/36852564/b41acd03-4478-47f1-a4fe-aff260ffd9a1)

Here's how to generate:
1. Create a brand new next js project `pnpm create next-app`
2. Install shadcn-ui `pnpx shadcn-ui init`
3. Install the Input component `pnpx shadcn-ui add input`
4. Navigate to `src -> app -> page.tsx` and use the following code
```js
export default function Home() {
  return (
    <div>
      <Input type="password" />;
    </div>
  );
}
```
5. Save and Reload the page. On every reload the error will occur. 

Another bizarre example of the error that I can't wrap my head around is as follows.
`<Label htmlFor="name"> Username </Label>`
if the text inside the label has "Username" in any way. It'll generate the above hydration error.
- Username - Doesn't work
- User-name - Doesn't work
- MyUsername - Doesn't work
- User              name - Does't work
- Anything else - Works

**Comment by benabdullah** [comment]
> ### The issue
> It seems that the issue you're experiencing could be related to a browser extension interfering with the code's behavior. In some cases, autocomplete extensions (like password managers) or other browser extensions can cause conflicts or unexpected behavior.
> 
> ### Try this
> * use Incognito mode
> * use a clean browser profile without any extension enabled
> 
> If the code works without any hydration errors, then an extension might be causing the problem.
> 
> Let me know.

Thanks, i was disabled LastPass plugin and fix this error

**Comment by Reniactor** [comment]
I know the LastPass disabling solved the issue, however, i'd like to see if there's a way to make it so that it works with and without LastPass
