### ISSUE TITLE
[bug]: Main content for Sidebar width expands to content and scrolls horizontally

### ISSUE THREAD

**Issue by kchro3** [shadcn-ui/ui#5545]
### Describe the bug

I'm trying out the Sidebar implementation, but I'm running into an issue where the "main" content's width expands to fit the content, which doesn't seem like a sensible default.

For example, if I make a sidebar-01 & add a data table with lots of columns, the main content will expand to fit the size of the table so that the main content of the sidebar becomes horizontally scrollable, which is almost never expected, unless you're building some kind of infinite canvas type of application.

Would be great if this could be considered for a bug fix

### Affected component/components

Sidebar

### How to reproduce

1. Check out sidebar-01 in v0 
2. Add a very wide Table component into the main content so that it will exceed the available width

<img width="957" alt="Screenshot 2024-10-24 at 15 13 26" src="https://github.com/user-attachments/assets/986fa27f-745b-478a-a8fd-f240c4210f3f">
<img width="962" alt="Screenshot 2024-10-24 at 15 13 36" src="https://github.com/user-attachments/assets/11aa9398-41f4-42d1-b0f2-511d0da84d2c">

### Codesandbox/StackBlitz link

https://v0.dev/chat/petY7aNQAYx?b=b_GgHLxNdMNlr

### System Info

```bash
N/A
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by incpo** [comment]
The issue is with the main content. Basically, if you try to render a wide object like a table and want it to overflow, you'll encounter an overflow issue. To solve this, you usually apply w-full and overflow-auto to the component, and you're done. 
Stackblitz demo - https://stackblitz.com/edit/stackblitz-starters-hf6zhn?file=components%2Fapp-table.tsx
![image](https://github.com/user-attachments/assets/8eaa3b89-9733-484f-9b64-7283aa03a875)

If you try to render a table, it won't squeeze as usual; it just overflows the HTML. This isn't solved by setting limitations on the parent div because they depend on the upper content, which is the main content div.
Here is a screencast of the problem and how to solve it:
https://youtu.be/eD8gnEZfBW4

The problem is that the main content doesn't directly depend on the sidebar, so it has an unsatisfactory width and overflows the HTML. To solve this, you need to make the main content depend on the sidebar by adding `width: calc(100vw - var(--sidebar-width)) `and `overflow: hidden`.

Perhaps I'm wrong, and by doing this, you might disrupt the HTML architecture, making the main content not overflowable and entirely based on the sidebar. However, on the other hand, it's a layout based on the sidebar, and we don't have any outer HTML elements.

Also, don't forget that this sidebar may be used in a dialog or other components, so it's not always 100vw. Based on these thoughts, I don't think it's a clear bug, but it might be. it may just be a specific case issue (not related to all).

**Comment by shahriyardx** [comment]
Adding `max-w-full` class in SidebarInset fixes the problem for me

**Comment by adiramardiani** [comment]
Thanks for your suggest @shahriyardx but it's not working

Your solution is nice @incpo but yes, some functionality seems not working well, can check my code :(

https://github.com/adiramardiani/shadcn-next/commit/d08a8f64225819f26843fa98cf85eede9d06bd13

![image](https://github.com/user-attachments/assets/44ce76c5-8bc4-41ad-9b4a-441e56ccc129)

Sorry for mention you @shadcn 
It's any best practice or the right way to handle this, I don't know this is bug on layout, or my sticky implementation is wrong 

Here the demo 
https://stackblitz.com/~/github.com/adiramardiani/shadcn-next

I refer with this source for sticky https://codepen.io/paulobrien/pen/LBrMxa

**Comment by damiankuchar** [comment]
In my case adding `className="overflow-hidden"` to `SidebarInset` solved the problem.

@kchro3 codesandbox link (fork): https://v0.dev/chat/K1ebiVKWPDV?b=JzbbCb0GaQc

Code snippet of the layout with header and sidebar:
```js
return (
  <SidebarProvider>
    <AppSidebar />
    <SidebarInset className="overflow-hidden">
      <Header />
      <div className="flex-1 flex flex-col mx-auto p-6 w-full">{children}</div>
    </SidebarInset>
  </SidebarProvider>
);
```

**Comment by adiramardiani** [comment]
> In my case adding `className="overflow-hidden"` to `SidebarInset` solved the problem.
> 
> @kchro3 codesandbox link (fork): https://v0.dev/chat/K1ebiVKWPDV?b=JzbbCb0GaQc
> 
> Code snippet of the layout with header and sidebar:
> 
> ```js
> return (
>   <SidebarProvider>
>     <AppSidebar />
>     <SidebarInset className="overflow-hidden">
>       <Header />
>       <div className="flex-1 flex flex-col mx-auto p-6 w-full">{children}</div>
>     </SidebarInset>
>   </SidebarProvider>
> );
> ```

![image](https://github.com/user-attachments/assets/ac31963d-c616-4547-805e-80508aa918a3)

using this my sticky header work on previous version, with this overflow hidden header not sticky anymore @damiankuchar

**Comment by ahmedivy** [comment]
> Adding `max-w-full` class in SidebarInset fixes the problem for me
> 
> ```js
> <SidebarInset className="max-w-full">
>     ....
> </SidebarInset>
> ```

thanks man 🙏🏻

**Comment by gtvasseur** [comment]
I’m experiencing the same issue that @adiramardiani mentioned. It seems that overflow disrupts the sticky position. 
While this approach works as a quick fix for overflowing data tables, it doesn’t address the problem effectively

**Comment by askareija** [comment]
after reading some comments here, i've found a tricky solution that fix the sticky header and overflow table by using sidebar hooks and fixed position.

On the `layout.tsx` use `overflow-auto` :

```jsx
<SidebarProvider>
                <AppSidebar />
                <SidebarInset className="overflow-auto">
                    <Header />

                    <div className="flex-1 flex flex-col mx-auto p-6 w-full">
                        <Outlet />
                    </div>
                </SidebarInset>
 </SidebarProvider>
```

On the `header.tsx` use `fixed` instead of `sticky` and use sidebar hooks and `cn`:

```jsx
const { isMobile, state } = useSidebar();

return (
<header className={cn(
            "fixed z-10 border-b bg-opacity-30 backdrop-blur-lg backdrop-filter transition-all",
            {
                "w-full": isMobile,
                "w-[calc(100%-var(--sidebar-width))]": !isMobile && state === "expanded",
                "w-[calc(100%-var(--sidebar-width-icon))]": !isMobile && state === "collapsed",
            }
        )}>
)
```

Yea i need to calculate the width 100% - sidebar width for `expanded` and 100% - sidebar width icon for `collapsed`. 

Result when desktop expand:
![gambar](https://github.com/user-attachments/assets/2f6bb6d1-51b8-4954-a7bd-44f0168d8494)

Result when sidebar collapsed:
![gambar](https://github.com/user-attachments/assets/99b6158e-6b68-4577-b2d0-f1fc2f21053b)

Result on mobile:
![gambar](https://github.com/user-attachments/assets/d768e8e9-d385-4407-b956-33b5c4f9cb7e)

**Comment by amraaone** [comment]
@askareija 

how to set only content side can scroll, if rendering datas over my screen size that time can overflow. other case no need that overflow.. how to hide? 


mainLayout.tsx /components 
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import React from "react"
import { MainLayoutProps } from "../types"
import Header from "./header"
import { AppSidebar } from "./sidebar"

const MainLayout: React.FC<MainLayoutProps> = ({ children, log_out }) => {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset className="overflow-hidden flex flex-col h-screen">
        {/* Header */}
        <Header log_out={log_out} />

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto mt-[64px] p-6 w-full">
          {children}
        </div>
      </SidebarInset>
    </SidebarProvider>
  )
}

export default MainLayout

mainLayout.tsx /containers here 
const MainLayoutContainer: React.FC<MainLayoutProps> = ({
  currentUser,
  ...props
}) => {
  const extendedProps = {
    ...props,
    log_out: () => log_out_user(),
  }

  return (
    <AppProvider currentUser={currentUser}>
      <TooltipProvider delayDuration={10}>
        <MainLayoutComponent {...extendedProps} />d
      </TooltipProvider>
    </AppProvider>
  )
}

export default MainLayoutContainer


header.tsx is here
import { SidebarTrigger, useSidebar } from "@/components/ui/sidebar"
import { cn } from "@/lib/utils"
import React from "react"
import { HeaderProps } from "../types"
import Language from "./language"
import Notification from "./notification"
import UserNav from "./userNav"

const Header: React.FC<HeaderProps> = ({ log_out }) => {
  const { isMobile, state } = useSidebar()

  return (
    <header
      className={cn(
        "fixed z-10 border-b bg-white flex items-center justify-between p-4  gap-1",
        {
          "w-full": isMobile, // Mobile view
          "w-[calc(100%-var(--sidebar-width))]":
            !isMobile && state === "expanded", // Sidebar expanded
          "w-[calc(100%-var(--sidebar-width-icon))]":
            !isMobile && state === "collapsed", // Sidebar collapsed
        }
      )}
      style={{ height: "64px" }} // Fixed header height
    >
      <div className="flex items-center">
        <SidebarTrigger />
      </div>
      <div className="flex items-center gap-2">
        <Language />
        <Notification />
        <UserNav log_out_user={log_out ?? (() => {})} />
      </div>
    </header>
  )
}

export default Header



/overview
![Screenshot 2024-12-14 at 13 46 45](https://github.com/user-attachments/assets/acfbad13-0764-4ef1-b218-e573b2f79500)


/economic-calendar
![Screenshot 2024-12-14 at 13 47 09](https://github.com/user-attachments/assets/088fc1a3-a68d-4e9e-9276-104d1bb74993)

**Comment by amraaone** [comment]
My simple solution. 

AppSidebar is here

import {
  BadgeCheckIcon,
  CalendarIcon,
  KanbanIcon,
  LayoutDashboardIcon,
} from "lucide-react"

import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
} from "@/components/ui/sidebar"

const sidebarData = [
  {
    label: "Main",
    items: [
      {
        name: "Psychology",
        url: "/psychology",
        icon: BadgeCheckIcon,
        subItems: [
          { name: "Overview", url: "/psychology/overview" },
          { name: "Tips", url: "/psychology/tips" },
        ],
      },
      {
        name: "Money Management",
        url: "/money-management",
        icon: KanbanIcon,
        subItems: [
          { name: "Budgeting", url: "/money-management/budgeting" },
          { name: "Saving", url: "/money-management/saving" },
        ],
      },
    ],
  },
  {
    label: "Application",
    items: [
      {
        name: "Dashboard",
        url: "/dashboard",
        icon: LayoutDashboardIcon,
        subItems: [
          { name: "Reports", url: "/dashboard/reports" },
          { name: "Analytics", url: "/dashboard/analytics" },
        ],
      },
      {
        name: "Calendar",
        url: "/calendar",
        icon: CalendarIcon,
        subItems: [
          { name: "Events", url: "/calendar/events" },
          { name: "Holidays", url: "/calendar/holidays" },
        ],
      },
    ],
  },
]

export function AppSidebar() {
  return (
    <Sidebar collapsible="icon" variant="floating" side="left">
      <SidebarContent>
        {sidebarData.map((group) => (
          <SidebarGroup key={group.label}>
            <SidebarGroupLabel>{group.label}</SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>
                {group.items.map((item) => (
                  <SidebarMenuItem key={item.name}>
                    <SidebarMenuButton asChild>
                      <a href={item.url}>
                        <item.icon />
                        <span>{item.name}</span>
                      </a>
                    </SidebarMenuButton>
                    {/* <SidebarMenuBadge>0</SidebarMenuBadge> */}
                    {item.subItems && item.subItems.length > 0 && (
                      <SidebarMenuSub>
                        {item.subItems.map((subItem) => (
                          <SidebarMenuSubItem key={subItem.name}>
                            <SidebarMenuSubButton asChild>
                              <a href={subItem.url}>
                                <span>{subItem.name}</span>
                              </a>
                            </SidebarMenuSubButton>
                          </SidebarMenuSubItem>
                        ))}
                      </SidebarMenuSub>
                    )}
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>
        ))}
      </SidebarContent>
    </Sidebar>
  )
}


Header.tsx is here
import { SidebarTrigger } from "@/components/ui/sidebar"
import React from "react"
import { HeaderProps } from "../types"
import Language from "./language"
import Notification from "./notification"
import UserNav from "./userNav"

const Header: React.FC<HeaderProps> = ({ log_out }) => {
  return (
    <header className="flex items-center justify-between bg-white p-4 border-b border-gray-100 gap-1 sticky top-0 z-10">
      <div className="flex items-center">
        <SidebarTrigger />
      </div>
      <div className="flex items-center gap-2">
        <Language />
        <Notification />
        <UserNav log_out_user={log_out ?? (() => {})} />
      </div>
    </header>
  )
}

export default Header



MainLayout.tsx is here
import { SidebarProvider } from "@/components/ui/sidebar"
import React from "react"
import { MainLayoutProps } from "../types"
import Header from "./header"
import { AppSidebar } from "./sidebar"

const MainLayout: React.FC<MainLayoutProps> = ({ children, log_out }) => {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="flex-1">
        <Header log_out={log_out} />
        {children}
      </main>
    </SidebarProvider>
  )
}

export default MainLayout


can collapsible sidebar and all of props can use. 
content is not render overflow when empty, if few more datas over screen hight that time overflow can works, but header always on top

**Comment by akshathere** [comment]
@incpo thanks a lot man
Your one w-full h-full made my night
thanks a lot

**Comment by AbdelrahmanAbounida** [comment]
this is what works for me 
```

<YourAppHeader classname="z-10 h-10" />

<Sidebar className="z-1 mt-10" />
```

**Comment by rezaafaisal** [comment]
may you can try this:

`<SidebarInset className="max-w-[calc(100vw-var(--sidebar-width))]">`

 that solve my problem

**Comment by rezaafaisal** [comment]
may you can try this:

`
<SidebarInset className="max-w-[calc(100vw-var(--sidebar-width))] peer-data-[state=collapsed]:max-w-[calc(100vw-var(--sidebar-width-icon))]">
`

 that solve my problem

**Comment by andreivictor** [comment]
I've used `<SidebarInset className="min-w-0" />` and it resolved the layout issue for me.

```tsx
<SidebarProvider>
  <AppSidebar />
  <SidebarInset className="min-w-0">
    ...
  </SidebarInset>
</SidebarProvider>
```

This approach doesn’t break any sticky elements inside, unlike setting overflow-hidden, which can interfere with sticky positioning.

**Comment by Threynaud** [comment]
> I've used `<SidebarInset className="min-w-0" />` and it resolved the layout issue for me.
> 
> ```tsx
> <SidebarProvider>
>   <AppSidebar />
>   <SidebarInset className="min-w-0">
>     ...
>   </SidebarInset>
> </SidebarProvider>
> ```
> 
> This approach doesn’t break any sticky elements inside, unlike setting overflow-hidden, which can interfere with sticky positioning.

Can we please give this man a medal?

**Comment by batuhangulgor** [comment]
> I've used `<SidebarInset className="min-w-0" />` and it resolved the layout issue for me.
> 
> <SidebarProvider>
>   <AppSidebar />
>   <SidebarInset className="min-w-0">
>     ...
>   </SidebarInset>
> </SidebarProvider>
> This approach doesn’t break any sticky elements inside, unlike setting overflow-hidden, which can interfere with sticky positioning.

bro saved my night.

**Comment by EliasGit117** [comment]
@andreivictor you are my savior!
