### ISSUE TITLE
[bug]: npm  error

### ISSUE THREAD

**Issue by Debanjannnn** [shadcn-ui/ui#5555]
### Describe the bug

After NEXT JS 15 shadcn is having issues in installation,  devs please look into this issue
![image](https://github.com/user-attachments/assets/d5a672d5-99c8-4db0-b77c-b7fae8a904e7)

### Affected component/components

its having error in installation

### How to reproduce

1.Install Next.js:  npx create-next-app@latest
2.Navigate to the Project Directory
3.Initialize ShadCN:   npx shadcn@latest init -d
4.Encounter Dependency Conflict:
Error appears due to React version mismatch:
ERESOLVE unable to resolve dependency tree
react@"^16.x || ^17.x || ^18.x" from @radix-ui/react-icons

### Codesandbox/StackBlitz link

https://ui.shadcn.com/docs/installation/next

### Logs

```bash
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: npm install tailwindcss-animate class-variance-authority lucide-react @radix-ui/react-icons clsx tailwind-merge
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: event-ticket@0.1.0
npm error Found: react@19.0.0-rc-69d4b800-20241021
npm error node_modules/react
npm error   react@"19.0.0-rc-69d4b800-20241021" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.x || ^17.x || ^18.x" from @radix-ui/react-icons@1.3.0
npm error node_modules/@radix-ui/react-icons
npm error   @radix-ui/react-icons@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
```

### System Info

```bash
./app/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[3]!./app/globals.css
Error: Cannot find module 'tailwindcss-animate'
Require stack:
- C:\Users\Debanjan Mondal\Desktop\event-ticket\tailwind.config.ts
Import trace for requested module:
./app/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[3]!./app/globals.css
./app/globals.css
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Gitstar-OC** [comment]
I am having the same error, is there a way I can resolve it by using a previous version or something ?

**Comment by hlcxpl** [comment]
me too

**Comment by onehundred** [comment]
@brannonwinn, worked for me as well, thanks!

**Comment by JorgeChibante** [comment]
Not a great workaround but if you choose the default style instead of New York it seems to work.

**Comment by Jorge-Chibante** [comment]
I tried chosing the Default style instead of New York and it worked. If the style is not relevant I guess you can work around it.

**Comment by shadcn** [comment]
I'm working on a fix. Let's use https://github.com/shadcn-ui/ui/issues/5557 to track since they are related.
