### ISSUE TITLE
[bug]: Peer Dependency Conflicts During Initialization and Adding Components with Next.js 15

### ISSUE THREAD

**Issue by Adi-ty** [shadcn-ui/ui#5562]
### Describe the bug

I'm encountering peer dependency conflicts when trying to set up a project with shadcn UI and Next.js (latest v15) as well as when attempting to add components to the project.

Could you please update the initialization and component addition processes to better handle peer dependency issues, especially with React 19 (even in its release candidate state)?

### Affected component/components

All

### How to reproduce

Steps to Reproduce:
1. Init
- Attempt to initialize shadcn UI using the following command:
```bash
npx shadcn@latest init
```
- The setup reaches the dependency installation and fails with the peer dependencies error.
 ***Workaround*** - I was able to complete the initialization by manually running the dependencies installation which were causing error but with `--legacy-peer-deps` .

2. Adding Components
- After resolving the initialization step, I tried adding components using: 
```bash
npx shadcn@latest add 
```
![image](https://github.com/user-attachments/assets/71c12eae-4543-499f-8e16-ca44b2a44111)
- This again failed during dependency installation due to peer dependency conflicts with React 19, producing a similar error:
```bash
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! Found: react@19.0.0-rc-69d4b800-20241021
npm ERR! peer react@"^16.8.0 || ^17 || ^18" from various libraries like react-hook-form, @hookform/resolvers, etc.
```
***Workaround*** - To resolve the issue, I had to downgrade from React 19 (rc) to React 18

The conflicts seem to stem from peer dependencies that expect versions of React from 16.x to 18.x. When using the pre-release React 19, these packages (like react-hook-form, @hookform/resolvers, and others) cause the dependency resolution to fail.

### System Info

```bash
OS: Ubuntu 22.04
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by mazeincoding** [comment]
I have the same issue A workaround is to downgrade React to 18 until they solve the issue. That worked for me.

**Comment by TomasioLT** [comment]
> I have the same issue A workaround is to downgrade React to 18 until they solve the issue. That worked for me.

For me it is also worked, used next js 14 version.

**Comment by shadcn** [comment]
I'm working on a fix. Let's use https://github.com/shadcn-ui/ui/issues/5557 to track since they are related.
