### ISSUE TITLE
[bug]: init and install component failed

### ISSUE THREAD

**Issue by gongsungg** [shadcn-ui/ui#5565]
### Describe the bug

$ npx shadcn@latest init
✔ Preflight checks.
✔ Verifying framework. Found Next.js.
✔ Validating Tailwind CSS.
✔ Validating import alias.

Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

request to https://ui.shadcn.com/r/styles/index.json failed, reason: connect ETIMEDOUT 76.76.21.98:443

### Affected component/components

install

### How to reproduce

My address is not in the United States and I downloaded it through a VPN, but it still doesn’t work.

### Codesandbox/StackBlitz link

1

### System Info

```bash
Windows11 edge
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by imyuanli** [comment]
I also have this problem and am looking forward to a solution. The new cli cannot be downloaded.

**Comment by melikdev** [comment]
Same problem on create-next-app@latest. Tried deleting node_modules and shadcn dependencies from package.json still having errors while initializing shadcn.

**Comment by sofisalmanarif** [comment]
i am also facing this issue i am using linux ubuntu

**Comment by unknowncoder-gamer** [comment]
ya me to having this error in next15 we can hope shadcn team fix it really soon

**Comment by Codenuclei** [comment]
**Prefer manual install wait for devs to upgrade to react 19**

**Comment by arhamkhnz** [comment]
I'm encountering the same problem with Next 14, receiving the message:

```
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

request to https://ui.shadcn.com/r/styles/new-york/avatar.json failed, reason: read ECONNRESET
```

Is there any fix or workaround available?

**Comment by GiancarlosIO** [comment]
same problem here 😢

**Comment by imyuanli** [comment]
> ya me to having this error in next15 we can hope shadcn team fix it really soon

No, I haven't upgraded my NextJS to 15 and still have this issue.

**Comment by imyuanli** [comment]
> Same problem on create-next-app@latest. Tried deleting node_modules and shadcn dependencies from package.json still having errors while initializing shadcn.
> 
> edit: adding npm install `--legacy-peer-deps` solved it for me.

I haven't upgraded my NextJS to 15 and still have this issue

**Comment by shadcn** [comment]
I'm working on a fix. Let's use https://github.com/shadcn-ui/ui/issues/5557 to track since they are related.

**Comment by gongsungg** [comment]
> I'm working on a fix. Let's use #5557 to track since they are related.

But I am not using nextjs15, I am still using next 14.

**Comment by gongsungg** [comment]
I switched the mirror source back to the official one and still got this error.This has been bothering me for many days, and I don't know how to solve it. Manually installing the style will cause problems.
![image](https://github.com/user-attachments/assets/b39184a1-d391-4cae-a1c1-1b416c708cbe)
![image](https://github.com/user-attachments/assets/1b9c6f16-c9a2-42b6-818c-d324f037c57c)
