### ISSUE TITLE
[feat]: side bar transition option

### ISSUE THREAD

**Issue by jinkwon** [shadcn-ui/ui#5576]
### Feature description

The Sidebar currently only supports the `ease-linear` option.  
I hope to be able to customize it with other options, such as `ease-in-out`

### Affected component/components

Sidebar

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by shadcn** [comment]
@jinkwon Swap the `ease-linear` with `east-in-out` in sidebar.tsx. The code is yours. You're encouraged to customize it.
