### ISSUE TITLE
[bug]: create-next-app errors are replaced with generic error message

### ISSUE THREAD

**Issue by Yonom** [shadcn-ui/ui#5585]
### Describe the bug

When triggering a new project via the shadcn CLI (running it in a folder without package.json), the create-next-app CLI errors are not displayed to the user (e.g. project name can only contain lower case letters)

### Affected component/components

npx shadcn

### How to reproduce

npx create-next-app AAAA
> Could not create a project called "AAAA" because of npm naming restrictions:
>    * name can no longer contain capital letters

npx shadcn@latest add button   
> ✔ The path / does not contain a package.json file. Would you like to start a new Next.js project? … yes
> ✔ What is your project named? … AAAA
> ⠼ Creating a new Next.js project. This may take a few minutes.
> Something went wrong creating a new Next.js project. Please try again.

### System Info

```bash
-
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by shadcn** [comment]
I'm working on a fix. Let's use https://github.com/shadcn-ui/ui/issues/5557 to track since they are related.
