### ISSUE TITLE
[bug]: Pointers-event in the body doesn't change after close the dialog

### ISSUE THREAD

**Issue by Ross249** [shadcn-ui/ui#5586]
### Describe the bug

While closing the dialog after changing states inside the dialog, the ```pointers-event:none``` in the body wasn't change and it prevent any clicks on the page.

### Affected component/components

Dialog

### How to reproduce

1. Go to Dialog while some states changing in the Dialog
2. Click outside to close the dialog
3. Check the ```pointers-event:none``` in the ```body``` tag.

### System Info

```bash
MacOS 14.4
Chrome 129.0.6668.70
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Lexachoc** [comment]
Without a test case link, it's hard to say. Perhaps you can try to prevent clicking event outside of it and use the controlled dialog.

something like
```
onInteractOutside={(e) => {
    e.preventDefault()
    setOpen(false)
}}
```

See: https://www.radix-ui.com/primitives/docs/components/dialog#content

**Comment by Ross249** [comment]
> Without a test case link, it's hard to say. Perhaps you can try to prevent clicking event outside of it and use the controlled dialog.
> 
> something like
> 
> ```
> onInteractOutside={(e) => {
>     e.preventDefault()
>     setOpen(false)
> }}
> ```
> 
> See: https://www.radix-ui.com/primitives/docs/components/dialog#content

I tried, but it doesn't work. I am trying to extract a minimal demo to display this problem.

**Comment by Agrim9841** [comment]
How did you fix this?

**Comment by MarcaiQuadras** [comment]
In my case I have a Dialog and a Drawer component controlled by its states.

I trigger a function that set 2 states to false in order to close the dialog and the drawer. 

When I do this the components close normally, but for some reason the property "pointer-events: none" didn't desapear from the body.

My solution was set a 300ms timeout in the dialog setter. ( I think it can be less then 300ms )

**Comment by bojonvi** [comment]
Thanks @MarcaiQuadras , I was able to make a work around with this implementation 😅

```ts
 const handleClose = () => {
    alertDialog.close();
    setTimeout(() => {
      document.body.style.pointerEvents = "auto";
    }, 500);
  };
```
