### ISSUE TITLE
[bug]: SidebarMenuButton Tooltip hidden

### ISSUE THREAD

**Issue by bllakcn** [shadcn-ui/ui#5619]
### Describe the bug

The `hidden` logic in the `TooltipContent` has a little bug.

I believe this is how it is supposed to be.
``` jsx
return (
  <Tooltip>
    <TooltipTrigger asChild>{button}</TooltipTrigger>
      <TooltipContent
	  side='right'
	  align='center'
	  hidden={state === 'collapsed' || isMobile}
	  {...tooltip}
    />
</Tooltip>
);
```

### Affected component/components

Sidebar

### How to reproduce

1. Add a tooltip for a `SidebarMenuButton`
2. Try to hover and trigger the tooltip

### System Info

```bash
Mac 15.0.1
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by shadcn** [comment]
hmm `state === 'collapsed'` will hide the tooltip when collapsed. we want it to show on collapsed. wdyt?

**Comment by bllakcn** [comment]
You are right. I haven't really thought this scenario through it seems, but now we don't get to show a tooltip in the `expanded` state, which was what i originally wanted to do.

Though that may not be implemented frequently. So feel free to close the issue. 🙏
