### ISSUE TITLE
[bug]: Broken link 

### ISSUE THREAD

**Issue by VibingCreator** [shadcn-ui/ui#5631]
### Describe the bug

https://ui.shadcn.com/docs/installation/next

`If you're using Next.js 15, see the [Next.js 15 + React 19](https://ui.shadcn.com/docs/installation/react-19) guide. `

It should be https://ui.shadcn.com/docs/react-19

### Affected component/components

-

### How to reproduce

-

### Logs

```bash
-
```

### System Info

```bash
-
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by techmaou** [comment]
i'm working on this issue. i'll submit a PR soon.

**Comment by grzegorzpokorski** [comment]
https://github.com/shadcn-ui/ui/pull/5633

**Comment by techmaou** [comment]
this is my first time contributing, so i picked rather simple one. do tell me if i make a mistake.

**Comment by shadcn** [comment]
This is fixed now. Thanks @techmaou
