### ISSUE TITLE
[bug]: A dependency doesn't support Next 15 or React 19

### ISSUE THREAD

**Issue by jefer94** [shadcn-ui/ui#5637]
### Describe the bug

https://github.com/radix-ui/icons/issues/190

### Affected component/components

toast,radio-group,pagination,navigation-menu,drowdown-menu,dialog,command,

### How to reproduce

1. upgrade to Next 15
2. run npm install

For Codesandbox link, run `npm add @radix-ui/react-icons`

### Codesandbox/StackBlitz link

https://codesandbox.io/p/devbox/busy-breeze-go8s7s

### Logs

```bash
npm error Could not resolve dependency:
npm error peer react@"^16.x || ^17.x || ^18.x" from @radix-ui/react-icons@1.3.0
npm error node_modules/@radix-ui/react-icons
npm error   @radix-ui/react-icons@"^1.3.0" from the root project
```

### System Info

```bash
Linux subsystem for Windows, Archlimux
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by shadcn** [comment]
@jefer94 Does the following help? https://ui.shadcn.com/docs/react-19#using-npm

**Comment by shadcn** [comment]
@jefer94 We now have a new release of `@radix-ui/react-icons` which should've fixed this issue. Please reopen if not. thank you.

**Comment by jefer94** [comment]
Running force install is a terrible idea, even knowing that this installation works, I'm installing that in production, and you will produce a lot of issues in production environment in future by being lazy
