### ISSUE TITLE
[bug]: Module not found: Can't resolve '@radix-ui/react-avatar'

### ISSUE THREAD

**Issue by Boby900** [shadcn-ui/ui#5641]
### Describe the bug

I have added an Avatar component using `bunx --bun shadcn@latest add avatar`.
It was working fine some time ago, I was able to look at the Shadcn's face but now it's throwing an error, PFA.
this module from the `@radix-ui/react-avatar` is not showing up in my package.json, at the time when I had installed the Avatar component. PFA.

![Screenshot (692)](https://github.com/user-attachments/assets/2d284280-be9e-46bf-a98e-274fba0b8208)

### Affected component/components

Avatar

### How to reproduce

 `bunx --bun shadcn@latest add avatar`.

### System Info

```bash
Windows 10, Chromium, Node 21, Next.js 15,
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by shadcn** [comment]
hmm could the dependency have been removed somehow? check git?

can you reinstall please? `bun add @radix-ui/react-avatar`

**Comment by Boby900** [comment]
> hmm could the dependency have been removed somehow? check git?
> 
> can you reinstall please? `bun add @radix-ui/react-avatar`

reinstalling fixed it, `bun add @radix-ui/react-avatar`
thanks for your help

**Comment by waxidiotic** [comment]
FYI, this just happened to me too. The Avatar was working fine until I installed your form component which doesn't make much sense. Not a huge deal since I just added it but it is weird.
