### ISSUE TITLE
[help wanted]: Unable to control multiple sidebars within one Sidebar provider

### ISSUE THREAD

**Issue by JolomiTee** [shadcn-ui/ui#5651]
### Describe the bug

I would like to have 2 or 3 sidebars within my project using the shadcn-ui sidebar component. Firstly, its possible to display them as they should look, for example:

![1](https://github.com/user-attachments/assets/f84d1811-2aed-42c2-81f9-d584abfaa410)

What i discovered is that only one Sidebar provider can be used to display the sidebars, i have tried using multiple Sidebar providers for each sidebar but they all return a weird space on the page, but i wont show that right now. What I need help with is this: here is my code with nothing much going on, only displaying the sidebars in the positions I want them.

![carbon](https://github.com/user-attachments/assets/71939255-1c50-430c-bef5-ecc877991cda)

I want to be able to toggle the open states of each sidebar individually, but that is not working. for context, if i set the collapsible for all of them to "icon", they will all collapse into the icon state on the click of a single trigger found within the `SidebarProvider`

![image](https://github.com/user-att

### Affected component/components

Sidebar, SidebarProvider

### How to reproduce

Copy and paste this basic component:

```
import {
	Sidebar,
	SidebarHeader,
	SidebarInset,
	SidebarMenu,
	SidebarMenuButton,
	SidebarMenuItem,
	SidebarProvider,
	SidebarTrigger,
} from "../components/ui/sidebar";
import { Command } from "lucide-react";
import { Separator } from "../components/ui/separator";

const Sandbox = () => {
	return (
		<SidebarProvider>
			{/* sidebar 1 */}
			<Collapsible />

			{/* sidebar 2 */}
			<Channels />

			<SidebarInset>
				<header className="sticky top-0 flex shrink-0 items-center gap-2 border-b bg-background p-4">
					{/* toggle the Collapsible */}
					<button>Co</button>
					<Separator orientation="vertical" className="mr-2 h-4" />
					{/* toggle the Channels */}
					<button>Ch</button>
					<Separator orientation="vertical" className="mr-2 h-4" />
					{/* toggle the Right */}
					<button>R</button>
					<SidebarTrigger className="-ml-1" />
				</header>

				<div className="flex">
					<div className="flex flex-1 flex-col gap-4 p-4">
						{Array.from({ length: 10 }).map((_, index) => (
							<div
								key={index}
								className="aspect-video h-12 w-full bg-purple-400 rounded-lg bg-muted/50"
							/>
						))}
					</div>

					{/* sidebar 3 */}
					<Right />
				</div>
			</SidebarInset>
		</SidebarProvider>
	);
};

export default Sandbox;

const Collapsible = () => {
	return (
		<Sidebar collapsible="icon" className="border-r bg-blue-600 z-50">
			<SidebarTrigger />
			<SidebarHeader>
				<SidebarMenu>
					<SidebarMenuItem>
						<SidebarMenuButton
							size="lg"
							asChild
							className="md:h-8 md:p-0"
						>
							<a href="#">
								<div className="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
									<Command className="size-4" />
								</div>
								<div className="grid flex-1 text-left text-sm leading-tight">
									<span className="truncate font-semibold">
										Acme Inc
									</span>
									<span className="truncate text-xs">
										Collapsible Sidebar
									</span>
								</div>
							</a>
						</SidebarMenuButton>
					</SidebarMenuItem>
				</SidebarMenu>
			</SidebarHeader>
		</Sidebar>
	);
};

const Channels = () => {
	return (
		<Sidebar collapsible="icon" className="border-r bg-red-400">
			<SidebarHeader>
				<SidebarMenu>
					<SidebarMenuItem>
						<SidebarMenuButton
							size="lg"
							asChild
							className="md:h-8 md:p-0"
						>
							<a href="#">
								<div className="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
									<Command className="size-4" />
								</div>
								<div className="grid flex-1 text-left text-sm leading-tight">
									<span className="truncate font-semibold">
										Acme Inc
									</span>
									<span className="truncate text-xs">
										Channels Sidebar
									</span>
								</div>
							</a>
						</SidebarMenuButton>
					</SidebarMenuItem>
				</SidebarMenu>
			</SidebarHeader>
		</Sidebar>
	);
};

const Right = () => {
	return (
		<Sidebar
			collapsible="icon"
			side="right"
			className="border-l bg-green-400"
		>
			<SidebarHeader>
				<SidebarMenu>
					<SidebarMenuItem>
						<SidebarMenuButton
							size="lg"
							asChild
							className="md:h-8 md:p-0"
						>
							<a href="#">
								<div className="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
									<Command className="size-4" />
								</div>
								<div className="grid flex-1 text-left text-sm leading-tight">
									<span className="truncate font-semibold">
										Acme Inc
									</span>
									<span className="truncate text-xs">
										Right Sidebar
									</span>
								</div>
							</a>
						</SidebarMenuButton>
					</SidebarMenuItem>
				</SidebarMenu>
			</SidebarHeader>
		</Sidebar>
	);
};

```

### System Info

```bash
OS: Linux Mint 22
Browser: Microsoft Edge Browser
React Version: 19
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Jomo178** [comment]
Hi @JolomiTee, did you find anything on this problem? I have the same problem as you. If I open one sidebar the other one gets opened too.

**Comment by JolomiTee** [comment]
@Jomo178 the only way I know of is to have a `SidebarProvider` wrapped around each individual sidebar instead of the whole App. Doing that, you can set individual widths, collapsible state too and most of all, control them individually.
The only downside I have seen with this is that it takes away the mobile responsiveness of the sidebar... Whereby the `Sheet component` doesn't come out anymore. 
This might be due to my many tweakings of the `sidebar.tsx` file which I had to do to get what I wanted to achieve.

**Comment by Jacksonmills** [comment]
Another option is to track each sidebar via an id on the provider and then you can track/toggle specific matching sidebars/toggles

You would need to make the state a bit more complex but it's definitely doable

**Comment by Jomo178** [comment]
@Jacksonmills you're right! The sidebar state is safed via cookies. So just change the SidebarProvider to take a custom name and you can controll them one by one. Change the setOpen so open via the custom name and not the setted cookie name. Hope this helps. @JolomiTee 

```
const SidebarProvider = React.forwardRef<
  HTMLDivElement,
  React.ComponentProps<"div"> & {
    defaultOpen?: boolean;
    open?: boolean;
    onOpenChange?: (open: boolean) => void;
    name: string;
  }
>(
  (
    {
      defaultOpen = true,
      open: openProp,
      onOpenChange: setOpenProp,
      className,
      style,
      children,
      name,
      ...props
    },
    ref
  ) => {
    const isMobile = useIsMobile();
    const [openMobile, setOpenMobile] = React.useState(false);

    // This is the internal state of the sidebar.
    // We use openProp and setOpenProp for control from outside the component.
    const [_open, _setOpen] = React.useState(() => {
      const cookieValue = document.cookie
        .split("; ")
        .find((row) => row.startsWith(`${name}:state=`))
        ?.split("=")[1];
      return cookieValue === "true" ? true : defaultOpen;
    });
    const open = openProp ?? _open;
    const setOpen = React.useCallback(
      (value: boolean | ((value: boolean) => boolean)) => {
        const openState = typeof value === "function" ? value(open) : value;
        if (setOpenProp) {
          setOpenProp(openState);
        } else {
          _setOpen(openState);
        }

        // This sets the cookie to keep the sidebar state.
        document.cookie = `${name}:state=${openState}; path=/; max-age=${SIDEBAR_COOKIE_MAX_AGE}`;
      },
      [setOpenProp, open, name]
    );

//Rest of the sidebar code..


//Example
 <SidebarProvider name="YOURE SIDEBAR NAME">
        <Sidebar variant="floating" collapsible="icon" side="right">
          <SidebarContent>
          </SidebarContent>
       </Sidebar>
</SidebarProvider>

**Comment by JolomiTee** [comment]
Thanks, @Jomo178 and @Jacksonmills, I will try it out and get back as soon as i can

**Comment by JolomiTee** [comment]
@Jomo178 @Jacksonmills 
I was able to adjust mine with the solution @Jomo178 implemented.

So from the screenshot below, I have wrapped each sidebar with the Provider, passed unique names to each, and then put the `SidebarTrigger` within the `Sidebar` and with that, each one is isolated and controlled individually

![Screenshot from 2024-11-03 22-11-01](https://github.com/user-attachments/assets/5c034e16-f47a-4173-8d32-bbefefbb6a62)
 
![image](https://github.com/user-attachments/assets/eba024c1-c114-4be6-b24b-d0ab583ba4ab)

What I want to test out now is how it works on mobile... because right now, it all disappears.. likely into the sheet form, waiting to be triggered and there is no way to trigger it yet with my current UI :)

**Comment by atmnksd** [comment]
can you post sample code for this which is working. my two leftside sidebars overlap.

**Comment by JolomiTee** [comment]
@atmnksd here is a [Stackblitz](https://stackblitz.com/edit/vitejs-vite-uq1vzr?file=src%2FApp.tsx) link containing my implementation.

The key takeaways here are these:

1. The `ui/sidebar.tsx` file has been modified in some parts. The important part is the one given by @Jomo178 regarding setting cookie names

> @Jacksonmills, you're right! The sidebar state is safe via cookies. So just change the SidebarProvider to take a custom name and you can control them one by one. Change the setOpen so open via the custom name and not the setted cookie name. Hope this helps. @JolomiTee
> 
> ```
> const SidebarProvider = React.forwardRef<
>   HTMLDivElement,
>   React.ComponentProps<"div"> & {
>     defaultOpen?: boolean;
>     open?: boolean;
>     onOpenChange?: (open: boolean) => void;
>     name: string;
>   }
> >(
>   (
>     {
>       defaultOpen = true,
> : openProp,
>       onOpenChange: setOpenProp,
>       className,
>       style,
>       children,
>       name,
>       ...props
>     },
>     ref
>   ) => {
>     const isMobile = useIsMobile();
>     const [openMobile, setOpenMobile] = React.useState(false);
> 
>     // This is the internal state of the sidebar.
>     // We use openProp and setOpenProp for control from outside the component.
>     const [_open, _setOpen] = React.useState(() => {
>       const cookieValue = document.cookie
>       .split("; ")
>        .find((row)=> row.startsWith(`${name}:state=`))
>         ?.split("=")[1];
>       return cookieValue === "true" ? true : defaultOpen;
>     });
>     const open = openProp ?? _open;
>     const setOpen = React.useCallback(
>       (value: boolean | ((value: boolean) => boolean)) => {
>         const openState = typeof value === "function" ? value(open) : value;
>         if (setOpenProp) {
>           setOpenProp(openState);
>        } else {
>           _setOpen(openState);
>         }
> 
>         // This sets the cookie to keep the sidebar state.
>         document.cookie = `${name}:state=${openState}; path=/; max-age=${SIDEBAR_COOKIE_MAX_AGE}`;
>       },
>       [setOpenProp, open, name]
>     );
> 
> Rest of the sidebar code.
> 
> 
> //Example
>  <SidebarProvider name="YOURE SIDEBAR NAME">
>         <Sidebar variant="floating" collapsible="icon" side="right">
>           <SidebarContent>
>           </SidebarContent>
>        </Sidebar>
> </SidebarProvider>
> ```

2. I have seen that to control each sidebar individually, you have to have each one within its own `SidebarProvider`.
3. To control the toggle state of the sidebar both on mobile and desktop, you have to make sure the `toggleSidebar` hook is called within the `SidebarProvider` which, for the sake of knowing what I'm doing, splits the providers and the sidebars into different components.

So there you have it, feel free to modify the code to your liking, this is what worked for me in my local sandbox testing

**Comment by Jomo178** [comment]
> Even though I can control these separate sidebars, I still have the weird spacing issue if I use 2 `SidebarProvider` together. If someone has a fix please let me know.

Hi @DevanceJ, could you provide me an example or a snippet of your code?

**Comment by NickWoodward** [comment]
> @Jomo178 @Jacksonmills I was able to adjust mine with the solution @Jomo178 implemented.
> 
> So from the screenshot below, I have wrapped each sidebar with the Provider, passed unique names to each, and then put the `SidebarTrigger` within the `Sidebar` and with that, each one is isolated and controlled individually
> 
> ![Screenshot from 2024-11-03 22-11-01](https://private-user-images.githubusercontent.com/83990965/382605437-5c034e16-f47a-4173-8d32-bbefefbb6a62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2OTM2MDgsIm5iZiI6MTczMzY5MzMwOCwicGF0aCI6Ii84Mzk5MDk2NS8zODI2MDU0MzctNWMwMzRlMTYtZjQ3YS00MTczLThkMzItYmJlZmVmYmI2YTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDIxMjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMWZhMDYzNzU3NDNiMGI2NDA2MDJjM2NkM2FiYzJkMTBhYmQwYzBhY2NmYmE5Yjg1NmNlZWFlM2IwN2Y5OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qA17s5TQxyhNJ5C3Sg93pD_koycvOSs-h21lZz3BDus)
> 
> ![image](https://private-user-images.githubusercontent.com/83990965/382605561-eba024c1-c114-4be6-b24b-d0ab583ba4ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2OTM2MDgsIm5iZiI6MTczMzY5MzMwOCwicGF0aCI6Ii84Mzk5MDk2NS8zODI2MDU1NjEtZWJhMDI0YzEtYzExNC00YmU2LWIyNGItZDBhYjU4M2JhNGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDIxMjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNTBmODBiNjUwMDA4ZTVjMDhiOGU4Yjk3ZGQ5NjY4ZGIyMDlmOTYwOTZkMGU3M2U2ZWY3MjNjNmI4Y2Q3ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AeQ3bknSjS8JFHT1CYbdqmAKlMoTC9QkXo54b2M2ldM)
> 
> What I want to test out now is how it works on mobile... because right now, it all disappears.. likely into the sheet form, waiting to be triggered and there is no way to trigger it yet with my current UI :)

thanks for these posts @Jomo178 & @JolomiTee 

just a quick question - doesn't this stackblitz have a bug? (not setting the cookie if the state is externally controlled)

really appreciate the help though, i wouldn't have got to this!

**Comment by NickWoodward** [comment]
> Even though I can control these separate sidebars, I still have the weird spacing issue if I use 2 `SidebarProvider` together. If someone has a fix please let me know.

I think it's the sidebar triggers. If you put them in the actual sidebar and absolutely position them you won't have the issue. Or at least that worked for me

**Comment by NickWoodward** [comment]
> 3\. sidebar both on mobile and desktop, you have to make sure the `toggleSidebar` hook is called within the `SidebarProvider` which, for the sake of knowing what I'm doing, splits the p

Hi JolomiTee,

I'm just having a bit of a play with your stackblitz demo (thanks!) and was just wondering - how are you getting the right hand sidebar to close to the right? It seems like it's based on the content in the component to the left? (ie if you remove that content, the sidebar no longer sticks to the right hand side?)

I'm basically just trying to have 2 sidebars, one on the left, one on the right, and have the content in the middle move out of the way of each menu. But it's proving difficult! (open and close states are all fine though thanks :))

If you get a sec I'd really appreciate any help you can give!

Thanks,

Nick

**Comment by JolomiTee** [comment]
Hey @NickWoodward, the right sidebar closes to the right because there is a direction based prop passed to the sidebar that defines the direction the sidebar closes into which is the `side="right"` passed to the `Sidebar` component. I think it default to left.

**Comment by NickWoodward** [comment]
> Hey @NickWoodward, the right sidebar closes to the right because there is a direction based prop passed to the sidebar that defines the direction the sidebar closes into which is the `side="right"` passed to the `Sidebar` component. I think it default to left.

haha, can't believe i missed that - have been using it in my demos all day but just didn't see it in your code. thanks a lot!

**Comment by JolomiTee** [comment]
> > Hey @NickWoodward, the right sidebar closes to the right because there is a direction based prop passed to the sidebar that defines the direction the sidebar closes into which is the `side="right"` passed to the `Sidebar` component. I think it default to left.
> 
> haha, can't believe i missed that - have been using it in my demos all day but just didn't see it in your code. thanks a lot!
You're welcome @NickWoodward

**Comment by tillka** [comment]
Just stumbled upon this thread, as I had the same issues. 

Thanks @JolomiTee,  your stackblitz brought me on the right track. I did get an "document is not defined" error though, pointing to the one within the useState. I fixed it as follows, if anyone has the same error: 

```tsx
const [_open, _setOpen] = React.useState(true)
```

```ts 
React.useEffect(() => {
      const cookieValue = document.cookie
        .split("; ")
        .find((row) => row.startsWith(`${name}:state=`))
        ?.split("=")[1]
      _setOpen(cookieValue === "true" ? true : defaultOpen)
    }, [defaultOpen, name])
```

> Even though I can control these separate sidebars, I still have the weird spacing issue if I use 2 `SidebarProvider` together. If someone has a fix please let me know.

@DevanceJ I had the same issue and it worked finally when I removed 'w-full' from some elements in the tree, including the <main> element within the SidebarInset. Don't know why that is the case though.

**Comment by DevanceJ** [comment]
Hi everyone, thank you for all these comments. I wanted to share this earlier but was busy with some projects. 
So I was able to have a two sidebar support using a single Sidebar provider but had to make some changes in the sidebar.tsx. Here you can see the entire file and how I used it.
edited shadcn's sidebar -> https://github.com/DevanceJ/echo/blob/main/components/ui/multisidebar.tsx
Usage -> https://github.com/DevanceJ/echo/blob/main/app/echo/layout.tsx
Left sidebar -> https://github.com/DevanceJ/echo/blob/main/components/sidebar/app-sidebar.tsx
Right sidebar -> https://github.com/DevanceJ/echo/blob/main/components/sidebar/queue-sidebar.tsx

Would've loved to explain this in much detail but again pretty busy these days. Changes are pretty clear and seem redundant but this works well.

Anyways you can check the whole project on my profile. Let me know if you have any doubts

**Comment by DevanceJ** [comment]
PS: You can use this code ❤️

**Comment by heymartinadams** [comment]
@DevanceJ that’s incredible. Wow. Just what I needed! Thank you! 🥳  Used it in OneTask.me

**Comment by DevanceJ** [comment]
You're welcome @heymartinadams I'm glad this helped.
Wishing you all the best with OneTask.me—great name! Would love to try it out

**Comment by JolomiTee** [comment]
> Just stumbled upon this thread, as I had the same issues. 
> 
> Thanks @JolomiTee,  your stackblitz brought me on the right track. I did get an "document is not defined" error though, pointing to the one within the useState. I fixed it as follows, if anyone has the same error: 
> 
> ```tsx
> const [_open, _setOpen] = React.useState(true)
> ```
> 
> ```ts 
> React.useEffect(() => {
>       const cookieValue = document.cookie
>         .split("; ")
>         .find((row) => row.startsWith(`${name}:state=`))
>         ?.split("=")[1]
>       _setOpen(cookieValue === "true" ? true : defaultOpen)
>     }, [defaultOpen, name])
> ```
> 
> > Even though I can control these separate sidebars, I still have the weird spacing issue if I use 2 `SidebarProvider` together. If someone has a fix please let me know.
> 
> @DevanceJ I had the same issue and it worked finally when I removed 'w-full' from some elements in the tree, including the <main> element within the SidebarInset. Don't know why that is the case though. 

You're welcome @tillka

**Comment by JolomiTee** [comment]
> Hi everyone, thank you for all these comments. I wanted to share this earlier but was busy with some projects. 
> So I was able to have a two sidebar support using a single Sidebar provider but had to make some changes in the sidebar.tsx. Here you can see the entire file and how I used it.
> edited shadcn's sidebar -> https://github.com/DevanceJ/echo/blob/main/components/ui/multisidebar.tsx
> Usage -> https://github.com/DevanceJ/echo/blob/main/app/echo/layout.tsx
> Left sidebar -> https://github.com/DevanceJ/echo/blob/main/components/sidebar/app-sidebar.tsx
> Right sidebar -> https://github.com/DevanceJ/echo/blob/main/components/sidebar/queue-sidebar.tsx
> 
> Would've loved to explain this in much detail but again pretty busy these days. Changes are pretty clear and seem redundant but this works well.
> 
> Anyways you can check the whole project on my profile. Let me know if you have any doubts

Very nice @DevanceJ 
Thank you

**Comment by JolomiTee** [comment]
> @DevanceJ that’s incredible. Wow. Just what I needed! Thank you! 🥳  Used it in [OneTask.me](https://onetask.me) — happy to gift you a lifetime.

This is lovely

**Comment by JosiMou** [comment]
> Hi everyone, thank you for all these comments. I wanted to share this earlier but was busy with some projects. So I was able to have a two sidebar support using a single Sidebar provider but had to make some changes in the sidebar.tsx. Here you can see the entire file and how I used it. edited shadcn's sidebar -> https://github.com/DevanceJ/echo/blob/main/components/ui/multisidebar.tsx Usage -> https://github.com/DevanceJ/echo/blob/main/app/echo/layout.tsx Left sidebar -> https://github.com/DevanceJ/echo/blob/main/components/sidebar/app-sidebar.tsx Right sidebar -> https://github.com/DevanceJ/echo/blob/main/components/sidebar/queue-sidebar.tsx
> 
> Would've loved to explain this in much detail but again pretty busy these days. Changes are pretty clear and seem redundant but this works well.
> 
> Anyways you can check the whole project on my profile. Let me know if you have any doubts

this is amazing

**Comment by heymartinadams** [comment]
> You're welcome @heymartinadams I'm glad this helped. Wishing you all the best with OneTask.me—great name! Would love to try it out

@DevanceJ message me in-app and I’ll upgrade your account!

**Comment by ercnshngit** [comment]
I had same issue so i edited the sidebar.tsx minimally.

https://gist.github.com/ercnshngit/e1510e966860e04e47d752d16be3cbc1/revisions

I preferred using a single provider instead of multiple providers to prevent layout shifts. The style added inside the provider configures the overall layout.

Usage:
```typescript
function DashboardLayout() {
  return (
    <SidebarProvider
      sidebarNames={["main-sidebar", "second-sidebar", "right-sidebar"]}
      style={
        {
          "--sidebar-width": "18rem",
        } as React.CSSProperties
      }
    >
      <AppSidebar name="main-sidebar" />
      <SidebarInset>
        <SidebarTrigger name="main-sidebar" />
        <SidebarTrigger name="second-sidebar" />
        <SidebarTrigger name="right-sidebar" />
      </SidebarInset>
      <SidebarRight
        name="right-sidebar"
        style={
          {
            "--sidebar-width": "18rem",
          } as React.CSSProperties
        }
      />
    </SidebarProvider>
  )
}
```

**Comment by hitecSmartHome** [comment]
> I had same issue so i edited the sidebar.tsx minimally.
> 
> https://gist.github.com/ercnshngit/e1510e966860e04e47d752d16be3cbc1/revisions
> 
> I preferred using a single provider instead of multiple providers to prevent layout shifts. The style added inside the provider configures the overall layout.

I have weird layout issues with this for some reason

**Comment by hitecSmartHome** [comment]
It is working on mobile but the main div is full width and is under the sidebars

**Comment by nickzelei** [comment]
I tried @ercnshngit 's but like @hitecSmartHome mentioned the styling was a bit wonky. This was due to some changes in the shadcn sidebar since them I believe.

I took the spirit of their changes and did it myself on the latest (I think I might have slightly edited it but it's by and large the default shadcn sidebar component).

I improved it a little by making the context keyed off of the name as opposed to having lists of all of the state. I also made it typesafe to the caller by making names `T[]`. This way after you define the `sidebarNames`, the other options like `defaultOpen` are now typesafe.

I also included a new `keyboardShortcuts` prop to allow for each sidebar to have its own letter as in the original component they were all bound to the same one.

Hope this helps some folks and appreciate all of the other's replies and variants.

https://gist.github.com/nickzelei/b6f016a971740863bb75f39eb6f91a9e

**Comment by BAHAA-THE-KING** [comment]
Why limit yourself to just one provider ?
I duplicated it and made a few changes, it works perfectly for me :)

**Comment by Grigore147** [comment]
Hi there,

Could someone please share a fully working example with a double sidebar?

I’m trying to achieve something similar to [this example](https://ui.shadcn.com/blocks/sidebar?utm_source=chatgpt.com#sidebar-09), but with the first sidebar being collapsible as well. I’ve run into some overlapping issues and other problems while experimenting with different approaches.

Any support would be greatly appreciated!

**Comment by inj-src** [comment]
# Sidebar Manager Pattern

A pattern for managing multiple sidebars from anywhere in your application. Find the code [here](https://gist.github.com/inj-src/033178f989199dc74ddfc4341f4b0ff6)

## Overview

The Sidebar Manager provides a way to register, track, and control multiple sidebars with unique names. This is particularly useful when:

- You have multiple sidebars that need to be controlled from different parts of the app
- You want to toggle a sidebar from a component that isn't a direct child of that sidebar's `SidebarProvider`
- You need coordinated control over multiple sidebars (e.g., close one when opening another)

## Components

| Component | Description |
|-----------|-------------|
| `SidebarManagerProvider` | Top-level provider that holds the registry of all sidebars |
| `SidebarManager` | Registers a sidebar with a unique name |
| `SidebarManagerTrigger` | A button to toggle a sidebar by name from anywhere |
| `useSidebarManager()` | Hook to access the sidebar registry |

## Basic Usage

### 1. Wrap your app with `SidebarManagerProvider`

```tsx
import {
  SidebarManagerProvider,
  SidebarProvider,
  SidebarManager,
  SidebarInset,
  Sidebar,
} from "@/components/ui/sidebar";

function App() {
  return (
    <SidebarManagerProvider>
      {/* Your sidebars go here */}
    </SidebarManagerProvider>
  );
}
```

### 2. Register each sidebar with a unique name

Each sidebar needs its own `SidebarProvider` and a `SidebarManager` with a unique `name`:

```tsx
<SidebarManagerProvider>
  <SidebarProvider>
    <SidebarManager name="left">
      <Sidebar side="left">
        {/* Left sidebar content */}
      </Sidebar>
    </SidebarManager>

    <SidebarInset>
      {/* Main content */}
    </SidebarInset>
  </SidebarProvider>
</SidebarManagerProvider>
```

### 3. Control sidebars from anywhere

**Using `SidebarManagerTrigger`:**

```tsx
import { SidebarManagerTrigger } from "@/components/ui/sidebar";

function Header() {
  return (
    <header>
      <SidebarManagerTrigger name="left" />
      <SidebarManagerTrigger name="right" />
    </header>
  );
}
```

**Using the `useSidebarManager` hook:**

```tsx
import { useSidebarManager } from "@/components/ui/sidebar";

function MyComponent() {
  const manager = useSidebarManager();
  const leftSidebar = manager.use("left");
  const rightSidebar = manager.use("right");

  return (
    <div>
      <button onClick={() => leftSidebar?.toggleSidebar()}>
        Toggle Left
      </button>
      <button onClick={() => rightSidebar?.setOpen(false)}>
        Close Right
      </button>
      <span>Left is {leftSidebar?.open ? "open" : "closed"}</span>
    </div>
  );
}
```

## Left and Right Sidebars

A common layout with a left sidebar, main content, and a right sidebar:



<img width="1920" height="976" alt="Image" src="https://github.com/user-attachments/assets/41aef16c-315c-439b-8d7d-1d7e7a1424fb" />

Code:

```tsx
<SidebarManagerProvider>
  <SidebarProvider>
    {/* Left sidebar */}
    <SidebarManager name="left">
      <Sidebar side="left">
        <SidebarContent>Left sidebar</SidebarContent>
      </Sidebar>
    </SidebarManager>

    <SidebarInset>
      {/* Nest another SidebarProvider for the right sidebar */}
      <SidebarProvider>

        {/* Main content in the middle */}
        <SidebarInset>
          <main>Middle content</main>
        </SidebarInset>

        {/* Right sidebar */}
        <SidebarManager name="right">
          <Sidebar side="right">
            <SidebarContent>Right sidebar</SidebarContent>
          </Sidebar>
        </SidebarManager>

      </SidebarProvider>
    </SidebarInset>
  </SidebarProvider>
</SidebarManagerProvider>
```

**Key points:**
- The outer `SidebarProvider` handles the left sidebar
- The inner `SidebarProvider` (inside `SidebarInset`) handles the right sidebar
- `SidebarInset` comes **before** the right `Sidebar` so content appears in the middle


### Why Nesting Works

- Each `SidebarProvider` creates its own context
- Each `SidebarInset` is the "main content" area for its parent sidebar
- The nested sidebar appears inside the outer `SidebarInset`, so it flows beside the first sidebar

## Multiple Side-by-Side Sidebars:


<img width="1920" height="976" alt="Image" src="https://github.com/user-attachments/assets/dd583eb7-7f72-4e03-ae87-e74caa2e3014" />



To have multiple sidebars stacked horizontally (e.g., two sidebars on the left), nest your `SidebarProvider` components:

```tsx
<SidebarManagerProvider>
  {/* First sidebar (fixed positioning, anchored to viewport) */}
  <SidebarProvider>
    <SidebarManager name="left">
      <Sidebar side="left">
        <SidebarContent>First Sidebar</SidebarContent>
      </Sidebar>
    </SidebarManager>

    <SidebarInset>
      {/* Second sidebar (relative to first sidebar's inset) */}
      <SidebarProvider>
        <SidebarManager name="second">
          <Sidebar side="left">
            <SidebarContent>Second Sidebar</SidebarContent>
          </Sidebar>
        </SidebarManager>

        <SidebarInset>
          {/* Main content area */}
          <main>Your content here</main>
        </SidebarInset>
      </SidebarProvider>
    </SidebarInset>
  </SidebarProvider>
</SidebarManagerProvider>
```

### Important: Positioning

The shadcn/ui sidebar component uses `position: fixed` to anchor the sidebar to the viewport. This works correctly when: With the `[Left Sidebar] [Main Content] [Right Sidebar]` layout. 

But when using this side-by-side Sidebars you have to use `position: absolute` otherwise the layout will be broken.

Swapping `position: fixed` with `position: absolute` might cause body scrolling of the sidebars. To avoid scrolling the sidebars with the main content you can wrap the main content with `ScrollArea`.

Like this:

```tsx
<SidebarInset>
  <ScrollArea className="h-screen">
    <main>Your content here</main>
  </ScrollArea>
</SidebarInset>
```

If you need truly fixed sidebars that stay visible during scroll, you may need to adjust the positioning strategy.

## API Reference

### `SidebarManagerProvider`

Top-level provider for the sidebar registry.

```tsx
<SidebarManagerProvider>
  {children}
</SidebarManagerProvider>
```

### `SidebarManager`

Registers a sidebar with a unique name.

| Prop | Type | Description |
|------|------|-------------|
| `name` | `string` | Unique identifier for this sidebar |
| `children` | `ReactNode` | The `Sidebar` component to register |

```tsx
<SidebarManager name="my-sidebar">
  <Sidebar>...</Sidebar>
</SidebarManager>
```

### `SidebarManagerTrigger`

A button to toggle a sidebar by name.

| Prop | Type | Description |
|------|------|-------------|
| `name` | `string` | Name of the sidebar to toggle |
| `...props` | `ButtonProps` | All Button component props |

```tsx
<SidebarManagerTrigger name="left" />
```

### `useSidebarManager()`

Hook to access the sidebar registry.

```tsx
const manager = useSidebarManager();

// Get a sidebar by name (returns SidebarContextProps | null)
const sidebar = manager.use("left");

// Available methods on `sidebar`:
sidebar?.open           // boolean - current open state
sidebar?.setOpen(bool)  // set open state directly
sidebar?.toggleSidebar() // toggle open/closed
sidebar?.state          // "expanded" | "collapsed"
sidebar?.isMobile       // boolean
sidebar?.openMobile     // boolean - mobile sheet open state
sidebar?.setOpenMobile(bool)
```

### Find the code here: https://gist.github.com/inj-src/033178f989199dc74ddfc4341f4b0ff6

**Comment by Grigore147** [comment]
@inj-src thanks!

I've setup multiple side-by-side sidebars, and it looks to be working great, but with exception of a few minor issues.

1. When second sidebar was collapsing, it went over the first one, so fixed this by applying a lower z-index (yet not sure if it's the best solution).
2. If I change the width of the second sidebar, then it goes over the main content, instead of pushing it more to the right ...

**Comment by inj-src** [comment]
> [@inj-src](https://github.com/inj-src) thanks!
> 
> I've setup multiple side-by-side sidebars, and it looks to be working great, but with exception of a few minor issues.
> 
> 1. When second sidebar was collapsing, it went over the first one, so fixed this by applying a lower z-index (yet not sure if it's the best solution).
> 2. If I change the width of the second sidebar, then it goes over the main content, instead of pushing it more to the right ...

1. This because the Sidebar component has position fixed by default you may use position absolute. 
2. All the sidebars uses same cookie, that could be the reason behind it. 

Non the less, Changing few CSS values should be all you need, or you may just ask an AI agent pointing out the file.

**Comment by Grigore147** [comment]
> > [@inj-src](https://github.com/inj-src) thanks!
> > I've setup multiple side-by-side sidebars, and it looks to be working great, but with exception of a few minor issues.
> > 
> > 1. When second sidebar was collapsing, it went over the first one, so fixed this by applying a lower z-index (yet not sure if it's the best solution).
> > 2. If I change the width of the second sidebar, then it goes over the main content, instead of pushing it more to the right ...
> 
> 1. This because the Sidebar component has position fixed by default you may use position absolute.
> 2. All the sidebars uses same cookie, that could be the reason behind it.
> 
> Non the less, Changing few CSS values should be all you need, or you may just ask an AI agent pointing out the file.

1. Position absolute was needed indeed, but only for the second sidebar, which I already had set, while z-index adjusting was also required anyway.
2. Fixed by providing custom `sidebar-width` style variable for the `SidebarProvider` of the second sidebar in my case.

Looks all clear now. ;)
