### ISSUE TITLE
[bug]: Input OTP with Arabic 

### ISSUE THREAD

**Issue by AivarGabd** [shadcn-ui/ui#5658]
### Describe the bug

Input OTP with tailwind dir='rtl' attribute
![image](https://github.com/user-attachments/assets/5ff8a1f8-7033-414a-8693-bc2bd35ec4bc)

### Affected component/components

Input OTP

### How to reproduce

Input OTP with tailwind dir='rtl' attribute

### System Info

```bash
Chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by zenoUsman** [comment]
Remove attribute rtl if you want from left to right 
<div className="flex flex-col items-center space-y-2" lang="ar">
      <InputOTP maxLength={6}>
        <InputOTPGroup>
          <InputOTPSlot index={0} />
          <InputOTPSlot index={1} />
          <InputOTPSlot index={2} />
        </InputOTPGroup>
        <InputOTPSeparator />
        <InputOTPGroup>
          <InputOTPSlot index={3} />
          <InputOTPSlot index={4} />
          <InputOTPSlot index={5} />
        </InputOTPGroup>
      </InputOTP>
      <p className="text-sm text-muted-foreground">أدخل رمز التحقق من اليسار إلى اليمين</p>
    </div>
