### ISSUE TITLE
[bug]: Adding a component with the CLI fails if you use a tailwind.config.ts file instead of .js

### ISSUE THREAD

**Issue by okanji** [shadcn-ui/ui#5697]
### Describe the bug

Adding a component with the CLI fails if you use a tailwind.config.ts file instead of .js

### Affected component/components

Accoridan

### How to reproduce

`npx shadcn@latest add accordion`

### Logs

```bash
git:(main) ✗ npx shadcn@latest add accordion

✔ Checking registry.
⠋ Updating tailwind.config.js
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

ENOENT: no such file or directory, open '/Users/okanji/Desktop/feedback/tailwind.config.js'
```

### System Info

```bash
Chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Jacksonmills** [comment]
can you share your `components.json`?

**Comment by okanji** [comment]
> can you share your `components.json`?

Ah! I took a look and the `components.json` indeed had `tailwind.config.js`. Changing that to `tailwind.config.ts` fixed the issue. Thanks
