### ISSUE TITLE
[bug]: unable to initialize for next Js 15+ 

### ISSUE THREAD

**Issue by aadltya** [shadcn-ui/ui#5702]
### Describe the bug

The issue seems to stem from the dependency tree being unable to resolve the peer dependency for @radix-ui/react-icons with React 19. Suggestions to resolve it using --legacy-peer-deps or --force were not ideal, as they may lead to other conflicts.

### Affected component/components

unable to add any components

### How to reproduce

![bug](https://github.com/user-attachments/assets/4f3c522a-96ad-4254-ba89-a59a9c7c096b)

### Logs

```bash
$ npx shadcn@latest init
✔ Preflight checks.
✔ Verifying framework. Found Next.js.
✔ Validating Tailwind CSS.
✔ Validating import alias.
√ Which style would you like to use? » New York
√ Which color would you like to use as the base color? » Zinc
√ Would you like to use CSS variables for theming? ... no / yes
✔ Writing components.json.
✔ Checking registry.
✔ Updating tailwind.config.js
✔ Updating app\index.css  
⠹ Installing dependencies.
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: npm install tailwindcss-animate class-variance-authority lucide-react @radix-ui/react-icons clsx tailwind-merge
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ai-interview@0.1.0
npm ERR! Found: react@19.0.0-rc-02c0e824-20241028
npm ERR! node_modules/react
npm ERR!   react@"19.0.0-rc-02c0e824-20241028" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.x || ^17.x || ^18.x || ^19.x" from @radix-ui/react-icons@1.3.1
npm ERR! node_modules/@radix-ui/react-icons
npm ERR!   @radix-ui/react-icons@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\ADITYA\AppData\Local\npm-cache\_logs\2024-11-04T06_55_31_607Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\ADITYA\AppData\Local\npm-cache\_logs\2024-11-04T06_55_31_607Z-debug-0.log
```

### System Info

```bash
windows 10
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by mallickwebstudio** [comment]
I'm facing the same issue

**Comment by aadltya** [comment]
you can fix this using the previous version of shadcn 
`
npx shadcn-ui@0.8.0 init
`

following that ex:
`npx shadcn-ui@0.8.0 add button`

**Comment by aadltya** [comment]
> I'm facing the same issue. It slows the development process and not Ideal condition.

you can fix this using the previous version of shadcn 
```
npx shadcn-ui@0.8.0 init
```

following that ex:
```
npx shadcn-ui@0.8.0 add button
```

**Comment by FurkanGulabi** [comment]
you can fix using

`npm config set legacy-peer-deps true`

and

`npx shadcn@latest init`

then

`npx shadcn@latest add button`

it will be fine.

you can revert npm settings using

`npm config set legacy-peer-deps false`

hope it works.

**Comment by shadcn** [comment]
I'm going to temporarily bring back the npm flags. Let's track in https://github.com/shadcn-ui/ui/issues/5557 please.

**Comment by aadltya** [comment]
yes that will help
