### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by Sooraj-Rao** [shadcn-ui/ui#5920]
closed

**Comment by avenbreaks** [comment]
same issue : 


```
⠴ Checking registry.

Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

The component at https://ui.shadcn.com/r/styles/new-york/toaster.json was not found.
It may not exist at the registry. Please make sure it is a valid component.
```

**Comment by greeneley** [comment]
Dear,
it appears that you're trying to use toaster component.
 The correctcommand to install it is:
   npx shadcn@latest add **toast**

However, the command you used was  **toaster**. It's incorrect for toast component.
Please to check again.
I successfully executed the install command yesterday without any issues

**Comment by agusgarcia3007** [comment]
Same issue here. trying to add a v0-generated block:

`Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

The component at https://ui.shadcn.com/r/styles/new-york/toaster.json was not found.
It may not exist at the registry. Please make sure it is a valid component.`

**Comment by kaimakes** [comment]
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

The component at https://ui.shadcn.com/r/styles/new-york/toaster.json was not found.
It may not exist at the registry. Please make sure it is a valid component.

Getting it too, even after manually installing shadcdn

**Comment by franciscoracosta** [comment]
same here, manually installed and still getting that error when importing the codebase

**Comment by peppertown** [comment]
same here please help

**Comment by 99mill** [comment]
any work arounds?

**Comment by adamsch** [comment]
Getting this error when I open the component in v0 from the Preview in Documentation:

Import Error
The file "registry/new-york/ui/select" cannot be found. Make sure the file exists.

**Comment by Brig4de** [comment]
Same problem, tried everything

**Comment by Cheizr** [comment]
Same problem

**Comment by franciscoracosta** [comment]
is there any fast workaround on this?

**Comment by ghulammurtaza27** [comment]
did anyone figure it out?

**Comment by Sooraj-Rao** [comment]
!

**Comment by ghulammurtaza27** [comment]
Why'd they close it?

**Comment by Sooraj-Rao** [comment]
.

**Comment by Cheizr** [comment]
What do you mean by closed?

**Comment by namish800** [comment]
npx shadcn@latest add toast

The toast component is deprecated. Use the sonner component instead.

Ask v0 to use sonner instead and it will fix the issue

**Comment by aadii2504** [comment]
Yeah Sonner Works Thanks :) @namish800 
If anyone wants to they can give a try atleast

npx shadcn@latest add sonner
