### ISSUE TITLE
[bug]: the select component is a bit broken

### ISSUE THREAD

**Issue by Andyrei** [shadcn-ui/ui#5970]
### Describe the bug

The select content **do not** stay into the select...is just fixed to the screen. if i move the select around the screen the content just stays into the top left position

It is hard to debug it or to add other classes to the content as it disapears as soon as i try to open the inspect tool

### Affected component/components

Select

### How to reproduce

Inserting the Select component into another div that will be in flex
```html
 <div className="flex justify-between">
 <h1>SOME TITLE</h1>
 <Select>
  <SelectTrigger className="">
   <SelectValue placeholder="Theme" />
  </SelectTrigger>
  <SelectContent>
   <SelectItem value="light">Light</SelectItem>
   <SelectItem value="dark">Dark</SelectItem>
   <SelectItem value="system">System</SelectItem>\
  </SelectContent>
 </Select>
</div>
```

### Codesandbox/StackBlitz link

https://stackblitz.com/edit/vitejs-vite-hivdga?file=src%2FApp.tsx

### System Info

```bash
The system for this issue do not matter
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by flixlix** [comment]
changing the import statement to: 
```tsx
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from './components/ui/select';
```

fixes the issue. You were importing the select component from radix-ui, not from your local shadcn component, meaning it was being used in a headless fashion
