### ISSUE TITLE
[bug]: Not Found - GET https://registry.npmjs.org/shadcn - Not found

### ISSUE THREAD

**Issue by MussadiqKhan** [shadcn-ui/ui#6016]
### Describe the bug

Getting 404 not found error when trying install radio group using

`npx shadcn@latest add radio-group`

### Affected component/components

Radio Group

### How to reproduce

Try installing any shadcn component using CLI

### System Info

```bash
mAC VERSION 15.0.1 Macbook Pro i5 2020
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by LucasJantschChitolina** [comment]
It is happening with me too!

![image](https://github.com/user-attachments/assets/4377bf2b-18b7-4e61-884a-9e36813c5077)

**Comment by joselvelez** [comment]
I am getting the same issue

**Comment by maxshugar** [comment]
Same here.

**Comment by Wardojack** [comment]
Seems to be an issue with the NPM package registry.  Every package I try is returning 404 right now.

**Comment by LucasJantschChitolina** [comment]
I think that the error is with npm: https://www.npmjs.com/package/expo

**Comment by Wardojack** [comment]
> Seems to be an issue with the NPM package registry. Every package I try is returning 404 right now.

> I was about to say that the error is with npm: https://www.npmjs.com/package/expo

Except this one, strangely.

**Comment by jasonhuras** [comment]
NPM is currently undergoing scheduled maintenance which started at 18:00 UTC

https://twitter.com/npmstatus/status/1865803617330246039

**Comment by rdzar** [comment]
> NPM is currently undergoing scheduled maintenance which started at 18:00 UTC
> 
> https://twitter.com/npmstatus/status/1865803617330246039

Although it shouldn't impact installations, but it indeed does impact installations. More packages running into this issue.

> We will be conducting a scheduled infrastructure upgrade that may temporarily impact publishing and certain website functionalities. While some features will remain operational, **like installations and search**, minor inefficiencies may occur. Normal operations are expected to resume following the maintenance window.
https://status.npmjs.org/

**Comment by ilyesm** [comment]
It's fixed and working now. This can be closed.

**Comment by rickyrosa36** [comment]
This is not fixed  still the same issue
