### ISSUE TITLE
[feat]: Add support for a searchbar component

### ISSUE THREAD

**Issue by Rednas83** [shadcn-ui/ui#6022]
Are there are also plans for a searchbar?

Something like
![image](https://github.com/user-attachments/assets/0219efae-760c-4cc2-b45e-4e7d1bc02b44)
Calling a popover for searching
![image](https://github.com/user-attachments/assets/76f1e3f5-aa16-4c62-8e3e-7cdcae7c79e2)
Ideally with an option to directly connect to a search client like for example [meili](https://www.meilisearch.com/docs/guides/front_end/vue_quick_start)

**Comment by flixlix** [comment]
I think you are looking for the Command component

**Comment by Rednas83** [comment]
Ok, looks interesting.
https://ui.shadcn.com/docs/components/command

I will have a look

**Comment by KevinNitroG** [comment]
> Ok, looks interesting. [ui.shadcn.com/docs/components/command](https://ui.shadcn.com/docs/components/command)
> 
> I will have a look

Hi @Rednas83, do you have any examples or any of your work that successfully implements shadcn-ui command component with Meilisearch? Thank you in advance

**Comment by Rednas83** [comment]
@KevinNitroG No, I currently don't have a need for it. More likely I will be using it with something like https://ui.nuxt.com/docs/components/dashboard-search-button because I am currently not working with shadcn. In the past I have successfully used it with formkit
