### ISSUE TITLE
[bug]: error: Cannot find module '@jridgewell/gen-mapping' from '/private/tmp/bunx-501-shadcn@latest/node_modules/@babel/generator/lib/source-map.js'

### ISSUE THREAD

**Issue by crazycodestar** [shadcn-ui/ui#6026]
### Describe the bug

I prompted v0.dev to create a starter template and I copied the command and changed the npx to bunx --bun and ran it only to find this error

```
error: Cannot find module '@jridgewell/gen-mapping' from '/private/tmp/bunx-501-shadcn@latest/node_modules/@babel/generator/lib/source-map.js'
```
I only just installed bun so maybe I didn't configure something write. bunx works for other things like `bunx --bun prettier foo.js` so I'm sure the problem is a shadcn@latest one.
Any help would be appreciated thank you.

### Affected component/components

Shadcn CLI

### How to reproduce

1. Install bun
2. in the terminal run bunx --bun shadcn@latest init

### Codesandbox/StackBlitz link

not applicable

### Logs

```bash
error: Cannot find module '@jridgewell/gen-mapping' from '/private/tmp/bunx-501-shadcn@latest/node_modules/@babel/generator/lib/source-map.js'
```

### System Info

```bash
┌─────────────────────────────────────────────────────────────────────────────────────────┐
│  SYSTEMINFORMATION                                                      Version: 5.23.8 │
└─────────────────────────────────────────────────────────────────────────────────────────┘

Operating System:
──────────────────────────────────────────────────────────────────────────────────────────
Platform         : darwin
Distro           : macOS
Release          : 15.1.1
Codename         : macOS Sequoia
Kernel           : 24.1.0
Arch             : arm64
Hostname         : Olalekans-MacBook-Pro.local
Codepage         : UTF-8
Build            : 24B91

System:
──────────────────────────────────────────────────────────────────────────────────────────
Manufacturer     : Apple Inc.
Model            : MacBookPro
Version          : 18,3
Virtual          : 

CPU:
──────────────────────────────────────────────────────────────────────────────────────────
Manufacturer     : Apple
Brand            : M1 Pro
Family           : 458787763
Model            : 
Stepping         : 4
Speed            : 2.4
Cores            : 8
PhysicalCores    : 8
PerformanceCores : 6
EfficiencyCores  : 2
Processors       : 1
Socket           : SOC
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by rszalski** [comment]
I'm facing the same issue on macOS running `npx shadcn@latest add`.

**Comment by yigitkerem** [comment]
Same issue on macOS. Tried Node 18 and 22 with both npx and ynpx

**Comment by Dastari** [comment]
Also having the same issue. Using node 20 did not fix the issue for me, nor did using any of the other package runners (bunx, pnpx)

Was working a few hours ago.

**Comment by mjjabarullah** [comment]
[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: D:/jafa/Portal/UI): [Error] Loading PostCSS Plugin failed: Cannot find module 'D:/jafa/Portal/UI/node_modules\@jridgewell\gen-mapping\dist\gen-mapping.umd.js'

I got same issue after removed node_modules and installed packages. It was working a hours ago.

**Comment by crazycodestar** [comment]
I just retried with `pnpm dlx` i'm getting the same error

**Comment by yigitkerem** [comment]
Seems to be not about the node version but rather about using `shadcn@latest` instead of `shadcn`. If you use the latter, it does seem to work with v20.

**Comment by iStorry** [comment]
I’m having the same issue. It seems like someone accidentally broke something in the linked library, and it’s causing this problem. It’s happening with Babel too.

**Comment by yigitkerem** [comment]
<img width="1311" alt="Screenshot 2024-12-10 at 11 29 17" src="https://github.com/user-attachments/assets/d3a3eeae-a64b-4183-9347-7fed52271649">
They seem to have broken the library and now the dist folder it is complaining about is not building.

**Comment by ve1997** [comment]
I cleared the cache using the following command and then retried, and it worked.
I can't guarantee that it will work for you, but
```
bun pm cache rm
```

**Comment by dahei07** [comment]
for pnpm dlx,i downgrade the version to v0.3.5 and remove the pnpm dlx cache folder.it's work for me.

**Comment by swapnilsparsh** [comment]
New version published `v0.3.7`
https://github.com/jridgewell/sourcemaps/issues/10#issuecomment-2530804362

**Comment by crazycodestar** [comment]
> I cleared the cache using the following command and then retried, and it worked. I can't guarantee that it will work for you, but
> 
> ```
> bun pm cache rm
> ```

this worked for me

**Comment by mjjabarullah** [comment]
New version is woking now.

**Comment by MaxLee1980** [comment]
> New version v0.3.7 is woking now.

but push a new error:
[error] /data/workspace/store/front_end/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js:1328
            const originalLine = originalSource[sourceLine] ||= [];
                                                            ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/data/workspace/store/front_end/node_modules/@babel/generator/lib/source-map.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/data/workspace/store/front_end/node_modules/@babel/generator/lib/index.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)

**Comment by MaxLee1980** [comment]
> New version v0.3.7 is woking now.
focus on position:
function buildBySources(decoded, memos) {
        const sources = memos.map(buildNullArray);
        for (let i = 0; i < decoded.length; i++) {
          const line = decoded[i];
          for (let j = 0; j < line.length; j++) {
            const seg = line[j];
            if (seg.length === 1) continue;
            const sourceIndex2 = seg[SOURCES_INDEX2];
            const sourceLine = seg[SOURCE_LINE2];
            const sourceColumn = seg[SOURCE_COLUMN2];
            const originalSource = sources[sourceIndex2];
            const originalLine = originalSource[sourceLine] ||= [];
            const memo = memos[sourceIndex2];
            let index = upperBound(
              originalLine,
              sourceColumn,
              memoizedBinarySearch(originalLine, sourceColumn, memo, sourceLine)
            );
            memo.lastIndex = ++index;
            insert2(originalLine, index, [sourceColumn, i, seg[COLUMN2]]);
          }
        }
        return sources;
      }

**Comment by swapnilsparsh** [comment]
@MaxLee1980 You can try installing again as the version has been reset to `v0.3.5`
https://github.com/jridgewell/sourcemaps/issues/10#issuecomment-2530884671

**Comment by riteshreg** [comment]
I downgrade  the version to 0.3.5
 
 pnpm install -g @jridgewell/gen-mapping@0.3.5
 
 and then I remove pnpm cache C:\Users\Ritesh Khadka\AppData\Local\pnpm-cache
