### ISSUE TITLE
[bug]: The Theme Customizer No Longer Works On The Main Site.

### ISSUE THREAD

**Issue by DanyaalMajid** [shadcn-ui/ui#6073]
### Describe the bug

Using the latest Firefox, Chromium, Thorium and Edge, even the Android Version of Chrome, changing the color or radius options has no effect, only light and dark modes are changeable, this seems like some sort of browser standard wide issue, i had a look via dev tools, and the css variables dont change.

I have a custom version of this component extracted for use in my own projects, and it stopped working there, so i tried this one and its not working as well.

### Affected component/components

Theme Customizer

### How to reproduce

1. Goto [shadcn-ui/themes](https://ui.shadcn.com/themes)
2. Click on the Customize Button.
3. Color and Radius Options Don't Work.

### Codesandbox/StackBlitz link

https://ui.shadcn.com/themes

### System Info

```bash
Windows 11 23H2
Firefox 133.0.3
Thorium 128.0.6613.189
Edge Version 131.0.2903.99

Disabled Any Adblock/Dark Mode extensions.
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by AndreiBadescu** [comment]
Yeah, tested on safari and brave, same for me.

**Comment by danhstevens** [comment]
As a fallback, I've been using an older version where the selector still works: https://ui-8dy8ykf4h-shadcn-pro.vercel.app/themes

**Comment by DanyaalMajid** [comment]
What changed between this and the latest version causing it to break?

**Comment by shadcn** [comment]
I fixed it. Thanks for the heads up. Appreciate it.
