### ISSUE TITLE
[bug]: React router v7 build - drawer animation not working (dev is working as expected).

### ISSUE THREAD

**Issue by yoni-noma** [shadcn-ui/ui#6087]
### Describe the bug

seems like when using "npm run react-router build" the animation arent working with the latest version of vaul.
i dont see the <style> and data attribues added to the css of the dialog div. and therefore there are no animaitons on it. 

### Affected component/components

Drawer

### How to reproduce

just try to open and close drawer on the latest version of react router build.

### System Info

```bash
using latest chrome with react-router v7.0.2 and latest drawer version (vaul 1.0.2)
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

* only enter animations doesnt work, exit does, maybe related to SSR mode.

**Comment by alexander-densley** [comment]
how did you set up shadcn in rr v7

**Comment by yoni-noma** [comment]
@alexander-densley ive upgraded remix to rr7.. nothing special, is there anything i need to add?

**Comment by yoni-noma** [comment]
issue related somehow to Sentry and react router v7 ssr mode. closing 🙏
