### ISSUE TITLE
[bug]: NextJS 15 + Select Option

### ISSUE THREAD

**Issue by decoderid** [shadcn-ui/ui#6175]
### Describe the bug

![image](https://github.com/user-attachments/assets/974c81ad-ac04-4fef-bbf7-1286f2e74426)

### package version
```ts
next@15.1.2
react@19.0.0
@radix-ui/react-select@2.1.4
```

### Affected component/components

Select

### How to reproduce

```ts
        <Select name="member[status]" defaultValue="ACTIVE">
          <SelectTrigger>
            <SelectValue placeholder="ACTIVE" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="ACTIVE">ACTIVE</SelectItem>
            <SelectItem value="SUSPEND">SUSPEND</SelectItem>
            <SelectItem value="DISABLED">DISABLED</SelectItem>
            <SelectItem value="BLACKLIST">BLACKLIST</SelectItem>
          </SelectContent>
        </Select>
        ```

### System Info

```bash
Browsers
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by yashranjan1** [comment]
check your import to make sure select item is coming from the components folder and not radix ui
![image](https://github.com/user-attachments/assets/36530091-fdb5-41a9-9322-8f5449b2fd29)

**Comment by Jahid0178** [comment]
@yashranjan1 Yes you'r right, He is import from radix-ui not from components/ui folder.

**Comment by decoderid** [comment]
> check your import to make sure select item is coming from the components folder and not radix ui ![image](https://private-user-images.githubusercontent.com/113207367/398564168-36530091-fdb5-41a9-9322-8f5449b2fd29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMzYyODAsIm5iZiI6MTczNTEzNTk4MCwicGF0aCI6Ii8xMTMyMDczNjcvMzk4NTY0MTY4LTM2NTMwMDkxLWZkYjUtNDFhOS05MzIyLThmNTQ0OWIyZmQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxNDEzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGM4OTY3MWRmM2VlNzVkZDdkMDE2MjNkYTYzNmM0YzU0OWYwMWY4N2QzZmFhNDc1ZDQ4NDg2MWJlY2U3OWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HOiaiLzaizyZl02r9UoyKJHbgYVLNKfb-zZip4_g2xE)

I imported from the UI component but the result is as shown in the picture

**Comment by yashranjan1** [comment]
can you post a screenshot of the import statement maybe?

**Comment by decoderid** [comment]
> can you post a screenshot of the import statement maybe?

I just realized that one of the imports refers to **@radix-ui/react-select**
