### ISSUE TITLE
Add a promise toast

### ISSUE THREAD

**Issue by nonwiz** [shadcn-ui/ui#621]
I usually use react-hot-toast, there are quite some cool features, for example, you can call the toast, without using useToast. Another main reason is toast can embed the promise, useful for "Loading", "Success", or "Error" states.

**Comment by philosofonusus** [comment]
It would be really nice, I also has faced it

**Comment by philosofonusus** [comment]
if you want toast within the same style I use library called `sonner` like this
`
"use client";

import { Toaster as RadToaster } from "sonner";

export function Toaster() {
  return (
    <RadToaster
      position="bottom-right"
      toastOptions={{
        style: {
          background: "hsl(var(--background))",
          color: "hsl(var(--foreground))",
          border: "1px solid hsl(var(--border))",
        },
      }}
    />
  );
}
`

**Comment by lacymorrow** [comment]
Sonner has been added to shadcn, this can be closed.
