### ISSUE TITLE
[bug]: Carousel moves item half item when basis-[1/4].

### ISSUE THREAD

**Issue by cong85010** [shadcn-ui/ui#6222]
### Describe the bug

<img width="584" alt="Screenshot 2024-12-30 at 14 39 55" src="https://github.com/user-attachments/assets/2df8383e-660a-46bc-9f56-72d9a02bb17c" />

### Affected component/components

Carousel

### How to reproduce

1. In CarouselItem
2. Set basis <CarouselItem key={index} className={`basis-1/4  py-4`}>
3. Click Next; it is just a half item move.

### Codesandbox/StackBlitz link

(https://v0.dev/chat/iWhbmnoz5iR?b=b_6bQDN1VDak4)

### System Info

```bash
chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by candymask0712** [comment]
The `py-4` property does not appear to be directly related to the bug. Even if it is excluded, the same situation is reproduced. ([link](https://v0.dev/chat/D8dBLrfjwUZ?b=Xh00uEF3ijS&p=0))

**Comment by candymask0712** [comment]
@cong85010 
How about adding {align: "start"} to the opts property of the Carousel, just like in the example code? This property allows you to specify the alignment method of the items. You can check this code in the size tab section of the official documentation. ([link](https://ui.shadcn.com/docs/components/carousel#sizes))

**Comment by cong85010** [comment]
> @cong85010 How about adding {align: "start"} to the opts property of the Carousel, just like in the example code? This property allows you to specify the alignment method of the items. You can check this code in the size tab section of the official documentation. ([link](https://ui.shadcn.com/docs/components/carousel#sizes))

Yes, but it can fixed bug ?

**Comment by candymask0712** [comment]
@cong85010 
Of course! You can use the `opt` option to control the sorting however you like. The link below shows a situation where I've only added the `opt` part to your code. It works perfectly. 😁

[link](https://v0.dev/chat/YRkSOdTOCrI?b=MfIbKw302Yz)

**Comment by cong85010** [comment]
> @cong85010 Of course! You can use the `opt` option to control the sorting however you like. The link below shows a situation where I've only added the `opt` part to your code. It works perfectly. 😁
> 
> [link](https://v0.dev/chat/YRkSOdTOCrI?b=MfIbKw302Yz)

Thank you, I think Your solution resolved my problem.
