### ISSUE TITLE
bug(docs): missing manual installation for certain components

### ISSUE THREAD

**Issue by dan5py** [shadcn-ui/ui#687]
The toast manual installation is missing the `Toaster` and the `useToast` files. At the moment there's only the `toast.tsx` file.

Also the `Form` is missing the manual installation.

**Comment by MendyLanda** [comment]
+

**Comment by shadcn** [comment]
@dan5py Is this still happening with the new cli?

**Comment by dan5py** [comment]
@shadcn Yes
