### ISSUE TITLE
Component preview requires horizontal scroll

### ISSUE THREAD

**Issue by squishydough** [shadcn-ui/ui#7]
In Firefox Developer edition, on my vertical monitor with a resolution of 1080x1920, previewing the component requires a long horizontal scroll. This problem is not visible at higher resolutions.  The issue is occurs in the `md` and `lg` breakpoints for much of the range in my testing. The cause appears to be the addition of the `aside` element messing up the `width: 100%` calculations used elsewhere. 

![image](https://user-images.githubusercontent.com/12982889/214609688-49dbe07e-b6f5-49f6-bcac-4e1871560efd.png)

**Comment by shadcn** [comment]
I believe we fixed this. Closing this but feel free to reopen if not.
