### ISSUE TITLE
Add documentation for components.json

### ISSUE THREAD

**Issue by plbstl** [shadcn-ui/ui#773]
It would be helpful if there's a dedicated documentation for the `components.json` file

<details>
<summary>&nbsp; screenshot </summary>

![Web capture_29-6-2023_16126_ui shadcn com](https://github.com/shadcn/ui/assets/49006567/39438c29-ce9c-4908-8aa0-7f30bc3da05a)
</details>

**Comment by Leiloukou** [comment]
Someone should do this soon.
