### ISSUE TITLE
adding DataTablePagination component via cli

### ISSUE THREAD

**Issue by pdeva** [shadcn-ui/ui#780]
The doc [here](https://ui.shadcn.com/docs/components/data-table#pagination-1) mentions the `DataTablePagination` component. However, it seems there is no way to add it via CLI. Is it expected to copy/paste from the source of the Tasks demo?

**Comment by Klotske** [comment]
The section with comonent's code is missing. 

![image](https://github.com/shadcn/ui/assets/30481105/d1124651-d8d0-4380-a89c-fef30a0bc4df)

With the recent change in check in lib/rehype-component.ts https://github.com/shadcn/ui/blob/c3377530f43baa95c9e41cce7c07b1a4db1e3ee6/apps/www/lib/rehype-component.ts#L78C9-L78C75

**Comment by dan5py** [comment]
Hi @pdeva, @Klotske is right there currently a problem with that.

For now you can copy it from [here](https://github.com/shadcn/ui/blob/c3377530f43baa95c9e41cce7c07b1a4db1e3ee6/apps/www/app/examples/tasks/components/data-table-pagination.tsx).

**Comment by dan5py** [comment]
I just updated this PR #768 to address this issue.
