### ISSUE TITLE
[Suggestion] Split button component

### ISSUE THREAD

**Issue by zisra** [shadcn-ui/ui#813]
Something like [this](https://ui.mantine.dev/component/split-button)

**Comment by Yohannfra** [comment]
There is one one the main page of the front page. So it can certainly be done already by composing components.

https://ui.shadcn.com/examples/cards

<img width="130" alt="Capture d’écran 2024-01-22 à 16 21 43" src="https://github.com/shadcn-ui/ui/assets/36271388/1ff18a1f-33e7-40fc-a4dc-f696439b3db1">
<img width="216" alt="Capture d’écran 2024-01-22 à 16 21 49" src="https://github.com/shadcn-ui/ui/assets/36271388/aad6447a-c9dc-42e4-9091-4403915c27ac">

**Comment by jimniels** [comment]
For anyone coming to this issue, like I did, here's some code that'll do the trick:

```jsx
<div className="flex items-center">
  <Button variant="outline" className={'rounded-r-none'}>
    Create file
  </Button>
  <DropdownMenu>
    <DropdownMenuTrigger asChild>
      <Button variant="outline" className={'rounded-l-none border-l-0 px-2'}>
        <CaretDownIcon />
      </Button>
    </DropdownMenuTrigger>
    <DropdownMenuContent>
      <DropdownMenuItem>Create sheet</DropdownMenuItem>
      <DropdownMenuItem>Create doc</DropdownMenuItem>
      <DropdownMenuItem>Create thingy</DropdownMenuItem>
    </DropdownMenuContent>
  </DropdownMenu>
</div>
```

It's essentially two buttons, side-by-side, with their borders and styles tweaked.

<img width=180 src=https://github.com/shadcn-ui/ui/assets/1316441/13d990f8-a00a-404b-b96c-0af76a9ea2a9 />

You can easily imagine extending this with an icon or tweaking the dropdown as you so please.

<img width=240 src=https://github.com/shadcn-ui/ui/assets/1316441/1a50a135-764b-4ab9-abe2-fc0037526b0c />

**Comment by zisra** [comment]
Thank you. Closed.
