### ISSUE TITLE
Page could not be found (error 404)

### ISSUE THREAD

**Issue by Pushpajekumar** [shadcn-ui/ui#818]
![Screenshot 2023-07-03 201557](https://github.com/shadcn/ui/assets/97593143/238967f1-65db-4766-a8a2-c32b05919227)
![Screenshot 2023-07-03 201611](https://github.com/shadcn/ui/assets/97593143/6b90919e-6a24-4861-9f1a-49ca029f21a4)

**Comment by dan5py** [comment]
Hi @Pushpajekumar, this is a duplicate of #811. Check that issue for the solution, thanks.

**Comment by MrBisbis631** [comment]
> Hi @Pushpajekumar, this is a duplicate of #811. Check that issue for the solution, thanks.
The solution in #811 is " Duplicated" as well...
Any solution?

**Comment by Pushpajekumar** [comment]
I found the solution we have to give right path while installing if we are using src folder
