### ISSUE TITLE
Cant install on a Js project

### ISSUE THREAD

**Issue by ayofimihan** [shadcn-ui/ui#821]
i keep getting this error everytime i try to install on my non-ts project

`Failed to load tsconfig.json. Couldn't find tsconfig.json`

**Comment by dan5py** [comment]
Hi @ayofimihan. This components are meant for TypeScript projects. If you want to use them in a js project you can copy them from the docs and remove the types.

**Comment by prashantchhonker** [comment]
I am facing the same issue. I am following the installation instructions to the dot. Which means running the following commands.
```
npx create-next-app@latest nextjs-test --typescript --tailwind --eslint
npx shadcn-ui@latest init
npx shadcn-ui@latest add button
```

**Comment by dan5py** [comment]
@prashantchhonker did you `cd` into the `nextjs-test` folder?

**Comment by dan5py** [comment]
@ayofimihan the latest version of the cli adds the support for JavaScript 🚀 .

**Comment by Namnika** [comment]
Hi @dan5py I recently faced this issue, I am also using js, and trying to install this lib. But When I use this `npx shadcn-ui@latest add alert-dialog` using the latest cli version it instantly gives me the error `Failed to load tsconfig.json. Couldn't find tsconfig.json`. I am used to `tsconfig.json`. 
And also I have init `components.json` using this `npx shadcn-ui@latest init`.

Any suggestions? What to do?

**Comment by spiritoftime** [comment]
Hello @Namnika @prashantchhonker ,i assume you are using react js. I have been using shadcn at my own js react vite project too, you can use my starter repo if you like. 
https://github.com/spiritoftime/shadcn-reactjs-starter

**Comment by alangardner-dev** [comment]
I ran into this issue as well with a non-TS project. I manually added a `tsconfig.json` file at the root of the project and inserted the block of code provided in [step 4 of the manual instructions](https://ui.shadcn.com/docs/installation/manual). Then I ran the init command `npx shadcn-ui@latest init` and stepped through the questions - specifying 'no' to the "Would you like to use TypeScript (recommended)?" questions. When I installed the `Badge` component, it added a `.jsx` file into `components/ui` dir.

**Comment by sakettawde** [comment]
Found the issue
You need to add a jsconfig.json to the file to mention the alias paths if you have a need to support any

For eg.
```
{
  "compilerOptions": {
    "paths": {
      "@/*": ["./*"]
    }
  }
}
```

The error message needs to be updated to specify missing jsconfig.js file instead of tsconfig.json file when tsx is false in components.json file

**Comment by sungkhum** [comment]
> Found the issue You need to add a jsconfig.json to the file to mention the alias paths if you have a need to support any
> 
> For eg.
> 
> ```
> {
>   "compilerOptions": {
>     "paths": {
>       "@/*": ["./*"]
>     }
>   }
> }
> ```
> 
> The error message needs to be updated to specify missing jsconfig.js file instead of tsconfig.json file when tsx is false in components.json file

Thanks! That was my problem!

**Comment by ayofimihan** [comment]
Thanks everyone, I now fully use typescript lol.

**Comment by SantiagoCC97** [comment]
> Hello @Namnika @prashantchhonker ,i assume you are using react js. I have been using shadcn at my own js react vite project too, you can use my starter repo if you like. https://github.com/spiritoftime/shadcn-reactjs-starter

Thanks!,

**Comment by itsOmSarraf** [comment]
> Hello @Namnika @prashantchhonker ,i assume you are using react js. I have been using shadcn at my own js react vite project too, you can use my starter repo if you like. https://github.com/spiritoftime/shadcn-reactjs-starter

Thanks :)

**Comment by ayushsoni1010** [comment]
Thanks :D

**Comment by sanchitrk** [comment]
@spiritoftime, thank you so much. it worked. I am so happy now!

**Comment by GeekyNaved** [comment]
> Found the issue You need to add a jsconfig.json to the file to mention the alias paths if you have a need to support any
> 
> For eg.
> 
> ```
> {
>   "compilerOptions": {
>     "paths": {
>       "@/*": ["./*"]
>     }
>   }
> }
> ```
> 
> The error message needs to be updated to specify missing jsconfig.js file instead of tsconfig.json file when tsx is false in components.json file

Thanks it worked for me

**Comment by Dodong2** [comment]
> @spiritoftime Thank you so much for sharing the repo link! :) And I tried to do it with customization of React + Vite + shandcn which worked well.
> 
> Thanks All of the way!

in my React.js vite its not working still the same error.

**Comment by 7Aceace** [comment]
It seems like it is back to not supporting the jsconfig.json. 
I have created the jsconfig.json and used the path but the error tsconfig.json appears.

Any solution to this?

**Comment by tanuharsh** [comment]
npx shadcn-ui@latest add stepper failed to use this

**Comment by aleBranching** [comment]
If using vite vite.config.js also needs to be updated. 


``` javascript
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./"),
    },
  },
});
```

I don't like typescript

**Comment by AllSparkTech100** [comment]
Thanks a lot [sakettawde](https://github.com/sakettawde)

**Comment by pHanToMcaNCoDE** [comment]
Hey!

For those how're having this issue, just do the following:

1. Create a 'tsconfig.json' or 'jsconfig.json' at the root directory of your project (create the file at the directory where your package.json file is located).

2. Add the following to the new file created:

For Ts:
 {
    "compilerOptions": {
      "target": "es6",
      "module": "commonjs",
      "strict": true,
      "esModuleInterop": true,
      "skipLibCheck": true,
      "forceConsistentCasingInFileNames": true
    },
    "include": ["src"]
  }

For Js:
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "checkJs": true
  },
  "include": ["src"]
}

3. You can run the command again and it will work 💯. Be sure to check shadcn docs so as to answer the questions asked correctly.

✌🏼

**Comment by ParshvLimbad** [comment]
@spiritoftime you are the goat, thanks

**Comment by ideabrian** [comment]
> I ran into this issue as well with a non-TS project. I manually added a `tsconfig.json` file at the root of the project and inserted the block of code provided in [step 4 of the manual instructions](https://ui.shadcn.com/docs/installation/manual). Then I ran the init command `npx shadcn-ui@latest init` and stepped through the questions - specifying 'no' to the "Would you like to use TypeScript (recommended)?" questions. When I installed the `Badge` component, it added a `.jsx` file into `components/ui` dir.

Used this on Aug 4, 2024 - and it worked.

**Comment by nullnullsieben** [comment]
https://www.instagram.com/1900_officelle?igsh=MW5ueDI0b21qbW44Zg==

Brian Ball ***@***.***> schrieb am Mo., 5. Aug. 2024, 06:35:
