### ISSUE TITLE
Problem adding component

### ISSUE THREAD

**Issue by wilkensgomes** [shadcn-ui/ui#847]
![Captura de tela 2023-07-05 153443](https://github.com/shadcn/ui/assets/38788876/358e3382-a002-40ce-b252-4eabb4f82f80)

If anyone knows how to solve this.

**Comment by NikharPandya** [comment]
@wilkensgomes could you check your tsconfig or jsconfig file for path alias, you will need to configure it. You could refer the config https://ui.shadcn.com/docs/installation

**Comment by dan5py** [comment]
Hi @wilkensgomes, you misspelled the component name, it's `calendar` not `calender`.

**Comment by dan5py** [comment]
Try to clean the npx cache.
