### ISSUE TITLE
Select component broken when site is translated via Google translate page or browser translate

### ISSUE THREAD

**Issue by damian0x** [shadcn-ui/ui#852]
If you use Select component example in here https://ui.shadcn.com/docs/components/select then translate page to different language in browser address bar, then select something, change selection, you have error "Application error: a client-side exception has occurred (see the browser console for more information)" froze whole site in console is "DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node"

**Comment by dan5py** [comment]
Hi @calciferlo. Using Google Translate adds an element to the page and NextJS complains because it doesn't know where the came from. Adding `translate="no"` to the html tag should fix the issue.

**Comment by anson0370** [comment]
Is disabling the translation of the entire HTML the only way to avoid this issue? Sometimes users might indeed need the translation.

**Comment by DaniloAlvesantos** [comment]
Did it work ?

**Comment by damian0x** [comment]
I use translate="no" and it's work. Close the issue.

**Comment by anson0370** [comment]
Wrapping the value in `SelectItem` with a `<span>` should be able to solve this problem.

Like below:
```
<Select>
  <SelectTrigger>
    <SelectValue/>
  </SelectTrigger>
  <SelectContent>
    {menuItems.map((item) => (
      <SelectItem key={item} value={item}>
        <span>{item}</span>
      </SelectItem>
    ))}
  </SelectContent>
</Select>
```

**Comment by alexfeng262** [comment]
Something that worked for me was wrapping the entire `<Select>` component into a `<div translate='no>`. This fixed the problem and also allow the translate.

Also, you can do `<span translate='no>` if you don't want the translate on that tag.

An example below:

```
<div translate='no'>
  <Select>
    <SelectTrigger>
      <SelectValue/>
    </SelectTrigger>
    <SelectContent>
      {menuItems.map((item) => (
        <SelectItem key={item} value={item}>
          <span translate='no'>{item}</span>
        </SelectItem>
      ))}
    </SelectContent>
  </Select>
</div>

```
