### ISSUE TITLE
The Combobox does not render all options and overflows off the screen.

### ISSUE THREAD

**Issue by alwalxed** [shadcn-ui/ui#912]
![سِيبَوَيْهِ (2)](https://github.com/shadcn/ui/assets/119763173/5e921107-0077-4784-adc2-04a6220db62d)

**Comment by limitless-dev** [comment]
Try adjusting the max height for `CommandList` in your component.
```jsx
<CommandList className="max-h-[200px]">
     ...
</CommandList>
```

**Comment by BrunoQuaresma** [comment]
I tried to put this `max-h-[200px]` in the `<CommandGroup>` but when I do that, the scrolling does not work even adding `overflow-y-auto`

**Comment by kyrylolvov** [comment]
@BrunoQuaresma The way I did it, is wrapping `<CommandGroup>` in `<ScrollArea>`.

<img width="707" alt="Screenshot 2024-01-10 at 2 55 06 PM" src="https://github.com/shadcn-ui/ui/assets/70720713/ed65cc08-6996-4773-b9da-5879565febfc">

**Comment by jpainam** [comment]
It's doesn't wokr for me. I wrapp` CommandGroup` with `ScrollArea` and defined a `max-h-[250px]`

**Comment by Desgue** [comment]
> @BrunoQuaresma The way I did it, is wrapping `<CommandGroup>` in `<ScrollArea>`.
> 
> <img alt="Screenshot 2024-01-10 at 2 55 06 PM" width="707" src="https://private-user-images.githubusercontent.com/70720713/295692498-ed65cc08-6996-4773-b9da-5879565febfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjE0NzgsIm5iZiI6MTcwOTcyMTE3OCwicGF0aCI6Ii83MDcyMDcxMy8yOTU2OTI0OTgtZWQ2NWNjMDgtNjk5Ni00NzczLWI5ZGEtNTg3OTU2NWZlYmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEwMzI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NmI1NjZmMjNmYWY1YThmY2VlNWEzMzZkMDAxOGYxYjA0YjJmYTZmYTgyNzhjOTg3MDk4OTIzMDdmNGVlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zQbu6dK5kXpGQBu3sFV9P7JJ1JH_e6mxADc8zuhhgPM">

I tried doing that and does not work for me. I ended up just setting a max height of 200px, its not scrollable, but the search makes up for that until I i find a solution.

**Comment by duongductrong** [comment]
You just set it on viewportClassname, it will be works.


Result:
<img width="224" alt="CleanShot 2024-04-01 at 08 34 37@2x" src="https://github.com/shadcn-ui/ui/assets/39333905/8a2c94dc-2740-4927-a572-eedc0b451c96">

Code:
<img width="769" alt="CleanShot 2024-04-01 at 08 33 09@2x" src="https://github.com/shadcn-ui/ui/assets/39333905/710f4597-e59d-4571-bf74-411f54e6549a">

**Comment by icarns** [comment]
Following @duongductrong advise:

```patch
 const ScrollArea = React.forwardRef<
 	React.ElementRef<typeof ScrollAreaPrimitive.Root>,
-	React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.Root>
->(({ className, children, ...props }, ref) => (
+	React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.Root> & { viewPortClassName?: string }
+>(({ className, children, viewPortClassName, ...props }, ref) => (
 	<ScrollAreaPrimitive.Root ref={ref} className={cn('relative overflow-hidden', className)} {...props}>
-		<ScrollAreaPrimitive.Viewport className="h-full w-full rounded-[inherit]">{children}</ScrollAreaPrimitive.Viewport>
+		<ScrollAreaPrimitive.Viewport className={cn('h-full w-full rounded-[inherit]', viewPortClassName)}>
+			{children}
+		</ScrollAreaPrimitive.Viewport>
 		<ScrollBar />
 		<ScrollAreaPrimitive.Corner />
 	</ScrollAreaPrimitive.Root>
```

Then simply use it:

```tsx
<ScrollArea viewPortClassName={'max-h-[200px]'}>
```

**Comment by brt-yilmaz** [comment]
Add className = {min-h-[<yourValue>px]} to CommandList. That works for me. 

`<CommandList className={'min-h-[400px]'} >`

**Comment by simonjcarr** [comment]
The answer from @brt-yilmaz works for me using fixed values, but I am populating my command list from a database. How do I make it dynamic. I have tried the following but it does not work.

```
export function TopNavMenuProjects() {
    const favProjects = [
        {
            id: 1,
            name: "Project 1",
        },
        {
            id: 2,
            name: "Project 2",
        },
        {
            id: 3,
            name: "Project 3",
        },
    ]

    const recentProjects = [
        {
            id: 4,
            name: "Project 4",
        },
        {
            id: 5,
            name: "Project 5",
        },
        {
            id: 6,
            name: "Project 6",
        },
    ]
    return (
        <Command className="rounded-lg border shadow-md h-full">
            <CommandInput placeholder="Search ..." />
            <CommandList className={`min-h-[calc(${favProjects.length * 50}px+${recentProjects.length * 50}px)]`}>
                <CommandEmpty>No results found.</CommandEmpty>
                <CommandGroup heading="Favourites">
                    <CommandItem>
                        {/* <CalendarIcon className="mr-2 h-4 w-4" /> */}
                        <span>Project 1</span>
                    </CommandItem>
                    <CommandItem>
                        {/* <FaceIcon className="mr-2 h-4 w-4" /> */}
                        <span>Project 2</span>
                    </CommandItem>
                    <CommandItem>
                        {/* <RocketIcon className="mr-2 h-4 w-4" /> */}
                        <span>Project 3</span>
                    </CommandItem>
                </CommandGroup>
                <CommandSeparator />
                <CommandGroup heading="Recent">
                    <CommandItem>
                        {/* <PersonIcon className="mr-2 h-4 w-4" /> */}
                        <span>Project 4</span>
                        {/* <CommandShortcut>⌘P</CommandShortcut> */}
                    </CommandItem>
                    <CommandItem>
                        {/* <EnvelopeClosedIcon className="mr-2 h-4 w-4" /> */}
                        <span>Project 5</span>
                        {/* <CommandShortcut>⌘B</CommandShortcut> */}
                    </CommandItem>
                    <CommandItem>
                        {/* <GearIcon className="mr-2 h-4 w-4" /> */}
                        <span>Project 6</span>
                        {/* <CommandShortcut>⌘S</CommandShortcut> */}
                    </CommandItem>
                </CommandGroup>
                <CommandGroup heading="More Projects">
                    <CommandItem>
                        {/* <PersonIcon className="mr-2 h-4 w-4" /> */}
                        <span>Project Dashboard</span>
                        {/* <CommandShortcut>⌘P</CommandShortcut> */}
                    </CommandItem>
                </CommandGroup>
            </CommandList>
        </Command>
    )
}
```
