### ISSUE TITLE
`CommandInput` filters value and not label

### ISSUE THREAD

**Issue by yannxaver** [shadcn-ui/ui#933]
https://ui.shadcn.com/docs/components/combobox#form

1. Type `sp` into `Select Language`
2. You expect Spanish to be available
3. It is not because the filter is run on the value instead of the label

```ts
const languages = [
  { label: "English", value: "en" },
  { label: "French", value: "fr" },
  { label: "German", value: "de" },
  { label: "Spanish", value: "es" },
  { label: "Portuguese", value: "pt" },
  { label: "Russian", value: "ru" },
  { label: "Japanese", value: "ja" },
  { label: "Korean", value: "ko" },
  { label: "Chinese", value: "zh" },
] as const
```

**Comment by limitless-dev** [comment]
If you want to search by label, you'll need to:
1. Pass `label` to `CommandInput` as value
```jsx
<CommandItem
value={language.label}
//  ...
>

```
2. Find language by `label.toLowerCase()`
```jsx
{field.value
  ? languages.find(
      (language) =>
        language.label.toLowerCase() === field.value
    )?.label
  : 'Select language'}

```
3. CheckIcon should be active for language based on `label.toLowerCase()`
```jsx
<CheckIcon
   // ...
    language.label.toLowerCase() === field.value
   // ..
/>
```

**Comment by mezzouhri** [comment]
Hi,
what can we do if we want search by label, but when the form is submit we get the value ?
Thank you

**Comment by yannxaver** [comment]
@limitless-dev Shouldn't filtering by label be the default? It's hard for me to imagine a situation in which you want to filter by value - which is basically unknowable for the user.

**Comment by limitless-dev** [comment]
> Hi, what can we do if we want search by label, but when the form is submit we get the value ? Thank you

@mezzouhri 
You would need to adjust the `onSelect` to something like this:
```jsx
  onSelect={(value) => {
    form.setValue(
      'language',
      languages
        .find(
          ({ label }) => label.toLowerCase() === value
        )
        ?.label.toLowerCase() ?? 'en'
    );
  }}
```

**Comment by limitless-dev** [comment]
> @limitless-dev Shouldn't filtering by label be the default? It's hard for me to imagine a situation in which you want to filter by value - which is basically unknowable for the user.

Maybe @shadcn can advise on this and if we should make a PR?

**Comment by chhuang** [comment]
> @limitless-dev Shouldn't filtering by label be the default? It's hard for me to imagine a situation in which you want to filter by value - which is basically unknowable for the user.

Agree. Typing `g` for `German` nothing shows up, I thought it was a bug.

**Comment by limitless-dev** [comment]
I created a PR for this #989 with minimal changes to the workaround I proposed above.
```jsx
<CommandItem
  value={language.label}
  key={language.value}
  onSelect={() => {
  form.setValue("language", language.value)
  }}
```

**Comment by mezzouhri** [comment]
> > Hi, what can we do if we want search by label, but when the form is submit we get the value ? Thank you
> 
> @mezzouhri You would need to adjust how data is being submitted, something like this:
> 
> ```js
>   function onSubmit(data: z.infer<typeof FormSchema>) {
>     // ...
>       JSON.stringify(
>         {
>           ...data,
>           language: languages.find(
>             ({ label }) => label.toLowerCase() === data.language
>           )?.value,
>         },
>         null,
>         2
>       )
>     // ...
>   }
> ```

Hi @limitless-dev , thank you for you response, I misspoke about what I want, in reality, I want display and search by `language.label`, but Item.value should be `language.value`.

Your logic is correct, but I found an other solution for my case, here the full example of my case (ongoing project) : [www.remitlib.com](https://www.remitlib.com/en).

**Comment by mezzouhri** [comment]
here is my code :

```typescript
//select-country.tsx

"use client";

import { useState } from "react";
import { Button } from "./ui/button";
import { cn } from "@/lib/utils";
import { Check, ChevronsUpDown } from "lucide-react";
import Image from "next/image";
import { Countries } from "@/types";
import { UseFormReturn } from "react-hook-form";
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
} from "@/components/ui/command";
import {
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { useTranslations } from "next-intl";

type Props = {
  name: "countryFrom" | "countryTo";
  setCountry: (countryCode: string) => void;
  countries: Countries;
  form: UseFormReturn<
    {
      countryFrom: string;
      countryTo: string;
      receiveMode: string;
      sendAmount: number;
    },
    any,
    undefined
  >;
};

const SelectCountry = ({ name, setCountry, countries, form }: Props) => {
  const t = useTranslations();
  const [open, setOpen] = useState(false);

  const countryWithFlag = (code?: string) => {
    const selectedCountry = countries.find((country) => country.code === code);
    return (
      <div className="flex flex-row items-center">
        <Image
          src={selectedCountry?.flag || "/favicon.ico"}
          alt="country flag"
          className="shrink-0 me-2 w-6 h-5"
          width={24}
          height={24}
        />
        <div className="grow flex-1">{selectedCountry?.label}</div>
      </div>
    );
  };

  return (
    <FormField
      control={form.control}
      name={name}
      render={({ field }) => (
        <FormItem className="flex flex-col">
          <FormLabel>{t("comparator.sendFrom")}</FormLabel>
          <Popover open={open} onOpenChange={setOpen}>
            <PopoverTrigger asChild>
              <FormControl>
                <Button
                  variant="outline"
                  role="combobox"
                  aria-expanded={open}
                  className={cn(
                    "w-full flex flex-row",
                    !field.value && "text-muted-foreground"
                  )}
                >
                  {field.value
                    ? countryWithFlag(field.value)
                    : t("comparator.selectCountry")}
                  <ChevronsUpDown className="ms-auto h-4 w-4 shrink-0 opacity-50" />
                </Button>
              </FormControl>
            </PopoverTrigger>
            <PopoverContent className="p-0">
              <Command
                filter={(value, search) => {
                  if (
                    t(`countries.${value}`)
                      .toLowerCase()
                      .includes(search?.toLowerCase())
                  )
                    return 1;
                  return 0;
                }}
              >
                <CommandInput placeholder={t("comparator.searchCountry")} />
                <CommandEmpty>{t("comparator.countryNotFound")}</CommandEmpty>
                <CommandGroup className="max-h-[240px] overflow-y-auto">
                  {countries.map((country) => (
                    <CommandItem
                      value={country.code}
                      key={country.code}
                      onSelect={(value) => {
                        form.setValue(name, value);
                        setCountry(value);
                        setOpen(false);
                      }}
                      className="w-full"
                    >
                      <Image
                        src={country.flag}
                        alt="country flag"
                        className="shrink-0 me-2 w-5 h-3"
                        width={20}
                        height={16}
                      />
                      <div className="grow flex-1">{country.label}</div>
                      <Check
                        className={cn(
                          "ms-auto h-4 w-4",
                          country.code === field.value
                            ? "opacity-100"
                            : "opacity-0"
                        )}
                      />
                    </CommandItem>
                  ))}
                </CommandGroup>
              </Command>
            </PopoverContent>
          </Popover>
          <FormMessage />
        </FormItem>
      )}
    />
  );
};

export default SelectCountry;


``` 

```typescript
//comparator.tsx

"use client";

import * as z from "zod";
import { useEffect } from "react";
import { useTranslations } from "next-intl";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { useRouter } from "next-intl/client";

import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";

import { Card, CardContent } from "@/components/ui/card";
import COUNTRIES from "../lib/countries.json";
import InputWithCurrency from "./input-with-currency";
import SelectCountry from "./select-country";
import SelectReceiveMode from "./select-receive-mode";
import { COUNTRY_FROM, COUNTRY_TO } from "@/lib/const";
import useCountryFrom from "@/store/use-countryFrom";
import useCountryTo from "@/store/use-countryTo";
import CurrencyTo from "./currency-to";

const Comparator = () => {
  const t = useTranslations();
  const router = useRouter();

  const countryFromCode = useCountryFrom(({ countryCode }) => countryCode);
  const setCountryFromCode = useCountryFrom(
    ({ setCountryCode }) => setCountryCode
  );
  const setCountryToCode = useCountryTo(({ setCountryCode }) => setCountryCode);

  const countries = COUNTRIES.map(({ flags, cca2, currencies }) => ({
    code: cca2.toLowerCase(),
    currency: Object.keys(currencies)[0].toLowerCase(),
    flag: flags.svg,
    label: t(`countries.${cca2.toLowerCase()}`),
  }));

  const FormSchema = z.object({
    [COUNTRY_FROM]: z.string({
      required_error: "Please select a countryFrom.",
    }),
  });

  const form = useForm<z.infer<typeof FormSchema>>({
    resolver: zodResolver(FormSchema),
  });

  useEffect(() => {
    //Add defaultValues inside a useEffect (client side), to not have hadration errors
    const defaultValues = {
      [COUNTRY_FROM]: countryFromCode,
    };
    form.reset({ ...defaultValues });
  }, []); // eslint-disable-line

  function onSubmit(data: z.infer<typeof FormSchema>) {
   console.log("data", data);
  }

  return (
    <Card className="mx-auto max-w-md sm:max-w-2xl md:max-w-3xl">
      <CardContent>
        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="py-4 grid grid-cols-1 md:grid-cols-3 gap-x-3 gap-y-6"
          >
            <SelectCountry
              name={COUNTRY_FROM}
              countries={countries}
              form={form}
              setCountry={setCountryFromCode}
            />

            <Button type="submit" className="self-end">
              {t("comparator.scan")}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
};

export default Comparator;

```

**Comment by mahmingtea** [comment]
> here is my code :
> 
> ```ts
> //select-country.tsx
> 
> "use client";
> 
> import { useState } from "react";
> import { Button } from "./ui/button";
> import { cn } from "@/lib/utils";
> import { Check, ChevronsUpDown } from "lucide-react";
> import Image from "next/image";
> import { Countries } from "@/types";
> import { UseFormReturn } from "react-hook-form";
> import {
>   Command,
>   CommandEmpty,
>   CommandGroup,
>   CommandInput,
>   CommandItem,
> } from "@/components/ui/command";
> import {
>   FormControl,
>   FormField,
>   FormItem,
>   FormLabel,
>   FormMessage,
> } from "@/components/ui/form";
> import {
>   Popover,
>   PopoverContent,
>   PopoverTrigger,
> } from "@/components/ui/popover";
> import { useTranslations } from "next-intl";
> 
> type Props = {
>   name: "countryFrom" | "countryTo";
>   setCountry: (countryCode: string) => void;
>   countries: Countries;
>   form: UseFormReturn<
>     {
>       countryFrom: string;
>       countryTo: string;
>       receiveMode: string;
>       sendAmount: number;
>     },
>     any,
>     undefined
>   >;
> };
> 
> const SelectCountry = ({ name, setCountry, countries, form }: Props) => {
>   const t = useTranslations();
>   const [open, setOpen] = useState(false);
> 
>   const countryWithFlag = (code?: string) => {
>     const selectedCountry = countries.find((country) => country.code === code);
>     return (
>       <div className="flex flex-row items-center">
>         <Image
>           src={selectedCountry?.flag || "/favicon.ico"}
>           alt="country flag"
>           className="shrink-0 me-2 w-6 h-5"
>           width={24}
>           height={24}
>         />
>         <div className="grow flex-1">{selectedCountry?.label}</div>
>       </div>
>     );
>   };
> 
>   return (
>     <FormField
>       control={form.control}
>       name={name}
>       render={({ field }) => (
>         <FormItem className="flex flex-col">
>           <FormLabel>{t("comparator.sendFrom")}</FormLabel>
>           <Popover open={open} onOpenChange={setOpen}>
>             <PopoverTrigger asChild>
>               <FormControl>
>                 <Button
>                   variant="outline"
>                   role="combobox"
>                   aria-expanded={open}
>                   className={cn(
>                     "w-full flex flex-row",
>                     !field.value && "text-muted-foreground"
>                   )}
>                 >
>                   {field.value
>                     ? countryWithFlag(field.value)
>                     : t("comparator.selectCountry")}
>                   <ChevronsUpDown className="ms-auto h-4 w-4 shrink-0 opacity-50" />
>                 </Button>
>               </FormControl>
>             </PopoverTrigger>
>             <PopoverContent className="p-0">
>               <Command
>                 filter={(value, search) => {
>                   if (
>                     t(`countries.${value}`)
>                       .toLowerCase()
>                       .includes(search?.toLowerCase())
>                   )
>                     return 1;
>                   return 0;
>                 }}
>               >
>                 <CommandInput placeholder={t("comparator.searchCountry")} />
>                 <CommandEmpty>{t("comparator.countryNotFound")}</CommandEmpty>
>                 <CommandGroup className="max-h-[240px] overflow-y-auto">
>                   {countries.map((country) => (
>                     <CommandItem
>                       value={country.code}
>                       key={country.code}
>                       onSelect={(value) => {
>                         form.setValue(name, value);
>                         setCountry(value);
>                         setOpen(false);
>                       }}
>                       className="w-full"
>                     >
>                       <Image
>                         src={country.flag}
>                         alt="country flag"
>                         className="shrink-0 me-2 w-5 h-3"
>                         width={20}
>                         height={16}
>                       />
>                       <div className="grow flex-1">{country.label}</div>
>                       <Check
>                         className={cn(
>                           "ms-auto h-4 w-4",
>                           country.code === field.value
>                             ? "opacity-100"
>                             : "opacity-0"
>                         )}
>                       />
>                     </CommandItem>
>                   ))}
>                 </CommandGroup>
>               </Command>
>             </PopoverContent>
>           </Popover>
>           <FormMessage />
>         </FormItem>
>       )}
>     />
>   );
> };
> 
> export default SelectCountry;
> ```
> 
> ```ts
> //comparator.tsx
> 
> "use client";
> 
> import * as z from "zod";
> import { useEffect } from "react";
> import { useTranslations } from "next-intl";
> import { zodResolver } from "@hookform/resolvers/zod";
> import { useForm } from "react-hook-form";
> import { useRouter } from "next-intl/client";
> 
> import { Button } from "@/components/ui/button";
> import {
>   Form,
>   FormControl,
>   FormField,
>   FormItem,
>   FormLabel,
>   FormMessage,
> } from "@/components/ui/form";
> 
> import { Card, CardContent } from "@/components/ui/card";
> import COUNTRIES from "../lib/countries.json";
> import InputWithCurrency from "./input-with-currency";
> import SelectCountry from "./select-country";
> import SelectReceiveMode from "./select-receive-mode";
> import { COUNTRY_FROM, COUNTRY_TO } from "@/lib/const";
> import useCountryFrom from "@/store/use-countryFrom";
> import useCountryTo from "@/store/use-countryTo";
> import CurrencyTo from "./currency-to";
> 
> const Comparator = () => {
>   const t = useTranslations();
>   const router = useRouter();
> 
>   const countryFromCode = useCountryFrom(({ countryCode }) => countryCode);
>   const setCountryFromCode = useCountryFrom(
>     ({ setCountryCode }) => setCountryCode
>   );
>   const setCountryToCode = useCountryTo(({ setCountryCode }) => setCountryCode);
> 
>   const countries = COUNTRIES.map(({ flags, cca2, currencies }) => ({
>     code: cca2.toLowerCase(),
>     currency: Object.keys(currencies)[0].toLowerCase(),
>     flag: flags.svg,
>     label: t(`countries.${cca2.toLowerCase()}`),
>   }));
> 
>   const FormSchema = z.object({
>     [COUNTRY_FROM]: z.string({
>       required_error: "Please select a countryFrom.",
>     }),
>   });
> 
>   const form = useForm<z.infer<typeof FormSchema>>({
>     resolver: zodResolver(FormSchema),
>   });
> 
>   useEffect(() => {
>     //Add defaultValues inside a useEffect (client side), to not have hadration errors
>     const defaultValues = {
>       [COUNTRY_FROM]: countryFromCode,
>     };
>     form.reset({ ...defaultValues });
>   }, []); // eslint-disable-line
> 
>   function onSubmit(data: z.infer<typeof FormSchema>) {
>    console.log("data", data);
>   }
> 
>   return (
>     <Card className="mx-auto max-w-md sm:max-w-2xl md:max-w-3xl">
>       <CardContent>
>         <Form {...form}>
>           <form
>             onSubmit={form.handleSubmit(onSubmit)}
>             className="py-4 grid grid-cols-1 md:grid-cols-3 gap-x-3 gap-y-6"
>           >
>             <SelectCountry
>               name={COUNTRY_FROM}
>               countries={countries}
>               form={form}
>               setCountry={setCountryFromCode}
>             />
> 
>             <Button type="submit" className="self-end">
>               {t("comparator.scan")}
>             </Button>
>           </form>
>         </Form>
>       </CardContent>
>     </Card>
>   );
> };
> 
> export default Comparator;
> ```

Like this?
```
{countries.map((country) => (
                    <CommandItem
                      value={country.label}
                      key={country.code}
                      onSelect={() => {
                        form.setValue(name, country.value);
                        setCountry(country.value);
                        setOpen(false);
                      }}
                      className="w-full"
                    >
                      <Image
                        src={country.flag}
                        alt="country flag"
                        className="shrink-0 me-2 w-5 h-3"
                        width={20}
                        height={16}
                      />
                      <div className="grow flex-1">{country.label}</div>
                      <Check
                        className={cn(
                          "ms-auto h-4 w-4",
                          country.code === field.value
                            ? "opacity-100"
                            : "opacity-0"
                        )}
                      />
                    </CommandItem>
                  ))}
```

**Comment by eedeebee** [comment]
This was marked as closed because?

**Comment by Kbadr1** [comment]
> `cmdk@1.0.0` added a `keywords` prop to `Command.Item` that can be used to adjust how the filter works. You can pass both the label and value to filter by both. See [the docs](https://github.com/pacocoursey/cmdk?tab=readme-ov-file#item-cmdk-item-data-disabled-data-selected).
> 
> ```tsx
> <Command.Item keywords={['fruit', 'apple']}>Apple</Command.Item>
> ```

Thank you! it worked ♥

**Comment by danielmnetto** [comment]
To solve this problem, I've added the `filter` prop on `<Command>` component and did this config:
```js
<Command
   filter={(_, search, keywords) => {
      return keywords
        ?.map((keyword) => keyword.includes(search))
        .some((result) => !!result)
        ? 1 : 0;
   }}
 >
  ...
</Command>
```
[The `filter` prop lets you customize the result of the search. The function returns 1 for matched results or 0 otherwise](https://github.com/pacocoursey/cmdk?tab=readme-ov-file#parts-and-styling). So the code above, instead of filtering the results by the `value` by default, it will filter by **keywords**. Said that, each `<CommandItem>` component must have configured by adding the `keyword` prop to it which holds an array that contains the label itself in order to the filter work.
```js
{languages.map((language) => (
  <CommandItem
    key={language.value}
    keywords={[language.label]}
    ...
  >
    ...
  </CommandItem>
))}
```

**Comment by gvsakhil** [comment]
> To solve this problem, I've added the `filter` prop on `<Command>` component and did this config:
> 
> <Command
>    filter={(_, search, keywords) => {
>       return keywords
>         ?.map((keyword) => keyword.includes(search))
>         .some((result) => !!result)
>         ? 1 : 0;
>    }}
>  >
>   ...
> </Command>
> [The `filter` prop lets you customize the result of the search. The function returns 1 for matched results or 0 otherwise](https://github.com/pacocoursey/cmdk?tab=readme-ov-file#parts-and-styling). So the code above, instead of filtering the results by the `value` by default, it will filter by **keywords**. Said that, each `<CommandItem>` component must have configured by adding the `keyword` prop to it which holds an array that contains the label itself in order to the filter work.
> 
> {languages.map((language) => (
>   <CommandItem
>     key={language.value}
>     keywords={[language.label]}
>     ...
>   >
>     ...
>   </CommandItem>
> ))}

Works like a charm... Thanks 👍

**Comment by pa4080** [comment]
> `cmdk@1.0.0` added a `keywords` prop to `Command.Item` that can be used to adjust how the filter works. You can pass both the label and value to filter by both. See [the docs](https://github.com/pacocoursey/cmdk?tab=readme-ov-file#item-cmdk-item-data-disabled-data-selected).
> 
> <Command.Item keywords={['fruit', 'apple']}>Apple</Command.Item>

Nice, here it is in an action:

```jsx
<CommandItem
  key={item.value}
  keywords={[item.label]}
  value={item.value}
  onSelect={(currentValue) => {
    setSelectedItem(currentValue === selectedItem ? "" : currentValue);
    setOpen(false);
  }}
>
  {item.label}
  <Check
    className={cn(
      "ml-auto",
      selectedItem === item.value ? "opacity-100" : "opacity-0"
    )}
  />
</CommandItem>
```
