### ISSUE TITLE
`DataTable` Component Error: "An error occurred during hydration. The server HTML was replaced with client content in <astro-island>" (Astro Website)

### ISSUE THREAD

**Issue by lucaswalter** [shadcn-ui/ui#936]
Hello, I'm having a bit of trouble tracing down the root of this so forgive me if this is not the correct spot to note this but I wanted to raise an issue to see if anyone else has encountered this or has a path forward.

I am using shadcn inside an Astro project and am attempting to display data in a `DataTable` component as documented on the shadcn documentation site. When I attempt to run the website locally, I get this hydration error when trying to apply custom formatting or JSX to the `header` or `cell` items on my `ColumnDef`.  **_An error occurred during hydration. The server HTML was replaced with client content in 'astro-island'_**

I've been able to reproduce this exact same issue on a fresh repro project after following these exact steps:
* Astro setup - https://ui.shadcn.com/docs/installation/astro
* DataTable setup - https://ui.shadcn.com/docs/components/data-table

Here is the repro link which uses exact same component as in the docs: https://github.com/lucaswalter/astro-shadcn-tanstack-repro/blob/main/src/pages/index.astro

In short, I am attempting to render and hydrate the `DataTable` like in the snippet below. Is it currently possible to use the DataTable component in an Astro project?
```
<Layout title="Welcome to Astro.">
	<main>
		<h1 class="mb-2">
			Welcome to <span class="text-gradient">Astro</span>
		</h1>

                 <!-- Data Table Usage -->
		<DataTable client:load columns={columns} data={data} />
	</main>
</Layout>
```

**Full Strack Trace**
```
react-dom.development.js:86 Warning: Did not expect server HTML to contain a <div> in <th>.
    at th
    at http://localhost:3000/src/components/ui/table.tsx:53:3
    at tr
    at http://localhost:3000/src/components/ui/table.tsx:44:3
    at thead
    at http://localhost:3000/src/components/ui/table.tsx:17:3
    at table
    at div
    at http://localhost:3000/src/components/ui/table.tsx:5:3
    at div
    at DataTable (http://localhost:3000/src/components/data-table.tsx:6:3)
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
warnForDeletedHydratableElement @ react-dom.development.js:10477
didNotHydrateInstance @ react-dom.development.js:11424
warnUnhydratedInstance @ react-dom.development.js:12313
warnIfUnhydratedTailNodes @ react-dom.development.js:12707
popHydrationState @ react-dom.development.js:12677
completeWork @ react-dom.development.js:22176
completeUnitOfWork @ react-dom.development.js:26593
performUnitOfWork @ react-dom.development.js:26568
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:86 Warning: An error occurred during hydration. The server HTML was replaced with client content in <astro-island>.
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
errorHydratingContainer @ react-dom.development.js:11473
recoverFromConcurrentError @ react-dom.development.js:25846
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at popHydrationState (react-dom.development.js:12678:9)
    at completeWork (react-dom.development.js:22176:30)
    at completeUnitOfWork (react-dom.development.js:26593:16)
    at performUnitOfWork (react-dom.development.js:26568:5)
    at workLoopConcurrent (react-dom.development.js:26543:5)
    at renderRootConcurrent (react-dom.development.js:26505:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:38)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
throwOnHydrationMismatch @ react-dom.development.js:12507
popHydrationState @ react-dom.development.js:12678
completeWork @ react-dom.development.js:22176
completeUnitOfWork @ react-dom.development.js:26593
performUnitOfWork @ react-dom.development.js:26568
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12535:7)
    at updateHostComponent (react-dom.development.js:19902:5)
    at beginWork (react-dom.development.js:21618:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26560:12)
    at workLoopConcurrent (react-dom.development.js:26543:5)
    at renderRootConcurrent (react-dom.development.js:26505:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:38)
    at workLoop (scheduler.development.js:266:34)
throwOnHydrationMismatch @ react-dom.development.js:12507
tryToClaimNextHydratableInstance @ react-dom.development.js:12535
updateHostComponent @ react-dom.development.js:19902
beginWork @ react-dom.development.js:21618
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26560
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:19849 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js:19849:57)
    at beginWork (react-dom.development.js:21615:14)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26560:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
updateHostRoot @ react-dom.development.js:19849
beginWork @ react-dom.development.js:21615
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26560
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

**Comment by lucaswalter** [comment]
Hey @servesh-chaturvedi Thanks for the input here. I was actually able to still recreate the issue on the link you provided. On your table it appears only plain-text column definitions are being used.

The rendering and same hydration error still appears for me when adding in basic Cell Formatting either to the header cell or data cell. (Additionally I was able to confirm I have `rsc: false` on my main project where I first discovered this.)

* shadcn docs - https://ui.shadcn.com/docs/components/data-table#cell-formatting
* Updated repro - https://stackblitz.com/edit/withastro-astro-m1xx1t?file=src%2Fpages%2Fpayment%2Fcolumns.tsx


```
export const columns: ColumnDef<Payment>[] = [
  {
    accessorKey: 'status',
    header: 'Status',
  },
  {
    accessorKey: 'email',
    header: 'Email',
  },
  {
    accessorKey: 'amount',
    // header: 'Amount', // This works for me
    header: () => <div className="text-right">Amount</div>, // This does not work for me
  },
];
```

**Comment by lucaswalter** [comment]
Thanks again, but as I understand that will make the component render completely on the server side and removes the ability for any client side interactions such as pagination, sorting, filtering etc.

In my application (and I believe many others) I would prefer to enable sorting and filtering. I'm still a bit stumped on how to approach or where to investigate this issue.

**Comment by servesh-chaturvedi** [comment]
Interesting, I tried to replicate what u said using pagination and it was true. However when I tried again and applied `client:load` it seemed to work 😂. Not sure what is going on but can u please try and confirm once?

**Comment by lucaswalter** [comment]
Still the same issue on my repro with `client:load` and `client:only="react"`. The core of the issues still appears to just happen when providing a function to build custom table HTML.

```
    accessorKey: 'amount',
    // header: 'Amount', // This works for me
    header: () => <div>Amount</div>, // This does not work for me
  },
```

**Comment by servesh-chaturvedi** [comment]
So I managed to setup the original example with Astro([link](https://stackblitz.com/edit/withastro-astro-ntdmwq?file=src%2Fpages%2Findex.astro)) and below are my observations.
 `client:only="react"` does not render the table for a long time (over 5s) but the result is responding as expected.
`client:load` manages to render but not reponsive at first. It becomes responsive after 7-8s.
But the most surprising part was to observe the network tab. See below:

![image](https://github.com/shadcn-ui/ui/assets/72094888/d4e319e7-9d31-45c1-925b-9f990afde79d)

Perhaps needs some additional configuration, maybe some Astro expert can help.

**Comment by plbstl** [comment]
@lucaswalter 

you have to import `columns` directly in your DataTable component.

taken from the astro docs: 

> You can pass a function as a prop to a framework component, but it only works during server rendering. If you try to use the function in a hydrated component (for example, as an event handler), an error will occur.
>
> This is because functions can’t be serialized (transferred from the server to the client) by Astro.

https://docs.astro.build/en/core-concepts/framework-components/#passing-props-to-framework-components

> The core of the issues still appears to just happen when providing a function to build custom table HTML.

you were right!

**Comment by lucaswalter** [comment]
Thanks for the assistance everyone, I the latest remarks were a huge help. The full solution is also documented here: https://discord.com/channels/830184174198718474/1130952479555735612

**Comment by servesh-chaturvedi** [comment]
Hi @lucaswalter the discord link is not working for me, can u please share a screenshot? Thanks

**Comment by kyeshmz** [comment]
To any one after this, the discord is the astro discord
