### ISSUE TITLE
Not able to change the colors of DropdownMenuItem on hover

### ISSUE THREAD

**Issue by BrunoQuaresma** [shadcn-ui/ui#940]
Hey, first of all, I want to thank you for your amazing work!

I have a `DropdownMenuItem` that I'm using for a remove action so I would like to make it red-ish but when I do something like:
```tsx
<DropdownMenuItem       
  className="text-red-600 !hover:text-red-600 !hover:bg-red-100"
  onClick={() => {
    disclosure.open(removeDisclosureId);
  }}
>
  <Trash className="h-4 w-4 mr-2" />
  Remover
</DropdownMenuItem>
```
The text color works, but when it hovers, the gray-ish style is applied even when forcing the hover styles with `!important`. 

Thanks in advance!

**Comment by joaom00** [comment]
Try, instead of `hover:`, with `focus:`

**Comment by plbstl** [comment]
@BrunoQuaresma 

According to the docs - https://tailwindcss.com/docs/configuration#important-modifier:

> The ! always goes at the beginning of the utility name, after any variants, but before any prefix

can you try changing the position of the exclamation mark?

```diff
<DropdownMenuItem       
-  className="text-red-600 !hover:text-red-600 !hover:bg-red-100"
+  className="text-red-600 hover:!text-red-600 hover:!bg-red-100"
  onClick={() => {
    disclosure.open(removeDisclosureId);
  }}
 >
  <Trash className="h-4 w-4 mr-2" />
  Remover
</DropdownMenuItem>
```

**Comment by BrunoQuaresma** [comment]
`focus:` worked! Thank you @joaom00

**Comment by Markkos89** [comment]
> @BrunoQuaresma
> 
> According to the docs - https://tailwindcss.com/docs/configuration#important-modifier:
> 
> > The ! always goes at the beginning of the utility name, after any variants, but before any prefix
> 
> can you try changing the position of the exclamation mark?
> 
> ```diff
> <DropdownMenuItem       
> -  className="text-red-600 !hover:text-red-600 !hover:bg-red-100"
> +  className="text-red-600 hover:!text-red-600 hover:!bg-red-100"
>   onClick={() => {
>     disclosure.open(removeDisclosureId);
>   }}
>  >
>   <Trash className="h-4 w-4 mr-2" />
>   Remover
> </DropdownMenuItem>
> ```

This worked for me !! :muscle: 

Thanks a lot @plbstl :raised_hands:  It's always nice to learn new things :smile: 

_The `!focus` didn't did the trick for me._

**Comment by a-mariam** [comment]
This works for me too 
Thank you @plbstl
