### ISSUE TITLE
The accordion animation fails to work correctly when attempting to open it.

### ISSUE THREAD

**Issue by Cristhianzl** [shadcn-ui/ui#944]
Hello,

The accordion animation is not functioning as expected when attempting to open it (but works normally when It closes). Currently, the animation fails to smoothly expand the accordion content, resulting in a jarring visual experience for the users.

Expected Behavior:
When opening the accordion, the animation should smoothly expand the accordion content from a collapsed state to its full height, providing a visually pleasing transition.

Actual Behavior:
The accordion animation does not work correctly. It either shows no animation at all or exhibits a sudden jump, instantly displaying the expanded state without any smooth transition.
```
keyframes: {
  "accordion-down": {
    from: { height: "0" },
    to: { height: "var(--radix-accordion-content-height)" },
  },
  "accordion-up": {
    from: { height: "var(--radix-accordion-content-height)" },
    to: { height: "0" },
  },
},
animation: {
  "accordion-down": "accordion-down 0.2s ease-out",
  "accordion-up": "accordion-up 0.2s ease-out",
}
```

I'm attaching the dialog.tsx file and the tailwind.config file for a more thorough analysis.
Thanks in advance.

[dialog.zip](https://github.com/shadcn/ui/files/12065212/dialog.zip)
[tailwind.config.zip](https://github.com/shadcn/ui/files/12065216/tailwind.config.zip)

**Comment by catz** [comment]
Hello @Cristhianzl 

What was the issue? Experiencing the same behaviour.

**Comment by catz** [comment]
Hi @Cristhianzl 

This seems a bit strange. Hardcoded height, removed shadcn animations. Don't you think it should work out of the box without such hacks ?

**Comment by Cristhianzl** [comment]
> 

Sorry, got that code from an older branch. 
var(--radix-accordion-content-height) is supposed to be the height.

**Comment by shug0** [comment]
Hello, I noticed that adding classes to the `className` property of `AccordionContent` produce the lag on the animation, removing them make my animation run smoothly.

I recommend wrapping content class into a children component to avoid this 🙏

**Comment by shadcn** [comment]
Fixed in #1670

**Comment by donttouchmylancable** [comment]
I had the problem, that i removed the value inside the accordion item.
After adding it back, it worked for me again.
`<AccordionItem value={`item-${i}`}>`
(but with ` around the item-${i})
I used it in a list and forgot to add the item index.
Without value, it did not open for me.
Hope that helps anyone.

**Comment by Niluminda007** [comment]
make sure its coming from shad-cn not radix i had the same issue

**Comment by vmnog** [comment]
Super stupid mistake that can happen sometimes, make sure you didn't put this animation and keyframes inside the wrong "{}" object. :face_exhaling:

**Comment by raumildhandhukia** [comment]
> Hi @Cristhianzl
> 
> This seems a bit strange. Hardcoded height, removed shadcn animations. Don't you think it should work out of the box without such hacks ?

I had the same issue, but the problem was, vscode auto imported the Accordion from Radix. Make sure you import from shadcn/ui not radix/ui. Hope it works for you too :)
