### ISSUE TITLE
Toaster Animation not working for me

### ISSUE THREAD

**Issue by kenbankspeng** [shadcn-ui/ui#954]
For Toast,  I observe in Radix demo code a slide-in animation implemented using @keyframes slideIn css. I observe in the Shadcn Toast demo a very nice slide-up and slide-out animation. 

When I add the Shadcn Toaster/Toast to my project, I do not observe the slide-up/ slide-out animation. I do notice that Shadcn Toast has `data-[state=open]:animate-in data-[state=closed]:animate-out` tailwind in its string. 

I see some keyframe and animation config added to my tailwind.config.js for accordion, but not for Toast. 

Am I doing something wrong? Or does the installed Toast not behave like the demo'd Toast out of the box?

Aside: I see swipe config using data- attributes referencing css var(--radix-toast-swipe-move-x) and  var(--radix-toast-swipe-end-x) but don't see where these vars vakues are defined.

**Comment by furkanmavili** [comment]
Did you install the `tailwindcss-animate` plugin?

**Comment by kenbankspeng** [comment]
I do see tailwindcss-animate in my package.json as a dependency and I see it available under node_modules. Great suggestion though.
