### ISSUE TITLE
All lucide-icons are loaded since 0.260.0 

### ISSUE THREAD

**Issue by nuno** [shadcn-ui/ui#956]
For reference https://github.com/lucide-icons/lucide/issues/1437

**Comment by shadcn** [comment]
Hmm, I'll follow up on the Lucide ticket. Thanks for the heads up.

**Comment by plbstl** [comment]
seems like there's now a fix for this

**Comment by nuno** [comment]
@plbstl Awesome!

**Comment by nuno** [comment]
Is fixed "lucide-react": "^0.263.0
