### ISSUE TITLE
Components and Utils import alias issues 

### ISSUE THREAD

**Issue by bilal42011** [shadcn-ui/ui#968]
Import alias for components and utils not work properly instead they create folders with that name aliases after doing shadcn init command for configuration.
I used react vite typescript project

**Comment by plbstl** [comment]
you can try manually moving the files to the appropriate folders

**Comment by bilal42011** [comment]
> you can try manually moving the files to the appropriate folders and delete the unused created folders
> 
> also, check your path alias & base url in tsconfig if they're set properly

Yes there were some config issues in vite.config file thankyou for support

**Comment by bilal42011** [comment]
> interesting, it should work properly just by setting up path aliases in tsconfig/jsconfig.

No in order to use import aliases in vite react ts project we need to set aliases for both in tsconfig.json and vite.connfig.json, otherwise aliases paths are not resolved properly at build time

**Comment by plbstl** [comment]
oh okay, noted

**Comment by rafikulislam775** [comment]
you can update your tsconfig.json like this 

{
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
