### ISSUE TITLE
Astro error - AvatarImage must be used within Avatar

### ISSUE THREAD

**Issue by MarkLyck** [shadcn-ui/ui#987]
I followed the installation instructions for Astro and tried to the use `Avatar` component.

However I get the following error:

`AvatarImage must be used within Avatar`

Minimal reproduction in `pages/index.astro`

```astro
---
import "@/styles/globals.css";

import Layout from "../layouts/Layout.astro";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Card, CardContent } from "@/components/ui/card";
---

<Layout title="shadcn test">
      <Card>
        <CardContent>
          <Avatar>
            <AvatarImage src="https://github.com/shadcn.png" alt="@marklyck" />
            <AvatarFallback>ML</AvatarFallback>
          </Avatar>
          <h2 class="text-lg">A portfolio brimming with innovation.</h2>
        </CardContent>
      </Card>
</Layout>
```

The `AvatarImage` is clearly within the `Avatar` component. Is there any way to get this working with Astro?

Edit:

The same issue also happens with `Tooltip`: `TooltipContent` must be used within `Tooltip` 😞

**Comment by MarkLyck** [comment]
This is due to how Astro creates an Island for each react component, so Context is not shared.

I solved this by moving all the Avatar/Tooltip/Tabs code to a React file, and importing it with `client:load`

**Comment by Elijas** [comment]
> This is due to how Astro creates an Island for each react component, so Context is not shared.
> 
> I solved this by moving all the Avatar/Tooltip/Tabs code to a React file, and importing it with `client:load`


More specifically

```
// AvatarComponent.jsx
import React from 'react';
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";

export const AvatarComponent = ({ src, alt, fallbackText }) => {
  return (
    <Avatar>
      <AvatarImage src={src} alt={alt} />
      <AvatarFallback>{fallbackText}</AvatarFallback>
    </Avatar>
  );
};
```

then

```
---
// pages/index.astro
import "@/styles/globals.css";
import Layout from "../layouts/Layout.astro";
import { Card, CardContent } from "@/components/ui/card";
import { AvatarComponent } from "../components/AvatarComponent.jsx"; // Adjust the path as needed
---

<Layout title="shadcn test">
  <Card>
    <CardContent>
      <AvatarComponent client:load src="https://github.com/shadcn.png" alt="@marklyck" fallbackText="ML" />
      <h2 class="text-lg">A portfolio brimming with innovation.</h2>
    </CardContent>
  </Card>
</Layout>
```

**Comment by pychap** [comment]
Many thanks, @MarkLyck and @Elijas !!
Thought I was going crazy!
