### ISSUE TITLE
Incorrect Position of SVG Icon in `Alert` Component in Firefox

### ISSUE THREAD

**Issue by limitless-dev** [shadcn-ui/ui#998]
- Firefox displays the SVG icon at an unintended position within the `Alert` component.
  - https://ui.shadcn.com/docs/components/alert

**Chrome** ✅
<img width="675" alt="Screen Shot 2023-07-21 at 4 17 18 PM" src="https://github.com/shadcn-ui/ui/assets/24194621/aff91348-fbc2-4c70-bbfa-5210e222df3f">

**Firefox** ❌
<img width="554" alt="Screen Shot 2023-07-21 at 4 17 07 PM" src="https://github.com/shadcn-ui/ui/assets/24194621/ebb171b8-13d5-4ef2-854b-6a4ccceef6f3">

**Comment by m-bohra8999** [comment]
please share the code?

**Comment by limitless-dev** [comment]
> please share the code?

I haven't written any code. This is how it looks in [doc examples](https://ui.shadcn.com/docs/components/alert) when opened through Firefox.

**Comment by m-bohra8999** [comment]
`[&:has(svg)]:pl-11` on the root div is causing the issue. It's not working in firefox.

**Comment by limitless-dev** [comment]
> `[&:has(svg)]:pl-11` on the root div is causing the issue. It's not working in firefox. It's a css4 feature which is not fully supported in all browsers. https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility seems like post-css didn't work on it. https://github.com/csstools/css-has-pseudo/blob/main/README-POSTCSS.md can be a solution

Good catch!  
`has` selector is currently [under development](https://connect.mozilla.org/t5/ideas/when-is-has-css-selector-going-to-be-fully-implemented-in/idc-p/35597/highlight/true#M20721) for Firefox.

**Comment by dan5py** [comment]
You can change `[&:has(svg)]:pl-11` to `[&>svg~*]:pl-7` to "simulate" the has selector.

**Comment by kubre** [comment]
Can confirm
chrome
![image](https://github.com/shadcn-ui/ui/assets/20380094/52e38355-a366-4a2e-a0ee-145eee4f46bd)


firefox
![image](https://github.com/shadcn-ui/ui/assets/20380094/7b435148-476b-4b71-bdd6-5883903cc8df)
